/** Grade 5 chunk D — technology, arts, sports, health (simple) (250 cards). */
export const GRADE5_CHUNK_D = [
  { word: "hotel", translation: "فندق", partOfSpeech: "noun", difficulty: "easy", example: "We heard hotel in the science video.", exampleTranslation: "سمعنا فندق في فيلم العلوم." },
  { word: "motel", translation: "نُزُل", partOfSpeech: "noun", difficulty: "medium", example: "Please copy motel into your notebook.", exampleTranslation: "من فضلك انسخ نُزُل في دفترك." },
  { word: "inn", translation: "نُزُل", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of inn.", exampleTranslation: "يُظهر المخطط مثالاً عن نُزُل." },
  { word: "terminal", translation: "محطة", partOfSpeech: "noun", difficulty: "medium", example: "Our group used terminal in the project.", exampleTranslation: "استخدمت مجموعتنا محطة في المشروع." },
  { word: "port", translation: "ميناء", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with port.", exampleTranslation: "أعطى المعلم مثالاً بـميناء." },
  { word: "dock", translation: "رصيف", partOfSpeech: "noun", difficulty: "medium", example: "I underlined dock in the paragraph.", exampleTranslation: "وضعت خطاً تحت رصيف في الفقرة." },
  { word: "pier", translation: "رصيف", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying pier aloud.", exampleTranslation: "تدرّبنا على نطق رصيف بصوت عالٍ." },
  { word: "plant", translation: "مصنع", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains plant with a drawing.", exampleTranslation: "يشرح الملصق مصنع برسم." },
  { word: "mill", translation: "مطحنة", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with mill.", exampleTranslation: "شارك الجميع جملة فيها مطحنة." },
  { word: "mine", translation: "منجم", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word mine.", exampleTranslation: "تضمّن الاختبار كلمة منجم." },
  { word: "quarry", translation: "محجر", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word quarry in class today.", exampleTranslation: "تعلّمنا كلمة محجر في الحصة اليوم." },
  { word: "ranch", translation: "مزرعة", partOfSpeech: "noun", difficulty: "medium", example: "Can you use ranch in a sentence?", exampleTranslation: "هل يمكنك استخدام مزرعة في جملة؟" },
  { word: "vineyard", translation: "كرم", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned vineyard on page ten.", exampleTranslation: "ذكرت القصة كرم في الصفحة العاشرة." },
  { word: "stable", translation: "إسطبل", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote stable on the board.", exampleTranslation: "كتب معلمنا إسطبل على السبورة." },
  { word: "plain", translation: "سهل", partOfSpeech: "noun", difficulty: "easy", example: "I spelled plain correctly on the quiz.", exampleTranslation: "تهجّيت سهل بشكل صحيح في الاختبار." },
  { word: "basin", translation: "حوض", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain basin.", exampleTranslation: "تساعد الصورة على شرح حوض." },
  { word: "channel", translation: "قناة", partOfSpeech: "noun", difficulty: "medium", example: "We found channel in our reading book.", exampleTranslation: "وجدنا قناة في كتاب القراءة." },
  { word: "canal", translation: "قناة", partOfSpeech: "noun", difficulty: "medium", example: "Canal is a new word for our unit.", exampleTranslation: "قناة كلمة جديدة لوحدتنا." },
  { word: "reservoir", translation: "خزان", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed reservoir.", exampleTranslation: "ناقشت خزان مع زميلي." },
  { word: "dam", translation: "سد", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about dam.", exampleTranslation: "يسأل ورق العمل عن سد." },
  { word: "levee", translation: "سد ترابي", partOfSpeech: "noun", difficulty: "medium", example: "We heard levee in the science video.", exampleTranslation: "سمعنا سد ترابي في فيلم العلوم." },
  { word: "pole", translation: "قطب", partOfSpeech: "noun", difficulty: "medium", example: "Please copy pole into your notebook.", exampleTranslation: "من فضلك انسخ قطب في دفترك." },
  { word: "tropic", translation: "مدار", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of tropic.", exampleTranslation: "يُظهر المخطط مثالاً عن مدار." },
  { word: "weather", translation: "طقس", partOfSpeech: "noun", difficulty: "easy", example: "Our group used weather in the project.", exampleTranslation: "استخدمت مجموعتنا طقس في المشروع." },
  { word: "timezone", translation: "منطقة زمنية", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with timezone.", exampleTranslation: "أعطى المعلم مثالاً بـمنطقة زمنية." },
  { word: "language", translation: "لغة", partOfSpeech: "noun", difficulty: "easy", example: "I underlined language in the paragraph.", exampleTranslation: "وضعت خطاً تحت لغة في الفقرة." },
  { word: "accent", translation: "لهجة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying accent aloud.", exampleTranslation: "تدرّبنا على نطق لهجة بصوت عالٍ." },
  { word: "alphabet", translation: "أبجدية", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains alphabet with a drawing.", exampleTranslation: "يشرح الملصق أبجدية برسم." },
  { word: "industry", translation: "صناعة", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with industry.", exampleTranslation: "شارك الجميع جملة فيها صناعة." },
  { word: "agriculture", translation: "زراعة", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word agriculture.", exampleTranslation: "تضمّن الاختبار كلمة زراعة." },
  { word: "mining", translation: "تعدين", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word mining in class today.", exampleTranslation: "تعلّمنا كلمة تعدين في الحصة اليوم." },
  { word: "tourism", translation: "سياحة", partOfSpeech: "noun", difficulty: "easy", example: "Can you use tourism in a sentence?", exampleTranslation: "هل يمكنك استخدام سياحة في جملة؟" },
  { word: "population", translation: "سكان", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned population on page ten.", exampleTranslation: "ذكرت القصة سكان في الصفحة العاشرة." },
  { word: "urban", translation: "حضري", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote urban on the board.", exampleTranslation: "كتب معلمنا حضري على السبورة." },
  { word: "suburb", translation: "ضاحية", partOfSpeech: "noun", difficulty: "medium", example: "I spelled suburb correctly on the quiz.", exampleTranslation: "تهجّيت ضاحية بشكل صحيح في الاختبار." },
  { word: "downtown", translation: "وسط المدينة", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain downtown.", exampleTranslation: "تساعد الصورة على شرح وسط المدينة." },
  { word: "uptown", translation: "أعلى المدينة", partOfSpeech: "noun", difficulty: "medium", example: "We found uptown in our reading book.", exampleTranslation: "وجدنا أعلى المدينة في كتاب القراءة." },
  { word: "outskirts", translation: "أطراف", partOfSpeech: "noun", difficulty: "medium", example: "Outskirts is a new word for our unit.", exampleTranslation: "أطراف كلمة جديدة لوحدتنا." },
  { word: "home", translation: "بيت", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed home.", exampleTranslation: "ناقشت بيت مع زميلي." },
  { word: "apartment", translation: "شقة", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about apartment.", exampleTranslation: "يسأل ورق العمل عن شقة." },
  { word: "condo", translation: "شقة تمليك", partOfSpeech: "noun", difficulty: "medium", example: "We heard condo in the science video.", exampleTranslation: "سمعنا شقة تمليك في فيلم العلوم." },
  { word: "mansion", translation: "قصر", partOfSpeech: "noun", difficulty: "medium", example: "Please copy mansion into your notebook.", exampleTranslation: "من فضلك انسخ قصر في دفترك." },
  { word: "hut", translation: "كوخ", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of hut.", exampleTranslation: "يُظهر المخطط مثالاً عن كوخ." },
  { word: "tent", translation: "خيمة", partOfSpeech: "noun", difficulty: "easy", example: "Our group used tent in the project.", exampleTranslation: "استخدمت مجموعتنا خيمة في المشروع." },
  { word: "shelter", translation: "مأوى", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with shelter.", exampleTranslation: "أعطى المعلم مثالاً بـمأوى." },
  { word: "roof", translation: "سقف", partOfSpeech: "noun", difficulty: "easy", example: "I underlined roof in the paragraph.", exampleTranslation: "وضعت خطاً تحت سقف في الفقرة." },
  { word: "ceiling", translation: "سقف", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying ceiling aloud.", exampleTranslation: "تدرّبنا على نطق سقف بصوت عالٍ." },
  { word: "rug", translation: "بساط", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains rug with a drawing.", exampleTranslation: "يشرح الملصق بساط برسم." },
  { word: "tile", translation: "بلاط", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with tile.", exampleTranslation: "شارك الجميع جملة فيها بلاط." },
  { word: "yard", translation: "فناء", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word yard.", exampleTranslation: "تضمّن الاختبار كلمة فناء." },
  { word: "porch", translation: "شرفة", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word porch in class today.", exampleTranslation: "تعلّمنا كلمة شرفة في الحصة اليوم." },
  { word: "patio", translation: "فناء", partOfSpeech: "noun", difficulty: "medium", example: "Can you use patio in a sentence?", exampleTranslation: "هل يمكنك استخدام فناء في جملة؟" },
  { word: "fireplace", translation: "موقد", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned fireplace on page ten.", exampleTranslation: "ذكرت القصة موقد في الصفحة العاشرة." },
  { word: "stove", translation: "موقد", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote stove on the board.", exampleTranslation: "كتب معلمنا موقد على السبورة." },
  { word: "fridge", translation: "ثلاجة", partOfSpeech: "noun", difficulty: "easy", example: "I spelled fridge correctly on the quiz.", exampleTranslation: "تهجّيت ثلاجة بشكل صحيح في الاختبار." },
  { word: "freezer", translation: "فريزر", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain freezer.", exampleTranslation: "تساعد الصورة على شرح فريزر." },
  { word: "tap", translation: "صنبور", partOfSpeech: "noun", difficulty: "easy", example: "We found tap in our reading book.", exampleTranslation: "وجدنا صنبور في كتاب القراءة." },
  { word: "pipe", translation: "أنبوب", partOfSpeech: "noun", difficulty: "easy", example: "Pipe is a new word for our unit.", exampleTranslation: "أنبوب كلمة جديدة لوحدتنا." },
  { word: "toilet", translation: "مرحاض", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed toilet.", exampleTranslation: "ناقشت مرحاض مع زميلي." },
  { word: "shower", translation: "دش", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about shower.", exampleTranslation: "يسأل ورق العمل عن دش." },
  { word: "bathtub", translation: "حوض استحمام", partOfSpeech: "noun", difficulty: "medium", example: "We heard bathtub in the science video.", exampleTranslation: "سمعنا حوض استحمام في فيلم العلوم." },
  { word: "shampoo", translation: "شامبو", partOfSpeech: "noun", difficulty: "easy", example: "Please copy shampoo into your notebook.", exampleTranslation: "من فضلك انسخ شامبو في دفترك." },
  { word: "toothbrush", translation: "فرشاة أسنان", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of toothbrush.", exampleTranslation: "يُظهر المخطط مثالاً عن فرشاة أسنان." },
  { word: "toothpaste", translation: "معجون أسنان", partOfSpeech: "noun", difficulty: "easy", example: "Our group used toothpaste in the project.", exampleTranslation: "استخدمت مجموعتنا معجون أسنان في المشروع." },
  { word: "sheet", translation: "ملاءة", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with sheet.", exampleTranslation: "أعطى المعلم مثالاً بـملاءة." },
  { word: "quilt", translation: "لحاف", partOfSpeech: "noun", difficulty: "medium", example: "I underlined quilt in the paragraph.", exampleTranslation: "وضعت خطاً تحت لحاف في الفقرة." },
  { word: "duvet", translation: "لحاف", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying duvet aloud.", exampleTranslation: "تدرّبنا على نطق لحاف بصوت عالٍ." },
  { word: "shelf", translation: "رف", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains shelf with a drawing.", exampleTranslation: "يشرح الملصق رف برسم." },
  { word: "counter", translation: "طاولة", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with counter.", exampleTranslation: "شارك الجميع جملة فيها طاولة." },
  { word: "stool", translation: "مقعد", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word stool.", exampleTranslation: "تضمّن الاختبار كلمة مقعد." },
  { word: "couch", translation: "أريكة", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word couch in class today.", exampleTranslation: "تعلّمنا كلمة أريكة في الحصة اليوم." },
  { word: "armchair", translation: "كرسي بذراعين", partOfSpeech: "noun", difficulty: "medium", example: "Can you use armchair in a sentence?", exampleTranslation: "هل يمكنك استخدام كرسي بذراعين في جملة؟" },
  { word: "bench", translation: "مقعد", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned bench on page ten.", exampleTranslation: "ذكرت القصة مقعد في الصفحة العاشرة." },
  { word: "plug", translation: "قابس", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote plug on the board.", exampleTranslation: "كتب معلمنا قابس على السبورة." },
  { word: "cord", translation: "سلك", partOfSpeech: "noun", difficulty: "easy", example: "I spelled cord correctly on the quiz.", exampleTranslation: "تهجّيت سلك بشكل صحيح في الاختبار." },
  { word: "remote", translation: "جهاز تحكم", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain remote.", exampleTranslation: "تساعد الصورة على شرح جهاز تحكم." },
  { word: "television", translation: "تلفاز", partOfSpeech: "noun", difficulty: "easy", example: "We found television in our reading book.", exampleTranslation: "وجدنا تلفاز في كتاب القراءة." },
  { word: "alarm", translation: "منبه", partOfSpeech: "noun", difficulty: "easy", example: "Alarm is a new word for our unit.", exampleTranslation: "منبه كلمة جديدة لوحدتنا." },
  { word: "picture", translation: "صورة", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed picture.", exampleTranslation: "ناقشت صورة مع زميلي." },
  { word: "photo", translation: "صورة", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about photo.", exampleTranslation: "يسأل ورق العمل عن صورة." },
  { word: "frame", translation: "إطار", partOfSpeech: "noun", difficulty: "easy", example: "We heard frame in the science video.", exampleTranslation: "سمعنا إطار في فيلم العلوم." },
  { word: "poster", translation: "ملصق", partOfSpeech: "noun", difficulty: "easy", example: "Please copy poster into your notebook.", exampleTranslation: "من فضلك انسخ ملصق في دفترك." },
  { word: "vase", translation: "مزهرية", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of vase.", exampleTranslation: "يُظهر المخطط مثالاً عن مزهرية." },
  { word: "blind", translation: "ستارة", partOfSpeech: "noun", difficulty: "medium", example: "Our group used blind in the project.", exampleTranslation: "استخدمت مجموعتنا ستارة في المشروع." },
  { word: "heater", translation: "سخان", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with heater.", exampleTranslation: "أعطى المعلم مثالاً بـسخان." },
  { word: "radiator", translation: "مشعاع", partOfSpeech: "noun", difficulty: "medium", example: "I underlined radiator in the paragraph.", exampleTranslation: "وضعت خطاً تحت مشعاع في الفقرة." },
  { word: "vent", translation: "فتحة تهوية", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying vent aloud.", exampleTranslation: "تدرّبنا على نطق فتحة تهوية بصوت عالٍ." },
  { word: "broom", translation: "مكنسة", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains broom with a drawing.", exampleTranslation: "يشرح الملصق مكنسة برسم." },
  { word: "bucket", translation: "دلو", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with bucket.", exampleTranslation: "شارك الجميع جملة فيها دلو." },
  { word: "sponge", translation: "إسفنجة", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word sponge.", exampleTranslation: "تضمّن الاختبار كلمة إسفنجة." },
  { word: "garbage", translation: "قمامة", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word garbage in class today.", exampleTranslation: "تعلّمنا كلمة قمامة في الحصة اليوم." },
  { word: "washer", translation: "غسالة", partOfSpeech: "noun", difficulty: "easy", example: "Can you use washer in a sentence?", exampleTranslation: "هل يمكنك استخدام غسالة في جملة؟" },
  { word: "dryer", translation: "مجفف", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned dryer on page ten.", exampleTranslation: "ذكرت القصة مجفف في الصفحة العاشرة." },
  { word: "clothes", translation: "ملابس", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote clothes on the board.", exampleTranslation: "كتب معلمنا ملابس على السبورة." },
  { word: "blouse", translation: "بلوزة", partOfSpeech: "noun", difficulty: "medium", example: "I spelled blouse correctly on the quiz.", exampleTranslation: "تهجّيت بلوزة بشكل صحيح في الاختبار." },
  { word: "jeans", translation: "جينز", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain jeans.", exampleTranslation: "تساعد الصورة على شرح جينز." },
  { word: "shorts", translation: "شورت", partOfSpeech: "noun", difficulty: "easy", example: "We found shorts in our reading book.", exampleTranslation: "وجدنا شورت في كتاب القراءة." },
  { word: "suit", translation: "بدلة", partOfSpeech: "noun", difficulty: "easy", example: "Suit is a new word for our unit.", exampleTranslation: "بدلة كلمة جديدة لوحدتنا." },
  { word: "hoodie", translation: "هودي", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed hoodie.", exampleTranslation: "ناقشت هودي مع زميلي." },
  { word: "vest", translation: "صديري", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about vest.", exampleTranslation: "يسأل ورق العمل عن صديري." },
  { word: "tie", translation: "ربطة عنق", partOfSpeech: "noun", difficulty: "easy", example: "We heard tie in the science video.", exampleTranslation: "سمعنا ربطة عنق في فيلم العلوم." },
  { word: "sock", translation: "جورب", partOfSpeech: "noun", difficulty: "easy", example: "Please copy sock into your notebook.", exampleTranslation: "من فضلك انسخ جورب في دفترك." },
  { word: "shoe", translation: "حذاء", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of shoe.", exampleTranslation: "يُظهر المخطط مثالاً عن حذاء." },
  { word: "boot", translation: "حذاء طويل", partOfSpeech: "noun", difficulty: "easy", example: "Our group used boot in the project.", exampleTranslation: "استخدمت مجموعتنا حذاء طويل في المشروع." },
  { word: "sandal", translation: "صندل", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with sandal.", exampleTranslation: "أعطى المعلم مثالاً بـصندل." },
  { word: "slipper", translation: "شبشب", partOfSpeech: "noun", difficulty: "medium", example: "I underlined slipper in the paragraph.", exampleTranslation: "وضعت خطاً تحت شبشب في الفقرة." },
  { word: "sneaker", translation: "حذاء رياضي", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying sneaker aloud.", exampleTranslation: "تدرّبنا على نطق حذاء رياضي بصوت عالٍ." },
  { word: "cap", translation: "قبعة", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains cap with a drawing.", exampleTranslation: "يشرح الملصق قبعة برسم." },
  { word: "glove", translation: "قفاز", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with glove.", exampleTranslation: "شارك الجميع جملة فيها قفاز." },
  { word: "purse", translation: "حقيبة يد", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word purse.", exampleTranslation: "تضمّن الاختبار كلمة حقيبة يد." },
  { word: "wallet", translation: "محفظة", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word wallet in class today.", exampleTranslation: "تعلّمنا كلمة محفظة في الحصة اليوم." },
  { word: "lock", translation: "قفل", partOfSpeech: "noun", difficulty: "easy", example: "Can you use lock in a sentence?", exampleTranslation: "هل يمكنك استخدام قفل في جملة؟" },
  { word: "tool", translation: "أداة", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned tool on page ten.", exampleTranslation: "ذكرت القصة أداة في الصفحة العاشرة." },
  { word: "hammer", translation: "مطرقة", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote hammer on the board.", exampleTranslation: "كتب معلمنا مطرقة على السبورة." },
  { word: "rope", translation: "حبل", partOfSpeech: "noun", difficulty: "easy", example: "I spelled rope correctly on the quiz.", exampleTranslation: "تهجّيت حبل بشكل صحيح في الاختبار." },
  { word: "chain", translation: "سلسلة", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain chain.", exampleTranslation: "تساعد الصورة على شرح سلسلة." },
  { word: "paint", translation: "دهان", partOfSpeech: "noun", difficulty: "easy", example: "We found paint in our reading book.", exampleTranslation: "وجدنا دهان في كتاب القراءة." },
  { word: "roller", translation: "أسطوانة دهان", partOfSpeech: "noun", difficulty: "medium", example: "Roller is a new word for our unit.", exampleTranslation: "أسطوانة دهان كلمة جديدة لوحدتنا." },
  { word: "knife", translation: "سكين", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed knife.", exampleTranslation: "ناقشت سكين مع زميلي." },
  { word: "bowl", translation: "وعاء", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about bowl.", exampleTranslation: "يسأل ورق العمل عن وعاء." },
  { word: "mug", translation: "كوب", partOfSpeech: "noun", difficulty: "easy", example: "We heard mug in the science video.", exampleTranslation: "سمعنا كوب في فيلم العلوم." },
  { word: "glass", translation: "كأس", partOfSpeech: "noun", difficulty: "easy", example: "Please copy glass into your notebook.", exampleTranslation: "من فضلك انسخ كأس في دفترك." },
  { word: "pot", translation: "قدر", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of pot.", exampleTranslation: "يُظهر المخطط مثالاً عن قدر." },
  { word: "pan", translation: "مقلاة", partOfSpeech: "noun", difficulty: "easy", example: "Our group used pan in the project.", exampleTranslation: "استخدمت مجموعتنا مقلاة في المشروع." },
  { word: "lid", translation: "غطاء", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with lid.", exampleTranslation: "أعطى المعلم مثالاً بـغطاء." },
  { word: "truck", translation: "شاحنة", partOfSpeech: "noun", difficulty: "easy", example: "I underlined truck in the paragraph.", exampleTranslation: "وضعت خطاً تحت شاحنة في الفقرة." },
  { word: "van", translation: "فان", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying van aloud.", exampleTranslation: "تدرّبنا على نطق فان بصوت عالٍ." },
  { word: "taxi", translation: "تاكسي", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains taxi with a drawing.", exampleTranslation: "يشرح الملصق تاكسي برسم." },
  { word: "subway", translation: "مترو", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with subway.", exampleTranslation: "شارك الجميع جملة فيها مترو." },
  { word: "metro", translation: "مترو", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word metro.", exampleTranslation: "تضمّن الاختبار كلمة مترو." },
  { word: "ship", translation: "سفينة", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word ship in class today.", exampleTranslation: "تعلّمنا كلمة سفينة في الحصة اليوم." },
  { word: "raft", translation: "طوافة", partOfSpeech: "noun", difficulty: "medium", example: "Can you use raft in a sentence?", exampleTranslation: "هل يمكنك استخدام طوافة في جملة؟" },
  { word: "sailboat", translation: "قارب شراعي", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned sailboat on page ten.", exampleTranslation: "ذكرت القصة قارب شراعي في الصفحة العاشرة." },
  { word: "speedboat", translation: "قارب سريع", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote speedboat on the board.", exampleTranslation: "كتب معلمنا قارب سريع على السبورة." },
  { word: "airplane", translation: "طائرة", partOfSpeech: "noun", difficulty: "easy", example: "I spelled airplane correctly on the quiz.", exampleTranslation: "تهجّيت طائرة بشكل صحيح في الاختبار." },
  { word: "plane", translation: "طائرة", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain plane.", exampleTranslation: "تساعد الصورة على شرح طائرة." },
  { word: "jet", translation: "طائرة نفاثة", partOfSpeech: "noun", difficulty: "easy", example: "We found jet in our reading book.", exampleTranslation: "وجدنا طائرة نفاثة في كتاب القراءة." },
  { word: "balloon", translation: "منطاد", partOfSpeech: "noun", difficulty: "easy", example: "Balloon is a new word for our unit.", exampleTranslation: "منطاد كلمة جديدة لوحدتنا." },
  { word: "bicycle", translation: "دراجة", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed bicycle.", exampleTranslation: "ناقشت دراجة مع زميلي." },
  { word: "scooter", translation: "سكوتر", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about scooter.", exampleTranslation: "يسأل ورق العمل عن سكوتر." },
  { word: "motorcycle", translation: "دراجة نارية", partOfSpeech: "noun", difficulty: "easy", example: "We heard motorcycle in the science video.", exampleTranslation: "سمعنا دراجة نارية في فيلم العلوم." },
  { word: "moped", translation: "دراجة صغيرة", partOfSpeech: "noun", difficulty: "medium", example: "Please copy moped into your notebook.", exampleTranslation: "من فضلك انسخ دراجة صغيرة في دفترك." },
  { word: "cart", translation: "عربة", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of cart.", exampleTranslation: "يُظهر المخطط مثالاً عن عربة." },
  { word: "wheelchair", translation: "كرسي متحرك", partOfSpeech: "noun", difficulty: "medium", example: "Our group used wheelchair in the project.", exampleTranslation: "استخدمت مجموعتنا كرسي متحرك في المشروع." },
  { word: "stroller", translation: "عربة أطفال", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with stroller.", exampleTranslation: "أعطى المعلم مثالاً بـعربة أطفال." },
  { word: "rollerblade", translation: "حذاء تزلج", partOfSpeech: "noun", difficulty: "medium", example: "I underlined rollerblade in the paragraph.", exampleTranslation: "وضعت خطاً تحت حذاء تزلج في الفقرة." },
  { word: "tire", translation: "إطار", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying tire aloud.", exampleTranslation: "تدرّبنا على نطق إطار بصوت عالٍ." },
  { word: "brake", translation: "فرامل", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains brake with a drawing.", exampleTranslation: "يشرح الملصق فرامل برسم." },
  { word: "steering", translation: "توجيه", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with steering.", exampleTranslation: "شارك الجميع جملة فيها توجيه." },
  { word: "accelerator", translation: "مسرّع", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word accelerator.", exampleTranslation: "تضمّن الاختبار كلمة مسرّع." },
  { word: "clutch", translation: "قابض", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word clutch in class today.", exampleTranslation: "تعلّمنا كلمة قابض في الحصة اليوم." },
  { word: "gearbox", translation: "علبة تروس", partOfSpeech: "noun", difficulty: "medium", example: "Can you use gearbox in a sentence?", exampleTranslation: "هل يمكنك استخدام علبة تروس في جملة؟" },
  { word: "exhaust", translation: "عادم", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned exhaust on page ten.", exampleTranslation: "ذكرت القصة عادم في الصفحة العاشرة." },
  { word: "bumper", translation: "مصد", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote bumper on the board.", exampleTranslation: "كتب معلمنا مصد على السبورة." },
  { word: "headlight", translation: "مصباح أمامي", partOfSpeech: "noun", difficulty: "medium", example: "I spelled headlight correctly on the quiz.", exampleTranslation: "تهجّيت مصباح أمامي بشكل صحيح في الاختبار." },
  { word: "taillight", translation: "مصباح خلفي", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain taillight.", exampleTranslation: "تساعد الصورة على شرح مصباح خلفي." },
  { word: "windshield", translation: "زجاج أمامي", partOfSpeech: "noun", difficulty: "medium", example: "We found windshield in our reading book.", exampleTranslation: "وجدنا زجاج أمامي في كتاب القراءة." },
  { word: "horn", translation: "بوق", partOfSpeech: "noun", difficulty: "easy", example: "Horn is a new word for our unit.", exampleTranslation: "بوق كلمة جديدة لوحدتنا." },
  { word: "fuel", translation: "وقود", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed fuel.", exampleTranslation: "ناقشت وقود مع زميلي." },
  { word: "gasoline", translation: "بنزين", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about gasoline.", exampleTranslation: "يسأل ورق العمل عن بنزين." },
  { word: "diesel", translation: "ديزل", partOfSpeech: "noun", difficulty: "medium", example: "We heard diesel in the science video.", exampleTranslation: "سمعنا ديزل في فيلم العلوم." },
  { word: "petrol", translation: "بنزين", partOfSpeech: "noun", difficulty: "medium", example: "Please copy petrol into your notebook.", exampleTranslation: "من فضلك انسخ بنزين في دفترك." },
  { word: "electric", translation: "كهربائي", partOfSpeech: "adjective", difficulty: "easy", example: "The chart shows an example of electric.", exampleTranslation: "يُظهر المخطط مثالاً عن كهربائي." },
  { word: "hybrid", translation: "هجين", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used hybrid in the project.", exampleTranslation: "استخدمت مجموعتنا هجين في المشروع." },
  { word: "ticket", translation: "تذكرة", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with ticket.", exampleTranslation: "أعطى المعلم مثالاً بـتذكرة." },
  { word: "fare", translation: "أجرة", partOfSpeech: "noun", difficulty: "medium", example: "I underlined fare in the paragraph.", exampleTranslation: "وضعت خطاً تحت أجرة في الفقرة." },
  { word: "visa", translation: "تأشيرة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying visa aloud.", exampleTranslation: "تدرّبنا على نطق تأشيرة بصوت عالٍ." },
  { word: "suitcase", translation: "حقيبة سفر", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains suitcase with a drawing.", exampleTranslation: "يشرح الملصق حقيبة سفر برسم." },
  { word: "baggage", translation: "أمتعة", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with baggage.", exampleTranslation: "شارك الجميع جملة فيها أمتعة." },
  { word: "delivery", translation: "توصيل", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word delivery.", exampleTranslation: "تضمّن الاختبار كلمة توصيل." },
  { word: "shipment", translation: "شحنة", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word shipment in class today.", exampleTranslation: "تعلّمنا كلمة شحنة في الحصة اليوم." },
  { word: "package", translation: "طرد", partOfSpeech: "noun", difficulty: "easy", example: "Can you use package in a sentence?", exampleTranslation: "هل يمكنك استخدام طرد في جملة؟" },
  { word: "parcel", translation: "طرد", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned parcel on page ten.", exampleTranslation: "ذكرت القصة طرد في الصفحة العاشرة." },
  { word: "postage", translation: "بريد", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote postage on the board.", exampleTranslation: "كتب معلمنا بريد على السبورة." },
  { word: "tragedy", translation: "تراجيديا", partOfSpeech: "noun", difficulty: "medium", example: "I spelled tragedy correctly on the quiz.", exampleTranslation: "تهجّيت تراجيديا بشكل صحيح في الاختبار." },
  { word: "story", translation: "قصة", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain story.", exampleTranslation: "تساعد الصورة على شرح قصة." },
  { word: "tale", translation: "حكاية", partOfSpeech: "noun", difficulty: "easy", example: "We found tale in our reading book.", exampleTranslation: "وجدنا حكاية في كتاب القراءة." },
  { word: "myth", translation: "أسطورة", partOfSpeech: "noun", difficulty: "medium", example: "Myth is a new word for our unit.", exampleTranslation: "أسطورة كلمة جديدة لوحدتنا." },
  { word: "rhyme", translation: "قافية", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed rhyme.", exampleTranslation: "ناقشت قافية مع زميلي." },
  { word: "note", translation: "نغمة", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about note.", exampleTranslation: "يسأل ورق العمل عن نغمة." },
  { word: "tune", translation: "لحن", partOfSpeech: "noun", difficulty: "easy", example: "We heard tune in the science video.", exampleTranslation: "سمعنا لحن في فيلم العلوم." },
  { word: "song", translation: "أغنية", partOfSpeech: "noun", difficulty: "easy", example: "Please copy song into your notebook.", exampleTranslation: "من فضلك انسخ أغنية في دفترك." },
  { word: "lyric", translation: "كلمات أغنية", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of lyric.", exampleTranslation: "يُظهر المخطط مثالاً عن كلمات أغنية." },
  { word: "solo", translation: "منفرد", partOfSpeech: "noun", difficulty: "medium", example: "Our group used solo in the project.", exampleTranslation: "استخدمت مجموعتنا منفرد في المشروع." },
  { word: "trio", translation: "ثلاثي", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with trio.", exampleTranslation: "أعطى المعلم مثالاً بـثلاثي." },
  { word: "quartet", translation: "رباعي", partOfSpeech: "noun", difficulty: "medium", example: "I underlined quartet in the paragraph.", exampleTranslation: "وضعت خطاً تحت رباعي في الفقرة." },
  { word: "band", translation: "فرقة", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying band aloud.", exampleTranslation: "تدرّبنا على نطق فرقة بصوت عالٍ." },
  { word: "choir", translation: "جوقة", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains choir with a drawing.", exampleTranslation: "يشرح الملصق جوقة برسم." },
  { word: "recital", translation: "حفل", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with recital.", exampleTranslation: "شارك الجميع جملة فيها حفل." },
  { word: "spotlight", translation: "ضوء كشاف", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word spotlight.", exampleTranslation: "تضمّن الاختبار كلمة ضوء كشاف." },
  { word: "costume", translation: "زي", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word costume in class today.", exampleTranslation: "تعلّمنا كلمة زي في الحصة اليوم." },
  { word: "mask", translation: "قناع", partOfSpeech: "noun", difficulty: "easy", example: "Can you use mask in a sentence?", exampleTranslation: "هل يمكنك استخدام قناع في جملة؟" },
  { word: "prop", translation: "دعامة مسرحية", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned prop on page ten.", exampleTranslation: "ذكرت القصة دعامة مسرحية في الصفحة العاشرة." },
  { word: "scenery", translation: "ديكور", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote scenery on the board.", exampleTranslation: "كتب معلمنا ديكور على السبورة." },
  { word: "drawing", translation: "رسم", partOfSpeech: "noun", difficulty: "easy", example: "I spelled drawing correctly on the quiz.", exampleTranslation: "تهجّيت رسم بشكل صحيح في الاختبار." },
  { word: "landscape", translation: "منظر طبيعي", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain landscape.", exampleTranslation: "تساعد الصورة على شرح منظر طبيعي." },
  { word: "stilllife", translation: "طبيعة صامتة", partOfSpeech: "noun", difficulty: "medium", example: "We found stilllife in our reading book.", exampleTranslation: "وجدنا طبيعة صامتة في كتاب القراءة." },
  { word: "carving", translation: "نحت", partOfSpeech: "noun", difficulty: "medium", example: "Carving is a new word for our unit.", exampleTranslation: "نحت كلمة جديدة لوحدتنا." },
  { word: "easel", translation: "حامل لوحة", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed easel.", exampleTranslation: "ناقشت حامل لوحة مع زميلي." },
  { word: "brushstroke", translation: "ضربة فرشاة", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about brushstroke.", exampleTranslation: "يسأل ورق العمل عن ضربة فرشاة." },
  { word: "tone", translation: "درجة لون", partOfSpeech: "noun", difficulty: "medium", example: "We heard tone in the science video.", exampleTranslation: "سمعنا درجة لون في فيلم العلوم." },
  { word: "hue", translation: "لون", partOfSpeech: "noun", difficulty: "medium", example: "Please copy hue into your notebook.", exampleTranslation: "من فضلك انسخ لون في دفترك." },
  { word: "tint", translation: "صبغة", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of tint.", exampleTranslation: "يُظهر المخطط مثالاً عن صبغة." },
  { word: "texture", translation: "ملمس", partOfSpeech: "noun", difficulty: "medium", example: "Our group used texture in the project.", exampleTranslation: "استخدمت مجموعتنا ملمس في المشروع." },
  { word: "style", translation: "أسلوب", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with style.", exampleTranslation: "أعطى المعلم مثالاً بـأسلوب." },
  { word: "weaving", translation: "نسيج", partOfSpeech: "noun", difficulty: "medium", example: "I underlined weaving in the paragraph.", exampleTranslation: "وضعت خطاً تحت نسيج في الفقرة." },
  { word: "photography", translation: "تصوير", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying photography aloud.", exampleTranslation: "تدرّبنا على نطق تصوير بصوت عالٍ." },
  { word: "flash", translation: "فلاش", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains flash with a drawing.", exampleTranslation: "يشرح الملصق فلاش برسم." },
  { word: "masterpiece", translation: "تحفة", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with masterpiece.", exampleTranslation: "شارك الجميع جملة فيها تحفة." },
  { word: "imagination", translation: "خيال", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word imagination.", exampleTranslation: "تضمّن الاختبار كلمة خيال." },
  { word: "inspiration", translation: "إلهام", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word inspiration in class today.", exampleTranslation: "تعلّمنا كلمة إلهام في الحصة اليوم." },
  { word: "talent", translation: "موهبة", partOfSpeech: "noun", difficulty: "easy", example: "Can you use talent in a sentence?", exampleTranslation: "هل يمكنك استخدام موهبة في جملة؟" },
  { word: "skill", translation: "مهارة", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned skill on page ten.", exampleTranslation: "ذكرت القصة مهارة في الصفحة العاشرة." },
  { word: "technique", translation: "تقنية", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote technique on the board.", exampleTranslation: "كتب معلمنا تقنية على السبورة." },
  { word: "achieve", translation: "تحقيق", partOfSpeech: "verb", difficulty: "medium", example: "I spelled achieve correctly on the quiz.", exampleTranslation: "تهجّيت تحقيق بشكل صحيح في الاختبار." },
  { word: "act", translation: "تصرف", partOfSpeech: "verb", difficulty: "easy", example: "The picture helps explain act.", exampleTranslation: "تساعد الصورة على شرح تصرف." },
  { word: "admire", translation: "إعجاب", partOfSpeech: "verb", difficulty: "medium", example: "We found admire in our reading book.", exampleTranslation: "وجدنا إعجاب في كتاب القراءة." },
  { word: "admit", translation: "اعتراف", partOfSpeech: "verb", difficulty: "medium", example: "Admit is a new word for our unit.", exampleTranslation: "اعتراف كلمة جديدة لوحدتنا." },
  { word: "advise", translation: "نصح", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed advise.", exampleTranslation: "ناقشت نصح مع زميلي." },
  { word: "allow", translation: "سماح", partOfSpeech: "verb", difficulty: "easy", example: "The worksheet asks about allow.", exampleTranslation: "يسأل ورق العمل عن سماح." },
  { word: "apply", translation: "تطبيق", partOfSpeech: "verb", difficulty: "easy", example: "We heard apply in the science video.", exampleTranslation: "سمعنا تطبيق في فيلم العلوم." },
  { word: "argue", translation: "جدال", partOfSpeech: "verb", difficulty: "easy", example: "Please copy argue into your notebook.", exampleTranslation: "من فضلك انسخ جدال في دفترك." },
  { word: "arrive", translation: "وصول", partOfSpeech: "verb", difficulty: "easy", example: "The chart shows an example of arrive.", exampleTranslation: "يُظهر المخطط مثالاً عن وصول." },
  { word: "assist", translation: "مساعدة", partOfSpeech: "verb", difficulty: "medium", example: "Our group used assist in the project.", exampleTranslation: "استخدمت مجموعتنا مساعدة في المشروع." },
  { word: "attach", translation: "إرفاق", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with attach.", exampleTranslation: "أعطى المعلم مثالاً بـإرفاق." },
  { word: "avoid", translation: "تجنب", partOfSpeech: "verb", difficulty: "easy", example: "I underlined avoid in the paragraph.", exampleTranslation: "وضعت خطاً تحت تجنب في الفقرة." },
  { word: "bake", translation: "خبز", partOfSpeech: "verb", difficulty: "easy", example: "We practiced saying bake aloud.", exampleTranslation: "تدرّبنا على نطق خبز بصوت عالٍ." },
  { word: "belong", translation: "انتماء", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains belong with a drawing.", exampleTranslation: "يشرح الملصق انتماء برسم." },
  { word: "bet", translation: "رهان", partOfSpeech: "verb", difficulty: "medium", example: "Everyone shared a sentence with bet.", exampleTranslation: "شارك الجميع جملة فيها رهان." },
  { word: "bite", translation: "عض", partOfSpeech: "verb", difficulty: "easy", example: "The quiz included the word bite.", exampleTranslation: "تضمّن الاختبار كلمة عض." },
  { word: "blow", translation: "نفخ", partOfSpeech: "verb", difficulty: "easy", example: "We learned the word blow in class today.", exampleTranslation: "تعلّمنا كلمة نفخ في الحصة اليوم." },
  { word: "boil", translation: "غليان", partOfSpeech: "verb", difficulty: "easy", example: "Can you use boil in a sentence?", exampleTranslation: "هل يمكنك استخدام غليان في جملة؟" },
  { word: "bow", translation: "انحناء", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned bow on page ten.", exampleTranslation: "ذكرت القصة انحناء في الصفحة العاشرة." },
  { word: "break", translation: "كسر", partOfSpeech: "verb", difficulty: "easy", example: "Our teacher wrote break on the board.", exampleTranslation: "كتب معلمنا كسر على السبورة." },
  { word: "breathe", translation: "تنفس", partOfSpeech: "verb", difficulty: "easy", example: "I spelled breathe correctly on the quiz.", exampleTranslation: "تهجّيت تنفس بشكل صحيح في الاختبار." },
  { word: "bring", translation: "إحضار", partOfSpeech: "verb", difficulty: "easy", example: "The picture helps explain bring.", exampleTranslation: "تساعد الصورة على شرح إحضار." },
  { word: "burn", translation: "حرق", partOfSpeech: "verb", difficulty: "easy", example: "We found burn in our reading book.", exampleTranslation: "وجدنا حرق في كتاب القراءة." },
  { word: "buy", translation: "شراء", partOfSpeech: "verb", difficulty: "easy", example: "Buy is a new word for our unit.", exampleTranslation: "شراء كلمة جديدة لوحدتنا." },
  { word: "camp", translation: "تخييم", partOfSpeech: "verb", difficulty: "easy", example: "My partner and I discussed camp.", exampleTranslation: "ناقشت تخييم مع زميلي." },
  { word: "care", translation: "اهتمام", partOfSpeech: "verb", difficulty: "easy", example: "The worksheet asks about care.", exampleTranslation: "يسأل ورق العمل عن اهتمام." },
  { word: "change", translation: "تغيير", partOfSpeech: "verb", difficulty: "easy", example: "We heard change in the science video.", exampleTranslation: "سمعنا تغيير في فيلم العلوم." },
  { word: "chase", translation: "مطاردة", partOfSpeech: "verb", difficulty: "easy", example: "Please copy chase into your notebook.", exampleTranslation: "من فضلك انسخ مطاردة في دفترك." },
  { word: "check", translation: "فحص", partOfSpeech: "verb", difficulty: "easy", example: "The chart shows an example of check.", exampleTranslation: "يُظهر المخطط مثالاً عن فحص." },
  { word: "cheer", translation: "هتاف", partOfSpeech: "verb", difficulty: "easy", example: "Our group used cheer in the project.", exampleTranslation: "استخدمت مجموعتنا هتاف في المشروع." },
  { word: "chop", translation: "تقطيع", partOfSpeech: "verb", difficulty: "easy", example: "The teacher gave an example with chop.", exampleTranslation: "أعطى المعلم مثالاً بـتقطيع." },
  { word: "climb", translation: "تسلق", partOfSpeech: "verb", difficulty: "easy", example: "I underlined climb in the paragraph.", exampleTranslation: "وضعت خطاً تحت تسلق في الفقرة." },
  { word: "come", translation: "مجيء", partOfSpeech: "verb", difficulty: "easy", example: "We practiced saying come aloud.", exampleTranslation: "تدرّبنا على نطق مجيء بصوت عالٍ." },
  { word: "communicate", translation: "تواصل", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains communicate with a drawing.", exampleTranslation: "يشرح الملصق تواصل برسم." },
  { word: "complain", translation: "شكوى", partOfSpeech: "verb", difficulty: "medium", example: "Everyone shared a sentence with complain.", exampleTranslation: "شارك الجميع جملة فيها شكوى." },
  { word: "complete", translation: "إكمال", partOfSpeech: "verb", difficulty: "easy", example: "The quiz included the word complete.", exampleTranslation: "تضمّن الاختبار كلمة إكمال." },
];
