/** Grade 6 chunk B — science & math vocabulary. */
export const GRADE6_CHUNK_B = [
  { word: "organism", translation: "كائن حي", partOfSpeech: "noun", difficulty: "medium", example: "A tiny organism can live in a drop of water.", exampleTranslation: "يمكن لكائن حي صغير أن يعيش في قطرة ماء." },
  { word: "ecosystem", translation: "نظام بيئي", partOfSpeech: "noun", difficulty: "hard", example: "A forest is a rich ecosystem.", exampleTranslation: "الغابة نظام بيئي غني." },
  { word: "environment", translation: "بيئة", partOfSpeech: "noun", difficulty: "medium", example: "We must protect the environment.", exampleTranslation: "علينا أن نحمي البيئة." },
  { word: "atmosphere", translation: "غلاف جوي", partOfSpeech: "noun", difficulty: "hard", example: "The atmosphere protects us from the sun.", exampleTranslation: "يحمينا الغلاف الجوي من الشمس." },
  { word: "climate", translation: "مناخ", partOfSpeech: "noun", difficulty: "medium", example: "The desert has a hot, dry climate.", exampleTranslation: "للصحراء مناخ حار وجاف." },
  { word: "energy", translation: "طاقة", partOfSpeech: "noun", difficulty: "easy", example: "The sun gives us light energy.", exampleTranslation: "تمنحنا الشمس طاقة ضوئية." },
  { word: "force", translation: "قوة", partOfSpeech: "noun", difficulty: "medium", example: "A push is a kind of force.", exampleTranslation: "الدفع نوع من القوة." },
  { word: "motion", translation: "حركة", partOfSpeech: "noun", difficulty: "medium", example: "The ball stayed in motion across the field.", exampleTranslation: "بقيت الكرة في حركة عبر الملعب." },
  { word: "gravity", translation: "جاذبية", partOfSpeech: "noun", difficulty: "hard", example: "Gravity pulls objects toward the ground.", exampleTranslation: "تجذب الجاذبية الأجسام نحو الأرض." },
  { word: "friction", translation: "احتكاك", partOfSpeech: "noun", difficulty: "hard", example: "Friction slows the moving car.", exampleTranslation: "يبطّئ الاحتكاك السيارة المتحركة." },
  { word: "molecule", translation: "جزيء", partOfSpeech: "noun", difficulty: "hard", example: "A water molecule has three atoms.", exampleTranslation: "يتكوّن جزيء الماء من ثلاث ذرات." },
  { word: "atom", translation: "ذرّة", partOfSpeech: "noun", difficulty: "hard", example: "An atom is far too small to see.", exampleTranslation: "الذرّة أصغر من أن تُرى." },
  { word: "element", translation: "عنصر", partOfSpeech: "noun", difficulty: "medium", example: "Oxygen is an important element.", exampleTranslation: "الأكسجين عنصر مهم." },
  { word: "compound", translation: "مركّب", partOfSpeech: "noun", difficulty: "hard", example: "Water is a compound of hydrogen and oxygen.", exampleTranslation: "الماء مركّب من الهيدروجين والأكسجين." },
  { word: "mixture", translation: "خليط", partOfSpeech: "noun", difficulty: "medium", example: "Sand and salt form a mixture.", exampleTranslation: "يكوّن الرمل والملح خليطاً." },
  { word: "solution", translation: "محلول", partOfSpeech: "noun", difficulty: "medium", example: "Salt dissolves to make a solution.", exampleTranslation: "يذوب الملح ليكوّن محلولاً." },
  { word: "reaction", translation: "تفاعل", partOfSpeech: "noun", difficulty: "hard", example: "The reaction produced a lot of heat.", exampleTranslation: "أنتج التفاعل كمية كبيرة من الحرارة." },
  { word: "experiment", translation: "تجربة", partOfSpeech: "noun", difficulty: "medium", example: "We did an experiment with magnets.", exampleTranslation: "أجرينا تجربة بالمغناطيس." },
  { word: "hypothesis", translation: "فرضية", partOfSpeech: "noun", difficulty: "hard", example: "Our hypothesis was that plants grow toward light.", exampleTranslation: "كانت فرضيتنا أن النباتات تنمو نحو الضوء." },
  { word: "observation", translation: "ملاحظة", partOfSpeech: "noun", difficulty: "medium", example: "Write down your observation in the notebook.", exampleTranslation: "دوّن ملاحظتك في الدفتر." },
  { word: "theory", translation: "نظرية", partOfSpeech: "noun", difficulty: "hard", example: "A scientific theory rests on strong evidence.", exampleTranslation: "تستند النظرية العلمية إلى أدلة قوية." },
  { word: "cell", translation: "خلية", partOfSpeech: "noun", difficulty: "medium", example: "Every living thing is made of cells.", exampleTranslation: "كل كائن حي مكوّن من خلايا." },
  { word: "tissue", translation: "نسيج", partOfSpeech: "noun", difficulty: "hard", example: "Muscle tissue helps us move.", exampleTranslation: "يساعدنا النسيج العضلي على الحركة." },
  { word: "species", translation: "نوع", partOfSpeech: "noun", difficulty: "hard", example: "This island has a rare species of bird.", exampleTranslation: "في هذه الجزيرة نوع نادر من الطيور." },
  { word: "population", translation: "تعداد/مجموع", partOfSpeech: "noun", difficulty: "medium", example: "The deer population grew this year.", exampleTranslation: "ازداد عدد الغزلان هذا العام." },
  { word: "evolution", translation: "تطوّر", partOfSpeech: "noun", difficulty: "hard", example: "Evolution explains how species change.", exampleTranslation: "يشرح التطوّر كيف تتغيّر الأنواع." },
  { word: "adaptation", translation: "تكيّف", partOfSpeech: "noun", difficulty: "hard", example: "Thick fur is an adaptation to cold.", exampleTranslation: "الفراء الكثيف تكيّف مع البرد." },
  { word: "predator", translation: "مفترس", partOfSpeech: "noun", difficulty: "medium", example: "The lion is a strong predator.", exampleTranslation: "الأسد مفترس قوي." },
  { word: "prey", translation: "فريسة", partOfSpeech: "noun", difficulty: "medium", example: "The rabbit was the eagle's prey.", exampleTranslation: "كان الأرنب فريسة النسر." },
  { word: "nutrient", translation: "مغذٍّ", partOfSpeech: "noun", difficulty: "hard", example: "Plants take nutrients from the soil.", exampleTranslation: "تأخذ النباتات المغذّيات من التربة." },
  { word: "photosynthesis", translation: "تركيب ضوئي", partOfSpeech: "noun", difficulty: "hard", example: "Photosynthesis lets plants make food.", exampleTranslation: "يتيح التركيب الضوئي للنباتات صنع غذائها." },
  { word: "respiration", translation: "تنفّس", partOfSpeech: "noun", difficulty: "hard", example: "Respiration brings oxygen into the body.", exampleTranslation: "يُدخل التنفّس الأكسجين إلى الجسم." },
  { word: "digestion", translation: "هضم", partOfSpeech: "noun", difficulty: "hard", example: "Digestion breaks food into small pieces.", exampleTranslation: "يفكّك الهضم الطعام إلى أجزاء صغيرة." },
  { word: "skeleton", translation: "هيكل عظمي", partOfSpeech: "noun", difficulty: "medium", example: "The skeleton supports the body.", exampleTranslation: "يدعم الهيكل العظمي الجسم." },
  { word: "muscle", translation: "عضلة", partOfSpeech: "noun", difficulty: "medium", example: "Exercise makes each muscle stronger.", exampleTranslation: "تجعل التمارين كل عضلة أقوى." },
  { word: "organ", translation: "عضو", partOfSpeech: "noun", difficulty: "medium", example: "The heart is a vital organ.", exampleTranslation: "القلب عضو حيوي." },
  { word: "nerve", translation: "عصب", partOfSpeech: "noun", difficulty: "hard", example: "A nerve carries signals to the brain.", exampleTranslation: "ينقل العصب الإشارات إلى الدماغ." },
  { word: "bacteria", translation: "بكتيريا", partOfSpeech: "noun", difficulty: "hard", example: "Some bacteria help us digest food.", exampleTranslation: "تساعدنا بعض البكتيريا على هضم الطعام." },
  { word: "fungus", translation: "فطر", partOfSpeech: "noun", difficulty: "hard", example: "A mushroom is a kind of fungus.", exampleTranslation: "الفطر عيش الغراب نوع من الفطريات." },
  { word: "mineral", translation: "معدن", partOfSpeech: "noun", difficulty: "medium", example: "Salt is a mineral found in the sea.", exampleTranslation: "الملح معدن يوجد في البحر." },
  { word: "particle", translation: "جسيم", partOfSpeech: "noun", difficulty: "hard", example: "Dust is made of tiny particles.", exampleTranslation: "يتكوّن الغبار من جسيمات صغيرة." },
  { word: "vapor", translation: "بخار", partOfSpeech: "noun", difficulty: "hard", example: "Boiling water turns into vapor.", exampleTranslation: "يتحول الماء المغلي إلى بخار." },
  { word: "evaporate", translation: "يتبخّر", partOfSpeech: "verb", difficulty: "hard", example: "The puddle will evaporate in the sun.", exampleTranslation: "ستتبخّر البركة في الشمس." },
  { word: "condense", translation: "يتكثّف", partOfSpeech: "verb", difficulty: "hard", example: "Water vapor condenses into clouds.", exampleTranslation: "يتكثّف بخار الماء ليصبح غيوماً." },
  { word: "temperature", translation: "درجة حرارة", partOfSpeech: "noun", difficulty: "medium", example: "The temperature dropped at night.", exampleTranslation: "انخفضت درجة الحرارة في الليل." },
  { word: "pressure", translation: "ضغط", partOfSpeech: "noun", difficulty: "hard", example: "Air pressure changes with the weather.", exampleTranslation: "يتغيّر ضغط الهواء مع الطقس." },
  { word: "volume", translation: "حجم", partOfSpeech: "noun", difficulty: "medium", example: "We measured the volume of the box.", exampleTranslation: "قِسنا حجم الصندوق." },
  { word: "density", translation: "كثافة", partOfSpeech: "noun", difficulty: "hard", example: "Oil has a lower density than water.", exampleTranslation: "كثافة الزيت أقل من كثافة الماء." },
  { word: "mass", translation: "كتلة", partOfSpeech: "noun", difficulty: "medium", example: "A balance measures the mass of an object.", exampleTranslation: "يقيس الميزان كتلة الجسم." },
  { word: "magnet", translation: "مغناطيس", partOfSpeech: "noun", difficulty: "medium", example: "A magnet attracts iron nails.", exampleTranslation: "يجذب المغناطيس مسامير الحديد." },
  { word: "circuit", translation: "دائرة كهربائية", partOfSpeech: "noun", difficulty: "hard", example: "The bulb lights up when the circuit is closed.", exampleTranslation: "يضيء المصباح عند إغلاق الدائرة الكهربائية." },
  { word: "current", translation: "تيار", partOfSpeech: "noun", difficulty: "medium", example: "An electric current flows through the wire.", exampleTranslation: "يسري التيار الكهربائي عبر السلك." },
  { word: "conductor", translation: "موصِل", partOfSpeech: "noun", difficulty: "hard", example: "Metal is a good conductor of heat.", exampleTranslation: "المعدن موصِل جيد للحرارة." },
  { word: "insulator", translation: "عازل", partOfSpeech: "noun", difficulty: "hard", example: "Rubber is a useful insulator.", exampleTranslation: "المطاط عازل مفيد." },
  { word: "orbit", translation: "مدار", partOfSpeech: "noun", difficulty: "medium", example: "The Earth moves in an orbit around the sun.", exampleTranslation: "تتحرك الأرض في مدار حول الشمس." },
  { word: "planet", translation: "كوكب", partOfSpeech: "noun", difficulty: "easy", example: "Mars is a red planet.", exampleTranslation: "المريخ كوكب أحمر." },
  { word: "galaxy", translation: "مجرّة", partOfSpeech: "noun", difficulty: "hard", example: "Our galaxy holds billions of stars.", exampleTranslation: "تضم مجرّتنا مليارات النجوم." },
  { word: "comet", translation: "مذنّب", partOfSpeech: "noun", difficulty: "hard", example: "A bright comet crossed the night sky.", exampleTranslation: "عبر مذنّب لامع سماء الليل." },
  { word: "satellite", translation: "قمر صناعي", partOfSpeech: "noun", difficulty: "hard", example: "A satellite sends signals to phones.", exampleTranslation: "يرسل القمر الصناعي إشارات إلى الهواتف." },
  { word: "telescope", translation: "تلسكوب", partOfSpeech: "noun", difficulty: "medium", example: "We watched the moon through a telescope.", exampleTranslation: "شاهدنا القمر عبر تلسكوب." },
  { word: "microscope", translation: "مجهر", partOfSpeech: "noun", difficulty: "medium", example: "We used a microscope to see the cells.", exampleTranslation: "استخدمنا مجهراً لرؤية الخلايا." },
  { word: "specimen", translation: "عيّنة", partOfSpeech: "noun", difficulty: "hard", example: "The leaf was a perfect specimen.", exampleTranslation: "كانت الورقة عيّنة مثالية." },
  { word: "fossil", translation: "أحفورة", partOfSpeech: "noun", difficulty: "medium", example: "They found a fossil of an old fish.", exampleTranslation: "عثروا على أحفورة لسمكة قديمة." },
  { word: "volcano", translation: "بركان", partOfSpeech: "noun", difficulty: "medium", example: "The volcano sent ash into the sky.", exampleTranslation: "قذف البركان الرماد في السماء." },
  { word: "earthquake", translation: "زلزال", partOfSpeech: "noun", difficulty: "medium", example: "The earthquake shook the whole town.", exampleTranslation: "هزّ الزلزال البلدة بأكملها." },
  { word: "erosion", translation: "تعرية", partOfSpeech: "noun", difficulty: "hard", example: "Water erosion carved the deep valley.", exampleTranslation: "نحتت تعرية الماء الوادي العميق." },
  { word: "mineralize", translation: "يتمعدن", partOfSpeech: "verb", difficulty: "hard", example: "Bones slowly mineralize into fossils.", exampleTranslation: "تتمعدن العظام ببطء لتصبح أحافير." },
  { word: "magma", translation: "صهارة", partOfSpeech: "noun", difficulty: "hard", example: "Hot magma rises beneath the volcano.", exampleTranslation: "ترتفع الصهارة الساخنة تحت البركان." },
  { word: "glacier", translation: "نهر جليدي", partOfSpeech: "noun", difficulty: "hard", example: "The glacier moves a few inches each year.", exampleTranslation: "يتحرك النهر الجليدي بضع بوصات كل عام." },
  { word: "median", translation: "وسيط", partOfSpeech: "noun", difficulty: "hard", example: "The median is the middle number in a list.", exampleTranslation: "الوسيط هو العدد الأوسط في القائمة." },
  { word: "fraction", translation: "كسر", partOfSpeech: "noun", difficulty: "medium", example: "One half is a simple fraction.", exampleTranslation: "النصف كسر بسيط." },
  { word: "decimal", translation: "عدد عشري", partOfSpeech: "noun", difficulty: "medium", example: "Write the answer as a decimal.", exampleTranslation: "اكتب الإجابة على هيئة عدد عشري." },
  { word: "percentage", translation: "نسبة مئوية", partOfSpeech: "noun", difficulty: "medium", example: "Fifty percent is a percentage.", exampleTranslation: "خمسون في المئة نسبة مئوية." },
  { word: "ratio", translation: "نسبة", partOfSpeech: "noun", difficulty: "hard", example: "The ratio of boys to girls is two to one.", exampleTranslation: "نسبة الأولاد إلى البنات اثنان إلى واحد." },
  { word: "proportion", translation: "تناسب", partOfSpeech: "noun", difficulty: "hard", example: "The two recipes keep the same proportion.", exampleTranslation: "تحافظ الوصفتان على التناسب نفسه." },
  { word: "equation", translation: "معادلة", partOfSpeech: "noun", difficulty: "hard", example: "Solve the equation to find x.", exampleTranslation: "حلّ المعادلة لإيجاد قيمة x." },
  { word: "variable", translation: "متغيّر", partOfSpeech: "noun", difficulty: "hard", example: "The letter x is a variable.", exampleTranslation: "الحرف x متغيّر." },
  { word: "formula", translation: "صيغة", partOfSpeech: "noun", difficulty: "hard", example: "Use the formula to find the area.", exampleTranslation: "استخدم الصيغة لإيجاد المساحة." },
  { word: "perimeter", translation: "محيط", partOfSpeech: "noun", difficulty: "medium", example: "Add the sides to find the perimeter.", exampleTranslation: "اجمع الأضلاع لإيجاد المحيط." },
  { word: "area", translation: "مساحة", partOfSpeech: "noun", difficulty: "medium", example: "The area of the room is large.", exampleTranslation: "مساحة الغرفة كبيرة." },
  { word: "diameter", translation: "قطر", partOfSpeech: "noun", difficulty: "hard", example: "The diameter passes through the center.", exampleTranslation: "يمرّ القطر عبر المركز." },
  { word: "radius", translation: "نصف قطر", partOfSpeech: "noun", difficulty: "hard", example: "The radius is half the diameter.", exampleTranslation: "نصف القطر يساوي نصف طول القطر." },
  { word: "average", translation: "متوسّط", partOfSpeech: "noun", difficulty: "medium", example: "Find the average of these numbers.", exampleTranslation: "أوجد متوسّط هذه الأعداد." },
  { word: "graph", translation: "رسم بياني", partOfSpeech: "noun", difficulty: "medium", example: "The graph shows the rise in sales.", exampleTranslation: "يُظهر الرسم البياني ارتفاع المبيعات." },
  { word: "multiply", translation: "يضرب", partOfSpeech: "verb", difficulty: "easy", example: "Multiply five by three to get fifteen.", exampleTranslation: "اضرب خمسة في ثلاثة لتحصل على خمسة عشر." },
  { word: "divide", translation: "يقسم", partOfSpeech: "verb", difficulty: "easy", example: "Divide the cake into eight pieces.", exampleTranslation: "اقسم الكعكة إلى ثماني قطع." },
  { word: "product", translation: "حاصل ضرب", partOfSpeech: "noun", difficulty: "medium", example: "The product of two and four is eight.", exampleTranslation: "حاصل ضرب اثنين في أربعة هو ثمانية." },
  { word: "quotient", translation: "حاصل قسمة", partOfSpeech: "noun", difficulty: "hard", example: "The quotient of ten and two is five.", exampleTranslation: "حاصل قسمة عشرة على اثنين هو خمسة." },
  { word: "remainder", translation: "باقي", partOfSpeech: "noun", difficulty: "hard", example: "Seven divided by two leaves a remainder of one.", exampleTranslation: "سبعة مقسومة على اثنين تترك باقياً مقداره واحد." },
  { word: "factor", translation: "عامل", partOfSpeech: "noun", difficulty: "hard", example: "Three is a factor of nine.", exampleTranslation: "ثلاثة عامل من عوامل تسعة." },
  { word: "multiple", translation: "مضاعف", partOfSpeech: "noun", difficulty: "hard", example: "Ten is a multiple of five.", exampleTranslation: "عشرة مضاعف للعدد خمسة." },
  { word: "integer", translation: "عدد صحيح", partOfSpeech: "noun", difficulty: "hard", example: "Negative three is an integer.", exampleTranslation: "سالب ثلاثة عدد صحيح." },
  { word: "estimation", translation: "تقدير", partOfSpeech: "noun", difficulty: "medium", example: "My estimation of the total was close.", exampleTranslation: "كان تقديري للمجموع قريباً." },
  { word: "angle", translation: "زاوية", partOfSpeech: "noun", difficulty: "medium", example: "A right angle measures ninety degrees.", exampleTranslation: "تقيس الزاوية القائمة تسعين درجة." },
  { word: "vertical", translation: "عمودي/رأسي", partOfSpeech: "adjective", difficulty: "medium", example: "The wall stands in a vertical line.", exampleTranslation: "يقف الجدار في خط رأسي." },
  { word: "horizontal", translation: "أفقي", partOfSpeech: "adjective", difficulty: "medium", example: "The floor is a horizontal surface.", exampleTranslation: "الأرضية سطح أفقي." },
  { word: "parallel", translation: "متوازٍ", partOfSpeech: "adjective", difficulty: "hard", example: "Train tracks are parallel lines.", exampleTranslation: "قضبان القطار خطوط متوازية." },
  { word: "symmetry", translation: "تماثل", partOfSpeech: "noun", difficulty: "hard", example: "A butterfly's wings show symmetry.", exampleTranslation: "تُظهر أجنحة الفراشة تماثلاً." },
  { word: "pattern", translation: "نمط", partOfSpeech: "noun", difficulty: "medium", example: "The numbers follow a clear pattern.", exampleTranslation: "تتبع الأعداد نمطاً واضحاً." },
  { word: "sequence", translation: "متتالية", partOfSpeech: "noun", difficulty: "hard", example: "Two, four, six is a simple sequence.", exampleTranslation: "اثنان، أربعة، ستة متتالية بسيطة." },
  { word: "approximate", translation: "تقريبي", partOfSpeech: "adjective", difficulty: "hard", example: "The approximate time of arrival is noon.", exampleTranslation: "الوقت التقريبي للوصول هو الظهر." },
  { word: "quantity", translation: "كمية", partOfSpeech: "noun", difficulty: "medium", example: "We measured the quantity of water.", exampleTranslation: "قِسنا كمية الماء." },
  { word: "react", translation: "يتفاعل", partOfSpeech: "verb", difficulty: "medium", example: "Some metals react with water.", exampleTranslation: "تتفاعل بعض المعادن مع الماء." },
  { word: "absorb", translation: "يمتصّ", partOfSpeech: "verb", difficulty: "medium", example: "Dry soil absorbs the rain quickly.", exampleTranslation: "تمتصّ التربة الجافة المطر بسرعة." },
  { word: "dissolve", translation: "يذوب", partOfSpeech: "verb", difficulty: "medium", example: "Sugar will dissolve in hot tea.", exampleTranslation: "يذوب السكر في الشاي الساخن." },
  { word: "freeze", translation: "يتجمّد", partOfSpeech: "verb", difficulty: "easy", example: "Water will freeze in the cold.", exampleTranslation: "يتجمّد الماء في البرد." },
  { word: "melt", translation: "يذوب/ينصهر", partOfSpeech: "verb", difficulty: "easy", example: "The ice began to melt in the sun.", exampleTranslation: "بدأ الجليد يذوب في الشمس." },
  { word: "expand", translation: "يتمدّد", partOfSpeech: "verb", difficulty: "hard", example: "Metal can expand when it is heated.", exampleTranslation: "يتمدّد المعدن عند تسخينه." },
  { word: "contract", translation: "ينكمش", partOfSpeech: "verb", difficulty: "hard", example: "Materials contract when they cool.", exampleTranslation: "تنكمش المواد عندما تبرد." },
  { word: "vibrate", translation: "يهتزّ", partOfSpeech: "verb", difficulty: "hard", example: "The strings vibrate to make sound.", exampleTranslation: "تهتزّ الأوتار لتصدر صوتاً." },
  { word: "radiate", translation: "يشعّ", partOfSpeech: "verb", difficulty: "hard", example: "The hot stove radiates heat into the room.", exampleTranslation: "يشعّ الموقد الساخن حرارة في الغرفة." },
  { word: "transparent", translation: "شفّاف", partOfSpeech: "adjective", difficulty: "hard", example: "Clean glass is transparent.", exampleTranslation: "الزجاج النظيف شفّاف." },
  { word: "opaque", translation: "معتم", partOfSpeech: "adjective", difficulty: "hard", example: "A wooden door is opaque.", exampleTranslation: "الباب الخشبي معتم." },
  { word: "flexible", translation: "مرن", partOfSpeech: "adjective", difficulty: "medium", example: "Rubber is a flexible material.", exampleTranslation: "المطاط مادة مرنة." },
  { word: "solid", translation: "صلب", partOfSpeech: "noun", difficulty: "easy", example: "Ice is the solid form of water.", exampleTranslation: "الجليد هو الحالة الصلبة للماء." },
  { word: "liquid", translation: "سائل", partOfSpeech: "noun", difficulty: "easy", example: "Milk is a liquid we drink.", exampleTranslation: "الحليب سائل نشربه." },
  { word: "gas", translation: "غاز", partOfSpeech: "noun", difficulty: "easy", example: "Air is a mixture of gases.", exampleTranslation: "الهواء خليط من الغازات." },
  { word: "oxygen", translation: "أكسجين", partOfSpeech: "noun", difficulty: "medium", example: "We breathe oxygen to stay alive.", exampleTranslation: "نتنفّس الأكسجين لنبقى أحياء." },
  { word: "carbon", translation: "كربون", partOfSpeech: "noun", difficulty: "medium", example: "Diamonds are made of carbon.", exampleTranslation: "يتكوّن الألماس من الكربون." },
  { word: "hydrogen", translation: "هيدروجين", partOfSpeech: "noun", difficulty: "hard", example: "Hydrogen is the lightest element.", exampleTranslation: "الهيدروجين أخفّ العناصر." },
  { word: "nitrogen", translation: "نيتروجين", partOfSpeech: "noun", difficulty: "hard", example: "Most of the air is nitrogen.", exampleTranslation: "معظم الهواء نيتروجين." },
  { word: "acid", translation: "حمض", partOfSpeech: "noun", difficulty: "medium", example: "Lemon juice is a mild acid.", exampleTranslation: "عصير الليمون حمض خفيف." },
  { word: "base", translation: "قاعدة (كيمياء)", partOfSpeech: "noun", difficulty: "hard", example: "Soap acts like a base in water.", exampleTranslation: "يتصرّف الصابون كقاعدة في الماء." },
  { word: "gene", translation: "جين", partOfSpeech: "noun", difficulty: "hard", example: "A gene carries information from parents.", exampleTranslation: "يحمل الجين معلومات من الوالدين." },
  { word: "trait", translation: "صفة", partOfSpeech: "noun", difficulty: "hard", example: "Eye color is an inherited trait.", exampleTranslation: "لون العين صفة وراثية." },
  { word: "inherit", translation: "يرث", partOfSpeech: "verb", difficulty: "hard", example: "Children inherit features from their parents.", exampleTranslation: "يرث الأطفال صفات من والديهم." },
  { word: "circulate", translation: "يدور", partOfSpeech: "verb", difficulty: "hard", example: "Blood circulates through the body.", exampleTranslation: "يدور الدم في الجسم." },
  { word: "function", translation: "وظيفة", partOfSpeech: "noun", difficulty: "medium", example: "The function of the lungs is to breathe.", exampleTranslation: "وظيفة الرئتين هي التنفّس." },
  { word: "system", translation: "نظام", partOfSpeech: "noun", difficulty: "medium", example: "The solar system has eight planets.", exampleTranslation: "يضم النظام الشمسي ثمانية كواكب." },
  { word: "process", translation: "عملية", partOfSpeech: "noun", difficulty: "medium", example: "Growing a plant is a slow process.", exampleTranslation: "زراعة نبتة عملية بطيئة." },
  { word: "cycle", translation: "دورة", partOfSpeech: "noun", difficulty: "medium", example: "The water cycle repeats every day.", exampleTranslation: "تتكرّر دورة الماء كل يوم." },
  { word: "renewable", translation: "متجدّد", partOfSpeech: "adjective", difficulty: "hard", example: "Wind is a renewable source of energy.", exampleTranslation: "الرياح مصدر متجدّد للطاقة." },
  { word: "pollution", translation: "تلوّث", partOfSpeech: "noun", difficulty: "medium", example: "Cars cause a lot of air pollution.", exampleTranslation: "تسبّب السيارات الكثير من تلوّث الهواء." },
  { word: "recycle", translation: "يعيد التدوير", partOfSpeech: "verb", difficulty: "medium", example: "We recycle paper and plastic at school.", exampleTranslation: "نعيد تدوير الورق والبلاستيك في المدرسة." },
  { word: "conserve", translation: "يحافظ على/يصون", partOfSpeech: "verb", difficulty: "hard", example: "We should conserve water at home.", exampleTranslation: "علينا أن نحافظ على الماء في المنزل." },
  { word: "extinct", translation: "منقرض", partOfSpeech: "adjective", difficulty: "hard", example: "The dinosaurs are now extinct.", exampleTranslation: "الديناصورات منقرضة الآن." },
  { word: "endangered", translation: "مهدّد بالانقراض", partOfSpeech: "adjective", difficulty: "hard", example: "The tiger is an endangered animal.", exampleTranslation: "النمر حيوان مهدّد بالانقراض." },
  { word: "migrate", translation: "يهاجر", partOfSpeech: "verb", difficulty: "hard", example: "Birds migrate south in winter.", exampleTranslation: "تهاجر الطيور جنوباً في الشتاء." },
  { word: "hibernate", translation: "يسبت", partOfSpeech: "verb", difficulty: "hard", example: "Bears hibernate during the cold months.", exampleTranslation: "تسبت الدببة خلال الأشهر الباردة." },
  { word: "germinate", translation: "ينبت", partOfSpeech: "verb", difficulty: "hard", example: "Seeds germinate when they get water.", exampleTranslation: "تنبت البذور عندما تحصل على الماء." },
  { word: "pollinate", translation: "يلقّح", partOfSpeech: "verb", difficulty: "hard", example: "Bees pollinate many flowers.", exampleTranslation: "تلقّح النحل كثيراً من الأزهار." },
  { word: "thermometer", translation: "ميزان حرارة", partOfSpeech: "noun", difficulty: "medium", example: "The thermometer shows the temperature.", exampleTranslation: "يُظهر ميزان الحرارة درجة الحرارة." },
  { word: "laboratory", translation: "مختبر", partOfSpeech: "noun", difficulty: "medium", example: "We do experiments in the laboratory.", exampleTranslation: "نُجري التجارب في المختبر." },
  { word: "apparatus", translation: "جهاز", partOfSpeech: "noun", difficulty: "hard", example: "The science apparatus sat on the bench.", exampleTranslation: "كان جهاز العلوم على الطاولة." },
  { word: "procedure", translation: "إجراء", partOfSpeech: "noun", difficulty: "hard", example: "Follow the procedure step by step.", exampleTranslation: "اتبع الإجراء خطوة بخطوة." },
  { word: "measurement", translation: "قياس", partOfSpeech: "noun", difficulty: "medium", example: "Record each measurement in the table.", exampleTranslation: "سجّل كل قياس في الجدول." },
  { word: "result", translation: "نتيجة", partOfSpeech: "noun", difficulty: "easy", example: "The result of the test surprised us.", exampleTranslation: "فاجأتنا نتيجة الاختبار." },
  { word: "eclipse", translation: "كسوف/خسوف", partOfSpeech: "noun", difficulty: "hard", example: "An eclipse blocks the sun for a short time.", exampleTranslation: "يحجب الكسوف الشمس لفترة قصيرة." },
  { word: "magnetic", translation: "مغناطيسي", partOfSpeech: "adjective", difficulty: "hard", example: "Iron has a magnetic property.", exampleTranslation: "للحديد خاصية مغناطيسية." },
  { word: "electric", translation: "كهربائي", partOfSpeech: "adjective", difficulty: "medium", example: "The electric fan cooled the room.", exampleTranslation: "برّدت المروحة الكهربائية الغرفة." },
  { word: "solar", translation: "شمسي", partOfSpeech: "adjective", difficulty: "medium", example: "Solar panels collect sunlight.", exampleTranslation: "تجمع الألواح الشمسية ضوء الشمس." },
  { word: "lunar", translation: "قمري", partOfSpeech: "adjective", difficulty: "hard", example: "A lunar eclipse hides the moon.", exampleTranslation: "يحجب الخسوف القمري القمر." },
  { word: "chemical", translation: "كيميائي", partOfSpeech: "adjective", difficulty: "medium", example: "A chemical change makes a new substance.", exampleTranslation: "ينتج التغيّر الكيميائي مادة جديدة." },
  { word: "physical", translation: "فيزيائي", partOfSpeech: "adjective", difficulty: "medium", example: "Melting ice is a physical change.", exampleTranslation: "ذوبان الجليد تغيّر فيزيائي." },
  { word: "substance", translation: "مادة", partOfSpeech: "noun", difficulty: "medium", example: "Water is a clear substance.", exampleTranslation: "الماء مادة صافية." },
  { word: "velocity", translation: "سرعة متجهة", partOfSpeech: "noun", difficulty: "hard", example: "The rocket gained great velocity.", exampleTranslation: "اكتسب الصاروخ سرعة متجهة كبيرة." },
  { word: "acceleration", translation: "تسارع", partOfSpeech: "noun", difficulty: "hard", example: "A push increases the car's acceleration.", exampleTranslation: "يزيد الدفع من تسارع السيارة." },
  { word: "momentum", translation: "زخم", partOfSpeech: "noun", difficulty: "hard", example: "A heavy ball has more momentum.", exampleTranslation: "للكرة الثقيلة زخم أكبر." },
  { word: "frequency", translation: "تردّد", partOfSpeech: "noun", difficulty: "hard", example: "A high frequency sound is very sharp.", exampleTranslation: "الصوت عالي التردّد حادّ جداً." },
  { word: "wavelength", translation: "طول موجي", partOfSpeech: "noun", difficulty: "hard", example: "Red light has a long wavelength.", exampleTranslation: "للضوء الأحمر طول موجي كبير." }
];
