/** Grade 6 extension batch B — simple examples (200 cards). Auto-generated. */
export const GRADE6_EXT_B = [
  { word: "secure", translation: "آمن", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word secure in class today.", exampleTranslation: "تعلّمنا كلمة آمن في الحصة اليوم." },
  { word: "seldom", translation: "نادراً", partOfSpeech: "adverb", difficulty: "medium", example: "Can you use seldom in a sentence?", exampleTranslation: "هل يمكنك استخدام نادراً في جملة؟" },
  { word: "seriously", translation: "بجدية", partOfSpeech: "adverb", difficulty: "medium", example: "The story mentioned seriously on page ten.", exampleTranslation: "ذكرت القصة بجدية في الصفحة العاشرة." },
  { word: "serve", translation: "خدمة", partOfSpeech: "verb", difficulty: "medium", example: "Our teacher wrote serve on the board.", exampleTranslation: "كتب معلمنا خدمة على السبورة." },
  { word: "set", translation: "وضع", partOfSpeech: "verb", difficulty: "medium", example: "I spelled set correctly on the quiz.", exampleTranslation: "تهجّيت وضع بشكل صحيح في الاختبار." },
  { word: "several", translation: "عدة", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain several.", exampleTranslation: "تساعد الصورة على شرح عدة." },
  { word: "sew", translation: "خياطة", partOfSpeech: "verb", difficulty: "medium", example: "We found sew in our reading book.", exampleTranslation: "وجدنا خياطة في كتاب القراءة." },
  { word: "shallow", translation: "ضحل", partOfSpeech: "adjective", difficulty: "medium", example: "Shallow is a new word for our unit.", exampleTranslation: "ضحل كلمة جديدة لوحدتنا." },
  { word: "shine", translation: "لمعان", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed shine.", exampleTranslation: "ناقشت لمعان مع زميلي." },
  { word: "shut", translation: "إغلاق", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about shut.", exampleTranslation: "يسأل ورق العمل عن إغلاق." },
  { word: "simple", translation: "بسيط", partOfSpeech: "adjective", difficulty: "medium", example: "We heard simple in the science video.", exampleTranslation: "سمعنا بسيط في فيلم العلوم." },
  { word: "simply", translation: "ببساطة", partOfSpeech: "adverb", difficulty: "medium", example: "Please copy simply into your notebook.", exampleTranslation: "من فضلك انسخ ببساطة في دفترك." },
  { word: "since", translation: "منذ ذلك الحين", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of since.", exampleTranslation: "يُظهر المخطط مثالاً عن منذ ذلك الحين." },
  { word: "skate", translation: "تزلج", partOfSpeech: "verb", difficulty: "medium", example: "Our group used skate in the project.", exampleTranslation: "استخدمت مجموعتنا تزلج في المشروع." },
  { word: "ski", translation: "تزلج", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with ski.", exampleTranslation: "أعطى المعلم مثالاً بـتزلج." },
  { word: "slide", translation: "انزلاق", partOfSpeech: "verb", difficulty: "medium", example: "I underlined slide in the paragraph.", exampleTranslation: "وضعت خطاً تحت انزلاق في الفقرة." },
  { word: "softly", translation: "بلطف", partOfSpeech: "adverb", difficulty: "medium", example: "We practiced saying softly aloud.", exampleTranslation: "تدرّبنا على نطق بلطف بصوت عالٍ." },
  { word: "somewhere", translation: "في مكان ما", partOfSpeech: "adverb", difficulty: "medium", example: "The poster explains somewhere with a drawing.", exampleTranslation: "يشرح الملصق في مكان ما برسم." },
  { word: "southern", translation: "جنوبي", partOfSpeech: "adjective", difficulty: "medium", example: "Everyone shared a sentence with southern.", exampleTranslation: "شارك الجميع جملة فيها جنوبي." },
  { word: "spare", translation: "احتياطي", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word spare.", exampleTranslation: "تضمّن الاختبار كلمة احتياطي." },
  { word: "special", translation: "خاص", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word special in class today.", exampleTranslation: "تعلّمنا كلمة خاص في الحصة اليوم." },
  { word: "spell", translation: "تهجئة", partOfSpeech: "verb", difficulty: "medium", example: "Can you use spell in a sentence?", exampleTranslation: "هل يمكنك استخدام تهجئة في جملة؟" },
  { word: "spill", translation: "سكب", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned spill on page ten.", exampleTranslation: "ذكرت القصة سكب في الصفحة العاشرة." },
  { word: "spit", translation: "بصق", partOfSpeech: "verb", difficulty: "medium", example: "Our teacher wrote spit on the board.", exampleTranslation: "كتب معلمنا بصق على السبورة." },
  { word: "split", translation: "تقسيم", partOfSpeech: "verb", difficulty: "medium", example: "I spelled split correctly on the quiz.", exampleTranslation: "تهجّيت تقسيم بشكل صحيح في الاختبار." },
  { word: "spread", translation: "انتشار", partOfSpeech: "verb", difficulty: "medium", example: "The picture helps explain spread.", exampleTranslation: "تساعد الصورة على شرح انتشار." },
  { word: "stale", translation: "قديم", partOfSpeech: "adjective", difficulty: "medium", example: "We found stale in our reading book.", exampleTranslation: "وجدنا قديم في كتاب القراءة." },
  { word: "steal", translation: "سرقة", partOfSpeech: "verb", difficulty: "medium", example: "Steal is a new word for our unit.", exampleTranslation: "سرقة كلمة جديدة لوحدتنا." },
  { word: "stick", translation: "لصق", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed stick.", exampleTranslation: "ناقشت لصق مع زميلي." },
  { word: "still", translation: "ما زال", partOfSpeech: "adverb", difficulty: "medium", example: "The worksheet asks about still.", exampleTranslation: "يسأل ورق العمل عن ما زال." },
  { word: "strange", translation: "غريب", partOfSpeech: "adjective", difficulty: "medium", example: "We heard strange in the science video.", exampleTranslation: "سمعنا غريب في فيلم العلوم." },
  { word: "strike", translation: "ضرب", partOfSpeech: "verb", difficulty: "medium", example: "Please copy strike into your notebook.", exampleTranslation: "من فضلك انسخ ضرب في دفترك." },
  { word: "strongly", translation: "بقوة", partOfSpeech: "adverb", difficulty: "medium", example: "The chart shows an example of strongly.", exampleTranslation: "يُظهر المخطط مثالاً عن بقوة." },
  { word: "suppose", translation: "افتراض", partOfSpeech: "verb", difficulty: "medium", example: "Our group used suppose in the project.", exampleTranslation: "استخدمت مجموعتنا افتراض في المشروع." },
  { word: "sweet", translation: "حلو", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with sweet.", exampleTranslation: "أعطى المعلم مثالاً بـحلو." },
  { word: "swift", translation: "سريع", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined swift in the paragraph.", exampleTranslation: "وضعت خطاً تحت سريع في الفقرة." },
  { word: "zodiac", translation: "برج", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying zodiac aloud.", exampleTranslation: "تدرّبنا على نطق برج بصوت عالٍ." },
  { word: "zen", translation: "تأمل", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains zen with a drawing.", exampleTranslation: "يشرح الملصق تأمل برسم." },
  { word: "about", translation: "بشأن", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with about.", exampleTranslation: "شارك الجميع جملة فيها بشأن." },
  { word: "across", translation: "عبر", partOfSpeech: "adverb", difficulty: "medium", example: "The quiz included the word across.", exampleTranslation: "تضمّن الاختبار كلمة عبر." },
  { word: "actually", translation: "في الواقع", partOfSpeech: "adverb", difficulty: "medium", example: "We learned the word actually in class today.", exampleTranslation: "تعلّمنا كلمة في الواقع في الحصة اليوم." },
  { word: "after", translation: "بعد", partOfSpeech: "verb", difficulty: "medium", example: "Can you use after in a sentence?", exampleTranslation: "هل يمكنك استخدام بعد في جملة؟" },
  { word: "again", translation: "مره اخرى", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned again on page ten.", exampleTranslation: "ذكرت القصة مره اخرى في الصفحة العاشرة." },
  { word: "against", translation: "ضد", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote against on the board.", exampleTranslation: "كتب معلمنا ضد على السبورة." },
  { word: "ahead", translation: "للأمام", partOfSpeech: "adverb", difficulty: "medium", example: "I spelled ahead correctly on the quiz.", exampleTranslation: "تهجّيت للأمام بشكل صحيح في الاختبار." },
  { word: "alive", translation: "حي", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain alive.", exampleTranslation: "تساعد الصورة على شرح حي." },
  { word: "along", translation: "على طول", partOfSpeech: "adverb", difficulty: "medium", example: "We found along in our reading book.", exampleTranslation: "وجدنا على طول في كتاب القراءة." },
  { word: "already", translation: "بالفعل", partOfSpeech: "adverb", difficulty: "medium", example: "Already is a new word for our unit.", exampleTranslation: "بالفعل كلمة جديدة لوحدتنا." },
  { word: "also", translation: "أيضاً", partOfSpeech: "adverb", difficulty: "medium", example: "My partner and I discussed also.", exampleTranslation: "ناقشت أيضاً مع زميلي." },
  { word: "angrily", translation: "بغضب", partOfSpeech: "adverb", difficulty: "medium", example: "The worksheet asks about angrily.", exampleTranslation: "يسأل ورق العمل عن بغضب." },
  { word: "another", translation: "آخر", partOfSpeech: "adjective", difficulty: "medium", example: "We heard another in the science video.", exampleTranslation: "سمعنا آخر في فيلم العلوم." },
  { word: "anywhere", translation: "في أي مكان", partOfSpeech: "adverb", difficulty: "medium", example: "Please copy anywhere into your notebook.", exampleTranslation: "من فضلك انسخ في أي مكان في دفترك." },
  { word: "apart", translation: "منفصلين", partOfSpeech: "adverb", difficulty: "medium", example: "The chart shows an example of apart.", exampleTranslation: "يُظهر المخطط مثالاً عن منفصلين." },
  { word: "around", translation: "حول", partOfSpeech: "adverb", difficulty: "medium", example: "Our group used around in the project.", exampleTranslation: "استخدمت مجموعتنا حول في المشروع." },
  { word: "attractive", translation: "جذاب", partOfSpeech: "adjective", difficulty: "hard", example: "The teacher gave an example with attractive.", exampleTranslation: "أعطى المعلم مثالاً بـجذاب." },
  { word: "badly", translation: "بشكل سيء", partOfSpeech: "adverb", difficulty: "medium", example: "I underlined badly in the paragraph.", exampleTranslation: "وضعت خطاً تحت بشكل سيء في الفقرة." },
  { word: "beautiful", translation: "جميل", partOfSpeech: "adjective", difficulty: "medium", example: "We practiced saying beautiful aloud.", exampleTranslation: "تدرّبنا على نطق جميل بصوت عالٍ." },
  { word: "before", translation: "قبل", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains before with a drawing.", exampleTranslation: "يشرح الملصق قبل برسم." },
  { word: "bland", translation: "فاتر", partOfSpeech: "adjective", difficulty: "medium", example: "Everyone shared a sentence with bland.", exampleTranslation: "شارك الجميع جملة فيها فاتر." },
  { word: "both", translation: "كلاهما", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word both.", exampleTranslation: "تضمّن الاختبار كلمة كلاهما." },
  { word: "bottom", translation: "سفلي", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word bottom in class today.", exampleTranslation: "تعلّمنا كلمة سفلي في الحصة اليوم." },
  { word: "bravely", translation: "بشجاعة", partOfSpeech: "adverb", difficulty: "medium", example: "Can you use bravely in a sentence?", exampleTranslation: "هل يمكنك استخدام بشجاعة في جملة؟" },
  { word: "calmly", translation: "بهدوء", partOfSpeech: "adverb", difficulty: "medium", example: "The story mentioned calmly on page ten.", exampleTranslation: "ذكرت القصة بهدوء في الصفحة العاشرة." },
  { word: "central", translation: "مركزي", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote central on the board.", exampleTranslation: "كتب معلمنا مركزي على السبورة." },
  { word: "certainly", translation: "بالتأكيد", partOfSpeech: "adverb", difficulty: "medium", example: "I spelled certainly correctly on the quiz.", exampleTranslation: "تهجّيت بالتأكيد بشكل صحيح في الاختبار." },
  { word: "closed", translation: "مغلق", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain closed.", exampleTranslation: "تساعد الصورة على شرح مغلق." },
  { word: "cost", translation: "تكلفة", partOfSpeech: "verb", difficulty: "medium", example: "We found cost in our reading book.", exampleTranslation: "وجدنا تكلفة في كتاب القراءة." },
  { word: "count", translation: "عد", partOfSpeech: "verb", difficulty: "medium", example: "Count is a new word for our unit.", exampleTranslation: "عد كلمة جديدة لوحدتنا." },
  { word: "cross", translation: "عبور", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed cross.", exampleTranslation: "ناقشت عبور مع زميلي." },
  { word: "dead", translation: "ميت", partOfSpeech: "adjective", difficulty: "medium", example: "The worksheet asks about dead.", exampleTranslation: "يسأل ورق العمل عن ميت." },
  { word: "deep", translation: "عميق", partOfSpeech: "adjective", difficulty: "medium", example: "We heard deep in the science video.", exampleTranslation: "سمعنا عميق في فيلم العلوم." },
  { word: "drive", translation: "قيادة", partOfSpeech: "verb", difficulty: "medium", example: "Please copy drive into your notebook.", exampleTranslation: "من فضلك انسخ قيادة في دفترك." },
  { word: "easy", translation: "سهل", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of easy.", exampleTranslation: "يُظهر المخطط مثالاً عن سهل." },
  { word: "feed", translation: "إطعام", partOfSpeech: "verb", difficulty: "medium", example: "Our group used feed in the project.", exampleTranslation: "استخدمت مجموعتنا إطعام في المشروع." },
  { word: "feel", translation: "شعور", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with feel.", exampleTranslation: "أعطى المعلم مثالاً بـشعور." },
  { word: "fill", translation: "ملء", partOfSpeech: "verb", difficulty: "medium", example: "I underlined fill in the paragraph.", exampleTranslation: "وضعت خطاً تحت ملء في الفقرة." },
  { word: "free", translation: "حر", partOfSpeech: "adjective", difficulty: "medium", example: "We practiced saying free aloud.", exampleTranslation: "تدرّبنا على نطق حر بصوت عالٍ." },
  { word: "front", translation: "أمامي", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains front with a drawing.", exampleTranslation: "يشرح الملصق أمامي برسم." },
  { word: "grab", translation: "إمساك", partOfSpeech: "verb", difficulty: "medium", example: "Everyone shared a sentence with grab.", exampleTranslation: "شارك الجميع جملة فيها إمساك." },
  { word: "hang", translation: "تعليق", partOfSpeech: "verb", difficulty: "medium", example: "The quiz included the word hang.", exampleTranslation: "تضمّن الاختبار كلمة تعليق." },
  { word: "hard", translation: "صلب", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word hard in class today.", exampleTranslation: "تعلّمنا كلمة صلب في الحصة اليوم." },
  { word: "hear", translation: "سماع", partOfSpeech: "verb", difficulty: "medium", example: "Can you use hear in a sentence?", exampleTranslation: "هل يمكنك استخدام سماع في جملة؟" },
  { word: "heavy", translation: "ثقيل", partOfSpeech: "adjective", difficulty: "medium", example: "The story mentioned heavy on page ten.", exampleTranslation: "ذكرت القصة ثقيل في الصفحة العاشرة." },
  { word: "here", translation: "هنا", partOfSpeech: "adverb", difficulty: "medium", example: "Our teacher wrote here on the board.", exampleTranslation: "كتب معلمنا هنا على السبورة." },
  { word: "hurt", translation: "إيذاء", partOfSpeech: "verb", difficulty: "medium", example: "I spelled hurt correctly on the quiz.", exampleTranslation: "تهجّيت إيذاء بشكل صحيح في الاختبار." },
  { word: "join", translation: "انضمام", partOfSpeech: "verb", difficulty: "medium", example: "The picture helps explain join.", exampleTranslation: "تساعد الصورة على شرح انضمام." },
  { word: "kiss", translation: "قبلة", partOfSpeech: "verb", difficulty: "medium", example: "We found kiss in our reading book.", exampleTranslation: "وجدنا قبلة في كتاب القراءة." },
  { word: "knock", translation: "طرق", partOfSpeech: "verb", difficulty: "medium", example: "Knock is a new word for our unit.", exampleTranslation: "طرق كلمة جديدة لوحدتنا." },
  { word: "large", translation: "كبير", partOfSpeech: "adjective", difficulty: "medium", example: "My partner and I discussed large.", exampleTranslation: "ناقشت كبير مع زميلي." },
  { word: "late", translation: "متأخر", partOfSpeech: "adjective", difficulty: "medium", example: "The worksheet asks about late.", exampleTranslation: "يسأل ورق العمل عن متأخر." },
  { word: "left", translation: "يسار", partOfSpeech: "adjective", difficulty: "medium", example: "We heard left in the science video.", exampleTranslation: "سمعنا يسار في فيلم العلوم." },
  { word: "live", translation: "عيش", partOfSpeech: "verb", difficulty: "medium", example: "Please copy live into your notebook.", exampleTranslation: "من فضلك انسخ عيش في دفترك." },
  { word: "long", translation: "طويل", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of long.", exampleTranslation: "يُظهر المخطط مثالاً عن طويل." },
  { word: "loud", translation: "صاخب", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used loud in the project.", exampleTranslation: "استخدمت مجموعتنا صاخب في المشروع." },
  { word: "many", translation: "كثير", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with many.", exampleTranslation: "أعطى المعلم مثالاً بـكثير." },
  { word: "mark", translation: "وضع علامة", partOfSpeech: "verb", difficulty: "medium", example: "I underlined mark in the paragraph.", exampleTranslation: "وضعت خطاً تحت وضع علامة في الفقرة." },
  { word: "meet", translation: "لقاء", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying meet aloud.", exampleTranslation: "تدرّبنا على نطق لقاء بصوت عالٍ." },
  { word: "miss", translation: "فقدان", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains miss with a drawing.", exampleTranslation: "يشرح الملصق فقدان برسم." },
  { word: "move", translation: "حركة", partOfSpeech: "verb", difficulty: "medium", example: "Everyone shared a sentence with move.", exampleTranslation: "شارك الجميع جملة فيها حركة." },
  { word: "need", translation: "حاجة", partOfSpeech: "verb", difficulty: "medium", example: "The quiz included the word need.", exampleTranslation: "تضمّن الاختبار كلمة حاجة." },
  { word: "only", translation: "فقط", partOfSpeech: "adverb", difficulty: "medium", example: "We learned the word only in class today.", exampleTranslation: "تعلّمنا كلمة فقط في الحصة اليوم." },
  { word: "pick", translation: "اختيار", partOfSpeech: "verb", difficulty: "medium", example: "Can you use pick in a sentence?", exampleTranslation: "هل يمكنك استخدام اختيار في جملة؟" },
  { word: "plan", translation: "تخطيط", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned plan on page ten.", exampleTranslation: "ذكرت القصة تخطيط في الصفحة العاشرة." },
  { word: "rich", translation: "غني", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote rich on the board.", exampleTranslation: "كتب معلمنا غني على السبورة." },
  { word: "ring", translation: "رنين", partOfSpeech: "verb", difficulty: "medium", example: "I spelled ring correctly on the quiz.", exampleTranslation: "تهجّيت رنين بشكل صحيح في الاختبار." },
  { word: "seem", translation: "يبدو", partOfSpeech: "verb", difficulty: "medium", example: "The picture helps explain seem.", exampleTranslation: "تساعد الصورة على شرح يبدو." },
  { word: "sell", translation: "بيع", partOfSpeech: "verb", difficulty: "medium", example: "We found sell in our reading book.", exampleTranslation: "وجدنا بيع في كتاب القراءة." },
  { word: "sick", translation: "مريض", partOfSpeech: "adjective", difficulty: "medium", example: "Sick is a new word for our unit.", exampleTranslation: "مريض كلمة جديدة لوحدتنا." },
  { word: "skip", translation: "تخطي", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed skip.", exampleTranslation: "ناقشت تخطي مع زميلي." },
  { word: "smell", translation: "شم", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about smell.", exampleTranslation: "يسأل ورق العمل عن شم." },
  { word: "smoke", translation: "تدخين", partOfSpeech: "verb", difficulty: "medium", example: "We heard smoke in the science video.", exampleTranslation: "سمعنا تدخين في فيلم العلوم." },
  { word: "snap", translation: "فرقعة", partOfSpeech: "verb", difficulty: "medium", example: "Please copy snap into your notebook.", exampleTranslation: "من فضلك انسخ فرقعة في دفترك." },
  { word: "some", translation: "بعض", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of some.", exampleTranslation: "يُظهر المخطط مثالاً عن بعض." },
  { word: "soon", translation: "قريباً", partOfSpeech: "adverb", difficulty: "medium", example: "Our group used soon in the project.", exampleTranslation: "استخدمت مجموعتنا قريباً في المشروع." },
  { word: "stay", translation: "بقاء", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with stay.", exampleTranslation: "أعطى المعلم مثالاً بـبقاء." },
  { word: "step", translation: "خطوة", partOfSpeech: "verb", difficulty: "medium", example: "I underlined step in the paragraph.", exampleTranslation: "وضعت خطاً تحت خطوة في الفقرة." },
  { word: "stir", translation: "تحريك", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying stir aloud.", exampleTranslation: "تدرّبنا على نطق تحريك بصوت عالٍ." },
  { word: "such", translation: "مثل", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains such with a drawing.", exampleTranslation: "يشرح الملصق مثل برسم." },
  { word: "taste", translation: "تذوق", partOfSpeech: "verb", difficulty: "medium", example: "Everyone shared a sentence with taste.", exampleTranslation: "شارك الجميع جملة فيها تذوق." },
  { word: "tasty", translation: "لذيذ", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word tasty.", exampleTranslation: "تضمّن الاختبار كلمة لذيذ." },
  { word: "tear", translation: "تمزيق", partOfSpeech: "verb", difficulty: "medium", example: "We learned the word tear in class today.", exampleTranslation: "تعلّمنا كلمة تمزيق في الحصة اليوم." },
  { word: "thank", translation: "شكر", partOfSpeech: "verb", difficulty: "medium", example: "Can you use thank in a sentence?", exampleTranslation: "هل يمكنك استخدام شكر في جملة؟" },
  { word: "then", translation: "ثم", partOfSpeech: "adverb", difficulty: "medium", example: "The story mentioned then on page ten.", exampleTranslation: "ذكرت القصة ثم في الصفحة العاشرة." },
  { word: "there", translation: "هناك", partOfSpeech: "adverb", difficulty: "medium", example: "Our teacher wrote there on the board.", exampleTranslation: "كتب معلمنا هناك على السبورة." },
  { word: "think", translation: "تفكير", partOfSpeech: "verb", difficulty: "medium", example: "I spelled think correctly on the quiz.", exampleTranslation: "تهجّيت تفكير بشكل صحيح في الاختبار." },
  { word: "through", translation: "عبر", partOfSpeech: "adverb", difficulty: "medium", example: "The picture helps explain through.", exampleTranslation: "تساعد الصورة على شرح عبر." },
  { word: "throughout", translation: "طوال, في كل مكان", partOfSpeech: "noun", difficulty: "hard", example: "We found throughout in our reading book.", exampleTranslation: "وجدنا طوال, في كل مكان في كتاب القراءة." },
  { word: "tiny", translation: "صغير جداً", partOfSpeech: "adjective", difficulty: "medium", example: "Tiny is a new word for our unit.", exampleTranslation: "صغير جداً كلمة جديدة لوحدتنا." },
  { word: "together", translation: "معاً", partOfSpeech: "adverb", difficulty: "medium", example: "My partner and I discussed together.", exampleTranslation: "ناقشت معاً مع زميلي." },
  { word: "total", translation: "إجمالي", partOfSpeech: "adjective", difficulty: "medium", example: "The worksheet asks about total.", exampleTranslation: "يسأل ورق العمل عن إجمالي." },
  { word: "totally", translation: "تماماً", partOfSpeech: "adverb", difficulty: "medium", example: "We heard totally in the science video.", exampleTranslation: "سمعنا تماماً في فيلم العلوم." },
  { word: "touch", translation: "لمس", partOfSpeech: "verb", difficulty: "medium", example: "Please copy touch into your notebook.", exampleTranslation: "من فضلك انسخ لمس في دفترك." },
  { word: "toward", translation: "نحو, في إتجاه, من جانب, بالنسبة الي, باتجاه", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of toward.", exampleTranslation: "يُظهر المخطط مثالاً عن نحو, في إتجاه, من جانب, بالنسبة الي, باتجاه." },
  { word: "towards", translation: "نحو, من أجل, قرب, باتجاه, من جانب, بالنسبة الي", partOfSpeech: "noun", difficulty: "medium", example: "Our group used towards in the project.", exampleTranslation: "استخدمت مجموعتنا نحو, من أجل, قرب, باتجاه, من جانب, بالنسبة الي في المشروع." },
  { word: "travel", translation: "سفر", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with travel.", exampleTranslation: "أعطى المعلم مثالاً بـسفر." },
  { word: "treat", translation: "معاملة", partOfSpeech: "verb", difficulty: "medium", example: "I underlined treat in the paragraph.", exampleTranslation: "وضعت خطاً تحت معاملة في الفقرة." },
  { word: "trick", translation: "خداع", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying trick aloud.", exampleTranslation: "تدرّبنا على نطق خداع بصوت عالٍ." },
  { word: "trim", translation: "تقليم", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains trim with a drawing.", exampleTranslation: "يشرح الملصق تقليم برسم." },
  { word: "trip", translation: "عثرة", partOfSpeech: "verb", difficulty: "medium", example: "Everyone shared a sentence with trip.", exampleTranslation: "شارك الجميع جملة فيها عثرة." },
  { word: "true", translation: "صحيح", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word true.", exampleTranslation: "تضمّن الاختبار كلمة صحيح." },
  { word: "truly", translation: "حقاً", partOfSpeech: "adverb", difficulty: "medium", example: "We learned the word truly in class today.", exampleTranslation: "تعلّمنا كلمة حقاً في الحصة اليوم." },
  { word: "turn", translation: "دوران", partOfSpeech: "verb", difficulty: "medium", example: "Can you use turn in a sentence?", exampleTranslation: "هل يمكنك استخدام دوران في جملة؟" },
  { word: "type", translation: "كتابة", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned type on page ten.", exampleTranslation: "ذكرت القصة كتابة في الصفحة العاشرة." },
  { word: "ugly", translation: "قبيح", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote ugly on the board.", exampleTranslation: "كتب معلمنا قبيح على السبورة." },
  { word: "unable", translation: "غير قادر", partOfSpeech: "adjective", difficulty: "medium", example: "I spelled unable correctly on the quiz.", exampleTranslation: "تهجّيت غير قادر بشكل صحيح في الاختبار." },
  { word: "uncertain", translation: "غير مؤكد", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain uncertain.", exampleTranslation: "تساعد الصورة على شرح غير مؤكد." },
  { word: "unequal", translation: "غير متساوٍ", partOfSpeech: "adjective", difficulty: "medium", example: "We found unequal in our reading book.", exampleTranslation: "وجدنا غير متساوٍ في كتاب القراءة." },
  { word: "unite", translation: "توحيد", partOfSpeech: "verb", difficulty: "medium", example: "Unite is a new word for our unit.", exampleTranslation: "توحيد كلمة جديدة لوحدتنا." },
  { word: "unlikely", translation: "غير محتمل", partOfSpeech: "adjective", difficulty: "medium", example: "My partner and I discussed unlikely.", exampleTranslation: "ناقشت غير محتمل مع زميلي." },
  { word: "unlock", translation: "فتح", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about unlock.", exampleTranslation: "يسأل ورق العمل عن فتح." },
  { word: "upper", translation: "علوي", partOfSpeech: "adjective", difficulty: "medium", example: "We heard upper in the science video.", exampleTranslation: "سمعنا علوي في فيلم العلوم." },
  { word: "upstairs", translation: "في الطابق العلوي", partOfSpeech: "adverb", difficulty: "medium", example: "Please copy upstairs into your notebook.", exampleTranslation: "من فضلك انسخ في الطابق العلوي في دفترك." },
  { word: "usual", translation: "معتاد", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of usual.", exampleTranslation: "يُظهر المخطط مثالاً عن معتاد." },
  { word: "visit", translation: "زيارة", partOfSpeech: "verb", difficulty: "medium", example: "Our group used visit in the project.", exampleTranslation: "استخدمت مجموعتنا زيارة في المشروع." },
  { word: "wake", translation: "استيقاظ", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with wake.", exampleTranslation: "أعطى المعلم مثالاً بـاستيقاظ." },
  { word: "warn", translation: "تحذير", partOfSpeech: "verb", difficulty: "medium", example: "I underlined warn in the paragraph.", exampleTranslation: "وضعت خطاً تحت تحذير في الفقرة." },
  { word: "waste", translation: "إهدار", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying waste aloud.", exampleTranslation: "تدرّبنا على نطق إهدار بصوت عالٍ." },
  { word: "weak", translation: "ضعيف", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains weak with a drawing.", exampleTranslation: "يشرح الملصق ضعيف برسم." },
  { word: "weakly", translation: "بضعف", partOfSpeech: "adverb", difficulty: "medium", example: "Everyone shared a sentence with weakly.", exampleTranslation: "شارك الجميع جملة فيها بضعف." },
  { word: "wealthy", translation: "ثري", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word wealthy.", exampleTranslation: "تضمّن الاختبار كلمة ثري." },
  { word: "wear", translation: "لبس", partOfSpeech: "verb", difficulty: "medium", example: "We learned the word wear in class today.", exampleTranslation: "تعلّمنا كلمة لبس في الحصة اليوم." },
  { word: "weekly", translation: "أسبوعي", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use weekly in a sentence?", exampleTranslation: "هل يمكنك استخدام أسبوعي في جملة؟" },
  { word: "weird", translation: "غريب", partOfSpeech: "adjective", difficulty: "medium", example: "The story mentioned weird on page ten.", exampleTranslation: "ذكرت القصة غريب في الصفحة العاشرة." },
  { word: "welcome", translation: "ترحيب", partOfSpeech: "verb", difficulty: "medium", example: "Our teacher wrote welcome on the board.", exampleTranslation: "كتب معلمنا ترحيب على السبورة." },
  { word: "well", translation: "بخير", partOfSpeech: "adjective", difficulty: "medium", example: "I spelled well correctly on the quiz.", exampleTranslation: "تهجّيت بخير بشكل صحيح في الاختبار." },
  { word: "western", translation: "غربي", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain western.", exampleTranslation: "تساعد الصورة على شرح غربي." },
  { word: "whole", translation: "كامل", partOfSpeech: "adjective", difficulty: "medium", example: "We found whole in our reading book.", exampleTranslation: "وجدنا كامل في كتاب القراءة." },
  { word: "wipe", translation: "مسح", partOfSpeech: "verb", difficulty: "medium", example: "Wipe is a new word for our unit.", exampleTranslation: "مسح كلمة جديدة لوحدتنا." },
  { word: "wish", translation: "أمنية", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed wish.", exampleTranslation: "ناقشت أمنية مع زميلي." },
  { word: "within", translation: "الجزء الداخلي من كذا", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about within.", exampleTranslation: "يسأل ورق العمل عن الجزء الداخلي من كذا." },
  { word: "without", translation: "بدون", partOfSpeech: "noun", difficulty: "medium", example: "We heard without in the science video.", exampleTranslation: "سمعنا بدون في فيلم العلوم." },
  { word: "worry", translation: "قلق", partOfSpeech: "verb", difficulty: "medium", example: "Please copy worry into your notebook.", exampleTranslation: "من فضلك انسخ قلق في دفترك." },
  { word: "worthless", translation: "عديم القيمة", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of worthless.", exampleTranslation: "يُظهر المخطط مثالاً عن عديم القيمة." },
  { word: "yell", translation: "صراخ", partOfSpeech: "verb", difficulty: "medium", example: "Our group used yell in the project.", exampleTranslation: "استخدمت مجموعتنا صراخ في المشروع." },
  { word: "aahed", translation: "عهد", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with aahed.", exampleTranslation: "أعطى المعلم مثالاً بـعهد." },
  { word: "aalii", translation: "عاليه", partOfSpeech: "noun", difficulty: "easy", example: "I underlined aalii in the paragraph.", exampleTranslation: "وضعت خطاً تحت عاليه في الفقرة." },
  { word: "aani", translation: "آني.", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying aani aloud.", exampleTranslation: "تدرّبنا على نطق آني. بصوت عالٍ." },
  { word: "aardvark", translation: "خنزير الأرض", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains aardvark with a drawing.", exampleTranslation: "يشرح الملصق خنزير الأرض برسم." },
  { word: "aardvarks", translation: "آردفاركس", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with aardvarks.", exampleTranslation: "شارك الجميع جملة فيها آردفاركس." },
  { word: "aardwolf", translation: "ذئب الأرض", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word aardwolf.", exampleTranslation: "تضمّن الاختبار كلمة ذئب الأرض." },
  { word: "aargh", translation: "Aargh!", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word aargh in class today.", exampleTranslation: "تعلّمنا كلمة Aargh! في الحصة اليوم." },
  { word: "aaron", translation: "آرون", partOfSpeech: "noun", difficulty: "easy", example: "Can you use aaron in a sentence?", exampleTranslation: "هل يمكنك استخدام آرون في جملة؟" },
  { word: "aaronic", translation: "هاروني, ما يتعلق بالكهنة من نسل هارون أو من ينتمي إليها", partOfSpeech: "adjective", difficulty: "medium", example: "The story mentioned aaronic on page ten.", exampleTranslation: "ذكرت القصة هاروني, ما يتعلق بالكهنة من نسل هارون أو من ينتمي إليها في الصفحة العاشرة." },
  { word: "aaronical", translation: "هرمي", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote aaronical on the board.", exampleTranslation: "كتب معلمنا هرمي على السبورة." },
  { word: "aaronite", translation: "أرونيت", partOfSpeech: "noun", difficulty: "medium", example: "I spelled aaronite correctly on the quiz.", exampleTranslation: "تهجّيت أرونيت بشكل صحيح في الاختبار." },
  { word: "aarrgh", translation: "أرررغ!", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain aarrgh.", exampleTranslation: "تساعد الصورة على شرح أرررغ!." },
  { word: "aarrghh", translation: "! آرغه", partOfSpeech: "noun", difficulty: "medium", example: "We found aarrghh in our reading book.", exampleTranslation: "وجدنا ! آرغه في كتاب القراءة." },
  { word: "aaru", translation: "آرو", partOfSpeech: "noun", difficulty: "easy", example: "Aaru is a new word for our unit.", exampleTranslation: "آرو كلمة جديدة لوحدتنا." },
  { word: "ababdeh", translation: "العبابدة", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed ababdeh.", exampleTranslation: "ناقشت العبابدة مع زميلي." },
  { word: "ababua", translation: "أبابوا", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about ababua.", exampleTranslation: "يسأل ورق العمل عن أبابوا." },
  { word: "abac", translation: "مكافحة الرشوة والفساد", partOfSpeech: "noun", difficulty: "easy", example: "We heard abac in the science video.", exampleTranslation: "سمعنا مكافحة الرشوة والفساد في فيلم العلوم." },
  { word: "abaca", translation: "قنب مانيلا", partOfSpeech: "noun", difficulty: "easy", example: "Please copy abaca into your notebook.", exampleTranslation: "من فضلك انسخ قنب مانيلا في دفترك." },
  { word: "abacay", translation: "أباكاي", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of abacay.", exampleTranslation: "يُظهر المخطط مثالاً عن أباكاي." },
  { word: "abacas", translation: "أباكاس", partOfSpeech: "noun", difficulty: "medium", example: "Our group used abacas in the project.", exampleTranslation: "استخدمت مجموعتنا أباكاس في المشروع." },
  { word: "abacate", translation: "غير مستقر", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with abacate.", exampleTranslation: "أعطى المعلم مثالاً بـغير مستقر." },
  { word: "abacaxi", translation: "أباكاكسي", partOfSpeech: "noun", difficulty: "medium", example: "I underlined abacaxi in the paragraph.", exampleTranslation: "وضعت خطاً تحت أباكاكسي في الفقرة." },
  { word: "abaci", translation: "العباسي", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying abaci aloud.", exampleTranslation: "تدرّبنا على نطق العباسي بصوت عالٍ." },
  { word: "abacinate", translation: "الإعماء باستخدام الحديد الملتهب بالقرب من العينين", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains abacinate with a drawing.", exampleTranslation: "يشرح الملصق الإعماء باستخدام الحديد الملتهب بالقرب من العينين برسم." },
  { word: "abacist", translation: "أباسيست", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with abacist.", exampleTranslation: "شارك الجميع جملة فيها أباسيست." },
  { word: "aback", translation: "الى الوراء", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word aback.", exampleTranslation: "تضمّن الاختبار كلمة الى الوراء." },
];
