/** Grade 6 chunk D — everyday action verbs (cards 501-1000, batch 1). */
export const GRADE6_CHUNK_D = [
  { word: "abandon", translation: "يتخلّى عن", partOfSpeech: "verb", difficulty: "hard", example: "They had to abandon the old house.", exampleTranslation: "اضطروا إلى التخلّي عن المنزل القديم." },
  { word: "accompany", translation: "يرافق", partOfSpeech: "verb", difficulty: "hard", example: "My sister will accompany me to school.", exampleTranslation: "سترافقني أختي إلى المدرسة." },
  { word: "accumulate", translation: "يتراكم", partOfSpeech: "verb", difficulty: "hard", example: "Dust can accumulate on the shelves.", exampleTranslation: "قد يتراكم الغبار على الرفوف." },
  { word: "admire", translation: "يُعجب بـ", partOfSpeech: "verb", difficulty: "medium", example: "We admire her courage.", exampleTranslation: "نُعجب بشجاعتها." },
  { word: "advance", translation: "يتقدّم", partOfSpeech: "verb", difficulty: "medium", example: "The soldiers advance slowly.", exampleTranslation: "يتقدّم الجنود ببطء." },
  { word: "advise", translation: "ينصح", partOfSpeech: "verb", difficulty: "medium", example: "The doctor will advise you to rest.", exampleTranslation: "سينصحك الطبيب بالراحة." },
  { word: "alert", translation: "ينبّه", partOfSpeech: "verb", difficulty: "medium", example: "The alarm will alert the whole school.", exampleTranslation: "سينبّه جرس الإنذار المدرسة كلها." },
  { word: "alter", translation: "يغيّر", partOfSpeech: "verb", difficulty: "hard", example: "Please do not alter the plan now.", exampleTranslation: "من فضلك لا تغيّر الخطة الآن." },
  { word: "amuse", translation: "يسلّي", partOfSpeech: "verb", difficulty: "medium", example: "The clown amused the children.", exampleTranslation: "سلّى المهرّج الأطفال." },
  { word: "anticipate", translation: "يتوقّع", partOfSpeech: "verb", difficulty: "hard", example: "We anticipate a busy weekend.", exampleTranslation: "نتوقّع عطلة نهاية أسبوع مزدحمة." },
  { word: "appoint", translation: "يعيّن", partOfSpeech: "verb", difficulty: "hard", example: "They will appoint a new captain.", exampleTranslation: "سيعيّنون قائداً جديداً." },
  { word: "approve", translation: "يوافق", partOfSpeech: "verb", difficulty: "medium", example: "The teacher will approve our project.", exampleTranslation: "سيوافق المعلّم على مشروعنا." },
  { word: "arrange", translation: "يرتّب", partOfSpeech: "verb", difficulty: "medium", example: "Arrange the chairs in a circle.", exampleTranslation: "رتّب الكراسي في دائرة." },
  { word: "assemble", translation: "يجمّع", partOfSpeech: "verb", difficulty: "hard", example: "We assemble the model step by step.", exampleTranslation: "نجمّع المجسّم خطوة بخطوة." },
  { word: "assist", translation: "يساعد", partOfSpeech: "verb", difficulty: "medium", example: "Nurses assist the doctor.", exampleTranslation: "يساعد الممرّضون الطبيب." },
  { word: "attach", translation: "يرفق", partOfSpeech: "verb", difficulty: "medium", example: "Attach the file to the email.", exampleTranslation: "أرفق الملف بالبريد." },
  { word: "attempt", translation: "يحاول", partOfSpeech: "verb", difficulty: "medium", example: "He made one more attempt to win.", exampleTranslation: "قام بمحاولة أخرى للفوز." },
  { word: "attend", translation: "يحضر", partOfSpeech: "verb", difficulty: "easy", example: "Students attend class every day.", exampleTranslation: "يحضر الطلاب الحصة كل يوم." },
  { word: "attract", translation: "يجذب", partOfSpeech: "verb", difficulty: "medium", example: "Bright flowers attract bees.", exampleTranslation: "تجذب الأزهار الزاهية النحل." },
  { word: "avoid", translation: "يتجنّب", partOfSpeech: "verb", difficulty: "medium", example: "Avoid the puddles on the road.", exampleTranslation: "تجنّب البرك على الطريق." },
  { word: "behave", translation: "يتصرّف", partOfSpeech: "verb", difficulty: "medium", example: "The children behave well in class.", exampleTranslation: "يتصرّف الأطفال بأدب في الصف." },
  { word: "belong", translation: "ينتمي", partOfSpeech: "verb", difficulty: "medium", example: "This book belongs to the library.", exampleTranslation: "هذا الكتاب يخصّ المكتبة." },
  { word: "blend", translation: "يمزج", partOfSpeech: "verb", difficulty: "medium", example: "Blend the fruit to make juice.", exampleTranslation: "امزج الفاكهة لصنع العصير." },
  { word: "borrow", translation: "يستعير", partOfSpeech: "verb", difficulty: "easy", example: "May I borrow your pencil?", exampleTranslation: "هل يمكنني استعارة قلمك؟" },
  { word: "bounce", translation: "يرتدّ", partOfSpeech: "verb", difficulty: "medium", example: "The ball will bounce off the wall.", exampleTranslation: "سترتدّ الكرة عن الجدار." },
  { word: "cancel", translation: "يلغي", partOfSpeech: "verb", difficulty: "medium", example: "They had to cancel the trip.", exampleTranslation: "اضطروا إلى إلغاء الرحلة." },
  { word: "capture", translation: "يلتقط/يأسر", partOfSpeech: "verb", difficulty: "hard", example: "The camera can capture fast motion.", exampleTranslation: "تستطيع الكاميرا التقاط الحركة السريعة." },
  { word: "celebrate", translation: "يحتفل", partOfSpeech: "verb", difficulty: "medium", example: "We celebrate the new year together.", exampleTranslation: "نحتفل بالعام الجديد معاً." },
  { word: "chase", translation: "يطارد", partOfSpeech: "verb", difficulty: "medium", example: "The dog likes to chase the ball.", exampleTranslation: "يحبّ الكلب مطاردة الكرة." },
  { word: "claim", translation: "يدّعي/يطالب", partOfSpeech: "verb", difficulty: "hard", example: "You can claim your prize at the desk.", exampleTranslation: "يمكنك المطالبة بجائزتك عند المكتب." },
  { word: "collect", translation: "يجمع", partOfSpeech: "verb", difficulty: "easy", example: "She likes to collect old stamps.", exampleTranslation: "تحبّ جمع الطوابع القديمة." },
  { word: "command", translation: "يأمر", partOfSpeech: "verb", difficulty: "hard", example: "The captain can command the ship.", exampleTranslation: "يستطيع القبطان أن يقود السفينة بالأوامر." },
  { word: "compete", translation: "يتنافس", partOfSpeech: "verb", difficulty: "medium", example: "Teams compete for the gold cup.", exampleTranslation: "تتنافس الفرق على الكأس الذهبية." },
  { word: "complain", translation: "يشتكي", partOfSpeech: "verb", difficulty: "medium", example: "He did not complain about the noise.", exampleTranslation: "لم يشتكِ من الضوضاء." },
  { word: "complete", translation: "يكمل", partOfSpeech: "verb", difficulty: "easy", example: "Complete the puzzle before lunch.", exampleTranslation: "أكمل اللغز قبل الغداء." },
  { word: "concentrate", translation: "يركّز", partOfSpeech: "verb", difficulty: "hard", example: "Concentrate on your reading.", exampleTranslation: "ركّز على قراءتك." },
  { word: "connect", translation: "يربط/يوصل", partOfSpeech: "verb", difficulty: "medium", example: "Connect the wires to the battery.", exampleTranslation: "اربط الأسلاك بالبطارية." },
  { word: "consider", translation: "يأخذ في الاعتبار", partOfSpeech: "verb", difficulty: "hard", example: "Please consider all the options.", exampleTranslation: "من فضلك خذ كل الخيارات في الاعتبار." },
  { word: "consult", translation: "يستشير", partOfSpeech: "verb", difficulty: "hard", example: "Consult a map before the hike.", exampleTranslation: "استشر خريطة قبل الرحلة." },
  { word: "consume", translation: "يستهلك", partOfSpeech: "verb", difficulty: "hard", example: "Big engines consume a lot of fuel.", exampleTranslation: "تستهلك المحركات الكبيرة وقوداً كثيراً." },
  { word: "contain", translation: "يحتوي", partOfSpeech: "verb", difficulty: "medium", example: "The box contains old photos.", exampleTranslation: "يحتوي الصندوق على صور قديمة." },
  { word: "convert", translation: "يحوّل", partOfSpeech: "verb", difficulty: "hard", example: "Convert the meters into centimeters.", exampleTranslation: "حوّل الأمتار إلى سنتيمترات." },
  { word: "correct", translation: "يصحّح", partOfSpeech: "verb", difficulty: "easy", example: "Correct the spelling mistakes.", exampleTranslation: "صحّح الأخطاء الإملائية." },
  { word: "decorate", translation: "يزيّن", partOfSpeech: "verb", difficulty: "medium", example: "We decorate the hall for the party.", exampleTranslation: "نزيّن القاعة للحفل." },
  { word: "defend", translation: "يدافع", partOfSpeech: "verb", difficulty: "medium", example: "The players defend their goal.", exampleTranslation: "يدافع اللاعبون عن مرماهم." },
  { word: "delay", translation: "يؤخّر", partOfSpeech: "verb", difficulty: "medium", example: "Rain may delay the match.", exampleTranslation: "قد يؤخّر المطر المباراة." },
  { word: "deliver", translation: "يوصّل/يسلّم", partOfSpeech: "verb", difficulty: "medium", example: "The driver will deliver the parcel.", exampleTranslation: "سيسلّم السائق الطرد." },
  { word: "deny", translation: "ينكر", partOfSpeech: "verb", difficulty: "hard", example: "He did not deny the truth.", exampleTranslation: "لم ينكر الحقيقة." },
  { word: "depend", translation: "يعتمد", partOfSpeech: "verb", difficulty: "medium", example: "Young birds depend on their parents.", exampleTranslation: "تعتمد الطيور الصغيرة على والديها." },
  { word: "deserve", translation: "يستحقّ", partOfSpeech: "verb", difficulty: "hard", example: "You deserve a reward for your work.", exampleTranslation: "تستحقّ مكافأة على عملك." },
  { word: "design", translation: "يصمّم", partOfSpeech: "verb", difficulty: "medium", example: "She will design a new logo.", exampleTranslation: "ستصمّم شعاراً جديداً." },
  { word: "destroy", translation: "يدمّر", partOfSpeech: "verb", difficulty: "medium", example: "The flood can destroy the bridge.", exampleTranslation: "قد يدمّر الفيضان الجسر." },
  { word: "detect", translation: "يكتشف/يرصد", partOfSpeech: "verb", difficulty: "hard", example: "Dogs can detect a faint smell.", exampleTranslation: "تستطيع الكلاب رصد رائحة خفيفة." },
  { word: "devote", translation: "يكرّس", partOfSpeech: "verb", difficulty: "hard", example: "She devotes her time to art.", exampleTranslation: "تكرّس وقتها للفن." },
  { word: "direct", translation: "يوجّه", partOfSpeech: "verb", difficulty: "medium", example: "Police direct the traffic at noon.", exampleTranslation: "توجّه الشرطة المرور عند الظهر." },
  { word: "disagree", translation: "يختلف/لا يوافق", partOfSpeech: "verb", difficulty: "medium", example: "We sometimes disagree about games.", exampleTranslation: "نختلف أحياناً حول الألعاب." },
  { word: "display", translation: "يعرض", partOfSpeech: "verb", difficulty: "medium", example: "The museum displays old coins.", exampleTranslation: "يعرض المتحف عملات قديمة." },
  { word: "donate", translation: "يتبرّع", partOfSpeech: "verb", difficulty: "hard", example: "They donate books to the school.", exampleTranslation: "يتبرّعون بكتب للمدرسة." },
  { word: "doubt", translation: "يشكّ", partOfSpeech: "verb", difficulty: "hard", example: "I doubt the story is true.", exampleTranslation: "أشكّ أن القصة صحيحة." },
  { word: "earn", translation: "يكسب", partOfSpeech: "verb", difficulty: "easy", example: "You earn points for good work.", exampleTranslation: "تكسب نقاطاً مقابل العمل الجيد." },
  { word: "educate", translation: "يثقّف/يعلّم", partOfSpeech: "verb", difficulty: "hard", example: "Schools educate young minds.", exampleTranslation: "تعلّم المدارس العقول الصغيرة." },
  { word: "embrace", translation: "يحتضن/يتبنّى", partOfSpeech: "verb", difficulty: "hard", example: "We embrace new ideas at school.", exampleTranslation: "نتبنّى الأفكار الجديدة في المدرسة." },
  { word: "enable", translation: "يمكّن", partOfSpeech: "verb", difficulty: "hard", example: "Maps enable us to find the way.", exampleTranslation: "تمكّننا الخرائط من إيجاد الطريق." },
  { word: "endure", translation: "يتحمّل", partOfSpeech: "verb", difficulty: "hard", example: "Camels endure the desert heat.", exampleTranslation: "تتحمّل الجِمال حرّ الصحراء." },
  { word: "entertain", translation: "يسلّي/يرفّه", partOfSpeech: "verb", difficulty: "medium", example: "The singers entertain the crowd.", exampleTranslation: "يرفّه المغنّون عن الجمهور." },
  { word: "escape", translation: "يهرب", partOfSpeech: "verb", difficulty: "medium", example: "The cat tried to escape the room.", exampleTranslation: "حاولت القطة الهرب من الغرفة." },
  { word: "exchange", translation: "يتبادل", partOfSpeech: "verb", difficulty: "medium", example: "We exchange gifts on the holiday.", exampleTranslation: "نتبادل الهدايا في العطلة." },
  { word: "exist", translation: "يوجد", partOfSpeech: "verb", difficulty: "hard", example: "Many stars exist far from Earth.", exampleTranslation: "توجد نجوم كثيرة بعيداً عن الأرض." },
  { word: "expect", translation: "يتوقّع", partOfSpeech: "verb", difficulty: "medium", example: "We expect rain this afternoon.", exampleTranslation: "نتوقّع مطراً بعد الظهر." },
  { word: "explode", translation: "ينفجر", partOfSpeech: "verb", difficulty: "hard", example: "The balloon will explode if you press it.", exampleTranslation: "سينفجر البالون إذا ضغطت عليه." },
  { word: "extend", translation: "يمدّد", partOfSpeech: "verb", difficulty: "hard", example: "They will extend the holiday by a day.", exampleTranslation: "سيمدّدون العطلة يوماً واحداً." },
  { word: "fasten", translation: "يثبّت/يربط", partOfSpeech: "verb", difficulty: "medium", example: "Fasten your seat belt now.", exampleTranslation: "اربط حزام الأمان الآن." },
  { word: "float", translation: "يطفو", partOfSpeech: "verb", difficulty: "easy", example: "Wood can float on water.", exampleTranslation: "يستطيع الخشب أن يطفو على الماء." },
  { word: "flow", translation: "يتدفّق", partOfSpeech: "verb", difficulty: "medium", example: "The river flows to the sea.", exampleTranslation: "يتدفّق النهر إلى البحر." },
  { word: "fold", translation: "يطوي", partOfSpeech: "verb", difficulty: "easy", example: "Fold the paper in half.", exampleTranslation: "اطوِ الورقة إلى نصفين." },
  { word: "forgive", translation: "يسامح", partOfSpeech: "verb", difficulty: "hard", example: "It is kind to forgive a friend.", exampleTranslation: "من اللطف أن تسامح صديقاً." },
  { word: "gather", translation: "يجتمع/يجمع", partOfSpeech: "verb", difficulty: "medium", example: "The family gathers for dinner.", exampleTranslation: "تجتمع العائلة لتناول العشاء." },
  { word: "glance", translation: "يلقي نظرة", partOfSpeech: "verb", difficulty: "hard", example: "She gave a quick glance at the clock.", exampleTranslation: "ألقت نظرة سريعة على الساعة." },
  { word: "grip", translation: "يمسك بإحكام", partOfSpeech: "verb", difficulty: "hard", example: "Grip the rope with both hands.", exampleTranslation: "أمسك الحبل بكلتا يديك." },
  { word: "greet", translation: "يحيّي", partOfSpeech: "verb", difficulty: "medium", example: "We greet our guests warmly.", exampleTranslation: "نحيّي ضيوفنا بحرارة." },
  { word: "guard", translation: "يحرس", partOfSpeech: "verb", difficulty: "medium", example: "The dog guards the house at night.", exampleTranslation: "يحرس الكلب المنزل في الليل." },
  { word: "guide", translation: "يرشد", partOfSpeech: "verb", difficulty: "medium", example: "A teacher guides the new students.", exampleTranslation: "يرشد المعلّم الطلاب الجدد." },
  { word: "handle", translation: "يتعامل مع", partOfSpeech: "verb", difficulty: "medium", example: "She can handle a difficult task.", exampleTranslation: "تستطيع التعامل مع مهمة صعبة." },
  { word: "heal", translation: "يشفي/يلتئم", partOfSpeech: "verb", difficulty: "medium", example: "The wound will heal in a week.", exampleTranslation: "سيلتئم الجرح خلال أسبوع." },
  { word: "hesitate", translation: "يتردّد", partOfSpeech: "verb", difficulty: "hard", example: "Do not hesitate to ask for help.", exampleTranslation: "لا تتردّد في طلب المساعدة." },
  { word: "hunt", translation: "يصطاد", partOfSpeech: "verb", difficulty: "medium", example: "Owls hunt small animals at night.", exampleTranslation: "تصطاد البوم حيوانات صغيرة في الليل." },
  { word: "ignore", translation: "يتجاهل", partOfSpeech: "verb", difficulty: "medium", example: "Try not to ignore the warning.", exampleTranslation: "حاول ألا تتجاهل التحذير." },
  { word: "imitate", translation: "يقلّد", partOfSpeech: "verb", difficulty: "hard", example: "Parrots can imitate human voices.", exampleTranslation: "تستطيع الببغاوات تقليد أصوات البشر." },
  { word: "impress", translation: "يثير الإعجاب", partOfSpeech: "verb", difficulty: "hard", example: "Her painting impressed the judges.", exampleTranslation: "أثارت لوحتها إعجاب الحكّام." },
  { word: "improve", translation: "يحسّن", partOfSpeech: "verb", difficulty: "medium", example: "Practice will improve your skills.", exampleTranslation: "ستحسّن الممارسة مهاراتك." },
  { word: "increase", translation: "يزيد", partOfSpeech: "verb", difficulty: "medium", example: "Exercise can increase your energy.", exampleTranslation: "يمكن أن تزيد التمارين من طاقتك." },
  { word: "influence", translation: "يؤثّر", partOfSpeech: "verb", difficulty: "hard", example: "Good friends influence our choices.", exampleTranslation: "يؤثّر الأصدقاء الجيدون في خياراتنا." },
  { word: "inspect", translation: "يفتّش", partOfSpeech: "verb", difficulty: "hard", example: "The teacher will inspect our work.", exampleTranslation: "سيفتّش المعلّم عملنا." },
  { word: "inspire", translation: "يلهم", partOfSpeech: "verb", difficulty: "hard", example: "Her story inspires young readers.", exampleTranslation: "تلهم قصتها القرّاء الصغار." },
  { word: "install", translation: "يثبّت/يركّب", partOfSpeech: "verb", difficulty: "hard", example: "They will install a new fan.", exampleTranslation: "سيركّبون مروحة جديدة." },
  { word: "intend", translation: "ينوي", partOfSpeech: "verb", difficulty: "hard", example: "We intend to start at dawn.", exampleTranslation: "ننوي البدء عند الفجر." },
  { word: "interrupt", translation: "يقاطع", partOfSpeech: "verb", difficulty: "hard", example: "Please do not interrupt the speaker.", exampleTranslation: "من فضلك لا تقاطع المتحدّث." },
  { word: "introduce", translation: "يقدّم/يعرّف", partOfSpeech: "verb", difficulty: "medium", example: "Let me introduce my friend.", exampleTranslation: "دعني أعرّفك بصديقي." },
  { word: "invent", translation: "يخترع", partOfSpeech: "verb", difficulty: "medium", example: "Engineers invent useful tools.", exampleTranslation: "يخترع المهندسون أدوات مفيدة." },
  { word: "invest", translation: "يستثمر", partOfSpeech: "verb", difficulty: "hard", example: "They invest money in the farm.", exampleTranslation: "يستثمرون المال في المزرعة." },
  { word: "invite", translation: "يدعو", partOfSpeech: "verb", difficulty: "easy", example: "We invite friends to the party.", exampleTranslation: "ندعو الأصدقاء إلى الحفل." },
  { word: "judge", translation: "يحكم", partOfSpeech: "verb", difficulty: "medium", example: "Do not judge a book by its cover.", exampleTranslation: "لا تحكم على الكتاب من غلافه." },
  { word: "launch", translation: "يطلق", partOfSpeech: "verb", difficulty: "hard", example: "They will launch the rocket today.", exampleTranslation: "سيطلقون الصاروخ اليوم." },
  { word: "lean", translation: "يميل/يتّكئ", partOfSpeech: "verb", difficulty: "medium", example: "Do not lean on the broken chair.", exampleTranslation: "لا تتّكئ على الكرسي المكسور." },
  { word: "lend", translation: "يُقرض/يُعير", partOfSpeech: "verb", difficulty: "medium", example: "Can you lend me your book?", exampleTranslation: "هل يمكنك أن تعيرني كتابك؟" },
  { word: "lift", translation: "يرفع", partOfSpeech: "verb", difficulty: "easy", example: "Lift the box with care.", exampleTranslation: "ارفع الصندوق بحذر." },
  { word: "link", translation: "يربط", partOfSpeech: "verb", difficulty: "medium", example: "The bridge links the two towns.", exampleTranslation: "يربط الجسر بين البلدتين." },
  { word: "locate", translation: "يحدّد موقع", partOfSpeech: "verb", difficulty: "hard", example: "Can you locate the city on the map?", exampleTranslation: "هل يمكنك تحديد موقع المدينة على الخريطة؟" },
  { word: "manage", translation: "يدير", partOfSpeech: "verb", difficulty: "medium", example: "She manages the school library.", exampleTranslation: "تدير مكتبة المدرسة." },
  { word: "manufacture", translation: "يصنّع", partOfSpeech: "verb", difficulty: "hard", example: "Factories manufacture cars.", exampleTranslation: "تصنّع المصانع السيارات." },
  { word: "mention", translation: "يذكر", partOfSpeech: "verb", difficulty: "medium", example: "She did not mention the time.", exampleTranslation: "لم تذكر الوقت." },
  { word: "obey", translation: "يطيع", partOfSpeech: "verb", difficulty: "medium", example: "Drivers must obey the signs.", exampleTranslation: "يجب على السائقين أن يطيعوا اللافتات." },
  { word: "occupy", translation: "يشغل/يحتلّ", partOfSpeech: "verb", difficulty: "hard", example: "The desk occupies half the room.", exampleTranslation: "يشغل المكتب نصف الغرفة." },
  { word: "occur", translation: "يحدث", partOfSpeech: "verb", difficulty: "hard", example: "Earthquakes occur without warning.", exampleTranslation: "تحدث الزلازل دون إنذار." },
  { word: "offer", translation: "يعرض/يقدّم", partOfSpeech: "verb", difficulty: "easy", example: "They offer free water to runners.", exampleTranslation: "يقدّمون ماءً مجانياً للعدّائين." },
  { word: "oppose", translation: "يعارض", partOfSpeech: "verb", difficulty: "hard", example: "Many people oppose the new rule.", exampleTranslation: "يعارض كثير من الناس القاعدة الجديدة." },
  { word: "overcome", translation: "يتغلّب على", partOfSpeech: "verb", difficulty: "hard", example: "She worked hard to overcome her fear.", exampleTranslation: "عملت بجدّ للتغلّب على خوفها." },
  { word: "pack", translation: "يحزم", partOfSpeech: "verb", difficulty: "easy", example: "Pack your bag for the trip.", exampleTranslation: "احزم حقيبتك للرحلة." },
  { word: "pause", translation: "يتوقّف مؤقتاً", partOfSpeech: "verb", difficulty: "medium", example: "Pause the video for a moment.", exampleTranslation: "أوقف الفيديو مؤقتاً للحظة." },
  { word: "perceive", translation: "يدرك", partOfSpeech: "verb", difficulty: "hard", example: "We perceive colors with our eyes.", exampleTranslation: "ندرك الألوان بأعيننا." },
  { word: "persist", translation: "يثابر", partOfSpeech: "verb", difficulty: "hard", example: "If you persist, you will succeed.", exampleTranslation: "إذا ثابرت، فستنجح." },
  { word: "plant", translation: "يزرع", partOfSpeech: "verb", difficulty: "easy", example: "We plant trees in the spring.", exampleTranslation: "نزرع الأشجار في الربيع." },
  { word: "pour", translation: "يصبّ", partOfSpeech: "verb", difficulty: "easy", example: "Pour the milk into the glass.", exampleTranslation: "اصبب الحليب في الكوب." },
  { word: "prepare", translation: "يحضّر/يجهّز", partOfSpeech: "verb", difficulty: "easy", example: "We prepare lunch together.", exampleTranslation: "نحضّر الغداء معاً." },
  { word: "preserve", translation: "يحفظ/يصون", partOfSpeech: "verb", difficulty: "hard", example: "We preserve old books carefully.", exampleTranslation: "نحفظ الكتب القديمة بعناية." },
  { word: "pretend", translation: "يتظاهر", partOfSpeech: "verb", difficulty: "medium", example: "The kids pretend to be pilots.", exampleTranslation: "يتظاهر الأطفال بأنهم طيّارون." },
  { word: "prevent", translation: "يمنع", partOfSpeech: "verb", difficulty: "medium", example: "Washing hands can prevent illness.", exampleTranslation: "غسل اليدين يمكن أن يمنع المرض." },
  { word: "produce", translation: "ينتج", partOfSpeech: "verb", difficulty: "medium", example: "Cows produce milk every day.", exampleTranslation: "تنتج الأبقار الحليب كل يوم." },
  { word: "promise", translation: "يعد", partOfSpeech: "verb", difficulty: "easy", example: "I promise to return the book.", exampleTranslation: "أعدك بإرجاع الكتاب." },
  { word: "promote", translation: "يعزّز/يروّج", partOfSpeech: "verb", difficulty: "hard", example: "Posters promote the school fair.", exampleTranslation: "تروّج الملصقات لمعرض المدرسة." },
  { word: "pronounce", translation: "ينطق", partOfSpeech: "verb", difficulty: "medium", example: "Try to pronounce the word slowly.", exampleTranslation: "حاول أن تنطق الكلمة ببطء." },
  { word: "protect", translation: "يحمي", partOfSpeech: "verb", difficulty: "easy", example: "Helmets protect our heads.", exampleTranslation: "تحمي الخوذات رؤوسنا." },
  { word: "prove", translation: "يثبت", partOfSpeech: "verb", difficulty: "medium", example: "The test will prove the idea.", exampleTranslation: "سيثبت الاختبار الفكرة." },
  { word: "provide", translation: "يوفّر", partOfSpeech: "verb", difficulty: "medium", example: "The school provides free books.", exampleTranslation: "توفّر المدرسة كتباً مجانية." },
  { word: "publish", translation: "ينشر", partOfSpeech: "verb", difficulty: "hard", example: "They will publish the magazine soon.", exampleTranslation: "سينشرون المجلة قريباً." },
  { word: "purchase", translation: "يشتري", partOfSpeech: "verb", difficulty: "hard", example: "We purchase fruit at the market.", exampleTranslation: "نشتري الفاكهة من السوق." },
  { word: "pursue", translation: "يسعى وراء", partOfSpeech: "verb", difficulty: "hard", example: "She wants to pursue a dream.", exampleTranslation: "تريد أن تسعى وراء حلم." },
  { word: "qualify", translation: "يتأهّل", partOfSpeech: "verb", difficulty: "hard", example: "Our team will qualify for the final.", exampleTranslation: "سيتأهّل فريقنا إلى النهائي." },
  { word: "realize", translation: "يدرك", partOfSpeech: "verb", difficulty: "medium", example: "I realize my mistake now.", exampleTranslation: "أدرك خطئي الآن." },
  { word: "receive", translation: "يستلم", partOfSpeech: "verb", difficulty: "easy", example: "We receive a letter every week.", exampleTranslation: "نستلم رسالة كل أسبوع." },
  { word: "reduce", translation: "يقلّل", partOfSpeech: "verb", difficulty: "medium", example: "We can reduce waste at home.", exampleTranslation: "نستطيع تقليل النفايات في المنزل." },
  { word: "refuse", translation: "يرفض", partOfSpeech: "verb", difficulty: "medium", example: "He may refuse the unfair offer.", exampleTranslation: "قد يرفض العرض غير العادل." },
  { word: "rely", translation: "يعتمد على", partOfSpeech: "verb", difficulty: "hard", example: "We rely on the sun for light.", exampleTranslation: "نعتمد على الشمس في الضوء." },
  { word: "remove", translation: "يزيل", partOfSpeech: "verb", difficulty: "medium", example: "Please remove your shoes inside.", exampleTranslation: "من فضلك أزل حذاءك في الداخل." },
  { word: "repair", translation: "يصلح", partOfSpeech: "verb", difficulty: "medium", example: "He can repair the broken bike.", exampleTranslation: "يستطيع إصلاح الدراجة المكسورة." },
  { word: "replace", translation: "يستبدل", partOfSpeech: "verb", difficulty: "medium", example: "Replace the old battery with a new one.", exampleTranslation: "استبدل البطارية القديمة بأخرى جديدة." },
  { word: "represent", translation: "يمثّل", partOfSpeech: "verb", difficulty: "hard", example: "This flag represents our team.", exampleTranslation: "يمثّل هذا العلم فريقنا." },
  { word: "require", translation: "يتطلّب", partOfSpeech: "verb", difficulty: "hard", example: "The task requires great patience.", exampleTranslation: "تتطلّب المهمة صبراً كبيراً." },
  { word: "rescue", translation: "ينقذ", partOfSpeech: "verb", difficulty: "medium", example: "Firefighters rescue people from danger.", exampleTranslation: "ينقذ رجال الإطفاء الناس من الخطر." },
  { word: "resist", translation: "يقاوم", partOfSpeech: "verb", difficulty: "hard", example: "Strong walls resist the wind.", exampleTranslation: "تقاوم الجدران القوية الرياح." },
  { word: "reward", translation: "يكافئ", partOfSpeech: "verb", difficulty: "medium", example: "We reward hard work with praise.", exampleTranslation: "نكافئ العمل الجاد بالثناء." },
  { word: "satisfy", translation: "يُرضي", partOfSpeech: "verb", difficulty: "hard", example: "A good meal will satisfy your hunger.", exampleTranslation: "ستُرضي وجبة جيدة جوعك." },
  { word: "search", translation: "يبحث", partOfSpeech: "verb", difficulty: "easy", example: "They search for the lost keys.", exampleTranslation: "يبحثون عن المفاتيح المفقودة." },
  { word: "settle", translation: "يستقرّ", partOfSpeech: "verb", difficulty: "hard", example: "The family settled in a new town.", exampleTranslation: "استقرّت العائلة في بلدة جديدة." },
  { word: "solve", translation: "يحلّ", partOfSpeech: "verb", difficulty: "easy", example: "Can you solve this riddle?", exampleTranslation: "هل تستطيع حلّ هذا اللغز؟" },
  { word: "support", translation: "يدعم", partOfSpeech: "verb", difficulty: "medium", example: "Strong beams support the roof.", exampleTranslation: "تدعم العوارض القوية السقف." },
  { word: "survive", translation: "ينجو", partOfSpeech: "verb", difficulty: "medium", example: "Cactus plants survive with little water.", exampleTranslation: "تنجو نباتات الصبّار بقليل من الماء." },
  { word: "succeed", translation: "ينجح", partOfSpeech: "verb", difficulty: "medium", example: "Work hard and you will succeed.", exampleTranslation: "اعمل بجدّ وستنجح." },
  { word: "struggle", translation: "يكافح", partOfSpeech: "verb", difficulty: "hard", example: "He struggled to lift the heavy crate.", exampleTranslation: "كافح ليرفع الصندوق الثقيل." },
  { word: "stretch", translation: "يمدّ/يتمدّد", partOfSpeech: "verb", difficulty: "medium", example: "Stretch your arms before you run.", exampleTranslation: "مُدّ ذراعيك قبل أن تركض." },
  { word: "transform", translation: "يحوّل", partOfSpeech: "verb", difficulty: "hard", example: "Paint can transform a dull room.", exampleTranslation: "يمكن للطلاء أن يحوّل غرفة باهتة." },
  { word: "twist", translation: "يلوي", partOfSpeech: "verb", difficulty: "medium", example: "Twist the cap to open the bottle.", exampleTranslation: "الوِ الغطاء لفتح الزجاجة." }
];
