/** Grade 6 extension batch A — simple examples (200 cards). Auto-generated. */
export const GRADE6_EXT_A = [
  { word: "compress", translation: "يضغط", partOfSpeech: "verb", difficulty: "medium", example: "We learned the word compress in class today.", exampleTranslation: "تعلّمنا كلمة يضغط في الحصة اليوم." },
  { word: "compromise", translation: "يتنازل", partOfSpeech: "verb", difficulty: "hard", example: "Can you use compromise in a sentence?", exampleTranslation: "هل يمكنك استخدام يتنازل في جملة؟" },
  { word: "comrade", translation: "رفيق", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned comrade on page ten.", exampleTranslation: "ذكرت القصة رفيق في الصفحة العاشرة." },
  { word: "concede", translation: "يعترف", partOfSpeech: "verb", difficulty: "medium", example: "Our teacher wrote concede on the board.", exampleTranslation: "كتب معلمنا يعترف على السبورة." },
  { word: "conceive", translation: "يتصوّر", partOfSpeech: "verb", difficulty: "medium", example: "I spelled conceive correctly on the quiz.", exampleTranslation: "تهجّيت يتصوّر بشكل صحيح في الاختبار." },
  { word: "concern", translation: "قلق", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain concern.", exampleTranslation: "تساعد الصورة على شرح قلق." },
  { word: "condemn", translation: "يدين", partOfSpeech: "verb", difficulty: "medium", example: "We found condemn in our reading book.", exampleTranslation: "وجدنا يدين في كتاب القراءة." },
  { word: "condition", translation: "حالة", partOfSpeech: "noun", difficulty: "medium", example: "Condition is a new word for our unit.", exampleTranslation: "حالة كلمة جديدة لوحدتنا." },
  { word: "cone", translation: "مخروط", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed cone.", exampleTranslation: "ناقشت مخروط مع زميلي." },
  { word: "confess", translation: "يعترف", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about confess.", exampleTranslation: "يسأل ورق العمل عن يعترف." },
  { word: "confine", translation: "يحصر", partOfSpeech: "verb", difficulty: "medium", example: "We heard confine in the science video.", exampleTranslation: "سمعنا يحصر في فيلم العلوم." },
  { word: "confuse", translation: "يربك", partOfSpeech: "verb", difficulty: "medium", example: "Please copy confuse into your notebook.", exampleTranslation: "من فضلك انسخ يربك في دفترك." },
  { word: "congratulate", translation: "يهنئ", partOfSpeech: "verb", difficulty: "hard", example: "The chart shows an example of congratulate.", exampleTranslation: "يُظهر المخطط مثالاً عن يهنئ." },
  { word: "congress", translation: "مؤتمر", partOfSpeech: "noun", difficulty: "medium", example: "Our group used congress in the project.", exampleTranslation: "استخدمت مجموعتنا مؤتمر في المشروع." },
  { word: "conscious", translation: "واعٍ", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with conscious.", exampleTranslation: "أعطى المعلم مثالاً بـواعٍ." },
  { word: "consist", translation: "يتكوّن", partOfSpeech: "verb", difficulty: "medium", example: "I underlined consist in the paragraph.", exampleTranslation: "وضعت خطاً تحت يتكوّن في الفقرة." },
  { word: "console", translation: "يواسي", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying console aloud.", exampleTranslation: "تدرّبنا على نطق يواسي بصوت عالٍ." },
  { word: "contact", translation: "اتصال", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains contact with a drawing.", exampleTranslation: "يشرح الملصق اتصال برسم." },
  { word: "contest", translation: "مسابقة", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with contest.", exampleTranslation: "شارك الجميع جملة فيها مسابقة." },
  { word: "continue", translation: "استمرار", partOfSpeech: "verb", difficulty: "medium", example: "The quiz included the word continue.", exampleTranslation: "تضمّن الاختبار كلمة استمرار." },
  { word: "control", translation: "تحكم", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word control in class today.", exampleTranslation: "تعلّمنا كلمة تحكم في الحصة اليوم." },
  { word: "convenient", translation: "مناسب", partOfSpeech: "adjective", difficulty: "hard", example: "Can you use convenient in a sentence?", exampleTranslation: "هل يمكنك استخدام مناسب في جملة؟" },
  { word: "conversation", translation: "محادثة", partOfSpeech: "noun", difficulty: "hard", example: "The story mentioned conversation on page ten.", exampleTranslation: "ذكرت القصة محادثة في الصفحة العاشرة." },
  { word: "convict", translation: "مدان", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote convict on the board.", exampleTranslation: "كتب معلمنا مدان على السبورة." },
  { word: "cope", translation: "يتأقلم", partOfSpeech: "verb", difficulty: "medium", example: "I spelled cope correctly on the quiz.", exampleTranslation: "تهجّيت يتأقلم بشكل صحيح في الاختبار." },
  { word: "core", translation: "لب", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain core.", exampleTranslation: "تساعد الصورة على شرح لب." },
  { word: "cornfield", translation: "حقل ذرة", partOfSpeech: "noun", difficulty: "medium", example: "We found cornfield in our reading book.", exampleTranslation: "وجدنا حقل ذرة في كتاب القراءة." },
  { word: "course", translation: "مساق", partOfSpeech: "noun", difficulty: "medium", example: "Course is a new word for our unit.", exampleTranslation: "مساق كلمة جديدة لوحدتنا." },
  { word: "cover", translation: "تغطية", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed cover.", exampleTranslation: "ناقشت تغطية مع زميلي." },
  { word: "craftsman", translation: "حرفي", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about craftsman.", exampleTranslation: "يسأل ورق العمل عن حرفي." },
  { word: "crash", translation: "تحطم", partOfSpeech: "verb", difficulty: "medium", example: "We heard crash in the science video.", exampleTranslation: "سمعنا تحطم في فيلم العلوم." },
  { word: "crevice", translation: "شق", partOfSpeech: "noun", difficulty: "medium", example: "Please copy crevice into your notebook.", exampleTranslation: "من فضلك انسخ شق في دفترك." },
  { word: "crew", translation: "طاقم", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of crew.", exampleTranslation: "يُظهر المخطط مثالاً عن طاقم." },
  { word: "crime", translation: "جريمة", partOfSpeech: "noun", difficulty: "easy", example: "Our group used crime in the project.", exampleTranslation: "استخدمت مجموعتنا جريمة في المشروع." },
  { word: "crisp", translation: "مقرمش", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with crisp.", exampleTranslation: "أعطى المعلم مثالاً بـمقرمش." },
  { word: "crossroads", translation: "مفترق", partOfSpeech: "noun", difficulty: "hard", example: "I underlined crossroads in the paragraph.", exampleTranslation: "وضعت خطاً تحت مفترق في الفقرة." },
  { word: "crouch", translation: "ينحني", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying crouch aloud.", exampleTranslation: "تدرّبنا على نطق ينحني بصوت عالٍ." },
  { word: "crowd", translation: "حشد", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains crowd with a drawing.", exampleTranslation: "يشرح الملصق حشد برسم." },
  { word: "crown", translation: "تاج", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with crown.", exampleTranslation: "شارك الجميع جملة فيها تاج." },
  { word: "crumble", translation: "يتفتت", partOfSpeech: "verb", difficulty: "medium", example: "The quiz included the word crumble.", exampleTranslation: "تضمّن الاختبار كلمة يتفتت." },
  { word: "crush", translation: "يسحق", partOfSpeech: "verb", difficulty: "medium", example: "We learned the word crush in class today.", exampleTranslation: "تعلّمنا كلمة يسحق في الحصة اليوم." },
  { word: "cube", translation: "مكعب", partOfSpeech: "noun", difficulty: "easy", example: "Can you use cube in a sentence?", exampleTranslation: "هل يمكنك استخدام مكعب في جملة؟" },
  { word: "curl", translation: "يجعّد", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned curl on page ten.", exampleTranslation: "ذكرت القصة يجعّد في الصفحة العاشرة." },
  { word: "curve", translation: "منحنى", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote curve on the board.", exampleTranslation: "كتب معلمنا منحنى على السبورة." },
  { word: "completely", translation: "تماماً", partOfSpeech: "adverb", difficulty: "hard", example: "I spelled completely correctly on the quiz.", exampleTranslation: "تهجّيت تماماً بشكل صحيح في الاختبار." },
  { word: "concerning", translation: "فيما يتعلق ب", partOfSpeech: "noun", difficulty: "hard", example: "The picture helps explain concerning.", exampleTranslation: "تساعد الصورة على شرح فيما يتعلق ب." },
  { word: "constantly", translation: "باستمرار", partOfSpeech: "adverb", difficulty: "hard", example: "We found constantly in our reading book.", exampleTranslation: "وجدنا باستمرار في كتاب القراءة." },
  { word: "continuously", translation: "باستمرار", partOfSpeech: "adverb", difficulty: "hard", example: "Continuously is a new word for our unit.", exampleTranslation: "باستمرار كلمة جديدة لوحدتنا." },
  { word: "currently", translation: "حالياً", partOfSpeech: "adverb", difficulty: "medium", example: "My partner and I discussed currently.", exampleTranslation: "ناقشت حالياً مع زميلي." },
  { word: "daily", translation: "يومي", partOfSpeech: "adjective", difficulty: "medium", example: "The worksheet asks about daily.", exampleTranslation: "يسأل ورق العمل عن يومي." },
  { word: "damp", translation: "رطب", partOfSpeech: "adjective", difficulty: "medium", example: "We heard damp in the science video.", exampleTranslation: "سمعنا رطب في فيلم العلوم." },
  { word: "dark", translation: "مظلم", partOfSpeech: "adjective", difficulty: "medium", example: "Please copy dark into your notebook.", exampleTranslation: "من فضلك انسخ مظلم في دفترك." },
  { word: "definitely", translation: "بالتأكيد", partOfSpeech: "adverb", difficulty: "hard", example: "The chart shows an example of definitely.", exampleTranslation: "يُظهر المخطط مثالاً عن بالتأكيد." },
  { word: "delicious", translation: "لذيذ", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used delicious in the project.", exampleTranslation: "استخدمت مجموعتنا لذيذ في المشروع." },
  { word: "die", translation: "موت", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with die.", exampleTranslation: "أعطى المعلم مثالاً بـموت." },
  { word: "dirty", translation: "قذر", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined dirty in the paragraph.", exampleTranslation: "وضعت خطاً تحت قذر في الفقرة." },
  { word: "distant", translation: "بعيد", partOfSpeech: "adjective", difficulty: "medium", example: "We practiced saying distant aloud.", exampleTranslation: "تدرّبنا على نطق بعيد بصوت عالٍ." },
  { word: "domestic", translation: "محلي", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains domestic with a drawing.", exampleTranslation: "يشرح الملصق محلي برسم." },
  { word: "downstairs", translation: "في الطابق السفلي", partOfSpeech: "adverb", difficulty: "hard", example: "Everyone shared a sentence with downstairs.", exampleTranslation: "شارك الجميع جملة فيها في الطابق السفلي." },
  { word: "dull", translation: "بليد", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word dull.", exampleTranslation: "تضمّن الاختبار كلمة بليد." },
  { word: "during", translation: "في", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word during in class today.", exampleTranslation: "تعلّمنا كلمة في في الحصة اليوم." },
  { word: "each", translation: "كل", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use each in a sentence?", exampleTranslation: "هل يمكنك استخدام كل في جملة؟" },
  { word: "early", translation: "مبكر", partOfSpeech: "adjective", difficulty: "medium", example: "The story mentioned early on page ten.", exampleTranslation: "ذكرت القصة مبكر في الصفحة العاشرة." },
  { word: "easily", translation: "بسهولة", partOfSpeech: "adverb", difficulty: "medium", example: "Our teacher wrote easily on the board.", exampleTranslation: "كتب معلمنا بسهولة على السبورة." },
  { word: "eastern", translation: "شرقي", partOfSpeech: "adjective", difficulty: "medium", example: "I spelled eastern correctly on the quiz.", exampleTranslation: "تهجّيت شرقي بشكل صحيح في الاختبار." },
  { word: "either", translation: "أي", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain either.", exampleTranslation: "تساعد الصورة على شرح أي." },
  { word: "elastic", translation: "مرن", partOfSpeech: "adjective", difficulty: "medium", example: "We found elastic in our reading book.", exampleTranslation: "وجدنا مرن في كتاب القراءة." },
  { word: "empty", translation: "فارغ", partOfSpeech: "adjective", difficulty: "medium", example: "Empty is a new word for our unit.", exampleTranslation: "فارغ كلمة جديدة لوحدتنا." },
  { word: "enjoy", translation: "استمتاع", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed enjoy.", exampleTranslation: "ناقشت استمتاع مع زميلي." },
  { word: "enter", translation: "دخول", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about enter.", exampleTranslation: "يسأل ورق العمل عن دخول." },
  { word: "especially", translation: "خصوصاً", partOfSpeech: "adverb", difficulty: "hard", example: "We heard especially in the science video.", exampleTranslation: "سمعنا خصوصاً في فيلم العلوم." },
  { word: "even", translation: "متساوٍ", partOfSpeech: "adjective", difficulty: "medium", example: "Please copy even into your notebook.", exampleTranslation: "من فضلك انسخ متساوٍ في دفترك." },
  { word: "eventually", translation: "في النهاية", partOfSpeech: "adverb", difficulty: "hard", example: "The chart shows an example of eventually.", exampleTranslation: "يُظهر المخطط مثالاً عن في النهاية." },
  { word: "every", translation: "كل", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used every in the project.", exampleTranslation: "استخدمت مجموعتنا كل في المشروع." },
  { word: "everywhere", translation: "في كل مكان", partOfSpeech: "adverb", difficulty: "hard", example: "The teacher gave an example with everywhere.", exampleTranslation: "أعطى المعلم مثالاً بـفي كل مكان." },
  { word: "exact", translation: "دقيق", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined exact in the paragraph.", exampleTranslation: "وضعت خطاً تحت دقيق في الفقرة." },
  { word: "exactly", translation: "بالضبط", partOfSpeech: "adverb", difficulty: "medium", example: "We practiced saying exactly aloud.", exampleTranslation: "تدرّبنا على نطق بالضبط بصوت عالٍ." },
  { word: "expensive", translation: "غالي", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains expensive with a drawing.", exampleTranslation: "يشرح الملصق غالي برسم." },
  { word: "extra", translation: "إضافي", partOfSpeech: "adjective", difficulty: "medium", example: "Everyone shared a sentence with extra.", exampleTranslation: "شارك الجميع جملة فيها إضافي." },
  { word: "extremely", translation: "للغاية", partOfSpeech: "adverb", difficulty: "medium", example: "The quiz included the word extremely.", exampleTranslation: "تضمّن الاختبار كلمة للغاية." },
  { word: "fake", translation: "مزيف", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word fake in class today.", exampleTranslation: "تعلّمنا كلمة مزيف في الحصة اليوم." },
  { word: "false", translation: "خاطئ", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use false in a sentence?", exampleTranslation: "هل يمكنك استخدام خاطئ في جملة؟" },
  { word: "fetch", translation: "إحضار", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned fetch on page ten.", exampleTranslation: "ذكرت القصة إحضار في الصفحة العاشرة." },
  { word: "fight", translation: "قتال", partOfSpeech: "verb", difficulty: "medium", example: "Our teacher wrote fight on the board.", exampleTranslation: "كتب معلمنا قتال على السبورة." },
  { word: "final", translation: "نهائي", partOfSpeech: "adjective", difficulty: "medium", example: "I spelled final correctly on the quiz.", exampleTranslation: "تهجّيت نهائي بشكل صحيح في الاختبار." },
  { word: "finish", translation: "إنهاء", partOfSpeech: "verb", difficulty: "medium", example: "The picture helps explain finish.", exampleTranslation: "تساعد الصورة على شرح إنهاء." },
  { word: "fit", translation: "لائق", partOfSpeech: "adjective", difficulty: "medium", example: "We found fit in our reading book.", exampleTranslation: "وجدنا لائق في كتاب القراءة." },
  { word: "formerly", translation: "سابقاً", partOfSpeech: "adverb", difficulty: "medium", example: "Formerly is a new word for our unit.", exampleTranslation: "سابقاً كلمة جديدة لوحدتنا." },
  { word: "frequently", translation: "بشكل متكرر", partOfSpeech: "adverb", difficulty: "hard", example: "My partner and I discussed frequently.", exampleTranslation: "ناقشت بشكل متكرر مع زميلي." },
  { word: "fully", translation: "بالكامل", partOfSpeech: "adverb", difficulty: "medium", example: "The worksheet asks about fully.", exampleTranslation: "يسأل ورق العمل عن بالكامل." },
  { word: "giant", translation: "عملاق", partOfSpeech: "adjective", difficulty: "medium", example: "We heard giant in the science video.", exampleTranslation: "سمعنا عملاق في فيلم العلوم." },
  { word: "global", translation: "عالمي", partOfSpeech: "adjective", difficulty: "medium", example: "Please copy global into your notebook.", exampleTranslation: "من فضلك انسخ عالمي في دفترك." },
  { word: "gradually", translation: "تدريجياً", partOfSpeech: "adverb", difficulty: "medium", example: "The chart shows an example of gradually.", exampleTranslation: "يُظهر المخطط مثالاً عن تدريجياً." },
  { word: "guess", translation: "تخمين", partOfSpeech: "verb", difficulty: "medium", example: "Our group used guess in the project.", exampleTranslation: "استخدمت مجموعتنا تخمين في المشروع." },
  { word: "handsome", translation: "وسيم", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with handsome.", exampleTranslation: "أعطى المعلم مثالاً بـوسيم." },
  { word: "happen", translation: "حدوث", partOfSpeech: "verb", difficulty: "medium", example: "I underlined happen in the paragraph.", exampleTranslation: "وضعت خطاً تحت حدوث في الفقرة." },
  { word: "hardly", translation: "بالكاد", partOfSpeech: "adverb", difficulty: "medium", example: "We practiced saying hardly aloud.", exampleTranslation: "تدرّبنا على نطق بالكاد بصوت عالٍ." },
  { word: "hate", translation: "كره", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains hate with a drawing.", exampleTranslation: "يشرح الملصق كره برسم." },
  { word: "high", translation: "عالي", partOfSpeech: "adjective", difficulty: "medium", example: "Everyone shared a sentence with high.", exampleTranslation: "شارك الجميع جملة فيها عالي." },
  { word: "highly", translation: "بدرجة عالية", partOfSpeech: "adverb", difficulty: "medium", example: "The quiz included the word highly.", exampleTranslation: "تضمّن الاختبار كلمة بدرجة عالية." },
  { word: "honestly", translation: "بصدق", partOfSpeech: "adverb", difficulty: "medium", example: "We learned the word honestly in class today.", exampleTranslation: "تعلّمنا كلمة بصدق في الحصة اليوم." },
  { word: "huge", translation: "ضخم", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use huge in a sentence?", exampleTranslation: "هل يمكنك استخدام ضخم في جملة؟" },
  { word: "hurry", translation: "عجلة", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned hurry on page ten.", exampleTranslation: "ذكرت القصة عجلة في الصفحة العاشرة." },
  { word: "immediately", translation: "فوراً", partOfSpeech: "adverb", difficulty: "hard", example: "Our teacher wrote immediately on the board.", exampleTranslation: "كتب معلمنا فوراً على السبورة." },
  { word: "imperfect", translation: "غير مثالي", partOfSpeech: "adjective", difficulty: "medium", example: "I spelled imperfect correctly on the quiz.", exampleTranslation: "تهجّيت غير مثالي بشكل صحيح في الاختبار." },
  { word: "incomplete", translation: "غير مكتمل", partOfSpeech: "adjective", difficulty: "hard", example: "The picture helps explain incomplete.", exampleTranslation: "تساعد الصورة على شرح غير مكتمل." },
  { word: "incorrect", translation: "خاطئ", partOfSpeech: "adjective", difficulty: "medium", example: "We found incorrect in our reading book.", exampleTranslation: "وجدنا خاطئ في كتاب القراءة." },
  { word: "indirectly", translation: "بشكل غير مباشر", partOfSpeech: "adverb", difficulty: "hard", example: "Indirectly is a new word for our unit.", exampleTranslation: "بشكل غير مباشر كلمة جديدة لوحدتنا." },
  { word: "indoor", translation: "داخلي", partOfSpeech: "adjective", difficulty: "medium", example: "My partner and I discussed indoor.", exampleTranslation: "ناقشت داخلي مع زميلي." },
  { word: "inject", translation: "حقن", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about inject.", exampleTranslation: "يسأل ورق العمل عن حقن." },
  { word: "inner", translation: "داخلي", partOfSpeech: "adjective", difficulty: "medium", example: "We heard inner in the science video.", exampleTranslation: "سمعنا داخلي في فيلم العلوم." },
  { word: "insist", translation: "إصرار", partOfSpeech: "verb", difficulty: "medium", example: "Please copy insist into your notebook.", exampleTranslation: "من فضلك انسخ إصرار في دفترك." },
  { word: "instantly", translation: "فوراً", partOfSpeech: "adverb", difficulty: "medium", example: "The chart shows an example of instantly.", exampleTranslation: "يُظهر المخطط مثالاً عن فوراً." },
  { word: "international", translation: "دولي", partOfSpeech: "adjective", difficulty: "hard", example: "Our group used international in the project.", exampleTranslation: "استخدمت مجموعتنا دولي في المشروع." },
  { word: "jog", translation: "هرولة", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with jog.", exampleTranslation: "أعطى المعلم مثالاً بـهرولة." },
  { word: "just", translation: "فقط", partOfSpeech: "adverb", difficulty: "medium", example: "I underlined just in the paragraph.", exampleTranslation: "وضعت خطاً تحت فقط في الفقرة." },
  { word: "keep", translation: "احتفاظ", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying keep aloud.", exampleTranslation: "تدرّبنا على نطق احتفاظ بصوت عالٍ." },
  { word: "kill", translation: "قتل", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains kill with a drawing.", exampleTranslation: "يشرح الملصق قتل برسم." },
  { word: "kindly", translation: "بلطف", partOfSpeech: "adverb", difficulty: "medium", example: "Everyone shared a sentence with kindly.", exampleTranslation: "شارك الجميع جملة فيها بلطف." },
  { word: "knit", translation: "حياكة", partOfSpeech: "verb", difficulty: "medium", example: "The quiz included the word knit.", exampleTranslation: "تضمّن الاختبار كلمة حياكة." },
  { word: "later", translation: "لاحقاً", partOfSpeech: "adverb", difficulty: "medium", example: "We learned the word later in class today.", exampleTranslation: "تعلّمنا كلمة لاحقاً في الحصة اليوم." },
  { word: "lay", translation: "وضع", partOfSpeech: "verb", difficulty: "medium", example: "Can you use lay in a sentence?", exampleTranslation: "هل يمكنك استخدام وضع في جملة؟" },
  { word: "leave", translation: "مغادرة", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned leave on page ten.", exampleTranslation: "ذكرت القصة مغادرة في الصفحة العاشرة." },
  { word: "let", translation: "سماح", partOfSpeech: "verb", difficulty: "medium", example: "Our teacher wrote let on the board.", exampleTranslation: "كتب معلمنا سماح على السبورة." },
  { word: "lie", translation: "كذب", partOfSpeech: "verb", difficulty: "medium", example: "I spelled lie correctly on the quiz.", exampleTranslation: "تهجّيت كذب بشكل صحيح في الاختبار." },
  { word: "likely", translation: "محتمل", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain likely.", exampleTranslation: "تساعد الصورة على شرح محتمل." },
  { word: "living", translation: "حي", partOfSpeech: "adjective", difficulty: "medium", example: "We found living in our reading book.", exampleTranslation: "وجدنا حي في كتاب القراءة." },
  { word: "local", translation: "محلي", partOfSpeech: "adjective", difficulty: "medium", example: "Local is a new word for our unit.", exampleTranslation: "محلي كلمة جديدة لوحدتنا." },
  { word: "lower", translation: "سفلي", partOfSpeech: "adjective", difficulty: "medium", example: "My partner and I discussed lower.", exampleTranslation: "ناقشت سفلي مع زميلي." },
  { word: "main", translation: "رئيسي", partOfSpeech: "adjective", difficulty: "medium", example: "The worksheet asks about main.", exampleTranslation: "يسأل ورق العمل عن رئيسي." },
  { word: "mainly", translation: "أساساً", partOfSpeech: "adverb", difficulty: "medium", example: "We heard mainly in the science video.", exampleTranslation: "سمعنا أساساً في فيلم العلوم." },
  { word: "make", translation: "صنع", partOfSpeech: "verb", difficulty: "medium", example: "Please copy make into your notebook.", exampleTranslation: "من فضلك انسخ صنع في دفترك." },
  { word: "maximum", translation: "أقصى", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of maximum.", exampleTranslation: "يُظهر المخطط مثالاً عن أقصى." },
  { word: "messy", translation: "فوضوي", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used messy in the project.", exampleTranslation: "استخدمت مجموعتنا فوضوي في المشروع." },
  { word: "middle", translation: "أوسط", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with middle.", exampleTranslation: "أعطى المعلم مثالاً بـأوسط." },
  { word: "minimum", translation: "أدنى", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined minimum in the paragraph.", exampleTranslation: "وضعت خطاً تحت أدنى في الفقرة." },
  { word: "minus", translation: "سالب", partOfSpeech: "adjective", difficulty: "medium", example: "We practiced saying minus aloud.", exampleTranslation: "تدرّبنا على نطق سالب بصوت عالٍ." },
  { word: "moist", translation: "رطب", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains moist with a drawing.", exampleTranslation: "يشرح الملصق رطب برسم." },
  { word: "monthly", translation: "شهري", partOfSpeech: "adjective", difficulty: "medium", example: "Everyone shared a sentence with monthly.", exampleTranslation: "شارك الجميع جملة فيها شهري." },
  { word: "mostly", translation: "في الغالب", partOfSpeech: "adverb", difficulty: "medium", example: "The quiz included the word mostly.", exampleTranslation: "تضمّن الاختبار كلمة في الغالب." },
  { word: "national", translation: "وطني", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word national in class today.", exampleTranslation: "تعلّمنا كلمة وطني في الحصة اليوم." },
  { word: "natural", translation: "طبيعي", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use natural in a sentence?", exampleTranslation: "هل يمكنك استخدام طبيعي في جملة؟" },
  { word: "neat", translation: "مرتب", partOfSpeech: "adjective", difficulty: "medium", example: "The story mentioned neat on page ten.", exampleTranslation: "ذكرت القصة مرتب في الصفحة العاشرة." },
  { word: "negative", translation: "سلبي", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote negative on the board.", exampleTranslation: "كتب معلمنا سلبي على السبورة." },
  { word: "neither", translation: "لا هذا ولا ذاك", partOfSpeech: "adjective", difficulty: "medium", example: "I spelled neither correctly on the quiz.", exampleTranslation: "تهجّيت لا هذا ولا ذاك بشكل صحيح في الاختبار." },
  { word: "nervously", translation: "بتوتر", partOfSpeech: "adverb", difficulty: "medium", example: "The picture helps explain nervously.", exampleTranslation: "تساعد الصورة على شرح بتوتر." },
  { word: "noisy", translation: "صاخب", partOfSpeech: "adjective", difficulty: "medium", example: "We found noisy in our reading book.", exampleTranslation: "وجدنا صاخب في كتاب القراءة." },
  { word: "normal", translation: "طبيعي", partOfSpeech: "adjective", difficulty: "medium", example: "Normal is a new word for our unit.", exampleTranslation: "طبيعي كلمة جديدة لوحدتنا." },
  { word: "northern", translation: "شمالي", partOfSpeech: "adjective", difficulty: "medium", example: "My partner and I discussed northern.", exampleTranslation: "ناقشت شمالي مع زميلي." },
  { word: "now", translation: "الآن", partOfSpeech: "adverb", difficulty: "medium", example: "The worksheet asks about now.", exampleTranslation: "يسأل ورق العمل عن الآن." },
  { word: "nowhere", translation: "في لا مكان", partOfSpeech: "adverb", difficulty: "medium", example: "We heard nowhere in the science video.", exampleTranslation: "سمعنا في لا مكان في فيلم العلوم." },
  { word: "obviously", translation: "بوضوح", partOfSpeech: "adverb", difficulty: "medium", example: "Please copy obviously into your notebook.", exampleTranslation: "من فضلك انسخ بوضوح في دفترك." },
  { word: "occasionally", translation: "أحياناً", partOfSpeech: "adverb", difficulty: "hard", example: "The chart shows an example of occasionally.", exampleTranslation: "يُظهر المخطط مثالاً عن أحياناً." },
  { word: "odd", translation: "غريب", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used odd in the project.", exampleTranslation: "استخدمت مجموعتنا غريب في المشروع." },
  { word: "openly", translation: "علناً", partOfSpeech: "adverb", difficulty: "medium", example: "The teacher gave an example with openly.", exampleTranslation: "أعطى المعلم مثالاً بـعلناً." },
  { word: "original", translation: "أصلي", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined original in the paragraph.", exampleTranslation: "وضعت خطاً تحت أصلي في الفقرة." },
  { word: "outdoor", translation: "خارجي", partOfSpeech: "adjective", difficulty: "medium", example: "We practiced saying outdoor aloud.", exampleTranslation: "تدرّبنا على نطق خارجي بصوت عالٍ." },
  { word: "outer", translation: "خارجي", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains outer with a drawing.", exampleTranslation: "يشرح الملصق خارجي برسم." },
  { word: "own", translation: "ملكية", partOfSpeech: "verb", difficulty: "medium", example: "Everyone shared a sentence with own.", exampleTranslation: "شارك الجميع جملة فيها ملكية." },
  { word: "pale", translation: "شاحب", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word pale.", exampleTranslation: "تضمّن الاختبار كلمة شاحب." },
  { word: "particularly", translation: "خصوصاً", partOfSpeech: "adverb", difficulty: "hard", example: "We learned the word particularly in class today.", exampleTranslation: "تعلّمنا كلمة خصوصاً في الحصة اليوم." },
  { word: "passive", translation: "سلبي", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use passive in a sentence?", exampleTranslation: "هل يمكنك استخدام سلبي في جملة؟" },
  { word: "peel", translation: "تقشير", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned peel on page ten.", exampleTranslation: "ذكرت القصة تقشير في الصفحة العاشرة." },
  { word: "perfect", translation: "مثالي", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote perfect on the board.", exampleTranslation: "كتب معلمنا مثالي على السبورة." },
  { word: "place", translation: "وضع", partOfSpeech: "verb", difficulty: "medium", example: "I spelled place correctly on the quiz.", exampleTranslation: "تهجّيت وضع بشكل صحيح في الاختبار." },
  { word: "plenty", translation: "وفير", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain plenty.", exampleTranslation: "تساعد الصورة على شرح وفير." },
  { word: "plus", translation: "موجب", partOfSpeech: "adjective", difficulty: "medium", example: "We found plus in our reading book.", exampleTranslation: "وجدنا موجب في كتاب القراءة." },
  { word: "politely", translation: "بأدب", partOfSpeech: "adverb", difficulty: "medium", example: "Politely is a new word for our unit.", exampleTranslation: "بأدب كلمة جديدة لوحدتنا." },
  { word: "poor", translation: "فقير", partOfSpeech: "adjective", difficulty: "medium", example: "My partner and I discussed poor.", exampleTranslation: "ناقشت فقير مع زميلي." },
  { word: "positive", translation: "إيجابي", partOfSpeech: "adjective", difficulty: "medium", example: "The worksheet asks about positive.", exampleTranslation: "يسأل ورق العمل عن إيجابي." },
  { word: "possible", translation: "ممكن", partOfSpeech: "adjective", difficulty: "medium", example: "We heard possible in the science video.", exampleTranslation: "سمعنا ممكن في فيلم العلوم." },
  { word: "possibly", translation: "ربما", partOfSpeech: "adverb", difficulty: "medium", example: "Please copy possibly into your notebook.", exampleTranslation: "من فضلك انسخ ربما في دفترك." },
  { word: "prefer", translation: "تفضيل", partOfSpeech: "verb", difficulty: "medium", example: "The chart shows an example of prefer.", exampleTranslation: "يُظهر المخطط مثالاً عن تفضيل." },
  { word: "previously", translation: "سابقاً", partOfSpeech: "adverb", difficulty: "hard", example: "Our group used previously in the project.", exampleTranslation: "استخدمت مجموعتنا سابقاً في المشروع." },
  { word: "print", translation: "طباعة", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with print.", exampleTranslation: "أعطى المعلم مثالاً بـطباعة." },
  { word: "public", translation: "عام", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined public in the paragraph.", exampleTranslation: "وضعت خطاً تحت عام في الفقرة." },
  { word: "put", translation: "وضع", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying put aloud.", exampleTranslation: "تدرّبنا على نطق وضع بصوت عالٍ." },
  { word: "quick", translation: "سريع", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains quick with a drawing.", exampleTranslation: "يشرح الملصق سريع برسم." },
  { word: "quietly", translation: "بهدوء", partOfSpeech: "adverb", difficulty: "medium", example: "Everyone shared a sentence with quietly.", exampleTranslation: "شارك الجميع جملة فيها بهدوء." },
  { word: "quit", translation: "ترك", partOfSpeech: "verb", difficulty: "medium", example: "The quiz included the word quit.", exampleTranslation: "تضمّن الاختبار كلمة ترك." },
  { word: "quite", translation: "تماماً", partOfSpeech: "adverb", difficulty: "medium", example: "We learned the word quite in class today.", exampleTranslation: "تعلّمنا كلمة تماماً في الحصة اليوم." },
  { word: "rapidly", translation: "بسرعة", partOfSpeech: "adverb", difficulty: "medium", example: "Can you use rapidly in a sentence?", exampleTranslation: "هل يمكنك استخدام بسرعة في جملة؟" },
  { word: "rarely", translation: "نادراً", partOfSpeech: "adverb", difficulty: "medium", example: "The story mentioned rarely on page ten.", exampleTranslation: "ذكرت القصة نادراً في الصفحة العاشرة." },
  { word: "ready", translation: "جاهز", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote ready on the board.", exampleTranslation: "كتب معلمنا جاهز على السبورة." },
  { word: "real", translation: "حقيقي", partOfSpeech: "adjective", difficulty: "medium", example: "I spelled real correctly on the quiz.", exampleTranslation: "تهجّيت حقيقي بشكل صحيح في الاختبار." },
  { word: "really", translation: "حقاً", partOfSpeech: "adverb", difficulty: "medium", example: "The picture helps explain really.", exampleTranslation: "تساعد الصورة على شرح حقاً." },
  { word: "recently", translation: "مؤخراً", partOfSpeech: "adverb", difficulty: "medium", example: "We found recently in our reading book.", exampleTranslation: "وجدنا مؤخراً في كتاب القراءة." },
  { word: "regarding", translation: "بجودة", partOfSpeech: "noun", difficulty: "medium", example: "Regarding is a new word for our unit.", exampleTranslation: "بجودة كلمة جديدة لوحدتنا." },
  { word: "relate", translation: "ربط", partOfSpeech: "verb", difficulty: "medium", example: "My partner and I discussed relate.", exampleTranslation: "ناقشت ربط مع زميلي." },
  { word: "relax", translation: "استرخاء", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about relax.", exampleTranslation: "يسأل ورق العمل عن استرخاء." },
  { word: "release", translation: "إطلاق", partOfSpeech: "verb", difficulty: "medium", example: "We heard release in the science video.", exampleTranslation: "سمعنا إطلاق في فيلم العلوم." },
  { word: "reply", translation: "رد", partOfSpeech: "verb", difficulty: "medium", example: "Please copy reply into your notebook.", exampleTranslation: "من فضلك انسخ رد في دفترك." },
  { word: "ride", translation: "ركوب", partOfSpeech: "verb", difficulty: "medium", example: "The chart shows an example of ride.", exampleTranslation: "يُظهر المخطط مثالاً عن ركوب." },
  { word: "right", translation: "يمين", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used right in the project.", exampleTranslation: "استخدمت مجموعتنا يمين في المشروع." },
  { word: "risky", translation: "محفوف بالمخاطر", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with risky.", exampleTranslation: "أعطى المعلم مثالاً بـمحفوف بالمخاطر." },
  { word: "rub", translation: "فرك", partOfSpeech: "verb", difficulty: "medium", example: "I underlined rub in the paragraph.", exampleTranslation: "وضعت خطاً تحت فرك في الفقرة." },
  { word: "rudely", translation: "بوقاحة", partOfSpeech: "adverb", difficulty: "medium", example: "We practiced saying rudely aloud.", exampleTranslation: "تدرّبنا على نطق بوقاحة بصوت عالٍ." },
  { word: "rush", translation: "عجلة", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains rush with a drawing.", exampleTranslation: "يشرح الملصق عجلة برسم." },
  { word: "say", translation: "قول", partOfSpeech: "verb", difficulty: "medium", example: "Everyone shared a sentence with say.", exampleTranslation: "شارك الجميع جملة فيها قول." },
  { word: "secretly", translation: "سراً", partOfSpeech: "adverb", difficulty: "medium", example: "The quiz included the word secretly.", exampleTranslation: "تضمّن الاختبار كلمة سراً." },
];
