/** Grade 5 chunk E — simple vocabulary (earth, civics, health, nature) (410 cards). */
export const GRADE5_CHUNK_E = [
  { word: "wolf", translation: "ذئب", partOfSpeech: "noun", difficulty: "easy", example: "We heard wolf in the science video.", exampleTranslation: "سمعنا ذئب في فيلم العلوم." },
  { word: "moose", translation: "موظ", partOfSpeech: "noun", difficulty: "medium", example: "Please copy moose into your notebook.", exampleTranslation: "من فضلك انسخ موظ في دفترك." },
  { word: "rhino", translation: "وحيد القرن", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of rhino.", exampleTranslation: "يُظهر المخطط مثالاً عن وحيد القرن." },
  { word: "donkey", translation: "حمار", partOfSpeech: "noun", difficulty: "easy", example: "Our group used donkey in the project.", exampleTranslation: "استخدمت مجموعتنا حمار في المشروع." },
  { word: "pony", translation: "مهر", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with pony.", exampleTranslation: "أعطى المعلم مثالاً بـمهر." },
  { word: "beaver", translation: "قندس", partOfSpeech: "noun", difficulty: "medium", example: "I underlined beaver in the paragraph.", exampleTranslation: "وضعت خطاً تحت قندس في الفقرة." },
  { word: "otter", translation: "قضاعة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying otter aloud.", exampleTranslation: "تدرّبنا على نطق قضاعة بصوت عالٍ." },
  { word: "lobster", translation: "جراد البحر", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains lobster with a drawing.", exampleTranslation: "يشرح الملصق جراد البحر برسم." },
  { word: "salmon", translation: "سلمون", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with salmon.", exampleTranslation: "شارك الجميع جملة فيها سلمون." },
  { word: "tuna", translation: "تونة", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word tuna.", exampleTranslation: "تضمّن الاختبار كلمة تونة." },
  { word: "trout", translation: "تروتة", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word trout in class today.", exampleTranslation: "تعلّمنا كلمة تروتة في الحصة اليوم." },
  { word: "penguin", translation: "بطريق", partOfSpeech: "noun", difficulty: "easy", example: "Can you use penguin in a sentence?", exampleTranslation: "هل يمكنك استخدام بطريق في جملة؟" },
  { word: "sparrow", translation: "عصفور", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned sparrow on page ten.", exampleTranslation: "ذكرت القصة عصفور في الصفحة العاشرة." },
  { word: "robin", translation: "أبو الحن", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote robin on the board.", exampleTranslation: "كتب معلمنا أبو الحن على السبورة." },
  { word: "hawk", translation: "صقر", partOfSpeech: "noun", difficulty: "easy", example: "I spelled hawk correctly on the quiz.", exampleTranslation: "تهجّيت صقر بشكل صحيح في الاختبار." },
  { word: "falcon", translation: "صقر صياد", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain falcon.", exampleTranslation: "تساعد الصورة على شرح صقر صياد." },
  { word: "crow", translation: "غراب", partOfSpeech: "noun", difficulty: "easy", example: "We found crow in our reading book.", exampleTranslation: "وجدنا غراب في كتاب القراءة." },
  { word: "raven", translation: "غراب أسود", partOfSpeech: "noun", difficulty: "medium", example: "Raven is a new word for our unit.", exampleTranslation: "غراب أسود كلمة جديدة لوحدتنا." },
  { word: "swan", translation: "بجعة", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed swan.", exampleTranslation: "ناقشت بجعة مع زميلي." },
  { word: "goose", translation: "إوزة", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about goose.", exampleTranslation: "يسأل ورق العمل عن إوزة." },
  { word: "turkey", translation: "ديك رومي", partOfSpeech: "noun", difficulty: "easy", example: "We heard turkey in the science video.", exampleTranslation: "سمعنا ديك رومي في فيلم العلوم." },
  { word: "rooster", translation: "ديك", partOfSpeech: "noun", difficulty: "easy", example: "Please copy rooster into your notebook.", exampleTranslation: "من فضلك انسخ ديك في دفترك." },
  { word: "pigeon", translation: "حمامة", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of pigeon.", exampleTranslation: "يُظهر المخطط مثالاً عن حمامة." },
  { word: "rat", translation: "جرذ", partOfSpeech: "noun", difficulty: "easy", example: "Our group used rat in the project.", exampleTranslation: "استخدمت مجموعتنا جرذ في المشروع." },
  { word: "gerbil", translation: "جربوع", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with gerbil.", exampleTranslation: "أعطى المعلم مثالاً بـجربوع." },
  { word: "toad", translation: "علجوم", partOfSpeech: "noun", difficulty: "medium", example: "I underlined toad in the paragraph.", exampleTranslation: "وضعت خطاً تحت علجوم في الفقرة." },
  { word: "alligator", translation: "تمساح أمريكي", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying alligator aloud.", exampleTranslation: "تدرّبنا على نطق تمساح أمريكي بصوت عالٍ." },
  { word: "koala", translation: "كوالا", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains koala with a drawing.", exampleTranslation: "يشرح الملصق كوالا برسم." },
  { word: "gorilla", translation: "غوريلا", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with gorilla.", exampleTranslation: "شارك الجميع جملة فيها غوريلا." },
  { word: "chimp", translation: "شمبانزي", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word chimp.", exampleTranslation: "تضمّن الاختبار كلمة شمبانزي." },
  { word: "leopard", translation: "فهد", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word leopard in class today.", exampleTranslation: "تعلّمنا كلمة فهد في الحصة اليوم." },
  { word: "cheetah", translation: "فهد صياد", partOfSpeech: "noun", difficulty: "medium", example: "Can you use cheetah in a sentence?", exampleTranslation: "هل يمكنك استخدام فهد صياد في جملة؟" },
  { word: "jaguar", translation: "جاغوار", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned jaguar on page ten.", exampleTranslation: "ذكرت القصة جاغوار في الصفحة العاشرة." },
  { word: "buffalo", translation: "جاموس", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote buffalo on the board.", exampleTranslation: "كتب معلمنا جاموس على السبورة." },
  { word: "bison", translation: "بيسون", partOfSpeech: "noun", difficulty: "medium", example: "I spelled bison correctly on the quiz.", exampleTranslation: "تهجّيت بيسون بشكل صحيح في الاختبار." },
  { word: "antelope", translation: "ظبي", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain antelope.", exampleTranslation: "تساعد الصورة على شرح ظبي." },
  { word: "lamb", translation: "حمل", partOfSpeech: "noun", difficulty: "easy", example: "We found lamb in our reading book.", exampleTranslation: "وجدنا حمل في كتاب القراءة." },
  { word: "bull", translation: "ثور", partOfSpeech: "noun", difficulty: "easy", example: "Bull is a new word for our unit.", exampleTranslation: "ثور كلمة جديدة لوحدتنا." },
  { word: "calf", translation: "عجل", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed calf.", exampleTranslation: "ناقشت عجل مع زميلي." },
  { word: "wasp", translation: "دبور", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about wasp.", exampleTranslation: "يسأل ورق العمل عن دبور." },
  { word: "moth", translation: "عثة", partOfSpeech: "noun", difficulty: "easy", example: "We heard moth in the science video.", exampleTranslation: "سمعنا عثة في فيلم العلوم." },
  { word: "starfish", translation: "نجم البحر", partOfSpeech: "noun", difficulty: "easy", example: "Please copy starfish into your notebook.", exampleTranslation: "من فضلك انسخ نجم البحر في دفترك." },
  { word: "goldfish", translation: "سمكة ذهبية", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of goldfish.", exampleTranslation: "يُظهر المخطط مثالاً عن سمكة ذهبية." },
  { word: "catfish", translation: "سمك السلور", partOfSpeech: "noun", difficulty: "medium", example: "Our group used catfish in the project.", exampleTranslation: "استخدمت مجموعتنا سمك السلور في المشروع." },
  { word: "pelican", translation: "بجع", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with pelican.", exampleTranslation: "أعطى المعلم مثالاً بـبجع." },
  { word: "flamingo", translation: "فلامنغو", partOfSpeech: "noun", difficulty: "medium", example: "I underlined flamingo in the paragraph.", exampleTranslation: "وضعت خطاً تحت فلامنغو في الفقرة." },
  { word: "peacock", translation: "طاووس", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying peacock aloud.", exampleTranslation: "تدرّبنا على نطق طاووس بصوت عالٍ." },
  { word: "ostrich", translation: "نعامة", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains ostrich with a drawing.", exampleTranslation: "يشرح الملصق نعامة برسم." },
  { word: "emu", translation: "إيمو", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with emu.", exampleTranslation: "شارك الجميع جملة فيها إيمو." },
  { word: "alpaca", translation: "ألباكا", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word alpaca.", exampleTranslation: "تضمّن الاختبار كلمة ألباكا." },
  { word: "llama", translation: "لاما", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word llama in class today.", exampleTranslation: "تعلّمنا كلمة لاما في الحصة اليوم." },
  { word: "reindeer", translation: "رنة", partOfSpeech: "noun", difficulty: "medium", example: "Can you use reindeer in a sentence?", exampleTranslation: "هل يمكنك استخدام رنة في جملة؟" },
  { word: "hedgehog", translation: "قنفذ", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned hedgehog on page ten.", exampleTranslation: "ذكرت القصة قنفذ في الصفحة العاشرة." },
  { word: "porcupine", translation: "نيص", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote porcupine on the board.", exampleTranslation: "كتب معلمنا نيص على السبورة." },
  { word: "raccoon", translation: "راكون", partOfSpeech: "noun", difficulty: "medium", example: "I spelled raccoon correctly on the quiz.", exampleTranslation: "تهجّيت راكون بشكل صحيح في الاختبار." },
  { word: "skunk", translation: "ظربان", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain skunk.", exampleTranslation: "تساعد الصورة على شرح ظربان." },
  { word: "badger", translation: "غرير", partOfSpeech: "noun", difficulty: "medium", example: "We found badger in our reading book.", exampleTranslation: "وجدنا غرير في كتاب القراءة." },
  { word: "weasel", translation: "ابن عرس", partOfSpeech: "noun", difficulty: "medium", example: "Weasel is a new word for our unit.", exampleTranslation: "ابن عرس كلمة جديدة لوحدتنا." },
  { word: "ferret", translation: "نمس", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed ferret.", exampleTranslation: "ناقشت نمس مع زميلي." },
  { word: "mole", translation: "خلد", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about mole.", exampleTranslation: "يسأل ورق العمل عن خلد." },
  { word: "chipmunk", translation: "سنجاب مخطط", partOfSpeech: "noun", difficulty: "medium", example: "We heard chipmunk in the science video.", exampleTranslation: "سمعنا سنجاب مخطط في فيلم العلوم." },
  { word: "coyote", translation: "ذئب أمريكي", partOfSpeech: "noun", difficulty: "medium", example: "Please copy coyote into your notebook.", exampleTranslation: "من فضلك انسخ ذئب أمريكي في دفترك." },
  { word: "hyena", translation: "ضبع", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of hyena.", exampleTranslation: "يُظهر المخطط مثالاً عن ضبع." },
  { word: "walrus", translation: "فظ", partOfSpeech: "noun", difficulty: "medium", example: "Our group used walrus in the project.", exampleTranslation: "استخدمت مجموعتنا فظ في المشروع." },
  { word: "orca", translation: "حوت قاتل", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with orca.", exampleTranslation: "أعطى المعلم مثالاً بـحوت قاتل." },
  { word: "iguana", translation: "إغوانا", partOfSpeech: "noun", difficulty: "medium", example: "I underlined iguana in the paragraph.", exampleTranslation: "وضعت خطاً تحت إغوانا في الفقرة." },
  { word: "gecko", translation: "وزغة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying gecko aloud.", exampleTranslation: "تدرّبنا على نطق وزغة بصوت عالٍ." },
  { word: "chameleon", translation: "حرباء", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains chameleon with a drawing.", exampleTranslation: "يشرح الملصق حرباء برسم." },
  { word: "newt", translation: "سمندل", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with newt.", exampleTranslation: "شارك الجميع جملة فيها سمندل." },
  { word: "salamander", translation: "سلمندر", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word salamander.", exampleTranslation: "تضمّن الاختبار كلمة سلمندر." },
  { word: "cockroach", translation: "صرصور", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word cockroach in class today.", exampleTranslation: "تعلّمنا كلمة صرصور في الحصة اليوم." },
  { word: "termite", translation: "نمل أبيض", partOfSpeech: "noun", difficulty: "medium", example: "Can you use termite in a sentence?", exampleTranslation: "هل يمكنك استخدام نمل أبيض في جملة؟" },
  { word: "scorpion", translation: "عقرب", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned scorpion on page ten.", exampleTranslation: "ذكرت القصة عقرب في الصفحة العاشرة." },
  { word: "centipede", translation: "أم أربع", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote centipede on the board.", exampleTranslation: "كتب معلمنا أم أربع على السبورة." },
  { word: "millipede", translation: "دودة ألفية", partOfSpeech: "noun", difficulty: "medium", example: "I spelled millipede correctly on the quiz.", exampleTranslation: "تهجّيت دودة ألفية بشكل صحيح في الاختبار." },
  { word: "flea", translation: "برغوث", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain flea.", exampleTranslation: "تساعد الصورة على شرح برغوث." },
  { word: "tick", translation: "قرادة", partOfSpeech: "noun", difficulty: "medium", example: "We found tick in our reading book.", exampleTranslation: "وجدنا قرادة في كتاب القراءة." },
  { word: "mite", translation: "عث", partOfSpeech: "noun", difficulty: "medium", example: "Mite is a new word for our unit.", exampleTranslation: "عث كلمة جديدة لوحدتنا." },
  { word: "slug", translation: "بزاق", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed slug.", exampleTranslation: "ناقشت بزاق مع زميلي." },
  { word: "clam", translation: "محار", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about clam.", exampleTranslation: "يسأل ورق العمل عن محار." },
  { word: "oyster", translation: "محارة", partOfSpeech: "noun", difficulty: "medium", example: "We heard oyster in the science video.", exampleTranslation: "سمعنا محارة في فيلم العلوم." },
  { word: "mussel", translation: "بلح البحر", partOfSpeech: "noun", difficulty: "medium", example: "Please copy mussel into your notebook.", exampleTranslation: "من فضلك انسخ بلح البحر في دفترك." },
  { word: "squid", translation: "حبار", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of squid.", exampleTranslation: "يُظهر المخطط مثالاً عن حبار." },
  { word: "ray", translation: "شفنين", partOfSpeech: "noun", difficulty: "medium", example: "Our group used ray in the project.", exampleTranslation: "استخدمت مجموعتنا شفنين في المشروع." },
  { word: "eel", translation: "ثعبان البحر", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with eel.", exampleTranslation: "أعطى المعلم مثالاً بـثعبان البحر." },
  { word: "angelfish", translation: "سمكة ملاك", partOfSpeech: "noun", difficulty: "medium", example: "I underlined angelfish in the paragraph.", exampleTranslation: "وضعت خطاً تحت سمكة ملاك في الفقرة." },
  { word: "clownfish", translation: "سمكة المهرج", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying clownfish aloud.", exampleTranslation: "تدرّبنا على نطق سمكة المهرج بصوت عالٍ." },
  { word: "pufferfish", translation: "سمكة منتفخة", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains pufferfish with a drawing.", exampleTranslation: "يشرح الملصق سمكة منتفخة برسم." },
  { word: "heron", translation: "بلشون", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with heron.", exampleTranslation: "شارك الجميع جملة فيها بلشون." },
  { word: "stork", translation: "لقلق", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word stork.", exampleTranslation: "تضمّن الاختبار كلمة لقلق." },
  { word: "vulture", translation: "نسر جارح", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word vulture in class today.", exampleTranslation: "تعلّمنا كلمة نسر جارح في الحصة اليوم." },
  { word: "condor", translation: "كندور", partOfSpeech: "noun", difficulty: "medium", example: "Can you use condor in a sentence?", exampleTranslation: "هل يمكنك استخدام كندور في جملة؟" },
  { word: "canary", translation: "كناري", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned canary on page ten.", exampleTranslation: "ذكرت القصة كناري في الصفحة العاشرة." },
  { word: "finch", translation: "شرشور", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote finch on the board.", exampleTranslation: "كتب معلمنا شرشور على السبورة." },
  { word: "woodpecker", translation: "نقار الخشب", partOfSpeech: "noun", difficulty: "medium", example: "I spelled woodpecker correctly on the quiz.", exampleTranslation: "تهجّيت نقار الخشب بشكل صحيح في الاختبار." },
  { word: "kingfisher", translation: "صياد السمك", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain kingfisher.", exampleTranslation: "تساعد الصورة على شرح صياد السمك." },
  { word: "hummingbird", translation: "طائر الطنان", partOfSpeech: "noun", difficulty: "medium", example: "We found hummingbird in our reading book.", exampleTranslation: "وجدنا طائر الطنان في كتاب القراءة." },
  { word: "magpie", translation: "عقعق", partOfSpeech: "noun", difficulty: "medium", example: "Magpie is a new word for our unit.", exampleTranslation: "عقعق كلمة جديدة لوحدتنا." },
  { word: "jay", translation: "قيق أزرق", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed jay.", exampleTranslation: "ناقشت قيق أزرق مع زميلي." },
  { word: "cardinal", translation: "طائر أحمر", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about cardinal.", exampleTranslation: "يسأل ورق العمل عن طائر أحمر." },
  { word: "dove", translation: "يمامة", partOfSpeech: "noun", difficulty: "easy", example: "We heard dove in the science video.", exampleTranslation: "سمعنا يمامة في فيلم العلوم." },
  { word: "quail", translation: "سمان", partOfSpeech: "noun", difficulty: "medium", example: "Please copy quail into your notebook.", exampleTranslation: "من فضلك انسخ سمان في دفترك." },
  { word: "pheasant", translation: "تدرج", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of pheasant.", exampleTranslation: "يُظهر المخطط مثالاً عن تدرج." },
  { word: "partridge", translation: "حجل", partOfSpeech: "noun", difficulty: "medium", example: "Our group used partridge in the project.", exampleTranslation: "استخدمت مجموعتنا حجل في المشروع." },
  { word: "mallard", translation: "بطة برية", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with mallard.", exampleTranslation: "أعطى المعلم مثالاً بـبطة برية." },
  { word: "swallow", translation: "سنونو", partOfSpeech: "noun", difficulty: "medium", example: "I underlined swallow in the paragraph.", exampleTranslation: "وضعت خطاً تحت سنونو في الفقرة." },
  { word: "nightingale", translation: "بلبل", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying nightingale aloud.", exampleTranslation: "تدرّبنا على نطق بلبل بصوت عالٍ." },
  { word: "cuckoo", translation: "وقواق", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains cuckoo with a drawing.", exampleTranslation: "يشرح الملصق وقواق برسم." },
  { word: "jungle", translation: "أدغال", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with jungle.", exampleTranslation: "شارك الجميع جملة فيها أدغال." },
  { word: "field", translation: "حقل", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word field.", exampleTranslation: "تضمّن الاختبار كلمة حقل." },
  { word: "peak", translation: "قمة", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word peak in class today.", exampleTranslation: "تعلّمنا كلمة قمة في الحصة اليوم." },
  { word: "cliff", translation: "جرف", partOfSpeech: "noun", difficulty: "medium", example: "Can you use cliff in a sentence?", exampleTranslation: "هل يمكنك استخدام جرف في جملة؟" },
  { word: "stream", translation: "جدول", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned stream on page ten.", exampleTranslation: "ذكرت القصة جدول في الصفحة العاشرة." },
  { word: "brook", translation: "جدول مائي", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote brook on the board.", exampleTranslation: "كتب معلمنا جدول مائي على السبورة." },
  { word: "pond", translation: "بركة", partOfSpeech: "noun", difficulty: "easy", example: "I spelled pond correctly on the quiz.", exampleTranslation: "تهجّيت بركة بشكل صحيح في الاختبار." },
  { word: "sea", translation: "بحر", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain sea.", exampleTranslation: "تساعد الصورة على شرح بحر." },
  { word: "shore", translation: "شاطئ", partOfSpeech: "noun", difficulty: "easy", example: "We found shore in our reading book.", exampleTranslation: "وجدنا شاطئ في كتاب القراءة." },
  { word: "bay", translation: "خليج", partOfSpeech: "noun", difficulty: "easy", example: "Bay is a new word for our unit.", exampleTranslation: "خليج كلمة جديدة لوحدتنا." },
  { word: "dune", translation: "كثيب رملي", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed dune.", exampleTranslation: "ناقشت كثيب رملي مع زميلي." },
  { word: "oasis", translation: "واحة", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about oasis.", exampleTranslation: "يسأل ورق العمل عن واحة." },
  { word: "iceberg", translation: "جبل جليدي", partOfSpeech: "noun", difficulty: "medium", example: "We heard iceberg in the science video.", exampleTranslation: "سمعنا جبل جليدي في فيلم العلوم." },
  { word: "universe", translation: "كون", partOfSpeech: "noun", difficulty: "medium", example: "Please copy universe into your notebook.", exampleTranslation: "من فضلك انسخ كون في دفترك." },
  { word: "stone", translation: "حجر", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of stone.", exampleTranslation: "يُظهر المخطط مثالاً عن حجر." },
  { word: "coal", translation: "فحم", partOfSpeech: "noun", difficulty: "easy", example: "Our group used coal in the project.", exampleTranslation: "استخدمت مجموعتنا فحم في المشروع." },
  { word: "bush", translation: "شجيرة", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with bush.", exampleTranslation: "أعطى المعلم مثالاً بـشجيرة." },
  { word: "shrub", translation: "شجيرة", partOfSpeech: "noun", difficulty: "medium", example: "I underlined shrub in the paragraph.", exampleTranslation: "وضعت خطاً تحت شجيرة في الفقرة." },
  { word: "root", translation: "جذر", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying root aloud.", exampleTranslation: "تدرّبنا على نطق جذر بصوت عالٍ." },
  { word: "fruit", translation: "فاكهة", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains fruit with a drawing.", exampleTranslation: "يشرح الملصق فاكهة برسم." },
  { word: "berry", translation: "توت", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with berry.", exampleTranslation: "شارك الجميع جملة فيها توت." },
  { word: "nut", translation: "جوزة", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word nut.", exampleTranslation: "تضمّن الاختبار كلمة جوزة." },
  { word: "acorn", translation: "بلوطة", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word acorn in class today.", exampleTranslation: "تعلّمنا كلمة بلوطة في الحصة اليوم." },
  { word: "pine", translation: "صنوبر", partOfSpeech: "noun", difficulty: "medium", example: "Can you use pine in a sentence?", exampleTranslation: "هل يمكنك استخدام صنوبر في جملة؟" },
  { word: "oak", translation: "بلوط", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned oak on page ten.", exampleTranslation: "ذكرت القصة بلوط في الصفحة العاشرة." },
  { word: "maple", translation: "قيقب", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote maple on the board.", exampleTranslation: "كتب معلمنا قيقب على السبورة." },
  { word: "palm", translation: "نخيل", partOfSpeech: "noun", difficulty: "easy", example: "I spelled palm correctly on the quiz.", exampleTranslation: "تهجّيت نخيل بشكل صحيح في الاختبار." },
  { word: "cedar", translation: "أرز", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain cedar.", exampleTranslation: "تساعد الصورة على شرح أرز." },
  { word: "willow", translation: "صفصاف", partOfSpeech: "noun", difficulty: "medium", example: "We found willow in our reading book.", exampleTranslation: "وجدنا صفصاف في كتاب القراءة." },
  { word: "birch", translation: "بتولا", partOfSpeech: "noun", difficulty: "medium", example: "Birch is a new word for our unit.", exampleTranslation: "بتولا كلمة جديدة لوحدتنا." },
  { word: "bamboo", translation: "خيزران", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed bamboo.", exampleTranslation: "ناقشت خيزران مع زميلي." },
  { word: "gust", translation: "هبة ريح", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about gust.", exampleTranslation: "يسأل ورق العمل عن هبة ريح." },
  { word: "wildfire", translation: "حرائق برية", partOfSpeech: "noun", difficulty: "medium", example: "We heard wildfire in the science video.", exampleTranslation: "سمعنا حرائق برية في فيلم العلوم." },
  { word: "marsh", translation: "مستنقع", partOfSpeech: "noun", difficulty: "medium", example: "Please copy marsh into your notebook.", exampleTranslation: "من فضلك انسخ مستنقع في دفترك." },
  { word: "swamp", translation: "مستنقع", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of swamp.", exampleTranslation: "يُظهر المخطط مثالاً عن مستنقع." },
  { word: "prairie", translation: "مرج واسع", partOfSpeech: "noun", difficulty: "medium", example: "Our group used prairie in the project.", exampleTranslation: "استخدمت مجموعتنا مرج واسع في المشروع." },
  { word: "undergrowth", translation: "نباتات سفلية", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with undergrowth.", exampleTranslation: "أعطى المعلم مثالاً بـنباتات سفلية." },
  { word: "gymnasium", translation: "صالة رياضية", partOfSpeech: "noun", difficulty: "medium", example: "I underlined gymnasium in the paragraph.", exampleTranslation: "وضعت خطاً تحت صالة رياضية في الفقرة." },
  { word: "board", translation: "سبورة", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying board aloud.", exampleTranslation: "تدرّبنا على نطق سبورة بصوت عالٍ." },
  { word: "workbook", translation: "كراسة تمارين", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains workbook with a drawing.", exampleTranslation: "يشرح الملصق كراسة تمارين برسم." },
  { word: "subject", translation: "مادة", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with subject.", exampleTranslation: "شارك الجميع جملة فيها مادة." },
  { word: "geography", translation: "جغرافيا", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word geography.", exampleTranslation: "تضمّن الاختبار كلمة جغرافيا." },
  { word: "theorem", translation: "نظرية", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word theorem in class today.", exampleTranslation: "تعلّمنا كلمة نظرية في الحصة اليوم." },
  { word: "area", translation: "مساحة", partOfSpeech: "noun", difficulty: "easy", example: "Can you use area in a sentence?", exampleTranslation: "هل يمكنك استخدام مساحة في جملة؟" },
  { word: "graph", translation: "رسم بياني", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned graph on page ten.", exampleTranslation: "ذكرت القصة رسم بياني في الصفحة العاشرة." },
  { word: "chart", translation: "مخطط", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote chart on the board.", exampleTranslation: "كتب معلمنا مخطط على السبورة." },
  { word: "data", translation: "بيانات", partOfSpeech: "noun", difficulty: "easy", example: "I spelled data correctly on the quiz.", exampleTranslation: "تهجّيت بيانات بشكل صحيح في الاختبار." },
  { word: "average", translation: "متوسط", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain average.", exampleTranslation: "تساعد الصورة على شرح متوسط." },
  { word: "polynomial", translation: "كثير حدود", partOfSpeech: "noun", difficulty: "medium", example: "We found polynomial in our reading book.", exampleTranslation: "وجدنا كثير حدود في كتاب القراءة." },
  { word: "origin", translation: "أصل", partOfSpeech: "noun", difficulty: "medium", example: "Origin is a new word for our unit.", exampleTranslation: "أصل كلمة جديدة لوحدتنا." },
  { word: "slope", translation: "ميل", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed slope.", exampleTranslation: "ناقشت ميل مع زميلي." },
  { word: "survey", translation: "استطلاع", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about survey.", exampleTranslation: "يسأل ورق العمل عن استطلاع." },
  { word: "conclusion", translation: "استنتاج", partOfSpeech: "noun", difficulty: "medium", example: "We heard conclusion in the science video.", exampleTranslation: "سمعنا استنتاج في فيلم العلوم." },
  { word: "essay", translation: "مقال", partOfSpeech: "noun", difficulty: "medium", example: "Please copy essay into your notebook.", exampleTranslation: "من فضلك انسخ مقال في دفترك." },
  { word: "sentence", translation: "جملة", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of sentence.", exampleTranslation: "يُظهر المخطط مثالاً عن جملة." },
  { word: "phrase", translation: "عبارة", partOfSpeech: "noun", difficulty: "easy", example: "Our group used phrase in the project.", exampleTranslation: "استخدمت مجموعتنا عبارة في المشروع." },
  { word: "vocabulary", translation: "مفردات", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with vocabulary.", exampleTranslation: "أعطى المعلم مثالاً بـمفردات." },
  { word: "thesaurus", translation: "مرادفات", partOfSpeech: "noun", difficulty: "medium", example: "I underlined thesaurus in the paragraph.", exampleTranslation: "وضعت خطاً تحت مرادفات في الفقرة." },
  { word: "encyclopedia", translation: "موسوعة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying encyclopedia aloud.", exampleTranslation: "تدرّبنا على نطق موسوعة بصوت عالٍ." },
  { word: "globe", translation: "كرة أرضية", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains globe with a drawing.", exampleTranslation: "يشرح الملصق كرة أرضية برسم." },
  { word: "map", translation: "خريطة", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with map.", exampleTranslation: "شارك الجميع جملة فيها خريطة." },
  { word: "calculator", translation: "آلة حاسبة", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word calculator.", exampleTranslation: "تضمّن الاختبار كلمة آلة حاسبة." },
  { word: "monitor", translation: "شاشة", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word monitor in class today.", exampleTranslation: "تعلّمنا كلمة شاشة في الحصة اليوم." },
  { word: "scanner", translation: "ماسح", partOfSpeech: "noun", difficulty: "medium", example: "Can you use scanner in a sentence?", exampleTranslation: "هل يمكنك استخدام ماسح في جملة؟" },
  { word: "projector", translation: "جهاز عرض", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned projector on page ten.", exampleTranslation: "ذكرت القصة جهاز عرض في الصفحة العاشرة." },
  { word: "semester", translation: "فصل دراسي", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote semester on the board.", exampleTranslation: "كتب معلمنا فصل دراسي على السبورة." },
  { word: "quarter", translation: "ربع سنة", partOfSpeech: "noun", difficulty: "medium", example: "I spelled quarter correctly on the quiz.", exampleTranslation: "تهجّيت ربع سنة بشكل صحيح في الاختبار." },
  { word: "grade", translation: "صف", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain grade.", exampleTranslation: "تساعد الصورة على شرح صف." },
  { word: "level", translation: "مستوى", partOfSpeech: "noun", difficulty: "easy", example: "We found level in our reading book.", exampleTranslation: "وجدنا مستوى في كتاب القراءة." },
  { word: "exam", translation: "امتحان", partOfSpeech: "noun", difficulty: "easy", example: "Exam is a new word for our unit.", exampleTranslation: "امتحان كلمة جديدة لوحدتنا." },
  { word: "fail", translation: "رسوب", partOfSpeech: "verb", difficulty: "easy", example: "My partner and I discussed fail.", exampleTranslation: "ناقشت رسوب مع زميلي." },
  { word: "learn", translation: "تعلم", partOfSpeech: "verb", difficulty: "easy", example: "The worksheet asks about learn.", exampleTranslation: "يسأل ورق العمل عن تعلم." },
  { word: "teach", translation: "تعليم", partOfSpeech: "verb", difficulty: "easy", example: "We heard teach in the science video.", exampleTranslation: "سمعنا تعليم في فيلم العلوم." },
  { word: "speech", translation: "خطاب", partOfSpeech: "noun", difficulty: "easy", example: "Please copy speech into your notebook.", exampleTranslation: "من فضلك انسخ خطاب في دفترك." },
  { word: "attendance", translation: "حضور", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of attendance.", exampleTranslation: "يُظهر المخطط مثالاً عن حضور." },
  { word: "absence", translation: "غياب", partOfSpeech: "noun", difficulty: "medium", example: "Our group used absence in the project.", exampleTranslation: "استخدمت مجموعتنا غياب في المشروع." },
  { word: "behavior", translation: "سلوك", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with behavior.", exampleTranslation: "أعطى المعلم مثالاً بـسلوك." },
  { word: "discipline", translation: "انضباط", partOfSpeech: "noun", difficulty: "medium", example: "I underlined discipline in the paragraph.", exampleTranslation: "وضعت خطاً تحت انضباط في الفقرة." },
  { word: "classmate", translation: "زميل", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying classmate aloud.", exampleTranslation: "تدرّبنا على نطق زميل بصوت عالٍ." },
  { word: "counselor", translation: "مرشد", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains counselor with a drawing.", exampleTranslation: "يشرح الملصق مرشد برسم." },
  { word: "janitor", translation: "عامل نظافة", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with janitor.", exampleTranslation: "شارك الجميع جملة فيها عامل نظافة." },
  { word: "guard", translation: "حارس", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word guard.", exampleTranslation: "تضمّن الاختبار كلمة حارس." },
  { word: "scientist", translation: "عالم", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word scientist in class today.", exampleTranslation: "تعلّمنا كلمة عالم في الحصة اليوم." },
  { word: "musician", translation: "موسيقي", partOfSpeech: "noun", difficulty: "easy", example: "Can you use musician in a sentence?", exampleTranslation: "هل يمكنك استخدام موسيقي في جملة؟" },
  { word: "poet", translation: "شاعر", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned poet on page ten.", exampleTranslation: "ذكرت القصة شاعر في الصفحة العاشرة." },
  { word: "inventor", translation: "مخترع", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote inventor on the board.", exampleTranslation: "كتب معلمنا مخترع على السبورة." },
  { word: "explorer", translation: "مستكشف", partOfSpeech: "noun", difficulty: "medium", example: "I spelled explorer correctly on the quiz.", exampleTranslation: "تهجّيت مستكشف بشكل صحيح في الاختبار." },
  { word: "captain", translation: "قائد", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain captain.", exampleTranslation: "تساعد الصورة على شرح قائد." },
  { word: "police", translation: "شرطة", partOfSpeech: "noun", difficulty: "easy", example: "We found police in our reading book.", exampleTranslation: "وجدنا شرطة في كتاب القراءة." },
  { word: "mailman", translation: "ساعي بريد", partOfSpeech: "noun", difficulty: "medium", example: "Mailman is a new word for our unit.", exampleTranslation: "ساعي بريد كلمة جديدة لوحدتنا." },
  { word: "cashier", translation: "أمين صندوق", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed cashier.", exampleTranslation: "ناقشت أمين صندوق مع زميلي." },
  { word: "clerk", translation: "موظف", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about clerk.", exampleTranslation: "يسأل ورق العمل عن موظف." },
  { word: "owner", translation: "مالك", partOfSpeech: "noun", difficulty: "easy", example: "We heard owner in the science video.", exampleTranslation: "سمعنا مالك في فيلم العلوم." },
  { word: "family", translation: "عائلة", partOfSpeech: "noun", difficulty: "easy", example: "Please copy family into your notebook.", exampleTranslation: "من فضلك انسخ عائلة في دفترك." },
  { word: "teen", translation: "مراهق", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of teen.", exampleTranslation: "يُظهر المخطط مثالاً عن مراهق." },
  { word: "adult", translation: "بالغ", partOfSpeech: "noun", difficulty: "easy", example: "Our group used adult in the project.", exampleTranslation: "استخدمت مجموعتنا بالغ في المشروع." },
  { word: "elder", translation: "كبير السن", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with elder.", exampleTranslation: "أعطى المعلم مثالاً بـكبير السن." },
  { word: "resident", translation: "مقيم", partOfSpeech: "noun", difficulty: "medium", example: "I underlined resident in the paragraph.", exampleTranslation: "وضعت خطاً تحت مقيم في الفقرة." },
  { word: "visitor", translation: "زائر", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying visitor aloud.", exampleTranslation: "تدرّبنا على نطق زائر بصوت عالٍ." },
  { word: "member", translation: "عضو", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains member with a drawing.", exampleTranslation: "يشرح الملصق عضو برسم." },
  { word: "judge", translation: "قاضٍ", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with judge.", exampleTranslation: "شارك الجميع جملة فيها قاضٍ." },
  { word: "lawyer", translation: "محامٍ", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word lawyer.", exampleTranslation: "تضمّن الاختبار كلمة محامٍ." },
  { word: "victim", translation: "ضحية", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word victim in class today.", exampleTranslation: "تعلّمنا كلمة ضحية في الحصة اليوم." },
  { word: "hero", translation: "بطل", partOfSpeech: "noun", difficulty: "easy", example: "Can you use hero in a sentence?", exampleTranslation: "هل يمكنك استخدام بطل في جملة؟" },
  { word: "winner", translation: "فائز", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned winner on page ten.", exampleTranslation: "ذكرت القصة فائز في الصفحة العاشرة." },
  { word: "loser", translation: "خاسر", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote loser on the board.", exampleTranslation: "كتب معلمنا خاسر على السبورة." },
  { word: "player", translation: "لاعب", partOfSpeech: "noun", difficulty: "easy", example: "I spelled player correctly on the quiz.", exampleTranslation: "تهجّيت لاعب بشكل صحيح في الاختبار." },
  { word: "runner", translation: "عداء", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain runner.", exampleTranslation: "تساعد الصورة على شرح عداء." },
  { word: "swimmer", translation: "سباح", partOfSpeech: "noun", difficulty: "easy", example: "We found swimmer in our reading book.", exampleTranslation: "وجدنا سباح في كتاب القراءة." },
  { word: "diver", translation: "غواص", partOfSpeech: "noun", difficulty: "medium", example: "Diver is a new word for our unit.", exampleTranslation: "غواص كلمة جديدة لوحدتنا." },
  { word: "skater", translation: "متزلج", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed skater.", exampleTranslation: "ناقشت متزلج مع زميلي." },
  { word: "skier", translation: "متزلج على الثلج", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about skier.", exampleTranslation: "يسأل ورق العمل عن متزلج على الثلج." },
  { word: "cyclist", translation: "دراج", partOfSpeech: "noun", difficulty: "medium", example: "We heard cyclist in the science video.", exampleTranslation: "سمعنا دراج في فيلم العلوم." },
  { word: "golfer", translation: "لاعب غولف", partOfSpeech: "noun", difficulty: "medium", example: "Please copy golfer into your notebook.", exampleTranslation: "من فضلك انسخ لاعب غولف في دفترك." },
  { word: "boxer", translation: "ملاكم", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of boxer.", exampleTranslation: "يُظهر المخطط مثالاً عن ملاكم." },
  { word: "wrestler", translation: "مصارع", partOfSpeech: "noun", difficulty: "medium", example: "Our group used wrestler in the project.", exampleTranslation: "استخدمت مجموعتنا مصارع في المشروع." },
  { word: "goalkeeper", translation: "حارس مرمى", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with goalkeeper.", exampleTranslation: "أعطى المعلم مثالاً بـحارس مرمى." },
  { word: "spectator", translation: "متفرج", partOfSpeech: "noun", difficulty: "medium", example: "I underlined spectator in the paragraph.", exampleTranslation: "وضعت خطاً تحت متفرج في الفقرة." },
  { word: "fan", translation: "مشجع", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying fan aloud.", exampleTranslation: "تدرّبنا على نطق مشجع بصوت عالٍ." },
  { word: "squad", translation: "فريق", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains squad with a drawing.", exampleTranslation: "يشرح الملصق فريق برسم." },
  { word: "league", translation: "دوري", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with league.", exampleTranslation: "شارك الجميع جملة فيها دوري." },
  { word: "championship", translation: "بطولة", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word championship.", exampleTranslation: "تضمّن الاختبار كلمة بطولة." },
  { word: "trophy", translation: "كأس", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word trophy in class today.", exampleTranslation: "تعلّمنا كلمة كأس في الحصة اليوم." },
  { word: "record", translation: "رقم قياسي", partOfSpeech: "noun", difficulty: "easy", example: "Can you use record in a sentence?", exampleTranslation: "هل يمكنك استخدام رقم قياسي في جملة؟" },
  { word: "court", translation: "ملعب", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned court on page ten.", exampleTranslation: "ذكرت القصة ملعب في الصفحة العاشرة." },
  { word: "track", translation: "مسار", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote track on the board.", exampleTranslation: "كتب معلمنا مسار على السبورة." },
  { word: "lane", translation: "مسار", partOfSpeech: "noun", difficulty: "medium", example: "I spelled lane correctly on the quiz.", exampleTranslation: "تهجّيت مسار بشكل صحيح في الاختبار." },
  { word: "goal", translation: "هدف", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain goal.", exampleTranslation: "تساعد الصورة على شرح هدف." },
  { word: "point", translation: "نقطة", partOfSpeech: "noun", difficulty: "easy", example: "We found point in our reading book.", exampleTranslation: "وجدنا نقطة في كتاب القراءة." },
  { word: "kick", translation: "ركلة", partOfSpeech: "verb", difficulty: "easy", example: "Kick is a new word for our unit.", exampleTranslation: "ركلة كلمة جديدة لوحدتنا." },
  { word: "shoot", translation: "تسديد", partOfSpeech: "verb", difficulty: "easy", example: "My partner and I discussed shoot.", exampleTranslation: "ناقشت تسديد مع زميلي." },
  { word: "dribble", translation: "مراوغة", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about dribble.", exampleTranslation: "يسأل ورق العمل عن مراوغة." },
  { word: "tackle", translation: "عرقلة", partOfSpeech: "verb", difficulty: "medium", example: "We heard tackle in the science video.", exampleTranslation: "سمعنا عرقلة في فيلم العلوم." },
  { word: "block", translation: "صد", partOfSpeech: "verb", difficulty: "easy", example: "Please copy block into your notebook.", exampleTranslation: "من فضلك انسخ صد في دفترك." },
  { word: "defend", translation: "دفاع", partOfSpeech: "verb", difficulty: "easy", example: "The chart shows an example of defend.", exampleTranslation: "يُظهر المخطط مثالاً عن دفاع." },
  { word: "attack", translation: "هجوم", partOfSpeech: "verb", difficulty: "easy", example: "Our group used attack in the project.", exampleTranslation: "استخدمت مجموعتنا هجوم في المشروع." },
  { word: "compete", translation: "منافسة", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with compete.", exampleTranslation: "أعطى المعلم مثالاً بـمنافسة." },
  { word: "warmup", translation: "إحماء", partOfSpeech: "noun", difficulty: "medium", example: "I underlined warmup in the paragraph.", exampleTranslation: "وضعت خطاً تحت إحماء في الفقرة." },
  { word: "cooldown", translation: "تهدئة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying cooldown aloud.", exampleTranslation: "تدرّبنا على نطق تهدئة بصوت عالٍ." },
  { word: "fitness", translation: "لياقة", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains fitness with a drawing.", exampleTranslation: "يشرح الملصق لياقة برسم." },
  { word: "strength", translation: "قوة", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with strength.", exampleTranslation: "شارك الجميع جملة فيها قوة." },
  { word: "speed", translation: "سرعة", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word speed.", exampleTranslation: "تضمّن الاختبار كلمة سرعة." },
  { word: "agility", translation: "رشاقة", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word agility in class today.", exampleTranslation: "تعلّمنا كلمة رشاقة في الحصة اليوم." },
  { word: "flexibility", translation: "مرونة", partOfSpeech: "noun", difficulty: "medium", example: "Can you use flexibility in a sentence?", exampleTranslation: "هل يمكنك استخدام مرونة في جملة؟" },
  { word: "football", translation: "كرة قدم", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned football on page ten.", exampleTranslation: "ذكرت القصة كرة قدم في الصفحة العاشرة." },
  { word: "basketball", translation: "كرة سلة", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote basketball on the board.", exampleTranslation: "كتب معلمنا كرة سلة على السبورة." },
  { word: "rugby", translation: "رغبي", partOfSpeech: "noun", difficulty: "medium", example: "I spelled rugby correctly on the quiz.", exampleTranslation: "تهجّيت رغبي بشكل صحيح في الاختبار." },
  { word: "golf", translation: "غولف", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain golf.", exampleTranslation: "تساعد الصورة على شرح غولف." },
  { word: "bowling", translation: "بولينغ", partOfSpeech: "noun", difficulty: "easy", example: "We found bowling in our reading book.", exampleTranslation: "وجدنا بولينغ في كتاب القراءة." },
  { word: "karate", translation: "كاراتيه", partOfSpeech: "noun", difficulty: "medium", example: "Karate is a new word for our unit.", exampleTranslation: "كاراتيه كلمة جديدة لوحدتنا." },
  { word: "judo", translation: "جودو", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed judo.", exampleTranslation: "ناقشت جودو مع زميلي." },
  { word: "rowing", translation: "تجديف", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about rowing.", exampleTranslation: "يسأل ورق العمل عن تجديف." },
  { word: "hunting", translation: "صيد", partOfSpeech: "noun", difficulty: "medium", example: "We heard hunting in the science video.", exampleTranslation: "سمعنا صيد في فيلم العلوم." },
  { word: "jumping", translation: "قفز", partOfSpeech: "noun", difficulty: "easy", example: "Please copy jumping into your notebook.", exampleTranslation: "من فضلك انسخ قفز في دفترك." },
  { word: "running", translation: "جري", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of running.", exampleTranslation: "يُظهر المخطط مثالاً عن جري." },
  { word: "walking", translation: "مشي", partOfSpeech: "noun", difficulty: "easy", example: "Our group used walking in the project.", exampleTranslation: "استخدمت مجموعتنا مشي في المشروع." },
  { word: "cycling", translation: "ركوب الدراجات", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with cycling.", exampleTranslation: "أعطى المعلم مثالاً بـركوب الدراجات." },
  { word: "swimming", translation: "سباحة", partOfSpeech: "noun", difficulty: "easy", example: "I underlined swimming in the paragraph.", exampleTranslation: "وضعت خطاً تحت سباحة في الفقرة." },
  { word: "racing", translation: "سباق", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying racing aloud.", exampleTranslation: "تدرّبنا على نطق سباق بصوت عالٍ." },
  { word: "lime", translation: "ليمون أخضر", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains lime with a drawing.", exampleTranslation: "يشرح الملصق ليمون أخضر برسم." },
  { word: "plum", translation: "برقوق", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with plum.", exampleTranslation: "شارك الجميع جملة فيها برقوق." },
  { word: "cherry", translation: "كرز", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word cherry.", exampleTranslation: "تضمّن الاختبار كلمة كرز." },
  { word: "mango", translation: "مانجو", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word mango in class today.", exampleTranslation: "تعلّمنا كلمة مانجو في الحصة اليوم." },
  { word: "watermelon", translation: "بطيخ", partOfSpeech: "noun", difficulty: "easy", example: "Can you use watermelon in a sentence?", exampleTranslation: "هل يمكنك استخدام بطيخ في جملة؟" },
  { word: "pineapple", translation: "أناناس", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned pineapple on page ten.", exampleTranslation: "ذكرت القصة أناناس في الصفحة العاشرة." },
  { word: "coconut", translation: "جوز هند", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote coconut on the board.", exampleTranslation: "كتب معلمنا جوز هند على السبورة." },
  { word: "raspberry", translation: "توت أحمر", partOfSpeech: "noun", difficulty: "medium", example: "I spelled raspberry correctly on the quiz.", exampleTranslation: "تهجّيت توت أحمر بشكل صحيح في الاختبار." },
  { word: "blackberry", translation: "توت أسود", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain blackberry.", exampleTranslation: "تساعد الصورة على شرح توت أسود." },
  { word: "cranberry", translation: "توت بري", partOfSpeech: "noun", difficulty: "medium", example: "We found cranberry in our reading book.", exampleTranslation: "وجدنا توت بري في كتاب القراءة." },
  { word: "papaya", translation: "بابايا", partOfSpeech: "noun", difficulty: "medium", example: "Papaya is a new word for our unit.", exampleTranslation: "بابايا كلمة جديدة لوحدتنا." },
  { word: "kiwi", translation: "كيوي", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed kiwi.", exampleTranslation: "ناقشت كيوي مع زميلي." },
  { word: "fig", translation: "تين", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about fig.", exampleTranslation: "يسأل ورق العمل عن تين." },
  { word: "date", translation: "تمر", partOfSpeech: "noun", difficulty: "easy", example: "We heard date in the science video.", exampleTranslation: "سمعنا تمر في فيلم العلوم." },
  { word: "apricot", translation: "مشمش", partOfSpeech: "noun", difficulty: "medium", example: "Please copy apricot into your notebook.", exampleTranslation: "من فضلك انسخ مشمش في دفترك." },
  { word: "nectarine", translation: "نكتارين", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of nectarine.", exampleTranslation: "يُظهر المخطط مثالاً عن نكتارين." },
  { word: "pomegranate", translation: "رمان", partOfSpeech: "noun", difficulty: "medium", example: "Our group used pomegranate in the project.", exampleTranslation: "استخدمت مجموعتنا رمان في المشروع." },
  { word: "cauliflower", translation: "قرنبيط", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with cauliflower.", exampleTranslation: "أعطى المعلم مثالاً بـقرنبيط." },
  { word: "peas", translation: "بازلاء", partOfSpeech: "noun", difficulty: "easy", example: "I underlined peas in the paragraph.", exampleTranslation: "وضعت خطاً تحت بازلاء في الفقرة." },
  { word: "beans", translation: "فاصوليا", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying beans aloud.", exampleTranslation: "تدرّبنا على نطق فاصوليا بصوت عالٍ." },
  { word: "lentils", translation: "عدس", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains lentils with a drawing.", exampleTranslation: "يشرح الملصق عدس برسم." },
  { word: "wheat", translation: "قمح", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with wheat.", exampleTranslation: "شارك الجميع جملة فيها قمح." },
  { word: "oats", translation: "شوفان", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word oats.", exampleTranslation: "تضمّن الاختبار كلمة شوفان." },
  { word: "barley", translation: "شعير", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word barley in class today.", exampleTranslation: "تعلّمنا كلمة شعير في الحصة اليوم." },
  { word: "toast", translation: "خبز محمص", partOfSpeech: "noun", difficulty: "easy", example: "Can you use toast in a sentence?", exampleTranslation: "هل يمكنك استخدام خبز محمص في جملة؟" },
  { word: "bun", translation: "كعكة صغيرة", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned bun on page ten.", exampleTranslation: "ذكرت القصة كعكة صغيرة في الصفحة العاشرة." },
  { word: "roll", translation: "لفة خبز", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote roll on the board.", exampleTranslation: "كتب معلمنا لفة خبز على السبورة." },
  { word: "bagel", translation: "بيغل", partOfSpeech: "noun", difficulty: "medium", example: "I spelled bagel correctly on the quiz.", exampleTranslation: "تهجّيت بيغل بشكل صحيح في الاختبار." },
  { word: "cracker", translation: "بسكويت مملح", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain cracker.", exampleTranslation: "تساعد الصورة على شرح بسكويت مملح." },
  { word: "pie", translation: "فطيرة", partOfSpeech: "noun", difficulty: "easy", example: "We found pie in our reading book.", exampleTranslation: "وجدنا فطيرة في كتاب القراءة." },
  { word: "spaghetti", translation: "سباغيتي", partOfSpeech: "noun", difficulty: "easy", example: "Spaghetti is a new word for our unit.", exampleTranslation: "سباغيتي كلمة جديدة لوحدتنا." },
  { word: "macaroni", translation: "مكرونة", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed macaroni.", exampleTranslation: "ناقشت مكرونة مع زميلي." },
  { word: "cereal", translation: "حبوب الإفطار", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about cereal.", exampleTranslation: "يسأل ورق العمل عن حبوب الإفطار." },
  { word: "pancake", translation: "فطيرة", partOfSpeech: "noun", difficulty: "easy", example: "We heard pancake in the science video.", exampleTranslation: "سمعنا فطيرة في فيلم العلوم." },
  { word: "donut", translation: "دونات", partOfSpeech: "noun", difficulty: "easy", example: "Please copy donut into your notebook.", exampleTranslation: "من فضلك انسخ دونات في دفترك." },
  { word: "chocolate", translation: "شوكولاتة", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of chocolate.", exampleTranslation: "يُظهر المخطط مثالاً عن شوكولاتة." },
  { word: "sugar", translation: "سكر", partOfSpeech: "noun", difficulty: "easy", example: "Our group used sugar in the project.", exampleTranslation: "استخدمت مجموعتنا سكر في المشروع." },
  { word: "salt", translation: "ملح", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with salt.", exampleTranslation: "أعطى المعلم مثالاً بـملح." },
  { word: "cream", translation: "قشدة", partOfSpeech: "noun", difficulty: "easy", example: "I underlined cream in the paragraph.", exampleTranslation: "وضعت خطاً تحت قشدة في الفقرة." },
  { word: "beef", translation: "لحم بقر", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying beef aloud.", exampleTranslation: "تدرّبنا على نطق لحم بقر بصوت عالٍ." },
  { word: "pork", translation: "لحم خنزير", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains pork with a drawing.", exampleTranslation: "يشرح الملصق لحم خنزير برسم." },
  { word: "veal", translation: "لحم عجل", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with veal.", exampleTranslation: "شارك الجميع جملة فيها لحم عجل." },
  { word: "bacon", translation: "لحم مقدد", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word bacon.", exampleTranslation: "تضمّن الاختبار كلمة لحم مقدد." },
  { word: "sausage", translation: "نقانق", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word sausage in class today.", exampleTranslation: "تعلّمنا كلمة نقانق في الحصة اليوم." },
  { word: "ham", translation: "لحم مقدد", partOfSpeech: "noun", difficulty: "easy", example: "Can you use ham in a sentence?", exampleTranslation: "هل يمكنك استخدام لحم مقدد في جملة؟" },
  { word: "steak", translation: "شريحة لحم", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned steak on page ten.", exampleTranslation: "ذكرت القصة شريحة لحم في الصفحة العاشرة." },
  { word: "burger", translation: "برغر", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote burger on the board.", exampleTranslation: "كتب معلمنا برغر على السبورة." },
  { word: "stew", translation: "يخنة", partOfSpeech: "noun", difficulty: "medium", example: "I spelled stew correctly on the quiz.", exampleTranslation: "تهجّيت يخنة بشكل صحيح في الاختبار." },
  { word: "sauce", translation: "صلصة", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain sauce.", exampleTranslation: "تساعد الصورة على شرح صلصة." },
  { word: "ketchup", translation: "كاتشب", partOfSpeech: "noun", difficulty: "easy", example: "We found ketchup in our reading book.", exampleTranslation: "وجدنا كاتشب في كتاب القراءة." },
  { word: "mustard", translation: "خردل", partOfSpeech: "noun", difficulty: "medium", example: "Mustard is a new word for our unit.", exampleTranslation: "خردل كلمة جديدة لوحدتنا." },
  { word: "mayo", translation: "مايونيز", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed mayo.", exampleTranslation: "ناقشت مايونيز مع زميلي." },
  { word: "vinegar", translation: "خل", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about vinegar.", exampleTranslation: "يسأل ورق العمل عن خل." },
  { word: "oil", translation: "زيت", partOfSpeech: "noun", difficulty: "easy", example: "We heard oil in the science video.", exampleTranslation: "سمعنا زيت في فيلم العلوم." },
  { word: "spice", translation: "بهار", partOfSpeech: "noun", difficulty: "easy", example: "Please copy spice into your notebook.", exampleTranslation: "من فضلك انسخ بهار في دفترك." },
  { word: "herb", translation: "عشب", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of herb.", exampleTranslation: "يُظهر المخطط مثالاً عن عشب." },
  { word: "basil", translation: "ريحان", partOfSpeech: "noun", difficulty: "medium", example: "Our group used basil in the project.", exampleTranslation: "استخدمت مجموعتنا ريحان في المشروع." },
  { word: "mint", translation: "نعناع", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with mint.", exampleTranslation: "أعطى المعلم مثالاً بـنعناع." },
  { word: "nutmeg", translation: "جوزة الطيب", partOfSpeech: "noun", difficulty: "medium", example: "I underlined nutmeg in the paragraph.", exampleTranslation: "وضعت خطاً تحت جوزة الطيب في الفقرة." },
  { word: "cocoa", translation: "كاكاو", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying cocoa aloud.", exampleTranslation: "تدرّبنا على نطق كاكاو بصوت عالٍ." },
  { word: "coffee", translation: "قهوة", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains coffee with a drawing.", exampleTranslation: "يشرح الملصق قهوة برسم." },
  { word: "soda", translation: "مشروب غازي", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with soda.", exampleTranslation: "شارك الجميع جملة فيها مشروب غازي." },
  { word: "smoothie", translation: "عصير مخلوط", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word smoothie.", exampleTranslation: "تضمّن الاختبار كلمة عصير مخلوط." },
  { word: "shake", translation: "ميلك شيك", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word shake in class today.", exampleTranslation: "تعلّمنا كلمة ميلك شيك في الحصة اليوم." },
  { word: "snack", translation: "وجبة خفيفة", partOfSpeech: "noun", difficulty: "easy", example: "Can you use snack in a sentence?", exampleTranslation: "هل يمكنك استخدام وجبة خفيفة في جملة؟" },
  { word: "breakfast", translation: "فطور", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned breakfast on page ten.", exampleTranslation: "ذكرت القصة فطور في الصفحة العاشرة." },
  { word: "lunch", translation: "غداء", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote lunch on the board.", exampleTranslation: "كتب معلمنا غداء على السبورة." },
  { word: "dinner", translation: "عشاء", partOfSpeech: "noun", difficulty: "easy", example: "I spelled dinner correctly on the quiz.", exampleTranslation: "تهجّيت عشاء بشكل صحيح في الاختبار." },
  { word: "supper", translation: "عشاء", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain supper.", exampleTranslation: "تساعد الصورة على شرح عشاء." },
  { word: "meal", translation: "وجبة", partOfSpeech: "noun", difficulty: "easy", example: "We found meal in our reading book.", exampleTranslation: "وجدنا وجبة في كتاب القراءة." },
  { word: "portion", translation: "حصة", partOfSpeech: "noun", difficulty: "medium", example: "Portion is a new word for our unit.", exampleTranslation: "حصة كلمة جديدة لوحدتنا." },
  { word: "serving", translation: "حصة", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed serving.", exampleTranslation: "ناقشت حصة مع زميلي." },
  { word: "calcium", translation: "كالسيوم", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about calcium.", exampleTranslation: "يسأل ورق العمل عن كالسيوم." },
  { word: "zinc", translation: "زنك", partOfSpeech: "noun", difficulty: "medium", example: "We heard zinc in the science video.", exampleTranslation: "سمعنا زنك في فيلم العلوم." },
  { word: "face", translation: "وجه", partOfSpeech: "noun", difficulty: "easy", example: "Please copy face into your notebook.", exampleTranslation: "من فضلك انسخ وجه في دفترك." },
  { word: "forehead", translation: "جبهة", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of forehead.", exampleTranslation: "يُظهر المخطط مثالاً عن جبهة." },
  { word: "eyebrow", translation: "حاجب", partOfSpeech: "noun", difficulty: "medium", example: "Our group used eyebrow in the project.", exampleTranslation: "استخدمت مجموعتنا حاجب في المشروع." },
  { word: "eyelash", translation: "رموش", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with eyelash.", exampleTranslation: "أعطى المعلم مثالاً بـرموش." },
  { word: "lip", translation: "شفة", partOfSpeech: "noun", difficulty: "easy", example: "I underlined lip in the paragraph.", exampleTranslation: "وضعت خطاً تحت شفة في الفقرة." },
  { word: "teeth", translation: "أسنان", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying teeth aloud.", exampleTranslation: "تدرّبنا على نطق أسنان بصوت عالٍ." },
  { word: "tongue", translation: "لسان", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains tongue with a drawing.", exampleTranslation: "يشرح الملصق لسان برسم." },
  { word: "throat", translation: "حلق", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with throat.", exampleTranslation: "شارك الجميع جملة فيها حلق." },
  { word: "neck", translation: "رقبة", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word neck.", exampleTranslation: "تضمّن الاختبار كلمة رقبة." },
  { word: "elbow", translation: "مرفق", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word elbow in class today.", exampleTranslation: "تعلّمنا كلمة مرفق في الحصة اليوم." },
  { word: "wrist", translation: "معصم", partOfSpeech: "noun", difficulty: "medium", example: "Can you use wrist in a sentence?", exampleTranslation: "هل يمكنك استخدام معصم في جملة؟" },
  { word: "thumb", translation: "إبهام", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned thumb on page ten.", exampleTranslation: "ذكرت القصة إبهام في الصفحة العاشرة." },
  { word: "nail", translation: "ظفر", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote nail on the board.", exampleTranslation: "كتب معلمنا ظفر على السبورة." },
  { word: "back", translation: "ظهر", partOfSpeech: "noun", difficulty: "easy", example: "I spelled back correctly on the quiz.", exampleTranslation: "تهجّيت ظهر بشكل صحيح في الاختبار." },
  { word: "spine", translation: "عمود فقري", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain spine.", exampleTranslation: "تساعد الصورة على شرح عمود فقري." },
  { word: "rib", translation: "ضلع", partOfSpeech: "noun", difficulty: "medium", example: "We found rib in our reading book.", exampleTranslation: "وجدنا ضلع في كتاب القراءة." },
  { word: "waist", translation: "خصر", partOfSpeech: "noun", difficulty: "easy", example: "Waist is a new word for our unit.", exampleTranslation: "خصر كلمة جديدة لوحدتنا." },
  { word: "hip", translation: "ورك", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed hip.", exampleTranslation: "ناقشت ورك مع زميلي." },
  { word: "navel", translation: "سرة", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about navel.", exampleTranslation: "يسأل ورق العمل عن سرة." },
  { word: "thigh", translation: "فخذ", partOfSpeech: "noun", difficulty: "medium", example: "We heard thigh in the science video.", exampleTranslation: "سمعنا فخذ في فيلم العلوم." },
  { word: "shin", translation: "قصبة الساق", partOfSpeech: "noun", difficulty: "medium", example: "Please copy shin into your notebook.", exampleTranslation: "من فضلك انسخ قصبة الساق في دفترك." },
  { word: "ankle", translation: "كاحل", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of ankle.", exampleTranslation: "يُظهر المخطط مثالاً عن كاحل." },
  { word: "heel", translation: "كعب", partOfSpeech: "noun", difficulty: "medium", example: "Our group used heel in the project.", exampleTranslation: "استخدمت مجموعتنا كعب في المشروع." },
  { word: "toe", translation: "إصبع القدم", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with toe.", exampleTranslation: "أعطى المعلم مثالاً بـإصبع القدم." },
  { word: "skin", translation: "جلد", partOfSpeech: "noun", difficulty: "easy", example: "I underlined skin in the paragraph.", exampleTranslation: "وضعت خطاً تحت جلد في الفقرة." },
  { word: "beard", translation: "لحية", partOfSpeech: "noun", difficulty: "easy", example: "We practiced saying beard aloud.", exampleTranslation: "تدرّبنا على نطق لحية بصوت عالٍ." },
  { word: "mustache", translation: "شارب", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains mustache with a drawing.", exampleTranslation: "يشرح الملصق شارب برسم." },
  { word: "bone", translation: "عظم", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with bone.", exampleTranslation: "شارك الجميع جملة فيها عظم." },
  { word: "joint", translation: "مفصل", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word joint.", exampleTranslation: "تضمّن الاختبار كلمة مفصل." },
  { word: "nerve", translation: "عصب", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word nerve in class today.", exampleTranslation: "تعلّمنا كلمة عصب في الحصة اليوم." },
  { word: "blood", translation: "دم", partOfSpeech: "noun", difficulty: "easy", example: "Can you use blood in a sentence?", exampleTranslation: "هل يمكنك استخدام دم في جملة؟" },
  { word: "brain", translation: "دماغ", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned brain on page ten.", exampleTranslation: "ذكرت القصة دماغ في الصفحة العاشرة." },
  { word: "skull", translation: "جمجمة", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote skull on the board.", exampleTranslation: "كتب معلمنا جمجمة على السبورة." },
  { word: "jaw", translation: "فك", partOfSpeech: "noun", difficulty: "medium", example: "I spelled jaw correctly on the quiz.", exampleTranslation: "تهجّيت فك بشكل صحيح في الاختبار." },
  { word: "cheek", translation: "خد", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain cheek.", exampleTranslation: "تساعد الصورة على شرح خد." },
  { word: "chin", translation: "ذقن", partOfSpeech: "noun", difficulty: "easy", example: "We found chin in our reading book.", exampleTranslation: "وجدنا ذقن في كتاب القراءة." },
  { word: "forearm", translation: "ساعد", partOfSpeech: "noun", difficulty: "medium", example: "Forearm is a new word for our unit.", exampleTranslation: "ساعد كلمة جديدة لوحدتنا." },
  { word: "bicep", translation: "عضلة ذات الرأسين", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed bicep.", exampleTranslation: "ناقشت عضلة ذات الرأسين مع زميلي." },
  { word: "tricep", translation: "عضلة ثلاثية", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about tricep.", exampleTranslation: "يسأل ورق العمل عن عضلة ثلاثية." },
  { word: "cell", translation: "خلية", partOfSpeech: "noun", difficulty: "easy", example: "We heard cell in the science video.", exampleTranslation: "سمعنا خلية في فيلم العلوم." },
  { word: "breath", translation: "نفس", partOfSpeech: "noun", difficulty: "easy", example: "Please copy breath into your notebook.", exampleTranslation: "من فضلك انسخ نفس في دفترك." },
  { word: "health", translation: "صحة", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of health.", exampleTranslation: "يُظهر المخطط مثالاً عن صحة." },
  { word: "illness", translation: "مرض", partOfSpeech: "noun", difficulty: "easy", example: "Our group used illness in the project.", exampleTranslation: "استخدمت مجموعتنا مرض في المشروع." },
  { word: "disease", translation: "مرض", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with disease.", exampleTranslation: "أعطى المعلم مثالاً بـمرض." },
  { word: "flu", translation: "إنفلونزا", partOfSpeech: "noun", difficulty: "easy", example: "I underlined flu in the paragraph.", exampleTranslation: "وضعت خطاً تحت إنفلونزا في الفقرة." },
  { word: "asthma", translation: "ربو", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying asthma aloud.", exampleTranslation: "تدرّبنا على نطق ربو بصوت عالٍ." },
  { word: "injury", translation: "إصابة", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains injury with a drawing.", exampleTranslation: "يشرح الملصق إصابة برسم." },
  { word: "wound", translation: "جرح", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with wound.", exampleTranslation: "شارك الجميع جملة فيها جرح." },
  { word: "bruise", translation: "كدمة", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word bruise.", exampleTranslation: "تضمّن الاختبار كلمة كدمة." },
  { word: "scar", translation: "ندبة", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word scar in class today.", exampleTranslation: "تعلّمنا كلمة ندبة في الحصة اليوم." },
  { word: "pill", translation: "حبة دواء", partOfSpeech: "noun", difficulty: "easy", example: "Can you use pill in a sentence?", exampleTranslation: "هل يمكنك استخدام حبة دواء في جملة؟" },
  { word: "surgery", translation: "جراحة", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned surgery on page ten.", exampleTranslation: "ذكرت القصة جراحة في الصفحة العاشرة." },
  { word: "therapy", translation: "علاج", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote therapy on the board.", exampleTranslation: "كتب معلمنا علاج على السبورة." },
  { word: "exercise", translation: "تمرين", partOfSpeech: "noun", difficulty: "easy", example: "I spelled exercise correctly on the quiz.", exampleTranslation: "تهجّيت تمرين بشكل صحيح في الاختبار." },
  { word: "rest", translation: "راحة", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain rest.", exampleTranslation: "تساعد الصورة على شرح راحة." },
  { word: "dream", translation: "حلم", partOfSpeech: "noun", difficulty: "easy", example: "We found dream in our reading book.", exampleTranslation: "وجدنا حلم في كتاب القراءة." },
  { word: "nightmare", translation: "كابوس", partOfSpeech: "noun", difficulty: "medium", example: "Nightmare is a new word for our unit.", exampleTranslation: "كابوس كلمة جديدة لوحدتنا." },
  { word: "mad", translation: "غاضب", partOfSpeech: "adjective", difficulty: "easy", example: "My partner and I discussed mad.", exampleTranslation: "ناقشت غاضب مع زميلي." },
  { word: "glad", translation: "مسرور", partOfSpeech: "adjective", difficulty: "easy", example: "The worksheet asks about glad.", exampleTranslation: "يسأل ورق العمل عن مسرور." },
  { word: "joyful", translation: "مبتهج", partOfSpeech: "adjective", difficulty: "medium", example: "We heard joyful in the science video.", exampleTranslation: "سمعنا مبتهج في فيلم العلوم." },
  { word: "cheerful", translation: "مبتهج", partOfSpeech: "adjective", difficulty: "medium", example: "Please copy cheerful into your notebook.", exampleTranslation: "من فضلك انسخ مبتهج في دفترك." },
  { word: "bored", translation: "ملل", partOfSpeech: "adjective", difficulty: "easy", example: "The chart shows an example of bored.", exampleTranslation: "يُظهر المخطط مثالاً عن ملل." },
  { word: "sleepy", translation: "نعسان", partOfSpeech: "adjective", difficulty: "easy", example: "Our group used sleepy in the project.", exampleTranslation: "استخدمت مجموعتنا نعسان في المشروع." },
  { word: "full", translation: "شبعان", partOfSpeech: "adjective", difficulty: "easy", example: "The teacher gave an example with full.", exampleTranslation: "أعطى المعلم مثالاً بـشبعان." },
  { word: "afraid", translation: "خائف", partOfSpeech: "adjective", difficulty: "easy", example: "I underlined afraid in the paragraph.", exampleTranslation: "وضعت خطاً تحت خائف في الفقرة." },
  { word: "fearful", translation: "خائف", partOfSpeech: "adjective", difficulty: "medium", example: "We practiced saying fearful aloud.", exampleTranslation: "تدرّبنا على نطق خائف بصوت عالٍ." },
  { word: "bold", translation: "جريء", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains bold with a drawing.", exampleTranslation: "يشرح الملصق جريء برسم." },
  { word: "calm", translation: "هادئ", partOfSpeech: "adjective", difficulty: "easy", example: "Everyone shared a sentence with calm.", exampleTranslation: "شارك الجميع جملة فيها هادئ." },
  { word: "relaxed", translation: "مسترخٍ", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word relaxed.", exampleTranslation: "تضمّن الاختبار كلمة مسترخٍ." },
];
