/** Grade 6 chunk F — feelings, character, abstract ideas, arts, tech & time (cards 501-1000, batch 3). */
export const GRADE6_CHUNK_F = [
  { word: "brave", translation: "شجاع", partOfSpeech: "adjective", difficulty: "easy", example: "The brave girl saved the kitten.", exampleTranslation: "أنقذت الفتاة الشجاعة الهرّة." },
  { word: "calm", translation: "هادئ", partOfSpeech: "adjective", difficulty: "easy", example: "The sea was calm at sunrise.", exampleTranslation: "كان البحر هادئاً عند الشروق." },
  { word: "clever", translation: "ذكي", partOfSpeech: "adjective", difficulty: "medium", example: "A clever plan solved the problem.", exampleTranslation: "حلّت خطة ذكية المشكلة." },
  { word: "eager", translation: "متحمّس", partOfSpeech: "adjective", difficulty: "medium", example: "The pupils were eager to start.", exampleTranslation: "كان التلاميذ متحمّسين للبدء." },
  { word: "gentle", translation: "لطيف/رقيق", partOfSpeech: "adjective", difficulty: "medium", example: "She gave the baby a gentle pat.", exampleTranslation: "ربتت على الطفل بلطف." },
  { word: "fierce", translation: "شرس", partOfSpeech: "adjective", difficulty: "hard", example: "The fierce wind shook the tents.", exampleTranslation: "هزّت الريح الشرسة الخيام." },
  { word: "jealous", translation: "غيور", partOfSpeech: "adjective", difficulty: "hard", example: "He felt jealous of his friend's bike.", exampleTranslation: "شعر بالغيرة من دراجة صديقه." },
  { word: "joyful", translation: "مبتهج", partOfSpeech: "adjective", difficulty: "medium", example: "The joyful crowd sang together.", exampleTranslation: "غنّى الحشد المبتهج معاً." },
  { word: "lonely", translation: "وحيد", partOfSpeech: "adjective", difficulty: "medium", example: "The lonely traveler missed his home.", exampleTranslation: "اشتاق المسافر الوحيد إلى بيته." },
  { word: "nervous", translation: "متوتّر", partOfSpeech: "adjective", difficulty: "medium", example: "She felt nervous before the show.", exampleTranslation: "شعرت بالتوتّر قبل العرض." },
  { word: "peaceful", translation: "مسالم/هادئ", partOfSpeech: "adjective", difficulty: "medium", example: "The garden was a peaceful place.", exampleTranslation: "كانت الحديقة مكاناً هادئاً." },
  { word: "proud", translation: "فخور", partOfSpeech: "adjective", difficulty: "easy", example: "They were proud of the team.", exampleTranslation: "كانوا فخورين بالفريق." },
  { word: "shy", translation: "خجول", partOfSpeech: "adjective", difficulty: "easy", example: "The shy boy spoke very softly.", exampleTranslation: "تحدّث الصبي الخجول بصوت خافت جداً." },
  { word: "stubborn", translation: "عنيد", partOfSpeech: "adjective", difficulty: "hard", example: "The stubborn mule would not move.", exampleTranslation: "رفض البغل العنيد أن يتحرّك." },
  { word: "thoughtful", translation: "مراعٍ/متأمّل", partOfSpeech: "adjective", difficulty: "hard", example: "It was thoughtful of her to help.", exampleTranslation: "كان من اللطف أن تساعد." },
  { word: "bold", translation: "جريء", partOfSpeech: "adjective", difficulty: "medium", example: "He made a bold decision.", exampleTranslation: "اتخذ قراراً جريئاً." },
  { word: "brilliant", translation: "بارع/لامع", partOfSpeech: "adjective", difficulty: "medium", example: "She had a brilliant idea.", exampleTranslation: "كانت لديها فكرة بارعة." },
  { word: "capable", translation: "قادر", partOfSpeech: "adjective", difficulty: "hard", example: "The team is capable of winning.", exampleTranslation: "الفريق قادر على الفوز." },
  { word: "content", translation: "راضٍ", partOfSpeech: "adjective", difficulty: "hard", example: "He felt content after the meal.", exampleTranslation: "شعر بالرضا بعد الوجبة." },
  { word: "faithful", translation: "مخلص", partOfSpeech: "adjective", difficulty: "hard", example: "A faithful dog waits for its owner.", exampleTranslation: "ينتظر الكلب المخلص صاحبه." },
  { word: "fearless", translation: "لا يخاف", partOfSpeech: "adjective", difficulty: "hard", example: "The fearless diver explored the cave.", exampleTranslation: "استكشف الغوّاص الذي لا يخاف الكهف." },
  { word: "friendly", translation: "ودود", partOfSpeech: "adjective", difficulty: "easy", example: "Our new neighbor is very friendly.", exampleTranslation: "جارنا الجديد ودود جداً." },
  { word: "hopeful", translation: "متفائل/يحدوه الأمل", partOfSpeech: "adjective", difficulty: "medium", example: "We are hopeful about the result.", exampleTranslation: "يحدونا الأمل بشأن النتيجة." },
  { word: "lively", translation: "نشيط/مفعم بالحياة", partOfSpeech: "adjective", difficulty: "medium", example: "The market was a lively place.", exampleTranslation: "كان السوق مكاناً مفعماً بالحياة." },
  { word: "modest", translation: "متواضع", partOfSpeech: "adjective", difficulty: "hard", example: "The winner gave a modest smile.", exampleTranslation: "ابتسم الفائز ابتسامة متواضعة." },
  { word: "noble", translation: "نبيل", partOfSpeech: "adjective", difficulty: "hard", example: "Helping others is a noble act.", exampleTranslation: "مساعدة الآخرين عمل نبيل." },
  { word: "pleasant", translation: "ممتع/لطيف", partOfSpeech: "adjective", difficulty: "medium", example: "We had a pleasant walk in the park.", exampleTranslation: "قمنا بنزهة لطيفة في الحديقة." },
  { word: "sensible", translation: "عاقل/حكيم", partOfSpeech: "adjective", difficulty: "hard", example: "She made a sensible choice.", exampleTranslation: "اتخذت خياراً عاقلاً." },
  { word: "sociable", translation: "اجتماعي", partOfSpeech: "adjective", difficulty: "hard", example: "He is sociable and makes friends fast.", exampleTranslation: "هو اجتماعي ويكوّن صداقات بسرعة." },
  { word: "tidy", translation: "مرتّب", partOfSpeech: "adjective", difficulty: "medium", example: "Keep your desk neat and tidy.", exampleTranslation: "أبقِ مكتبك أنيقاً ومرتّباً." },
  { word: "witty", translation: "سريع البديهة", partOfSpeech: "adjective", difficulty: "hard", example: "Her witty reply made us laugh.", exampleTranslation: "أضحكنا ردّها سريع البديهة." },
  { word: "courage", translation: "شجاعة", partOfSpeech: "noun", difficulty: "medium", example: "It took courage to speak up.", exampleTranslation: "تطلّب الأمر شجاعة للتحدّث." },
  { word: "curiosity", translation: "فضول", partOfSpeech: "noun", difficulty: "hard", example: "Curiosity led her to the old map.", exampleTranslation: "قاد الفضول قدميها إلى الخريطة القديمة." },
  { word: "delight", translation: "بهجة", partOfSpeech: "noun", difficulty: "hard", example: "The gift filled him with delight.", exampleTranslation: "ملأته الهدية بهجة." },
  { word: "despair", translation: "يأس", partOfSpeech: "noun", difficulty: "hard", example: "Do not give in to despair.", exampleTranslation: "لا تستسلم لليأس." },
  { word: "disappointment", translation: "خيبة أمل", partOfSpeech: "noun", difficulty: "hard", example: "The loss brought deep disappointment.", exampleTranslation: "جلبت الخسارة خيبة أمل عميقة." },
  { word: "emotion", translation: "عاطفة", partOfSpeech: "noun", difficulty: "hard", example: "Music can stir strong emotion.", exampleTranslation: "يمكن للموسيقى أن تثير عاطفة قوية." },
  { word: "envy", translation: "حسد", partOfSpeech: "noun", difficulty: "hard", example: "Try to feel joy instead of envy.", exampleTranslation: "حاول أن تشعر بالفرح بدل الحسد." },
  { word: "excitement", translation: "إثارة", partOfSpeech: "noun", difficulty: "medium", example: "The game filled us with excitement.", exampleTranslation: "ملأتنا المباراة بالإثارة." },
  { word: "fear", translation: "خوف", partOfSpeech: "noun", difficulty: "easy", example: "She faced her fear of the dark.", exampleTranslation: "واجهت خوفها من الظلام." },
  { word: "gratitude", translation: "امتنان", partOfSpeech: "noun", difficulty: "hard", example: "He showed gratitude with a kind note.", exampleTranslation: "أظهر امتنانه بملاحظة لطيفة." },
  { word: "grief", translation: "حزن شديد", partOfSpeech: "noun", difficulty: "hard", example: "The village shared its grief.", exampleTranslation: "تشاركت القرية حزنها الشديد." },
  { word: "happiness", translation: "سعادة", partOfSpeech: "noun", difficulty: "easy", example: "Small things can bring happiness.", exampleTranslation: "يمكن للأشياء الصغيرة أن تجلب السعادة." },
  { word: "hope", translation: "أمل", partOfSpeech: "noun", difficulty: "easy", example: "A new day brings fresh hope.", exampleTranslation: "يجلب يوم جديد أملاً متجدّداً." },
  { word: "mood", translation: "مزاج", partOfSpeech: "noun", difficulty: "medium", example: "Sunny weather lifts my mood.", exampleTranslation: "يرفع الطقس المشمس مزاجي." },
  { word: "passion", translation: "شغف", partOfSpeech: "noun", difficulty: "hard", example: "She has a passion for painting.", exampleTranslation: "لديها شغف بالرسم." },
  { word: "pity", translation: "شفقة", partOfSpeech: "noun", difficulty: "hard", example: "He felt pity for the lost dog.", exampleTranslation: "شعر بالشفقة على الكلب التائه." },
  { word: "pride", translation: "فخر/كبرياء", partOfSpeech: "noun", difficulty: "medium", example: "She takes pride in her work.", exampleTranslation: "تفخر بعملها." },
  { word: "sorrow", translation: "أسى", partOfSpeech: "noun", difficulty: "hard", example: "His eyes were full of sorrow.", exampleTranslation: "كانت عيناه مليئتين بالأسى." },
  { word: "sympathy", translation: "تعاطف", partOfSpeech: "noun", difficulty: "hard", example: "She offered sympathy to the family.", exampleTranslation: "قدّمت التعاطف للعائلة." },
  { word: "tension", translation: "توتّر", partOfSpeech: "noun", difficulty: "hard", example: "There was tension before the result.", exampleTranslation: "كان هناك توتّر قبل النتيجة." },
  { word: "ambition", translation: "طموح", partOfSpeech: "noun", difficulty: "hard", example: "Her ambition is to be a pilot.", exampleTranslation: "طموحها أن تصبح طيّارة." },
  { word: "awareness", translation: "وعي", partOfSpeech: "noun", difficulty: "hard", example: "The campaign raised awareness of safety.", exampleTranslation: "رفعت الحملة الوعي بالسلامة." },
  { word: "belief", translation: "اعتقاد", partOfSpeech: "noun", difficulty: "hard", example: "Her belief in hard work never faded.", exampleTranslation: "لم يتلاشَ اعتقادها بأهمية العمل الجاد." },
  { word: "bravery", translation: "بسالة", partOfSpeech: "noun", difficulty: "hard", example: "The medal honored his bravery.", exampleTranslation: "كرّمت الميدالية بسالته." },
  { word: "choice", translation: "اختيار", partOfSpeech: "noun", difficulty: "easy", example: "You made the right choice.", exampleTranslation: "اتخذت الاختيار الصحيح." },
  { word: "concept", translation: "مفهوم", partOfSpeech: "noun", difficulty: "hard", example: "The teacher explained a new concept.", exampleTranslation: "شرح المعلّم مفهوماً جديداً." },
  { word: "confidence", translation: "ثقة", partOfSpeech: "noun", difficulty: "medium", example: "Practice gives you confidence.", exampleTranslation: "تمنحك الممارسة الثقة." },
  { word: "conscience", translation: "ضمير", partOfSpeech: "noun", difficulty: "hard", example: "His conscience told him to be honest.", exampleTranslation: "أمره ضميره بأن يكون صادقاً." },
  { word: "consequence", translation: "نتيجة/عاقبة", partOfSpeech: "noun", difficulty: "hard", example: "Every action has a consequence.", exampleTranslation: "لكل فعل عاقبة." },
  { word: "creativity", translation: "إبداع", partOfSpeech: "noun", difficulty: "hard", example: "Art classes spark creativity.", exampleTranslation: "تشعل حصص الفن الإبداع." },
  { word: "discipline", translation: "انضباط", partOfSpeech: "noun", difficulty: "hard", example: "Sport teaches discipline.", exampleTranslation: "تعلّم الرياضة الانضباط." },
  { word: "dream", translation: "حلم", partOfSpeech: "noun", difficulty: "easy", example: "She follows her dream every day.", exampleTranslation: "تتبع حلمها كل يوم." },
  { word: "duty", translation: "واجب", partOfSpeech: "noun", difficulty: "medium", example: "It is our duty to help others.", exampleTranslation: "من واجبنا مساعدة الآخرين." },
  { word: "enthusiasm", translation: "حماس", partOfSpeech: "noun", difficulty: "hard", example: "She greeted the news with enthusiasm.", exampleTranslation: "استقبلت الخبر بحماس." },
  { word: "fairness", translation: "إنصاف", partOfSpeech: "noun", difficulty: "hard", example: "The referee is known for fairness.", exampleTranslation: "يُعرف الحكم بالإنصاف." },
  { word: "faith", translation: "إيمان/ثقة", partOfSpeech: "noun", difficulty: "hard", example: "They had faith in their leader.", exampleTranslation: "كانت لديهم ثقة بقائدهم." },
  { word: "focus", translation: "تركيز", partOfSpeech: "noun", difficulty: "medium", example: "Keep your focus on the goal.", exampleTranslation: "أبقِ تركيزك على الهدف." },
  { word: "fortune", translation: "حظّ/ثروة", partOfSpeech: "noun", difficulty: "hard", example: "Good fortune followed the kind man.", exampleTranslation: "تبع الحظّ السعيد الرجل الطيّب." },
  { word: "generosity", translation: "كرم", partOfSpeech: "noun", difficulty: "hard", example: "Her generosity surprised everyone.", exampleTranslation: "فاجأ كرمها الجميع." },
  { word: "honor", translation: "شرف", partOfSpeech: "noun", difficulty: "hard", example: "It is an honor to meet you.", exampleTranslation: "إنه لشرف أن ألتقي بك." },
  { word: "humor", translation: "روح الدعابة", partOfSpeech: "noun", difficulty: "hard", example: "His sense of humor cheered us up.", exampleTranslation: "أبهجتنا روح الدعابة لديه." },
  { word: "imagination", translation: "خيال", partOfSpeech: "noun", difficulty: "hard", example: "Stories feed the imagination.", exampleTranslation: "تغذّي القصص الخيال." },
  { word: "instinct", translation: "غريزة", partOfSpeech: "noun", difficulty: "hard", example: "Birds build nests by instinct.", exampleTranslation: "تبني الطيور أعشاشها بالغريزة." },
  { word: "intelligence", translation: "ذكاء", partOfSpeech: "noun", difficulty: "hard", example: "Dolphins show great intelligence.", exampleTranslation: "تُظهر الدلافين ذكاءً كبيراً." },
  { word: "intention", translation: "نيّة", partOfSpeech: "noun", difficulty: "hard", example: "Her intention was to help.", exampleTranslation: "كانت نيّتها أن تساعد." },
  { word: "memory", translation: "ذاكرة", partOfSpeech: "noun", difficulty: "medium", example: "He has a sharp memory for names.", exampleTranslation: "لديه ذاكرة قوية للأسماء." },
  { word: "patience", translation: "صبر", partOfSpeech: "noun", difficulty: "medium", example: "Teaching requires great patience.", exampleTranslation: "يتطلّب التعليم صبراً كبيراً." },
  { word: "peace", translation: "سلام", partOfSpeech: "noun", difficulty: "easy", example: "The whole town hoped for peace.", exampleTranslation: "تمنّت البلدة كلها السلام." },
  { word: "principle", translation: "مبدأ", partOfSpeech: "noun", difficulty: "hard", example: "Honesty is a key principle.", exampleTranslation: "الأمانة مبدأ أساسي." },
  { word: "reason", translation: "سبب", partOfSpeech: "noun", difficulty: "easy", example: "Give one reason for your answer.", exampleTranslation: "أعطِ سبباً واحداً لإجابتك." },
  { word: "reputation", translation: "سمعة", partOfSpeech: "noun", difficulty: "hard", example: "The shop has a good reputation.", exampleTranslation: "يتمتّع المتجر بسمعة جيدة." },
  { word: "sacrifice", translation: "تضحية", partOfSpeech: "noun", difficulty: "hard", example: "Parents make many sacrifices.", exampleTranslation: "يقدّم الآباء تضحيات كثيرة." },
  { word: "trust", translation: "ثقة", partOfSpeech: "noun", difficulty: "medium", example: "Friendship is built on trust.", exampleTranslation: "تُبنى الصداقة على الثقة." },
  { word: "truth", translation: "حقيقة", partOfSpeech: "noun", difficulty: "easy", example: "Always tell the truth.", exampleTranslation: "قل الحقيقة دائماً." },
  { word: "virtue", translation: "فضيلة", partOfSpeech: "noun", difficulty: "hard", example: "Patience is a great virtue.", exampleTranslation: "الصبر فضيلة عظيمة." },
  { word: "spirit", translation: "روح", partOfSpeech: "noun", difficulty: "medium", example: "The team played with great spirit.", exampleTranslation: "لعب الفريق بروح عالية." },
  { word: "silence", translation: "صمت", partOfSpeech: "noun", difficulty: "medium", example: "A deep silence filled the hall.", exampleTranslation: "ملأ صمت عميق القاعة." },
  { word: "melody", translation: "لحن", partOfSpeech: "noun", difficulty: "hard", example: "The flute played a soft melody.", exampleTranslation: "عزف الناي لحناً ناعماً." },
  { word: "orchestra", translation: "أوركسترا", partOfSpeech: "noun", difficulty: "hard", example: "The orchestra tuned its instruments.", exampleTranslation: "ضبطت الأوركسترا آلاتها." },
  { word: "instrument", translation: "آلة موسيقية", partOfSpeech: "noun", difficulty: "medium", example: "The violin is her favorite instrument.", exampleTranslation: "الكمان آلتها المفضّلة." },
  { word: "chorus", translation: "جوقة/لازمة", partOfSpeech: "noun", difficulty: "hard", example: "The whole class sang the chorus.", exampleTranslation: "غنّى الصف كله اللازمة." },
  { word: "tune", translation: "نغمة", partOfSpeech: "noun", difficulty: "medium", example: "He hummed a cheerful tune.", exampleTranslation: "دندن نغمة مرحة." },
  { word: "sculpture", translation: "منحوتة", partOfSpeech: "noun", difficulty: "hard", example: "The marble sculpture stood in the hall.", exampleTranslation: "وقفت المنحوتة الرخامية في القاعة." },
  { word: "portrait", translation: "صورة شخصية", partOfSpeech: "noun", difficulty: "hard", example: "The artist painted a portrait of the queen.", exampleTranslation: "رسم الفنان صورة شخصية للملكة." },
  { word: "canvas", translation: "قماش الرسم", partOfSpeech: "noun", difficulty: "hard", example: "She spread the paint across the canvas.", exampleTranslation: "وزّعت الطلاء على قماش الرسم." },
  { word: "gallery", translation: "صالة عرض", partOfSpeech: "noun", difficulty: "medium", example: "We saw famous works at the gallery.", exampleTranslation: "شاهدنا أعمالاً مشهورة في صالة العرض." },
  { word: "drama", translation: "دراما/مسرحية", partOfSpeech: "noun", difficulty: "medium", example: "The school drama was a big success.", exampleTranslation: "كانت مسرحية المدرسة نجاحاً كبيراً." },
  { word: "theater", translation: "مسرح", partOfSpeech: "noun", difficulty: "medium", example: "We watched a play at the theater.", exampleTranslation: "شاهدنا مسرحية في المسرح." },
  { word: "costume", translation: "زيّ", partOfSpeech: "noun", difficulty: "medium", example: "Her costume looked like a star.", exampleTranslation: "بدا زيّها كنجمة." },
  { word: "pottery", translation: "فخّار", partOfSpeech: "noun", difficulty: "hard", example: "They shaped clay into fine pottery.", exampleTranslation: "شكّلوا الطين إلى فخّار جميل." },
  { word: "photography", translation: "تصوير", partOfSpeech: "noun", difficulty: "hard", example: "Photography is a creative hobby.", exampleTranslation: "التصوير هواية إبداعية." },
  { word: "device", translation: "جهاز", partOfSpeech: "noun", difficulty: "medium", example: "A phone is a useful device.", exampleTranslation: "الهاتف جهاز مفيد." },
  { word: "gadget", translation: "أداة تقنية صغيرة", partOfSpeech: "noun", difficulty: "hard", example: "This gadget can measure the temperature.", exampleTranslation: "تستطيع هذه الأداة قياس درجة الحرارة." },
  { word: "screen", translation: "شاشة", partOfSpeech: "noun", difficulty: "easy", example: "The screen showed a bright map.", exampleTranslation: "عرضت الشاشة خريطة زاهية." },
  { word: "keyboard", translation: "لوحة مفاتيح", partOfSpeech: "noun", difficulty: "medium", example: "She types fast on the keyboard.", exampleTranslation: "تكتب بسرعة على لوحة المفاتيح." },
  { word: "network", translation: "شبكة", partOfSpeech: "noun", difficulty: "hard", example: "The school network connects all rooms.", exampleTranslation: "تربط شبكة المدرسة كل الغرف." },
  { word: "software", translation: "برمجيات", partOfSpeech: "noun", difficulty: "hard", example: "New software runs the robot.", exampleTranslation: "تشغّل برمجيات جديدة الروبوت." },
  { word: "program", translation: "برنامج", partOfSpeech: "noun", difficulty: "medium", example: "They wrote a simple program.", exampleTranslation: "كتبوا برنامجاً بسيطاً." },
  { word: "digital", translation: "رقمي", partOfSpeech: "adjective", difficulty: "hard", example: "The clock shows digital numbers.", exampleTranslation: "تعرض الساعة أرقاماً رقمية." },
  { word: "signal", translation: "إشارة", partOfSpeech: "noun", difficulty: "medium", example: "The phone lost its signal in the tunnel.", exampleTranslation: "فقد الهاتف إشارته في النفق." },
  { word: "sensor", translation: "مستشعر", partOfSpeech: "noun", difficulty: "hard", example: "A sensor opens the shop door.", exampleTranslation: "يفتح مستشعر باب المتجر." },
  { word: "robot", translation: "روبوت", partOfSpeech: "noun", difficulty: "medium", example: "The robot can lift heavy boxes.", exampleTranslation: "يستطيع الروبوت رفع صناديق ثقيلة." },
  { word: "engine", translation: "محرّك", partOfSpeech: "noun", difficulty: "medium", example: "The engine roared to life.", exampleTranslation: "هدر المحرّك عند بدء التشغيل." },
  { word: "machine", translation: "آلة", partOfSpeech: "noun", difficulty: "easy", example: "The machine prints a hundred pages.", exampleTranslation: "تطبع الآلة مئة صفحة." },
  { word: "battery", translation: "بطارية", partOfSpeech: "noun", difficulty: "medium", example: "The toy needs a new battery.", exampleTranslation: "تحتاج اللعبة إلى بطارية جديدة." },
  { word: "fuel", translation: "وقود", partOfSpeech: "noun", difficulty: "medium", example: "The plane filled up with fuel.", exampleTranslation: "تزوّدت الطائرة بالوقود." },
  { word: "wheel", translation: "عجلة", partOfSpeech: "noun", difficulty: "easy", example: "The front wheel of the bike was flat.", exampleTranslation: "كانت العجلة الأمامية للدراجة فارغة من الهواء." },
  { word: "gear", translation: "ترس", partOfSpeech: "noun", difficulty: "hard", example: "A small gear turns the big one.", exampleTranslation: "يدير ترس صغير الترس الكبير." },
  { word: "lever", translation: "رافعة", partOfSpeech: "noun", difficulty: "hard", example: "Pull the lever to start the machine.", exampleTranslation: "اسحب الرافعة لتشغيل الآلة." },
  { word: "pulley", translation: "بكرة", partOfSpeech: "noun", difficulty: "hard", example: "A pulley lifts the bucket easily.", exampleTranslation: "ترفع البكرة الدلو بسهولة." },
  { word: "antenna", translation: "هوائي", partOfSpeech: "noun", difficulty: "hard", example: "The antenna catches the radio waves.", exampleTranslation: "يلتقط الهوائي موجات الراديو." },
  { word: "century", translation: "قرن", partOfSpeech: "noun", difficulty: "medium", example: "The castle is over a century old.", exampleTranslation: "عمر القلعة أكثر من قرن." },
  { word: "decade", translation: "عقد (عشر سنوات)", partOfSpeech: "noun", difficulty: "hard", example: "The city changed a lot in a decade.", exampleTranslation: "تغيّرت المدينة كثيراً خلال عقد." },
  { word: "era", translation: "حقبة", partOfSpeech: "noun", difficulty: "hard", example: "We live in a digital era.", exampleTranslation: "نعيش في حقبة رقمية." },
  { word: "moment", translation: "لحظة", partOfSpeech: "noun", difficulty: "easy", example: "Wait for me a moment.", exampleTranslation: "انتظرني لحظة." },
  { word: "period", translation: "فترة", partOfSpeech: "noun", difficulty: "medium", example: "The rest period lasts ten minutes.", exampleTranslation: "تستمرّ فترة الراحة عشر دقائق." },
  { word: "season", translation: "فصل (من السنة)", partOfSpeech: "noun", difficulty: "easy", example: "Autumn is my favorite season.", exampleTranslation: "الخريف فصلي المفضّل." },
  { word: "calendar", translation: "تقويم", partOfSpeech: "noun", difficulty: "medium", example: "Mark the date on the calendar.", exampleTranslation: "ضع علامة على التاريخ في التقويم." },
  { word: "schedule", translation: "جدول زمني", partOfSpeech: "noun", difficulty: "hard", example: "Check the bus schedule before you go.", exampleTranslation: "تحقّق من جدول الحافلة قبل الذهاب." },
  { word: "deadline", translation: "موعد نهائي", partOfSpeech: "noun", difficulty: "hard", example: "The deadline for the project is Friday.", exampleTranslation: "الموعد النهائي للمشروع هو الجمعة." },
  { word: "future", translation: "مستقبل", partOfSpeech: "noun", difficulty: "easy", example: "We plan for a bright future.", exampleTranslation: "نخطّط لمستقبل مشرق." },
  { word: "dawn", translation: "فجر", partOfSpeech: "noun", difficulty: "medium", example: "The birds sing at dawn.", exampleTranslation: "تغرّد الطيور عند الفجر." },
  { word: "dusk", translation: "غسق", partOfSpeech: "noun", difficulty: "hard", example: "The lamps glow at dusk.", exampleTranslation: "تتوهّج المصابيح عند الغسق." },
  { word: "twilight", translation: "شفق", partOfSpeech: "noun", difficulty: "hard", example: "The sky turned pink in the twilight.", exampleTranslation: "تحوّلت السماء إلى وردية في الشفق." },
  { word: "midnight", translation: "منتصف الليل", partOfSpeech: "noun", difficulty: "medium", example: "The clock struck midnight.", exampleTranslation: "دقّت الساعة منتصف الليل." },
  { word: "instant", translation: "لحظة/فوري", partOfSpeech: "noun", difficulty: "hard", example: "In an instant the light went out.", exampleTranslation: "في لحظة انطفأ الضوء." },
  { word: "elegant", translation: "أنيق", partOfSpeech: "adjective", difficulty: "hard", example: "She wore an elegant dress.", exampleTranslation: "ارتدت فستاناً أنيقاً." },
  { word: "graceful", translation: "رشيق", partOfSpeech: "adjective", difficulty: "hard", example: "The dancer was slow and graceful.", exampleTranslation: "كانت الراقصة بطيئة ورشيقة." },
  { word: "gloomy", translation: "كئيب", partOfSpeech: "adjective", difficulty: "hard", example: "The gloomy sky warned of rain.", exampleTranslation: "أنذرت السماء الكئيبة بالمطر." },
  { word: "keen", translation: "حريص/شغوف", partOfSpeech: "adjective", difficulty: "hard", example: "He is keen to learn new skills.", exampleTranslation: "هو حريص على تعلّم مهارات جديدة." },
  { word: "fair", translation: "عادل", partOfSpeech: "adjective", difficulty: "easy", example: "The teacher gave a fair grade.", exampleTranslation: "أعطى المعلّم درجة عادلة." },
  { word: "helpful", translation: "مفيد/متعاون", partOfSpeech: "adjective", difficulty: "easy", example: "The guide gave helpful advice.", exampleTranslation: "قدّم المرشد نصيحة مفيدة." },
  { word: "skill", translation: "مهارة", partOfSpeech: "noun", difficulty: "medium", example: "Swimming is a useful skill.", exampleTranslation: "السباحة مهارة مفيدة." },
  { word: "idea", translation: "فكرة", partOfSpeech: "noun", difficulty: "easy", example: "That is a wonderful idea.", exampleTranslation: "تلك فكرة رائعة." },
  { word: "thought", translation: "فكر/خاطرة", partOfSpeech: "noun", difficulty: "medium", example: "A kind thought made her smile.", exampleTranslation: "جعلتها خاطرة لطيفة تبتسم." },
  { word: "mind", translation: "عقل", partOfSpeech: "noun", difficulty: "easy", example: "Keep an open mind when you learn.", exampleTranslation: "أبقِ عقلك متفتّحاً عندما تتعلّم." },
  { word: "motivation", translation: "دافع/تحفيز", partOfSpeech: "noun", difficulty: "hard", example: "Her motivation kept the team going.", exampleTranslation: "أبقى حماسها الفريق مستمرّاً." },
  { word: "interest", translation: "اهتمام", partOfSpeech: "noun", difficulty: "medium", example: "She has an interest in space.", exampleTranslation: "لديها اهتمام بالفضاء." },
  { word: "liberty", translation: "حرية", partOfSpeech: "noun", difficulty: "hard", example: "The statue is a symbol of liberty.", exampleTranslation: "التمثال رمز للحرية." },
  { word: "mercy", translation: "رحمة", partOfSpeech: "noun", difficulty: "hard", example: "The king showed mercy to the prisoner.", exampleTranslation: "أظهر الملك الرحمة للسجين." },
  { word: "comfort", translation: "راحة", partOfSpeech: "noun", difficulty: "medium", example: "The warm blanket gave him comfort.", exampleTranslation: "منحته البطانية الدافئة راحة." },
  { word: "security", translation: "أمن", partOfSpeech: "noun", difficulty: "hard", example: "Locks add a sense of security.", exampleTranslation: "تضيف الأقفال شعوراً بالأمن." },
  { word: "satisfaction", translation: "رضا", partOfSpeech: "noun", difficulty: "hard", example: "Finishing the work brought satisfaction.", exampleTranslation: "جلب إنهاء العمل شعوراً بالرضا." },
  { word: "fate", translation: "قَدَر/مصير", partOfSpeech: "noun", difficulty: "hard", example: "The hero faced an unknown fate.", exampleTranslation: "واجه البطل مصيراً مجهولاً." },
  { word: "notion", translation: "فكرة/تصوّر", partOfSpeech: "noun", difficulty: "hard", example: "He had no notion of the time.", exampleTranslation: "لم يكن لديه أي تصوّر عن الوقت." },
  { word: "dedication", translation: "تفانٍ", partOfSpeech: "noun", difficulty: "hard", example: "Her dedication earned the team's respect.", exampleTranslation: "كسب تفانيها احترام الفريق." },
  { word: "perception", translation: "إدراك", partOfSpeech: "noun", difficulty: "hard", example: "Color changes our perception of size.", exampleTranslation: "يغيّر اللون إدراكنا للحجم." },
  { word: "certainty", translation: "يقين", partOfSpeech: "noun", difficulty: "hard", example: "No one can say the future with certainty.", exampleTranslation: "لا أحد يستطيع قول المستقبل بيقين." },
  { word: "glory", translation: "مجد", partOfSpeech: "noun", difficulty: "hard", example: "The team enjoyed the glory of winning.", exampleTranslation: "استمتع الفريق بمجد الفوز." },
  { word: "triumph", translation: "انتصار", partOfSpeech: "noun", difficulty: "hard", example: "The race ended in a great triumph.", exampleTranslation: "انتهى السباق بانتصار عظيم." }
];
