/** Grade 6 chunk A — academic thinking verbs & language-arts vocabulary. */
export const GRADE6_CHUNK_A = [
  { word: "assess", translation: "يقيّم", partOfSpeech: "verb", difficulty: "medium", example: "Teachers assess our progress each term.", exampleTranslation: "يقيّم المعلمون تقدّمنا كل فصل دراسي." },
  { word: "evaluate", translation: "يقيّم/يثمّن", partOfSpeech: "verb", difficulty: "medium", example: "We evaluate each idea before choosing one.", exampleTranslation: "نقيّم كل فكرة قبل اختيار واحدة." },
  { word: "demonstrate", translation: "يبيّن", partOfSpeech: "verb", difficulty: "medium", example: "She will demonstrate the experiment to the class.", exampleTranslation: "ستبيّن التجربة أمام الصف." },
  { word: "illustrate", translation: "يوضّح بالرسم", partOfSpeech: "verb", difficulty: "medium", example: "The artist illustrates each story in the book.", exampleTranslation: "يوضّح الفنان كل قصة في الكتاب بالرسم." },
  { word: "summarize", translation: "يلخّص", partOfSpeech: "verb", difficulty: "medium", example: "Please summarize the chapter in three sentences.", exampleTranslation: "من فضلك لخّص الفصل في ثلاث جمل." },
  { word: "conclude", translation: "يستنتج", partOfSpeech: "verb", difficulty: "medium", example: "From the results we conclude that plants need light.", exampleTranslation: "من النتائج نستنتج أن النباتات تحتاج إلى الضوء." },
  { word: "predict", translation: "يتنبّأ", partOfSpeech: "verb", difficulty: "medium", example: "Can you predict the end of the story?", exampleTranslation: "هل يمكنك أن تتنبّأ بنهاية القصة؟" },
  { word: "classify", translation: "يصنّف", partOfSpeech: "verb", difficulty: "medium", example: "We classify animals into groups by their features.", exampleTranslation: "نصنّف الحيوانات إلى مجموعات حسب صفاتها." },
  { word: "compare", translation: "يقارن", partOfSpeech: "verb", difficulty: "medium", example: "Let us compare the two methods carefully.", exampleTranslation: "لنقارن بين الطريقتين بعناية." },
  { word: "contrast", translation: "يقابل/يباين", partOfSpeech: "verb", difficulty: "medium", example: "The essay contrasts city life with village life.", exampleTranslation: "يقابل المقال بين حياة المدينة وحياة القرية." },
  { word: "interpret", translation: "يفسّر", partOfSpeech: "verb", difficulty: "medium", example: "Historians interpret old letters and maps.", exampleTranslation: "يفسّر المؤرخون الرسائل والخرائط القديمة." },
  { word: "organize", translation: "ينظّم", partOfSpeech: "verb", difficulty: "medium", example: "Organize your notes before the exam.", exampleTranslation: "نظّم ملاحظاتك قبل الامتحان." },
  { word: "identify", translation: "يحدّد هوية", partOfSpeech: "verb", difficulty: "medium", example: "Identify the main idea of each paragraph.", exampleTranslation: "حدّد الفكرة الرئيسية لكل فقرة." },
  { word: "describe", translation: "يصف", partOfSpeech: "verb", difficulty: "easy", example: "Describe your favorite place in detail.", exampleTranslation: "صف مكانك المفضّل بالتفصيل." },
  { word: "explain", translation: "يشرح", partOfSpeech: "verb", difficulty: "easy", example: "The teacher will explain the rule again.", exampleTranslation: "سيشرح المعلّم القاعدة مرة أخرى." },
  { word: "calculate", translation: "يحسب", partOfSpeech: "verb", difficulty: "medium", example: "Calculate the total cost of the books.", exampleTranslation: "احسب التكلفة الإجمالية للكتب." },
  { word: "estimate", translation: "يقدّر", partOfSpeech: "verb", difficulty: "medium", example: "Estimate how long the trip will take.", exampleTranslation: "قدّر كم سيستغرق وقت الرحلة." },
  { word: "measure", translation: "يقيس", partOfSpeech: "verb", difficulty: "easy", example: "We measure the length with a ruler.", exampleTranslation: "نقيس الطول بالمسطرة." },
  { word: "examine", translation: "يفحص", partOfSpeech: "verb", difficulty: "medium", example: "The doctor will examine the patient soon.", exampleTranslation: "سيفحص الطبيب المريض قريباً." },
  { word: "explore", translation: "يستكشف", partOfSpeech: "verb", difficulty: "medium", example: "Explorers explore unknown lands.", exampleTranslation: "يستكشف المستكشفون أراضيَ مجهولة." },
  { word: "discover", translation: "يكتشف", partOfSpeech: "verb", difficulty: "easy", example: "Scientists discover new facts every year.", exampleTranslation: "يكتشف العلماء حقائق جديدة كل عام." },
  { word: "propose", translation: "يقترح", partOfSpeech: "verb", difficulty: "medium", example: "I propose a new plan for the trip.", exampleTranslation: "أقترح خطة جديدة للرحلة." },
  { word: "suggest", translation: "يقترح", partOfSpeech: "verb", difficulty: "easy", example: "She suggested a quiet place to read.", exampleTranslation: "اقترحت مكاناً هادئاً للقراءة." },
  { word: "recommend", translation: "يوصي", partOfSpeech: "verb", difficulty: "medium", example: "I recommend this book to every reader.", exampleTranslation: "أوصي بهذا الكتاب لكل قارئ." },
  { word: "justify", translation: "يبرّر", partOfSpeech: "verb", difficulty: "hard", example: "You must justify your answer with reasons.", exampleTranslation: "عليك أن تبرّر إجابتك بأسباب." },
  { word: "argue", translation: "يجادل", partOfSpeech: "verb", difficulty: "medium", example: "The two students argue about the best plan.", exampleTranslation: "يجادل الطالبان حول أفضل خطة." },
  { word: "persuade", translation: "يقنع", partOfSpeech: "verb", difficulty: "hard", example: "He tried to persuade us to join the club.", exampleTranslation: "حاول أن يقنعنا بالانضمام إلى النادي." },
  { word: "convince", translation: "يُقنع", partOfSpeech: "verb", difficulty: "medium", example: "Her speech convinced the whole class.", exampleTranslation: "أقنع خطابها الصف بأكمله." },
  { word: "emphasize", translation: "يؤكّد", partOfSpeech: "verb", difficulty: "hard", example: "The coach emphasized the value of teamwork.", exampleTranslation: "أكّد المدرّب على قيمة العمل الجماعي." },
  { word: "indicate", translation: "يشير إلى", partOfSpeech: "verb", difficulty: "medium", example: "The arrow indicates the right direction.", exampleTranslation: "يشير السهم إلى الاتجاه الصحيح." },
  { word: "reveal", translation: "يكشف", partOfSpeech: "verb", difficulty: "medium", example: "The final page reveals the secret.", exampleTranslation: "تكشف الصفحة الأخيرة السر." },
  { word: "determine", translation: "يقرّر/يحدّد", partOfSpeech: "verb", difficulty: "hard", example: "The judges determine the winner of the contest.", exampleTranslation: "يحدّد الحكّام الفائز في المسابقة." },
  { word: "distinguish", translation: "يميّز", partOfSpeech: "verb", difficulty: "hard", example: "We can distinguish facts from opinions.", exampleTranslation: "نستطيع أن نميّز الحقائق عن الآراء." },
  { word: "recognize", translation: "يتعرّف على", partOfSpeech: "verb", difficulty: "medium", example: "I recognize this song from the show.", exampleTranslation: "أتعرّف على هذه الأغنية من العرض." },
  { word: "acknowledge", translation: "يعترف بـ", partOfSpeech: "verb", difficulty: "hard", example: "She acknowledged her mistake politely.", exampleTranslation: "اعترفت بخطئها بأدب." },
  { word: "assume", translation: "يفترض", partOfSpeech: "verb", difficulty: "hard", example: "Do not assume the answer without checking.", exampleTranslation: "لا تفترض الإجابة دون تحقّق." },
  { word: "imply", translation: "يلمّح", partOfSpeech: "verb", difficulty: "hard", example: "His tone seemed to imply a warning.", exampleTranslation: "بدا أن نبرته تلمّح إلى تحذير." },
  { word: "infer", translation: "يستدلّ", partOfSpeech: "verb", difficulty: "hard", example: "Readers infer the mood from the words.", exampleTranslation: "يستدلّ القرّاء على الحالة المزاجية من الكلمات." },
  { word: "obtain", translation: "يحصل على", partOfSpeech: "verb", difficulty: "medium", example: "You can obtain a card from the office.", exampleTranslation: "يمكنك الحصول على بطاقة من المكتب." },
  { word: "acquire", translation: "يكتسب", partOfSpeech: "verb", difficulty: "hard", example: "Children acquire language very quickly.", exampleTranslation: "يكتسب الأطفال اللغة بسرعة كبيرة." },
  { word: "achieve", translation: "يحقّق", partOfSpeech: "verb", difficulty: "medium", example: "Hard work helps you achieve your goals.", exampleTranslation: "يساعدك العمل الجاد على تحقيق أهدافك." },
  { word: "accomplish", translation: "ينجز", partOfSpeech: "verb", difficulty: "medium", example: "We accomplished the task before noon.", exampleTranslation: "أنجزنا المهمة قبل الظهر." },
  { word: "perform", translation: "يؤدّي", partOfSpeech: "verb", difficulty: "medium", example: "The band will perform on Friday night.", exampleTranslation: "ستؤدّي الفرقة عرضها مساء الجمعة." },
  { word: "implement", translation: "ينفّذ", partOfSpeech: "verb", difficulty: "hard", example: "The school will implement a new schedule.", exampleTranslation: "ستنفّذ المدرسة جدولاً جديداً." },
  { word: "apply", translation: "يطبّق", partOfSpeech: "verb", difficulty: "easy", example: "Apply the rule to solve the problem.", exampleTranslation: "طبّق القاعدة لحل المسألة." },
  { word: "utilize", translation: "يستخدم", partOfSpeech: "verb", difficulty: "hard", example: "We utilize maps to plan our journey.", exampleTranslation: "نستخدم الخرائط لتخطيط رحلتنا." },
  { word: "operate", translation: "يشغّل", partOfSpeech: "verb", difficulty: "medium", example: "She knows how to operate the machine.", exampleTranslation: "تعرف كيف تشغّل الآلة." },
  { word: "contribute", translation: "يساهم", partOfSpeech: "verb", difficulty: "hard", example: "Everyone can contribute to the project.", exampleTranslation: "يمكن للجميع أن يساهموا في المشروع." },
  { word: "engage", translation: "ينخرط/يشغل", partOfSpeech: "verb", difficulty: "hard", example: "Good games engage the whole class.", exampleTranslation: "تشغل الألعاب الجيدة الصف بأكمله." },
  { word: "involve", translation: "يتضمّن", partOfSpeech: "verb", difficulty: "medium", example: "The plan involves three simple steps.", exampleTranslation: "تتضمّن الخطة ثلاث خطوات بسيطة." },
  { word: "include", translation: "يشمل", partOfSpeech: "verb", difficulty: "easy", example: "The price includes the school trip.", exampleTranslation: "يشمل السعر الرحلة المدرسية." },
  { word: "exclude", translation: "يستبعد", partOfSpeech: "verb", difficulty: "hard", example: "We should not exclude anyone from the game.", exampleTranslation: "لا ينبغي أن نستبعد أحداً من اللعبة." },
  { word: "combine", translation: "يدمج", partOfSpeech: "verb", difficulty: "medium", example: "Combine the colors to make green.", exampleTranslation: "ادمج الألوان لصنع اللون الأخضر." },
  { word: "integrate", translation: "يدمج/يوحّد", partOfSpeech: "verb", difficulty: "hard", example: "The teacher integrates art into science.", exampleTranslation: "يدمج المعلّم الفن في العلوم." },
  { word: "separate", translation: "يفصل", partOfSpeech: "verb", difficulty: "medium", example: "Separate the trash for recycling.", exampleTranslation: "افصل النفايات لإعادة التدوير." },
  { word: "distribute", translation: "يوزّع", partOfSpeech: "verb", difficulty: "hard", example: "Please distribute the papers to each row.", exampleTranslation: "من فضلك وزّع الأوراق على كل صف." },
  { word: "assign", translation: "يكلّف", partOfSpeech: "verb", difficulty: "medium", example: "The teacher will assign homework today.", exampleTranslation: "سيكلّف المعلّم بالواجب اليوم." },
  { word: "select", translation: "يختار", partOfSpeech: "verb", difficulty: "easy", example: "Select the best title for your story.", exampleTranslation: "اختر أفضل عنوان لقصتك." },
  { word: "decide", translation: "يقرّر", partOfSpeech: "verb", difficulty: "easy", example: "We must decide where to go.", exampleTranslation: "علينا أن نقرّر إلى أين نذهب." },
  { word: "resolve", translation: "يحلّ/يعزم", partOfSpeech: "verb", difficulty: "hard", example: "They worked together to resolve the problem.", exampleTranslation: "عملوا معاً لحلّ المشكلة." },
  { word: "negotiate", translation: "يتفاوض", partOfSpeech: "verb", difficulty: "hard", example: "The leaders negotiate a fair deal.", exampleTranslation: "يتفاوض القادة على اتفاق عادل." },
  { word: "clarify", translation: "يوضّح", partOfSpeech: "verb", difficulty: "hard", example: "Could you clarify the second question?", exampleTranslation: "هل يمكنك توضيح السؤال الثاني؟" },
  { word: "modify", translation: "يعدّل", partOfSpeech: "verb", difficulty: "hard", example: "Modify your plan to save time.", exampleTranslation: "عدّل خطتك لتوفير الوقت." },
  { word: "adapt", translation: "يتكيّف", partOfSpeech: "verb", difficulty: "medium", example: "Animals adapt to their surroundings.", exampleTranslation: "تتكيّف الحيوانات مع محيطها." },
  { word: "revise", translation: "يراجع/ينقّح", partOfSpeech: "verb", difficulty: "medium", example: "Revise your essay before you submit it.", exampleTranslation: "راجع مقالك قبل أن تسلّمه." },
  { word: "edit", translation: "يحرّر", partOfSpeech: "verb", difficulty: "medium", example: "We edit the report to fix the errors.", exampleTranslation: "نحرّر التقرير لتصحيح الأخطاء." },
  { word: "compose", translation: "يؤلّف", partOfSpeech: "verb", difficulty: "hard", example: "She likes to compose short poems.", exampleTranslation: "تحبّ أن تؤلّف قصائد قصيرة." },
  { word: "narrate", translation: "يروي", partOfSpeech: "verb", difficulty: "hard", example: "He will narrate the story to the children.", exampleTranslation: "سيروي القصة للأطفال." },
  { word: "cite", translation: "يستشهد بـ", partOfSpeech: "verb", difficulty: "hard", example: "Always cite the source of your facts.", exampleTranslation: "استشهد دائماً بمصدر معلوماتك." },
  { word: "paraphrase", translation: "يعيد الصياغة", partOfSpeech: "verb", difficulty: "hard", example: "Paraphrase the sentence in your own words.", exampleTranslation: "أعد صياغة الجملة بأسلوبك الخاص." },
  { word: "translate", translation: "يترجم", partOfSpeech: "verb", difficulty: "medium", example: "Can you translate this word into Arabic?", exampleTranslation: "هل يمكنك ترجمة هذه الكلمة إلى العربية؟" },
  { word: "memorize", translation: "يحفظ", partOfSpeech: "verb", difficulty: "medium", example: "Try to memorize the new vocabulary.", exampleTranslation: "حاول أن تحفظ المفردات الجديدة." },
  { word: "comprehend", translation: "يستوعب", partOfSpeech: "verb", difficulty: "hard", example: "Slow reading helps you comprehend the text.", exampleTranslation: "القراءة البطيئة تساعدك على استيعاب النص." },
  { word: "outline", translation: "مخطط/يخطّط", partOfSpeech: "noun", difficulty: "medium", example: "Write an outline before your report.", exampleTranslation: "اكتب مخططاً قبل تقريرك." },
  { word: "research", translation: "بحث", partOfSpeech: "noun", difficulty: "medium", example: "Her research took several weeks.", exampleTranslation: "استغرق بحثها عدة أسابيع." },
  { word: "paragraph", translation: "فقرة", partOfSpeech: "noun", difficulty: "easy", example: "Each paragraph has one main idea.", exampleTranslation: "لكل فقرة فكرة رئيسية واحدة." },
  { word: "sentence", translation: "جملة", partOfSpeech: "noun", difficulty: "easy", example: "A sentence begins with a capital letter.", exampleTranslation: "تبدأ الجملة بحرف كبير." },
  { word: "phrase", translation: "عبارة", partOfSpeech: "noun", difficulty: "medium", example: "A phrase is a small group of words.", exampleTranslation: "العبارة مجموعة صغيرة من الكلمات." },
  { word: "clause", translation: "جملة فرعية", partOfSpeech: "noun", difficulty: "hard", example: "This clause adds extra information.", exampleTranslation: "تضيف هذه الجملة الفرعية معلومات إضافية." },
  { word: "synonym", translation: "مرادف", partOfSpeech: "noun", difficulty: "medium", example: "Happy is a synonym for glad.", exampleTranslation: "كلمة سعيد مرادفة لكلمة مسرور." },
  { word: "antonym", translation: "ضدّ", partOfSpeech: "noun", difficulty: "medium", example: "Hot is the antonym of cold.", exampleTranslation: "حار ضدّ بارد." },
  { word: "prefix", translation: "بادئة", partOfSpeech: "noun", difficulty: "medium", example: "The prefix re means again.", exampleTranslation: "البادئة re تعني مرة أخرى." },
  { word: "suffix", translation: "لاحقة", partOfSpeech: "noun", difficulty: "medium", example: "Add the suffix ly to make an adverb.", exampleTranslation: "أضف اللاحقة ly لتكوين ظرف." },
  { word: "syllable", translation: "مقطع لفظي", partOfSpeech: "noun", difficulty: "medium", example: "The word water has two syllables.", exampleTranslation: "كلمة water تتكوّن من مقطعين لفظيين." },
  { word: "vocabulary", translation: "مفردات", partOfSpeech: "noun", difficulty: "medium", example: "Reading builds a strong vocabulary.", exampleTranslation: "تبني القراءة حصيلة قوية من المفردات." },
  { word: "grammar", translation: "قواعد", partOfSpeech: "noun", difficulty: "medium", example: "Good grammar makes writing clear.", exampleTranslation: "القواعد السليمة تجعل الكتابة واضحة." },
  { word: "punctuation", translation: "علامات الترقيم", partOfSpeech: "noun", difficulty: "hard", example: "Punctuation helps the reader pause.", exampleTranslation: "تساعد علامات الترقيم القارئ على التوقف." },
  { word: "narrative", translation: "سرد", partOfSpeech: "noun", difficulty: "hard", example: "Her narrative kept us interested.", exampleTranslation: "أبقانا سردها مهتمّين." },
  { word: "character", translation: "شخصية", partOfSpeech: "noun", difficulty: "easy", example: "The main character is very brave.", exampleTranslation: "الشخصية الرئيسية شجاعة جداً." },
  { word: "setting", translation: "مكان وزمان الأحداث", partOfSpeech: "noun", difficulty: "medium", example: "The setting of the story is a small village.", exampleTranslation: "تدور أحداث القصة في قرية صغيرة." },
  { word: "plot", translation: "حبكة", partOfSpeech: "noun", difficulty: "medium", example: "The plot of the movie was exciting.", exampleTranslation: "كانت حبكة الفيلم مثيرة." },
  { word: "theme", translation: "موضوع/فكرة", partOfSpeech: "noun", difficulty: "medium", example: "Friendship is the theme of the book.", exampleTranslation: "الصداقة هي موضوع الكتاب." },
  { word: "author", translation: "مؤلّف", partOfSpeech: "noun", difficulty: "easy", example: "The author signed copies of her novel.", exampleTranslation: "وقّعت المؤلّفة نسخاً من روايتها." },
  { word: "audience", translation: "جمهور", partOfSpeech: "noun", difficulty: "medium", example: "The audience clapped after the play.", exampleTranslation: "صفّق الجمهور بعد المسرحية." },
  { word: "fiction", translation: "خيال", partOfSpeech: "noun", difficulty: "medium", example: "This story is a work of fiction.", exampleTranslation: "هذه القصة عمل من نسج الخيال." },
  { word: "biography", translation: "سيرة ذاتية", partOfSpeech: "noun", difficulty: "hard", example: "I read a biography of a famous scientist.", exampleTranslation: "قرأت سيرة عالم مشهور." },
  { word: "metaphor", translation: "استعارة", partOfSpeech: "noun", difficulty: "hard", example: "The poem uses a metaphor for hope.", exampleTranslation: "تستخدم القصيدة استعارة للأمل." },
  { word: "simile", translation: "تشبيه", partOfSpeech: "noun", difficulty: "hard", example: "A simile compares two things using like.", exampleTranslation: "يقارن التشبيه بين شيئين باستخدام كأنّ." },
  { word: "summary", translation: "ملخّص", partOfSpeech: "noun", difficulty: "medium", example: "Write a short summary of the article.", exampleTranslation: "اكتب ملخّصاً قصيراً للمقال." },
  { word: "introduction", translation: "مقدّمة", partOfSpeech: "noun", difficulty: "medium", example: "The introduction explains the topic.", exampleTranslation: "تشرح المقدّمة الموضوع." },
  { word: "dialogue", translation: "حوار", partOfSpeech: "noun", difficulty: "medium", example: "The dialogue between them was funny.", exampleTranslation: "كان الحوار بينهما مضحكاً." },
  { word: "quotation", translation: "اقتباس", partOfSpeech: "noun", difficulty: "hard", example: "She began her speech with a famous quotation.", exampleTranslation: "بدأت خطابها باقتباس مشهور." },
  { word: "vowel", translation: "حرف علّة", partOfSpeech: "noun", difficulty: "medium", example: "The letter a is a vowel.", exampleTranslation: "الحرف a حرف علّة." },
  { word: "consonant", translation: "حرف ساكن", partOfSpeech: "noun", difficulty: "medium", example: "The letter b is a consonant.", exampleTranslation: "الحرف b حرف ساكن." },
  { word: "passage", translation: "مقطع نصّي", partOfSpeech: "noun", difficulty: "medium", example: "Read the passage and answer the questions.", exampleTranslation: "اقرأ المقطع وأجب عن الأسئلة." },
  { word: "context", translation: "سياق", partOfSpeech: "noun", difficulty: "hard", example: "Use the context to guess the meaning.", exampleTranslation: "استخدم السياق لتخمين المعنى." },
  { word: "definition", translation: "تعريف", partOfSpeech: "noun", difficulty: "medium", example: "Look up the definition in the dictionary.", exampleTranslation: "ابحث عن التعريف في القاموس." },
  { word: "glossary", translation: "مسرد", partOfSpeech: "noun", difficulty: "hard", example: "The glossary explains the hard words.", exampleTranslation: "يشرح المسرد الكلمات الصعبة." },
  { word: "index", translation: "فهرس", partOfSpeech: "noun", difficulty: "medium", example: "The index lists topics in order.", exampleTranslation: "يسرد الفهرس المواضيع بالترتيب." },
  { word: "caption", translation: "تعليق توضيحي", partOfSpeech: "noun", difficulty: "medium", example: "The caption describes the photo.", exampleTranslation: "يصف التعليق الصورة." },
  { word: "headline", translation: "عنوان رئيسي", partOfSpeech: "noun", difficulty: "medium", example: "The headline caught my attention.", exampleTranslation: "لفت العنوان الرئيسي انتباهي." },
  { word: "article", translation: "مقال", partOfSpeech: "noun", difficulty: "easy", example: "I read an article about the ocean.", exampleTranslation: "قرأت مقالاً عن المحيط." },
  { word: "essay", translation: "مقالة", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher gave us an essay to write.", exampleTranslation: "أعطانا معلّمنا مقالة لنكتبها." },
  { word: "novel", translation: "رواية", partOfSpeech: "noun", difficulty: "medium", example: "This novel has three hundred pages.", exampleTranslation: "تحتوي هذه الرواية على ثلاثمئة صفحة." },
  { word: "chapter", translation: "فصل", partOfSpeech: "noun", difficulty: "easy", example: "I finished the first chapter tonight.", exampleTranslation: "أنهيت الفصل الأول الليلة." },
  { word: "rhyme", translation: "قافية", partOfSpeech: "noun", difficulty: "medium", example: "The words cat and hat rhyme.", exampleTranslation: "كلمتا cat وhat تتّفقان في القافية." },
  { word: "rhythm", translation: "إيقاع", partOfSpeech: "noun", difficulty: "hard", example: "The poem has a steady rhythm.", exampleTranslation: "للقصيدة إيقاع ثابت." },
  { word: "stanza", translation: "مقطع شعري", partOfSpeech: "noun", difficulty: "hard", example: "Each stanza has four lines.", exampleTranslation: "كل مقطع شعري يتكوّن من أربعة أسطر." },
  { word: "descriptive", translation: "وصفي", partOfSpeech: "adjective", difficulty: "hard", example: "She wrote a descriptive paragraph about the sea.", exampleTranslation: "كتبت فقرة وصفية عن البحر." },
  { word: "persuasive", translation: "إقناعي", partOfSpeech: "adjective", difficulty: "hard", example: "A persuasive letter changed his mind.", exampleTranslation: "رسالة إقناعية غيّرت رأيه." },
  { word: "literal", translation: "حرفي", partOfSpeech: "adjective", difficulty: "hard", example: "The literal meaning is different from the joke.", exampleTranslation: "المعنى الحرفي يختلف عن النكتة." },
  { word: "figurative", translation: "مجازي", partOfSpeech: "adjective", difficulty: "hard", example: "Poets often use figurative language.", exampleTranslation: "كثيراً ما يستخدم الشعراء اللغة المجازية." },
  { word: "formal", translation: "رسمي", partOfSpeech: "adjective", difficulty: "medium", example: "A formal letter uses polite words.", exampleTranslation: "تستخدم الرسالة الرسمية كلمات مهذّبة." },
  { word: "informal", translation: "غير رسمي", partOfSpeech: "adjective", difficulty: "medium", example: "We use informal language with friends.", exampleTranslation: "نستخدم اللغة غير الرسمية مع الأصدقاء." },
  { word: "review", translation: "مراجعة", partOfSpeech: "noun", difficulty: "medium", example: "The review of the book was positive.", exampleTranslation: "كانت مراجعة الكتاب إيجابية." },
  { word: "draft", translation: "مسودّة", partOfSpeech: "noun", difficulty: "medium", example: "This is only the first draft of my story.", exampleTranslation: "هذه مجرد المسودّة الأولى لقصتي." },
  { word: "topic", translation: "موضوع", partOfSpeech: "noun", difficulty: "easy", example: "Choose a topic for your presentation.", exampleTranslation: "اختر موضوعاً لعرضك التقديمي." },
  { word: "purpose", translation: "غرض", partOfSpeech: "noun", difficulty: "medium", example: "The purpose of the text is to inform.", exampleTranslation: "غرض النص هو الإعلام." },
  { word: "evidence", translation: "دليل", partOfSpeech: "noun", difficulty: "hard", example: "Give evidence to support your opinion.", exampleTranslation: "قدّم دليلاً لدعم رأيك." },
  { word: "conclusion", translation: "خاتمة/استنتاج", partOfSpeech: "noun", difficulty: "medium", example: "The conclusion sums up the main points.", exampleTranslation: "تلخّص الخاتمة النقاط الرئيسية." },
  { word: "opinion", translation: "رأي", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared an opinion in class.", exampleTranslation: "شارك الجميع برأي في الصف." },
  { word: "detail", translation: "تفصيل", partOfSpeech: "noun", difficulty: "easy", example: "Add one more detail to your answer.", exampleTranslation: "أضف تفصيلاً آخر إلى إجابتك." },
  { word: "fluent", translation: "طليق/فصيح", partOfSpeech: "adjective", difficulty: "hard", example: "She is fluent in two languages.", exampleTranslation: "هي طليقة في لغتين." },
  { word: "accurate", translation: "دقيق", partOfSpeech: "adjective", difficulty: "medium", example: "Your answer must be accurate.", exampleTranslation: "يجب أن تكون إجابتك دقيقة." },
  { word: "relevant", translation: "ذو صلة", partOfSpeech: "adjective", difficulty: "hard", example: "Keep your notes relevant to the topic.", exampleTranslation: "اجعل ملاحظاتك ذات صلة بالموضوع." },
  { word: "concise", translation: "موجز", partOfSpeech: "adjective", difficulty: "hard", example: "A concise answer is short and clear.", exampleTranslation: "الإجابة الموجزة قصيرة وواضحة." },
  { word: "logical", translation: "منطقي", partOfSpeech: "adjective", difficulty: "hard", example: "Your argument should be logical.", exampleTranslation: "ينبغي أن تكون حجتك منطقية." },
  { word: "respond", translation: "يستجيب", partOfSpeech: "verb", difficulty: "medium", example: "Please respond to the email today.", exampleTranslation: "من فضلك استجب للبريد اليوم." },
  { word: "express", translation: "يعبّر", partOfSpeech: "verb", difficulty: "medium", example: "Art helps us express our feelings.", exampleTranslation: "يساعدنا الفن على التعبير عن مشاعرنا." },
  { word: "discuss", translation: "يناقش", partOfSpeech: "verb", difficulty: "medium", example: "We discuss the news every morning.", exampleTranslation: "نناقش الأخبار كل صباح." },
  { word: "debate", translation: "مناظرة", partOfSpeech: "noun", difficulty: "hard", example: "The class held a debate about sports.", exampleTranslation: "أجرى الصف مناظرة حول الرياضة." },
  { word: "respect", translation: "احترام", partOfSpeech: "noun", difficulty: "easy", example: "We show respect to our teachers.", exampleTranslation: "نُظهر الاحترام لمعلّمينا." },
  { word: "instruct", translation: "يُرشد", partOfSpeech: "verb", difficulty: "medium", example: "The guide will instruct the new students.", exampleTranslation: "سيُرشد المرشد الطلاب الجدد." },
  { word: "inform", translation: "يُعلم", partOfSpeech: "verb", difficulty: "medium", example: "The sign informs visitors of the rules.", exampleTranslation: "تُعلم اللافتة الزوار بالقواعد." },
  { word: "announce", translation: "يُعلن", partOfSpeech: "verb", difficulty: "medium", example: "They will announce the winners tomorrow.", exampleTranslation: "سيعلنون عن الفائزين غداً." },
  { word: "respondent", translation: "مجيب", partOfSpeech: "noun", difficulty: "hard", example: "Each respondent answered the survey.", exampleTranslation: "أجاب كل مجيب عن الاستبيان." },
  { word: "request", translation: "يطلب", partOfSpeech: "verb", difficulty: "medium", example: "You may request extra time politely.", exampleTranslation: "يمكنك أن تطلب وقتاً إضافياً بأدب." },
  { word: "confirm", translation: "يؤكّد", partOfSpeech: "verb", difficulty: "medium", example: "Please confirm your seat for the trip.", exampleTranslation: "من فضلك أكّد مقعدك للرحلة." },
  { word: "remind", translation: "يذكّر", partOfSpeech: "verb", difficulty: "easy", example: "Remind me to bring my book.", exampleTranslation: "ذكّرني بإحضار كتابي." },
  { word: "encourage", translation: "يشجّع", partOfSpeech: "verb", difficulty: "medium", example: "Good teachers encourage their students.", exampleTranslation: "يشجّع المعلّمون الجيدون طلابهم." },
  { word: "praise", translation: "يمدح", partOfSpeech: "verb", difficulty: "medium", example: "The judge praised her brave answer.", exampleTranslation: "مدح الحكَم إجابتها الشجاعة." },
  { word: "criticize", translation: "ينتقد", partOfSpeech: "verb", difficulty: "hard", example: "Try not to criticize without a reason.", exampleTranslation: "حاول ألا تنتقد دون سبب." },
  { word: "responsible", translation: "مسؤول", partOfSpeech: "adjective", difficulty: "medium", example: "A responsible student finishes the work.", exampleTranslation: "الطالب المسؤول يُنهي عمله." },
  { word: "creative", translation: "مبدع", partOfSpeech: "adjective", difficulty: "medium", example: "She had a creative idea for the poster.", exampleTranslation: "كانت لديها فكرة مبدعة للملصق." },
  { word: "curious", translation: "فضولي", partOfSpeech: "adjective", difficulty: "medium", example: "Curious students ask many questions.", exampleTranslation: "يطرح الطلاب الفضوليون أسئلة كثيرة." },
  { word: "confident", translation: "واثق", partOfSpeech: "adjective", difficulty: "medium", example: "Be confident when you give a speech.", exampleTranslation: "كن واثقاً عندما تلقي خطاباً." },
  { word: "elaborate", translation: "يُفصّل/يُسهب", partOfSpeech: "verb", difficulty: "hard", example: "Please elaborate on your main idea.", exampleTranslation: "من فضلك فصّل فكرتك الرئيسية." },
  { word: "coherent", translation: "متماسك/مترابط", partOfSpeech: "adjective", difficulty: "hard", example: "A coherent essay flows from start to end.", exampleTranslation: "المقال المترابط ينساب من البداية إلى النهاية." },
  { word: "comprehensive", translation: "شامل", partOfSpeech: "adjective", difficulty: "hard", example: "The report gave a comprehensive view.", exampleTranslation: "قدّم التقرير نظرة شاملة." },
  { word: "objective", translation: "موضوعي/هدف", partOfSpeech: "noun", difficulty: "hard", example: "Our objective is to finish on time.", exampleTranslation: "هدفنا أن ننتهي في الوقت المحدّد." }
];
