/** Grade 6 final batch A — daily-life vocabulary (210 cards). Auto-generated. */
export const GRADE6_FINAL_A = [
  { word: "gem", translation: "جوهرة", partOfSpeech: "noun", difficulty: "easy", example: "I saw a gem at the park today.", exampleTranslation: "رأيت جوهرة في الحديقة اليوم." },
  { word: "ink", translation: "حبر", partOfSpeech: "noun", difficulty: "easy", example: "We bought a ink at the store.", exampleTranslation: "اشترينا حبر من المتجر." },
  { word: "ivy", translation: "لبلاب", partOfSpeech: "noun", difficulty: "easy", example: "There is a ivy in our kitchen.", exampleTranslation: "يوجد لبلاب في مطبخنا." },
  { word: "oat", translation: "شوفان نباتة", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a oat.", exampleTranslation: "أراني صديقي شوفان نباتة." },
  { word: "paw", translation: "مخلب", partOfSpeech: "noun", difficulty: "easy", example: "We use a paw every day at home.", exampleTranslation: "نستخدم مخلب كل يوم في البيت." },
  { word: "rag", translation: "خرقة", partOfSpeech: "noun", difficulty: "easy", example: "I found a rag in my bag.", exampleTranslation: "وجدت خرقة في حقيبتي." },
  { word: "rye", translation: "الجاودار", partOfSpeech: "noun", difficulty: "easy", example: "The rye is on the table.", exampleTranslation: "الجاودار على الطاولة." },
  { word: "wax", translation: "الشمع", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small wax.", exampleTranslation: "أعطتني الشمع صغيراً." },
  { word: "wig", translation: "شعر مستعار", partOfSpeech: "noun", difficulty: "easy", example: "We packed a wig for the trip.", exampleTranslation: "حزمنا شعر مستعار للرحلة." },
  { word: "jam", translation: "مربى", partOfSpeech: "noun", difficulty: "easy", example: "I like this jam very much.", exampleTranslation: "أحب هذا مربى كثيراً." },
  { word: "jar", translation: "جرة", partOfSpeech: "noun", difficulty: "easy", example: "I saw a jar at the park today.", exampleTranslation: "رأيت جرة في الحديقة اليوم." },
  { word: "log", translation: "سجل", partOfSpeech: "noun", difficulty: "easy", example: "We bought a log at the store.", exampleTranslation: "اشترينا سجل من المتجر." },
  { word: "beet", translation: "بنجر", partOfSpeech: "noun", difficulty: "easy", example: "There is a beet in our kitchen.", exampleTranslation: "يوجد بنجر في مطبخنا." },
  { word: "cola", translation: "كولا", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a cola.", exampleTranslation: "أراني صديقي كولا." },
  { word: "cork", translation: "الفلين", partOfSpeech: "noun", difficulty: "easy", example: "We use a cork every day at home.", exampleTranslation: "نستخدم الفلين كل يوم في البيت." },
  { word: "crib", translation: "سرير", partOfSpeech: "noun", difficulty: "easy", example: "I found a crib in my bag.", exampleTranslation: "وجدت سرير في حقيبتي." },
  { word: "deck", translation: "ظهر السفينة", partOfSpeech: "noun", difficulty: "easy", example: "The deck is on the table.", exampleTranslation: "ظهر السفينة على الطاولة." },
  { word: "dirt", translation: "الأوساخ", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small dirt.", exampleTranslation: "أعطتني الأوساخ صغيراً." },
  { word: "dish", translation: "طبق", partOfSpeech: "noun", difficulty: "easy", example: "We packed a dish for the trip.", exampleTranslation: "حزمنا طبق للرحلة." },
  { word: "doll", translation: "لعبة", partOfSpeech: "noun", difficulty: "easy", example: "I like this doll very much.", exampleTranslation: "أحب هذا لعبة كثيراً." },
  { word: "dust", translation: "تراب", partOfSpeech: "noun", difficulty: "easy", example: "I saw a dust at the park today.", exampleTranslation: "رأيت تراب في الحديقة اليوم." },
  { word: "fist", translation: "قبضة", partOfSpeech: "noun", difficulty: "easy", example: "We bought a fist at the store.", exampleTranslation: "اشترينا قبضة من المتجر." },
  { word: "foam", translation: "رغوة", partOfSpeech: "noun", difficulty: "easy", example: "There is a foam in our kitchen.", exampleTranslation: "يوجد رغوة في مطبخنا." },
  { word: "gong", translation: "غونغ", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a gong.", exampleTranslation: "أراني صديقي غونغ." },
  { word: "gown", translation: "ثوب", partOfSpeech: "noun", difficulty: "easy", example: "We use a gown every day at home.", exampleTranslation: "نستخدم ثوب كل يوم في البيت." },
  { word: "herd", translation: "قطيع", partOfSpeech: "noun", difficulty: "easy", example: "I found a herd in my bag.", exampleTranslation: "وجدت قطيع في حقيبتي." },
  { word: "hood", translation: "كَبُّوت", partOfSpeech: "noun", difficulty: "easy", example: "The hood is on the table.", exampleTranslation: "كَبُّوت على الطاولة." },
  { word: "hook", translation: "خطاف", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small hook.", exampleTranslation: "أعطتني خطاف صغيراً." },
  { word: "hull", translation: "بدن", partOfSpeech: "noun", difficulty: "easy", example: "We packed a hull for the trip.", exampleTranslation: "حزمنا بدن للرحلة." },
  { word: "icon", translation: "رمز", partOfSpeech: "noun", difficulty: "easy", example: "I like this icon very much.", exampleTranslation: "أحب هذا رمز كثيراً." },
  { word: "knob", translation: "مقبض الباب", partOfSpeech: "noun", difficulty: "easy", example: "I saw a knob at the park today.", exampleTranslation: "رأيت مقبض الباب في الحديقة اليوم." },
  { word: "knot", translation: "عقدة", partOfSpeech: "noun", difficulty: "easy", example: "We bought a knot at the store.", exampleTranslation: "اشترينا عقدة من المتجر." },
  { word: "lard", translation: "شحم الخنزير", partOfSpeech: "noun", difficulty: "easy", example: "There is a lard in our kitchen.", exampleTranslation: "يوجد شحم الخنزير في مطبخنا." },
  { word: "lark", translation: "قبرة", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a lark.", exampleTranslation: "أراني صديقي قبرة." },
  { word: "lawn", translation: "العشب", partOfSpeech: "noun", difficulty: "easy", example: "We use a lawn every day at home.", exampleTranslation: "نستخدم العشب كل يوم في البيت." },
  { word: "leap", translation: "خطوة", partOfSpeech: "noun", difficulty: "easy", example: "I found a leap in my bag.", exampleTranslation: "وجدت خطوة في حقيبتي." },
  { word: "lily", translation: "زنبق", partOfSpeech: "noun", difficulty: "easy", example: "The lily is on the table.", exampleTranslation: "زنبق على الطاولة." },
  { word: "lure", translation: "إغراء", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small lure.", exampleTranslation: "أعطتني إغراء صغيراً." },
  { word: "maid", translation: "خادمة", partOfSpeech: "noun", difficulty: "easy", example: "We packed a maid for the trip.", exampleTranslation: "حزمنا خادمة للرحلة." },
  { word: "moat", translation: "خندق", partOfSpeech: "noun", difficulty: "easy", example: "I like this moat very much.", exampleTranslation: "أحب هذا خندق كثيراً." },
  { word: "mold", translation: "قالب", partOfSpeech: "noun", difficulty: "easy", example: "I saw a mold at the park today.", exampleTranslation: "رأيت قالب في الحديقة اليوم." },
  { word: "monk", translation: "راهب", partOfSpeech: "noun", difficulty: "easy", example: "We bought a monk at the store.", exampleTranslation: "اشترينا راهب من المتجر." },
  { word: "navy", translation: "البحرية", partOfSpeech: "noun", difficulty: "easy", example: "There is a navy in our kitchen.", exampleTranslation: "يوجد البحرية في مطبخنا." },
  { word: "pail", translation: "سطل", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a pail.", exampleTranslation: "أراني صديقي سطل." },
  { word: "pile", translation: "كومة", partOfSpeech: "noun", difficulty: "easy", example: "We use a pile every day at home.", exampleTranslation: "نستخدم كومة كل يوم في البيت." },
  { word: "puff", translation: "نفخة", partOfSpeech: "noun", difficulty: "easy", example: "I found a puff in my bag.", exampleTranslation: "وجدت نفخة في حقيبتي." },
  { word: "rack", translation: "رف", partOfSpeech: "noun", difficulty: "easy", example: "The rack is on the table.", exampleTranslation: "رف على الطاولة." },
  { word: "reed", translation: "ريد", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small reed.", exampleTranslation: "أعطتني ريد صغيراً." },
  { word: "reel", translation: "بكرة", partOfSpeech: "noun", difficulty: "easy", example: "We packed a reel for the trip.", exampleTranslation: "حزمنا بكرة للرحلة." },
  { word: "rink", translation: "حلبة التزلج", partOfSpeech: "noun", difficulty: "easy", example: "I like this rink very much.", exampleTranslation: "أحب هذا حلبة التزلج كثيراً." },
  { word: "ruby", translation: "روبي", partOfSpeech: "noun", difficulty: "easy", example: "I saw a ruby at the park today.", exampleTranslation: "رأيت روبي في الحديقة اليوم." },
  { word: "sack", translation: "كيس", partOfSpeech: "noun", difficulty: "easy", example: "We bought a sack at the store.", exampleTranslation: "اشترينا كيس من المتجر." },
  { word: "sash", translation: "وشاح", partOfSpeech: "noun", difficulty: "easy", example: "There is a sash in our kitchen.", exampleTranslation: "يوجد وشاح في مطبخنا." },
  { word: "seam", translation: "التماس", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a seam.", exampleTranslation: "أراني صديقي التماس." },
  { word: "sill", translation: "عتبة", partOfSpeech: "noun", difficulty: "easy", example: "We use a sill every day at home.", exampleTranslation: "نستخدم عتبة كل يوم في البيت." },
  { word: "sled", translation: "تزلج", partOfSpeech: "noun", difficulty: "easy", example: "I found a sled in my bag.", exampleTranslation: "وجدت تزلج في حقيبتي." },
  { word: "span", translation: "فترة", partOfSpeech: "noun", difficulty: "easy", example: "The span is on the table.", exampleTranslation: "فترة على الطاولة." },
  { word: "tart", translation: "تورتة", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small tart.", exampleTranslation: "أعطتني تورتة صغيراً." },
  { word: "wand", translation: "عصا", partOfSpeech: "noun", difficulty: "easy", example: "We packed a wand for the trip.", exampleTranslation: "حزمنا عصا للرحلة." },
  { word: "yarn", translation: "غزل", partOfSpeech: "noun", difficulty: "easy", example: "I like this yarn very much.", exampleTranslation: "أحب هذا غزل كثيراً." },
  { word: "hymn", translation: "ترنيمة", partOfSpeech: "noun", difficulty: "easy", example: "I saw a hymn at the park today.", exampleTranslation: "رأيت ترنيمة في الحديقة اليوم." },
  { word: "jazz", translation: "موسيقى الجاز", partOfSpeech: "noun", difficulty: "easy", example: "We bought a jazz at the store.", exampleTranslation: "اشترينا موسيقى الجاز من المتجر." },
  { word: "jeep", translation: "جيب", partOfSpeech: "noun", difficulty: "easy", example: "There is a jeep in our kitchen.", exampleTranslation: "يوجد جيب في مطبخنا." },
  { word: "tube", translation: "أنبوب", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a tube.", exampleTranslation: "أراني صديقي أنبوب." },
  { word: "rate", translation: "معدل", partOfSpeech: "noun", difficulty: "easy", example: "We use a rate every day at home.", exampleTranslation: "نستخدم معدل كل يوم في البيت." },
  { word: "form", translation: "استمارة", partOfSpeech: "noun", difficulty: "easy", example: "I found a form in my bag.", exampleTranslation: "وجدت استمارة في حقيبتي." },
  { word: "view", translation: "منظر", partOfSpeech: "noun", difficulty: "easy", example: "The view is on the table.", exampleTranslation: "منظر على الطاولة." },
  { word: "badge", translation: "شارة", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small badge.", exampleTranslation: "أعطتني شارة صغيراً." },
  { word: "booth", translation: "كشك", partOfSpeech: "noun", difficulty: "easy", example: "We packed a booth for the trip.", exampleTranslation: "حزمنا كشك للرحلة." },
  { word: "brand", translation: "ماركة", partOfSpeech: "noun", difficulty: "easy", example: "I like this brand very much.", exampleTranslation: "أحب هذا ماركة كثيراً." },
  { word: "brass", translation: "النحاس", partOfSpeech: "noun", difficulty: "easy", example: "I saw a brass at the park today.", exampleTranslation: "رأيت النحاس في الحديقة اليوم." },
  { word: "chili", translation: "الفلفل الحار", partOfSpeech: "noun", difficulty: "easy", example: "We bought a chili at the store.", exampleTranslation: "اشترينا الفلفل الحار من المتجر." },
  { word: "crate", translation: "قفص", partOfSpeech: "verb", difficulty: "easy", example: "Please crate before dinner.", exampleTranslation: "من فضلك قفص قبل العشاء." },
  { word: "creek", translation: "الخور", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a creek.", exampleTranslation: "أراني صديقي الخور." },
  { word: "crumb", translation: "كسرة خبز", partOfSpeech: "noun", difficulty: "easy", example: "We use a crumb every day at home.", exampleTranslation: "نستخدم كسرة خبز كل يوم في البيت." },
  { word: "daisy", translation: "ديزي", partOfSpeech: "noun", difficulty: "easy", example: "I found a daisy in my bag.", exampleTranslation: "وجدت ديزي في حقيبتي." },
  { word: "diary", translation: "مذكرة", partOfSpeech: "noun", difficulty: "easy", example: "The diary is on the table.", exampleTranslation: "مذكرة على الطاولة." },
  { word: "diner", translation: "العشاء", partOfSpeech: "verb", difficulty: "easy", example: "Do you diner at home?", exampleTranslation: "هل العشاء في البيت؟" },
  { word: "fryer", translation: "المقلاة", partOfSpeech: "verb", difficulty: "easy", example: "He fryer before he sleeps.", exampleTranslation: "هو يالمقلاة قبل أن ينام." },
  { word: "ghost", translation: "شبح", partOfSpeech: "noun", difficulty: "easy", example: "I like this ghost very much.", exampleTranslation: "أحب هذا شبح كثيراً." },
  { word: "grave", translation: "خطير", partOfSpeech: "noun", difficulty: "easy", example: "I saw a grave at the park today.", exampleTranslation: "رأيت خطير في الحديقة اليوم." },
  { word: "gravy", translation: "المرق", partOfSpeech: "noun", difficulty: "easy", example: "We bought a gravy at the store.", exampleTranslation: "اشترينا المرق من المتجر." },
  { word: "grill", translation: "شواء", partOfSpeech: "noun", difficulty: "easy", example: "There is a grill in our kitchen.", exampleTranslation: "يوجد شواء في مطبخنا." },
  { word: "hatch", translation: "يفقس", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a hatch.", exampleTranslation: "أراني صديقي يفقس." },
  { word: "hedge", translation: "التحوط", partOfSpeech: "noun", difficulty: "easy", example: "We use a hedge every day at home.", exampleTranslation: "نستخدم التحوط كل يوم في البيت." },
  { word: "hinge", translation: "المفصلي", partOfSpeech: "noun", difficulty: "easy", example: "I found a hinge in my bag.", exampleTranslation: "وجدت المفصلي في حقيبتي." },
  { word: "hover", translation: "تحوم", partOfSpeech: "verb", difficulty: "easy", example: "She will hover later today.", exampleTranslation: "ستتحوم لاحقاً اليوم." },
  { word: "igloo", translation: "كوخ الإسكيمو", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small igloo.", exampleTranslation: "أعطتني كوخ الإسكيمو صغيراً." },
  { word: "inlet", translation: "مدخل", partOfSpeech: "noun", difficulty: "easy", example: "We packed a inlet for the trip.", exampleTranslation: "حزمنا مدخل للرحلة." },
  { word: "intro", translation: "مقدمة", partOfSpeech: "noun", difficulty: "easy", example: "I like this intro very much.", exampleTranslation: "أحب هذا مقدمة كثيراً." },
  { word: "jelly", translation: "هلام", partOfSpeech: "adverb", difficulty: "easy", example: "She spoke jelly to the class.", exampleTranslation: "تحدثت هلام إلى الصف." },
  { word: "jewel", translation: "جوهرة", partOfSpeech: "noun", difficulty: "easy", example: "We bought a jewel at the store.", exampleTranslation: "اشترينا جوهرة من المتجر." },
  { word: "khaki", translation: "الكاكي", partOfSpeech: "noun", difficulty: "easy", example: "There is a khaki in our kitchen.", exampleTranslation: "يوجد الكاكي في مطبخنا." },
  { word: "kneel", translation: "يركع", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a kneel.", exampleTranslation: "أراني صديقي يركع." },
  { word: "latch", translation: "مزلاج", partOfSpeech: "noun", difficulty: "easy", example: "We use a latch every day at home.", exampleTranslation: "نستخدم مزلاج كل يوم في البيت." },
  { word: "layer", translation: "طبقة", partOfSpeech: "verb", difficulty: "easy", example: "We layer together as a family.", exampleTranslation: "نطبقة معاً كعائلة." },
  { word: "lobby", translation: "ردهة", partOfSpeech: "noun", difficulty: "easy", example: "The lobby is on the table.", exampleTranslation: "ردهة على الطاولة." },
  { word: "lodge", translation: "لودج", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small lodge.", exampleTranslation: "أعطتني لودج صغيراً." },
  { word: "mason", translation: "ماسون", partOfSpeech: "noun", difficulty: "easy", example: "We packed a mason for the trip.", exampleTranslation: "حزمنا ماسون للرحلة." },
  { word: "merry", translation: "مرح", partOfSpeech: "noun", difficulty: "easy", example: "I like this merry very much.", exampleTranslation: "أحب هذا مرح كثيراً." },
  { word: "mixer", translation: "خلاط", partOfSpeech: "verb", difficulty: "easy", example: "I mixer every morning.", exampleTranslation: "أخلاط كل صباح." },
  { word: "mound", translation: "تل", partOfSpeech: "noun", difficulty: "easy", example: "We bought a mound at the store.", exampleTranslation: "اشترينا تل من المتجر." },
  { word: "panel", translation: "لوحة", partOfSpeech: "noun", difficulty: "easy", example: "There is a panel in our kitchen.", exampleTranslation: "يوجد لوحة في مطبخنا." },
  { word: "patch", translation: "رقعة", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a patch.", exampleTranslation: "أراني صديقي رقعة." },
  { word: "pedal", translation: "دواسة", partOfSpeech: "noun", difficulty: "easy", example: "We use a pedal every day at home.", exampleTranslation: "نستخدم دواسة كل يوم في البيت." },
  { word: "pouch", translation: "كيس", partOfSpeech: "noun", difficulty: "easy", example: "I found a pouch in my bag.", exampleTranslation: "وجدت كيس في حقيبتي." },
  { word: "punch", translation: "لكمة", partOfSpeech: "noun", difficulty: "easy", example: "The punch is on the table.", exampleTranslation: "لكمة على الطاولة." },
  { word: "radar", translation: "رادار", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small radar.", exampleTranslation: "أعطتني رادار صغيراً." },
  { word: "razor", translation: "ماكينة حلاقة", partOfSpeech: "noun", difficulty: "easy", example: "We packed a razor for the trip.", exampleTranslation: "حزمنا ماكينة حلاقة للرحلة." },
  { word: "rifle", translation: "بندقية", partOfSpeech: "noun", difficulty: "easy", example: "I like this rifle very much.", exampleTranslation: "أحب هذا بندقية كثيراً." },
  { word: "royal", translation: "ملكي", partOfSpeech: "noun", difficulty: "easy", example: "I saw a royal at the park today.", exampleTranslation: "رأيت ملكي في الحديقة اليوم." },
  { word: "salon", translation: "صالون", partOfSpeech: "noun", difficulty: "easy", example: "We bought a salon at the store.", exampleTranslation: "اشترينا صالون من المتجر." },
  { word: "scent", translation: "رائحة", partOfSpeech: "noun", difficulty: "easy", example: "There is a scent in our kitchen.", exampleTranslation: "يوجد رائحة في مطبخنا." },
  { word: "scoop", translation: "مغرفة", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a scoop.", exampleTranslation: "أراني صديقي مغرفة." },
  { word: "shift", translation: "يحول", partOfSpeech: "noun", difficulty: "easy", example: "We use a shift every day at home.", exampleTranslation: "نستخدم يحول كل يوم في البيت." },
  { word: "slime", translation: "الوحل", partOfSpeech: "noun", difficulty: "easy", example: "I found a slime in my bag.", exampleTranslation: "وجدت الوحل في حقيبتي." },
  { word: "spade", translation: "الأشياء بأسمائها الحقيقية", partOfSpeech: "noun", difficulty: "easy", example: "The spade is on the table.", exampleTranslation: "الأشياء بأسمائها الحقيقية على الطاولة." },
  { word: "spark", translation: "شرارة", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small spark.", exampleTranslation: "أعطتني شرارة صغيراً." },
  { word: "speck", translation: "بقعة", partOfSpeech: "noun", difficulty: "easy", example: "We packed a speck for the trip.", exampleTranslation: "حزمنا بقعة للرحلة." },
  { word: "steam", translation: "بخار", partOfSpeech: "noun", difficulty: "easy", example: "I like this steam very much.", exampleTranslation: "أحب هذا بخار كثيراً." },
  { word: "sushi", translation: "سوشي", partOfSpeech: "noun", difficulty: "easy", example: "I saw a sushi at the park today.", exampleTranslation: "رأيت سوشي في الحديقة اليوم." },
  { word: "teddy", translation: "تيدي", partOfSpeech: "noun", difficulty: "easy", example: "We bought a teddy at the store.", exampleTranslation: "اشترينا تيدي من المتجر." },
  { word: "tulip", translation: "الخزامى", partOfSpeech: "noun", difficulty: "easy", example: "There is a tulip in our kitchen.", exampleTranslation: "يوجد الخزامى في مطبخنا." },
  { word: "union", translation: "الاتحاد", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a union.", exampleTranslation: "أراني صديقي الاتحاد." },
  { word: "penny", translation: "بنس واحد", partOfSpeech: "noun", difficulty: "easy", example: "We use a penny every day at home.", exampleTranslation: "نستخدم بنس واحد كل يوم في البيت." },
  { word: "scene", translation: "مشهد", partOfSpeech: "noun", difficulty: "easy", example: "I found a scene in my bag.", exampleTranslation: "وجدت مشهد في حقيبتي." },
  { word: "price", translation: "سعر", partOfSpeech: "noun", difficulty: "easy", example: "The price is on the table.", exampleTranslation: "سعر على الطاولة." },
  { word: "flame", translation: "لهب", partOfSpeech: "noun", difficulty: "easy", example: "She gave me a small flame.", exampleTranslation: "أعطتني لهب صغيراً." },
  { word: "group", translation: "مجموعة", partOfSpeech: "noun", difficulty: "easy", example: "We packed a group for the trip.", exampleTranslation: "حزمنا مجموعة للرحلة." },
  { word: "proof", translation: "دليل", partOfSpeech: "noun", difficulty: "easy", example: "I like this proof very much.", exampleTranslation: "أحب هذا دليل كثيراً." },
  { word: "sales", translation: "مبيعات", partOfSpeech: "noun", difficulty: "easy", example: "I saw a sales at the park today.", exampleTranslation: "رأيت مبيعات في الحديقة اليوم." },
  { word: "quake", translation: "زلزال", partOfSpeech: "noun", difficulty: "easy", example: "We bought a quake at the store.", exampleTranslation: "اشترينا زلزال من المتجر." },
  { word: "niche", translation: "المكانة", partOfSpeech: "noun", difficulty: "easy", example: "There is a niche in our kitchen.", exampleTranslation: "يوجد المكانة في مطبخنا." },
  { word: "altar", translation: "مذبح", partOfSpeech: "noun", difficulty: "easy", example: "My friend showed me a altar.", exampleTranslation: "أراني صديقي مذبح." },
  { word: "amber", translation: "العنبر", partOfSpeech: "verb", difficulty: "easy", example: "I like to amber on weekends.", exampleTranslation: "أحب أن العنبر في عطلة نهاية الأسبوع." },
  { word: "amigo", translation: "صديق", partOfSpeech: "noun", difficulty: "easy", example: "I found a amigo in my bag.", exampleTranslation: "وجدت صديق في حقيبتي." },
  { word: "anvil", translation: "سندان", partOfSpeech: "noun", difficulty: "easy", example: "The anvil is on the table.", exampleTranslation: "سندان على الطاولة." },
  { word: "awning", translation: "المظلة", partOfSpeech: "adjective", difficulty: "medium", example: "Our trip was awning.", exampleTranslation: "كانت رحلتنا المظلة." },
  { word: "barber", translation: "حلاق", partOfSpeech: "verb", difficulty: "medium", example: "He barber before he sleeps.", exampleTranslation: "هو يحلاق قبل أن ينام." },
  { word: "barrel", translation: "برميل", partOfSpeech: "noun", difficulty: "medium", example: "I like this barrel very much.", exampleTranslation: "أحب هذا برميل كثيراً." },
  { word: "basket", translation: "سلة", partOfSpeech: "noun", difficulty: "medium", example: "I saw a basket at the park today.", exampleTranslation: "رأيت سلة في الحديقة اليوم." },
  { word: "bonnet", translation: "غطاء محرك السيارة", partOfSpeech: "noun", difficulty: "medium", example: "We bought a bonnet at the store.", exampleTranslation: "اشترينا غطاء محرك السيارة من المتجر." },
  { word: "bunker", translation: "القبو", partOfSpeech: "verb", difficulty: "medium", example: "Please bunker before dinner.", exampleTranslation: "من فضلك القبو قبل العشاء." },
  { word: "circus", translation: "سيرك", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a circus.", exampleTranslation: "أراني صديقي سيرك." },
  { word: "cradle", translation: "مهد", partOfSpeech: "noun", difficulty: "medium", example: "We use a cradle every day at home.", exampleTranslation: "نستخدم مهد كل يوم في البيت." },
  { word: "fiddle", translation: "كمان", partOfSpeech: "noun", difficulty: "medium", example: "I found a fiddle in my bag.", exampleTranslation: "وجدت كمان في حقيبتي." },
  { word: "flavor", translation: "نكهة", partOfSpeech: "noun", difficulty: "medium", example: "The flavor is on the table.", exampleTranslation: "نكهة على الطاولة." },
  { word: "fondue", translation: "مخفوق بالجبن", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small fondue.", exampleTranslation: "أعطتني مخفوق بالجبن صغيراً." },
  { word: "fringe", translation: "هامش", partOfSpeech: "noun", difficulty: "medium", example: "We packed a fringe for the trip.", exampleTranslation: "حزمنا هامش للرحلة." },
  { word: "gazebo", translation: "شرفة المراقبة", partOfSpeech: "noun", difficulty: "medium", example: "I like this gazebo very much.", exampleTranslation: "أحب هذا شرفة المراقبة كثيراً." },
  { word: "gravel", translation: "الحصى", partOfSpeech: "noun", difficulty: "medium", example: "I saw a gravel at the park today.", exampleTranslation: "رأيت الحصى في الحديقة اليوم." },
  { word: "grocer", translation: "البقال", partOfSpeech: "verb", difficulty: "medium", example: "We grocer after school.", exampleTranslation: "نالبقال بعد المدرسة." },
  { word: "helper", translation: "المساعد", partOfSpeech: "verb", difficulty: "medium", example: "Please helper before dinner.", exampleTranslation: "من فضلك المساعد قبل العشاء." },
  { word: "hostel", translation: "نزل", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a hostel.", exampleTranslation: "أراني صديقي نزل." },
  { word: "hotdog", translation: "نقانق", partOfSpeech: "noun", difficulty: "medium", example: "We use a hotdog every day at home.", exampleTranslation: "نستخدم نقانق كل يوم في البيت." },
  { word: "huddle", translation: "تجمهر", partOfSpeech: "noun", difficulty: "medium", example: "I found a huddle in my bag.", exampleTranslation: "وجدت تجمهر في حقيبتي." },
  { word: "hunger", translation: "الجوع", partOfSpeech: "verb", difficulty: "medium", example: "She will hunger later today.", exampleTranslation: "ستالجوع لاحقاً اليوم." },
  { word: "hunter", translation: "صياد", partOfSpeech: "verb", difficulty: "medium", example: "Do you hunter at home?", exampleTranslation: "هل صياد في البيت؟" },
  { word: "hurdle", translation: "عقبة", partOfSpeech: "noun", difficulty: "medium", example: "We packed a hurdle for the trip.", exampleTranslation: "حزمنا عقبة للرحلة." },
  { word: "icicle", translation: "جليد", partOfSpeech: "noun", difficulty: "medium", example: "I like this icicle very much.", exampleTranslation: "أحب هذا جليد كثيراً." },
  { word: "impact", translation: "تأثير", partOfSpeech: "noun", difficulty: "medium", example: "I saw a impact at the park today.", exampleTranslation: "رأيت تأثير في الحديقة اليوم." },
  { word: "infant", translation: "رضيع", partOfSpeech: "noun", difficulty: "medium", example: "We bought a infant at the store.", exampleTranslation: "اشترينا رضيع من المتجر." },
  { word: "keeper", translation: "حارس", partOfSpeech: "verb", difficulty: "medium", example: "Please keeper before dinner.", exampleTranslation: "من فضلك حارس قبل العشاء." },
  { word: "laptop", translation: "كمبيوتر محمول", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a laptop.", exampleTranslation: "أراني صديقي كمبيوتر محمول." },
  { word: "litter", translation: "القمامة", partOfSpeech: "verb", difficulty: "medium", example: "I like to litter on weekends.", exampleTranslation: "أحب أن القمامة في عطلة نهاية الأسبوع." },
  { word: "locket", translation: "المدلاة", partOfSpeech: "noun", difficulty: "medium", example: "I found a locket in my bag.", exampleTranslation: "وجدت المدلاة في حقيبتي." },
  { word: "lotion", translation: "غسول", partOfSpeech: "noun", difficulty: "medium", example: "The lotion is on the table.", exampleTranslation: "غسول على الطاولة." },
  { word: "lounge", translation: "صالة", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small lounge.", exampleTranslation: "أعطتني صالة صغيراً." },
  { word: "lumber", translation: "الخشب", partOfSpeech: "verb", difficulty: "medium", example: "He lumber before he sleeps.", exampleTranslation: "هو يالخشب قبل أن ينام." },
  { word: "makeup", translation: "ماكياج", partOfSpeech: "noun", difficulty: "medium", example: "I like this makeup very much.", exampleTranslation: "أحب هذا ماكياج كثيراً." },
  { word: "margin", translation: "هامِش", partOfSpeech: "noun", difficulty: "medium", example: "I saw a margin at the park today.", exampleTranslation: "رأيت هامِش في الحديقة اليوم." },
  { word: "mitten", translation: "القفاز", partOfSpeech: "verb", difficulty: "medium", example: "We mitten after school.", exampleTranslation: "نالقفاز بعد المدرسة." },
  { word: "mutton", translation: "لحم الضأن", partOfSpeech: "noun", difficulty: "medium", example: "There is a mutton in our kitchen.", exampleTranslation: "يوجد لحم الضأن في مطبخنا." },
  { word: "needle", translation: "إبرة", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a needle.", exampleTranslation: "أراني صديقي إبرة." },
  { word: "nozzle", translation: "فوهة", partOfSpeech: "noun", difficulty: "medium", example: "We use a nozzle every day at home.", exampleTranslation: "نستخدم فوهة كل يوم في البيت." },
  { word: "omelet", translation: "عجة البيض", partOfSpeech: "noun", difficulty: "medium", example: "I found a omelet in my bag.", exampleTranslation: "وجدت عجة البيض في حقيبتي." },
  { word: "orchid", translation: "الأوركيد", partOfSpeech: "noun", difficulty: "medium", example: "The orchid is on the table.", exampleTranslation: "الأوركيد على الطاولة." },
  { word: "paddle", translation: "مجداف", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small paddle.", exampleTranslation: "أعطتني مجداف صغيراً." },
  { word: "peanut", translation: "الفول السوداني", partOfSpeech: "noun", difficulty: "medium", example: "We packed a peanut for the trip.", exampleTranslation: "حزمنا الفول السوداني للرحلة." },
  { word: "picnic", translation: "نزهه", partOfSpeech: "adjective", difficulty: "medium", example: "He seems picnic today.", exampleTranslation: "يبدو نزهه اليوم." },
  { word: "pirate", translation: "قرصان", partOfSpeech: "verb", difficulty: "medium", example: "I pirate every morning.", exampleTranslation: "أقرصان كل صباح." },
  { word: "poison", translation: "سم", partOfSpeech: "noun", difficulty: "medium", example: "We bought a poison at the store.", exampleTranslation: "اشترينا سم من المتجر." },
  { word: "powder", translation: "مسحوق", partOfSpeech: "verb", difficulty: "medium", example: "Please powder before dinner.", exampleTranslation: "من فضلك مسحوق قبل العشاء." },
  { word: "puppet", translation: "دمية", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a puppet.", exampleTranslation: "أراني صديقي دمية." },
  { word: "raisin", translation: "زبيب", partOfSpeech: "noun", difficulty: "medium", example: "We use a raisin every day at home.", exampleTranslation: "نستخدم زبيب كل يوم في البيت." },
  { word: "rapids", translation: "المنحدرات", partOfSpeech: "noun", difficulty: "medium", example: "I found a rapids in my bag.", exampleTranslation: "وجدت المنحدرات في حقيبتي." },
  { word: "reader", translation: "قارئ", partOfSpeech: "verb", difficulty: "medium", example: "She will reader later today.", exampleTranslation: "ستقارئ لاحقاً اليوم." },
  { word: "ripple", translation: "تموج", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small ripple.", exampleTranslation: "أعطتني تموج صغيراً." },
  { word: "rumble", translation: "ترعد", partOfSpeech: "noun", difficulty: "medium", example: "We packed a rumble for the trip.", exampleTranslation: "حزمنا ترعد للرحلة." },
  { word: "saddle", translation: "سرج", partOfSpeech: "noun", difficulty: "medium", example: "I like this saddle very much.", exampleTranslation: "أحب هذا سرج كثيراً." },
  { word: "safari", translation: "سفاري", partOfSpeech: "noun", difficulty: "medium", example: "I saw a safari at the park today.", exampleTranslation: "رأيت سفاري في الحديقة اليوم." },
  { word: "samosa", translation: "سمبوسة", partOfSpeech: "noun", difficulty: "medium", example: "We bought a samosa at the store.", exampleTranslation: "اشترينا سمبوسة من المتجر." },
  { word: "saucer", translation: "صحن", partOfSpeech: "verb", difficulty: "medium", example: "Please saucer before dinner.", exampleTranslation: "من فضلك صحن قبل العشاء." },
  { word: "series", translation: "مسلسل", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a series.", exampleTranslation: "أراني صديقي مسلسل." },
  { word: "smarty", translation: "ذكي", partOfSpeech: "noun", difficulty: "medium", example: "We use a smarty every day at home.", exampleTranslation: "نستخدم ذكي كل يوم في البيت." },
  { word: "socket", translation: "المقبس", partOfSpeech: "noun", difficulty: "medium", example: "I found a socket in my bag.", exampleTranslation: "وجدت المقبس في حقيبتي." },
  { word: "target", translation: "هدف", partOfSpeech: "noun", difficulty: "medium", example: "The target is on the table.", exampleTranslation: "هدف على الطاولة." },
  { word: "tattoo", translation: "وشم", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small tattoo.", exampleTranslation: "أعطتني وشم صغيراً." },
  { word: "tavern", translation: "حانة", partOfSpeech: "noun", difficulty: "medium", example: "We packed a tavern for the trip.", exampleTranslation: "حزمنا حانة للرحلة." },
  { word: "teapot", translation: "إبريق الشاي", partOfSpeech: "noun", difficulty: "medium", example: "I like this teapot very much.", exampleTranslation: "أحب هذا إبريق الشاي كثيراً." },
  { word: "tuxedo", translation: "سهرة", partOfSpeech: "noun", difficulty: "medium", example: "I saw a tuxedo at the park today.", exampleTranslation: "رأيت سهرة في الحديقة اليوم." },
  { word: "useful", translation: "مفيد", partOfSpeech: "adjective", difficulty: "medium", example: "My room looks useful today.", exampleTranslation: "غرفتي تبدو مفيد اليوم." },
  { word: "velvet", translation: "مخمل", partOfSpeech: "noun", difficulty: "medium", example: "There is a velvet in our kitchen.", exampleTranslation: "يوجد مخمل في مطبخنا." },
  { word: "vendor", translation: "بائع", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a vendor.", exampleTranslation: "أراني صديقي بائع." },
  { word: "walnut", translation: "الجوز", partOfSpeech: "noun", difficulty: "medium", example: "We use a walnut every day at home.", exampleTranslation: "نستخدم الجوز كل يوم في البيت." },
  { word: "wizard", translation: "معالج", partOfSpeech: "noun", difficulty: "medium", example: "I found a wizard in my bag.", exampleTranslation: "وجدت معالج في حقيبتي." },
  { word: "wreath", translation: "إكليل", partOfSpeech: "noun", difficulty: "medium", example: "The wreath is on the table.", exampleTranslation: "إكليل على الطاولة." },
  { word: "writer", translation: "الكاتب", partOfSpeech: "verb", difficulty: "medium", example: "Do you writer at home?", exampleTranslation: "هل الكاتب في البيت؟" },
  { word: "effect", translation: "تأثير", partOfSpeech: "noun", difficulty: "medium", example: "We packed a effect for the trip.", exampleTranslation: "حزمنا تأثير للرحلة." },
  { word: "markup", translation: "العلامات", partOfSpeech: "noun", difficulty: "medium", example: "I like this markup very much.", exampleTranslation: "أحب هذا العلامات كثيراً." },
];
