/** Grade 6 final batch B — daily-life vocabulary (210 cards). Auto-generated. */
export const GRADE6_FINAL_B = [
  { word: "mental", translation: "عقلي", partOfSpeech: "adjective", difficulty: "medium", example: "The soup tastes mental.", exampleTranslation: "الحساء طعمه عقلي." },
  { word: "source", translation: "مصدر", partOfSpeech: "noun", difficulty: "medium", example: "We bought a source at the store.", exampleTranslation: "اشترينا مصدر من المتجر." },
  { word: "scalar", translation: "العددية", partOfSpeech: "noun", difficulty: "medium", example: "There is a scalar in our kitchen.", exampleTranslation: "يوجد العددية في مطبخنا." },
  { word: "portal", translation: "منفذ", partOfSpeech: "adjective", difficulty: "medium", example: "The weather feels portal.", exampleTranslation: "الطقس يبدو منفذ." },
  { word: "reform", translation: "إصلاح", partOfSpeech: "noun", difficulty: "medium", example: "We use a reform every day at home.", exampleTranslation: "نستخدم إصلاح كل يوم في البيت." },
  { word: "pacing", translation: "سرعة", partOfSpeech: "adjective", difficulty: "medium", example: "This shirt is too pacing.", exampleTranslation: "هذا القميص سرعة جداً." },
  { word: "airman", translation: "طيار", partOfSpeech: "noun", difficulty: "medium", example: "The airman is on the table.", exampleTranslation: "طيار على الطاولة." },
  { word: "alcove", translation: "الكوة", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small alcove.", exampleTranslation: "أعطتني الكوة صغيراً." },
  { word: "amulet", translation: "تميمة", partOfSpeech: "noun", difficulty: "medium", example: "We packed a amulet for the trip.", exampleTranslation: "حزمنا تميمة للرحلة." },
  { word: "angler", translation: "الصياد", partOfSpeech: "verb", difficulty: "medium", example: "We angler when we have time.", exampleTranslation: "نالصياد عندما يكون لدينا وقت." },
  { word: "anorak", translation: "واق", partOfSpeech: "noun", difficulty: "medium", example: "I saw a anorak at the park today.", exampleTranslation: "رأيت واق في الحديقة اليوم." },
  { word: "antler", translation: "قرن الوعل", partOfSpeech: "verb", difficulty: "medium", example: "We antler after school.", exampleTranslation: "نقرن الوعل بعد المدرسة." },
  { word: "armpit", translation: "إبط", partOfSpeech: "noun", difficulty: "medium", example: "There is a armpit in our kitchen.", exampleTranslation: "يوجد إبط في مطبخنا." },
  { word: "aviary", translation: "القفص", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a aviary.", exampleTranslation: "أراني صديقي القفص." },
  { word: "baboon", translation: "قرد البابون", partOfSpeech: "noun", difficulty: "medium", example: "We use a baboon every day at home.", exampleTranslation: "نستخدم قرد البابون كل يوم في البيت." },
  { word: "bedroom", translation: "غرفة نوم", partOfSpeech: "noun", difficulty: "medium", example: "I found a bedroom in my bag.", exampleTranslation: "وجدت غرفة نوم في حقيبتي." },
  { word: "bouquet", translation: "باقة", partOfSpeech: "noun", difficulty: "medium", example: "The bouquet is on the table.", exampleTranslation: "باقة على الطاولة." },
  { word: "dessert", translation: "حَلوَى", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small dessert.", exampleTranslation: "أعطتني حَلوَى صغيراً." },
  { word: "diamond", translation: "الماس", partOfSpeech: "noun", difficulty: "medium", example: "We packed a diamond for the trip.", exampleTranslation: "حزمنا الماس للرحلة." },
  { word: "doorway", translation: "مدخل", partOfSpeech: "noun", difficulty: "medium", example: "I like this doorway very much.", exampleTranslation: "أحب هذا مدخل كثيراً." },
  { word: "dresser", translation: "مضمد", partOfSpeech: "verb", difficulty: "medium", example: "I dresser every morning.", exampleTranslation: "أمضمد كل صباح." },
  { word: "dustpan", translation: "مجرود", partOfSpeech: "noun", difficulty: "medium", example: "We bought a dustpan at the store.", exampleTranslation: "اشترينا مجرود من المتجر." },
  { word: "earring", translation: "حلق", partOfSpeech: "adjective", difficulty: "medium", example: "That was a earring day.", exampleTranslation: "كان ذلك يوماً حلق." },
  { word: "emerald", translation: "الزمرد", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a emerald.", exampleTranslation: "أراني صديقي الزمرد." },
  { word: "feather", translation: "ريشة", partOfSpeech: "verb", difficulty: "medium", example: "I like to feather on weekends.", exampleTranslation: "أحب أن ريشة في عطلة نهاية الأسبوع." },
  { word: "garment", translation: "ملابس", partOfSpeech: "noun", difficulty: "medium", example: "I found a garment in my bag.", exampleTranslation: "وجدت ملابس في حقيبتي." },
  { word: "grocery", translation: "خضروات", partOfSpeech: "noun", difficulty: "medium", example: "The grocery is on the table.", exampleTranslation: "خضروات على الطاولة." },
  { word: "haircut", translation: "قصة شعر", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small haircut.", exampleTranslation: "أعطتني قصة شعر صغيراً." },
  { word: "hammock", translation: "أرجوحة", partOfSpeech: "noun", difficulty: "medium", example: "We packed a hammock for the trip.", exampleTranslation: "حزمنا أرجوحة للرحلة." },
  { word: "headset", translation: "سماعة الرأس", partOfSpeech: "noun", difficulty: "medium", example: "I like this headset very much.", exampleTranslation: "أحب هذا سماعة الرأس كثيراً." },
  { word: "hydrant", translation: "صنبور", partOfSpeech: "noun", difficulty: "medium", example: "I saw a hydrant at the park today.", exampleTranslation: "رأيت صنبور في الحديقة اليوم." },
  { word: "journal", translation: "مجلة", partOfSpeech: "adjective", difficulty: "medium", example: "My room looks journal today.", exampleTranslation: "غرفتي تبدو مجلة اليوم." },
  { word: "license", translation: "رخصة", partOfSpeech: "noun", difficulty: "medium", example: "There is a license in our kitchen.", exampleTranslation: "يوجد رخصة في مطبخنا." },
  { word: "mercury", translation: "الزئبق", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a mercury.", exampleTranslation: "أراني صديقي الزئبق." },
  { word: "nursery", translation: "حضانة", partOfSpeech: "noun", difficulty: "medium", example: "We use a nursery every day at home.", exampleTranslation: "نستخدم حضانة كل يوم في البيت." },
  { word: "painter", translation: "رسام", partOfSpeech: "verb", difficulty: "medium", example: "We painter together as a family.", exampleTranslation: "نرسام معاً كعائلة." },
  { word: "parsley", translation: "بَقدونس", partOfSpeech: "noun", difficulty: "medium", example: "The parsley is on the table.", exampleTranslation: "بَقدونس على الطاولة." },
  { word: "perfume", translation: "عطر", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small perfume.", exampleTranslation: "أعطتني عطر صغيراً." },
  { word: "pudding", translation: "بودنغ", partOfSpeech: "adjective", difficulty: "medium", example: "The fruit looks pudding.", exampleTranslation: "الفاكهة تبدو بودنغ." },
  { word: "savings", translation: "المدخرات", partOfSpeech: "noun", difficulty: "medium", example: "I like this savings very much.", exampleTranslation: "أحب هذا المدخرات كثيراً." },
  { word: "scallop", translation: "إكليل", partOfSpeech: "noun", difficulty: "medium", example: "I saw a scallop at the park today.", exampleTranslation: "رأيت إكليل في الحديقة اليوم." },
  { word: "scratch", translation: "يخدش", partOfSpeech: "noun", difficulty: "medium", example: "We bought a scratch at the store.", exampleTranslation: "اشترينا يخدش من المتجر." },
  { word: "seagull", translation: "النورس", partOfSpeech: "noun", difficulty: "medium", example: "There is a seagull in our kitchen.", exampleTranslation: "يوجد النورس في مطبخنا." },
  { word: "snowman", translation: "رجل ثلج", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a snowman.", exampleTranslation: "أراني صديقي رجل ثلج." },
  { word: "spatula", translation: "ملعقة", partOfSpeech: "noun", difficulty: "medium", example: "We use a spatula every day at home.", exampleTranslation: "نستخدم ملعقة كل يوم في البيت." },
  { word: "thicket", translation: "غابة", partOfSpeech: "noun", difficulty: "medium", example: "I found a thicket in my bag.", exampleTranslation: "وجدت غابة في حقيبتي." },
  { word: "toddler", translation: "طفل صغير", partOfSpeech: "verb", difficulty: "medium", example: "She will toddler later today.", exampleTranslation: "ستطفل صغير لاحقاً اليوم." },
  { word: "toolbox", translation: "الأدوات", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small toolbox.", exampleTranslation: "أعطتني الأدوات صغيراً." },
  { word: "vampire", translation: "مصاص دماء", partOfSpeech: "noun", difficulty: "medium", example: "We packed a vampire for the trip.", exampleTranslation: "حزمنا مصاص دماء للرحلة." },
  { word: "voucher", translation: "قسيمة", partOfSpeech: "verb", difficulty: "medium", example: "We voucher when we have time.", exampleTranslation: "نقسيمة عندما يكون لدينا وقت." },
  { word: "warrior", translation: "محارب", partOfSpeech: "noun", difficulty: "medium", example: "I saw a warrior at the park today.", exampleTranslation: "رأيت محارب في الحديقة اليوم." },
  { word: "weekend", translation: "عطلة نهاية الأسبوع", partOfSpeech: "noun", difficulty: "medium", example: "We bought a weekend at the store.", exampleTranslation: "اشترينا عطلة نهاية الأسبوع من المتجر." },
  { word: "vehicle", translation: "عربة", partOfSpeech: "noun", difficulty: "medium", example: "There is a vehicle in our kitchen.", exampleTranslation: "يوجد عربة في مطبخنا." },
  { word: "goggles", translation: "نظارات واقية", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a goggles.", exampleTranslation: "أراني صديقي نظارات واقية." },
  { word: "deposit", translation: "إيداع", partOfSpeech: "noun", difficulty: "medium", example: "We use a deposit every day at home.", exampleTranslation: "نستخدم إيداع كل يوم في البيت." },
  { word: "numbers", translation: "أرقام", partOfSpeech: "noun", difficulty: "medium", example: "I found a numbers in my bag.", exampleTranslation: "وجدت أرقام في حقيبتي." },
  { word: "pacific", translation: "المحيط الهادئ", partOfSpeech: "adjective", difficulty: "medium", example: "The movie was pacific.", exampleTranslation: "كان الفيلم المحيط الهادئ." },
  { word: "section", translation: "قسم", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small section.", exampleTranslation: "أعطتني قسم صغيراً." },
  { word: "meeting", translation: "مقابلة", partOfSpeech: "adjective", difficulty: "medium", example: "The fruit looks meeting.", exampleTranslation: "الفاكهة تبدو مقابلة." },
  { word: "hearing", translation: "السمع", partOfSpeech: "adjective", difficulty: "medium", example: "He seems hearing today.", exampleTranslation: "يبدو السمع اليوم." },
  { word: "hashtag", translation: "الوسم", partOfSpeech: "noun", difficulty: "medium", example: "I saw a hashtag at the park today.", exampleTranslation: "رأيت الوسم في الحديقة اليوم." },
  { word: "acrobat", translation: "بهلوان", partOfSpeech: "noun", difficulty: "medium", example: "We bought a acrobat at the store.", exampleTranslation: "اشترينا بهلوان من المتجر." },
  { word: "admiral", translation: "أدميرال", partOfSpeech: "adjective", difficulty: "medium", example: "That was a admiral day.", exampleTranslation: "كان ذلك يوماً أدميرال." },
  { word: "airlift", translation: "جسر جوي", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a airlift.", exampleTranslation: "أراني صديقي جسر جوي." },
  { word: "airlock", translation: "غرفة معادلة الضغط", partOfSpeech: "noun", difficulty: "medium", example: "We use a airlock every day at home.", exampleTranslation: "نستخدم غرفة معادلة الضغط كل يوم في البيت." },
  { word: "airways", translation: "الخطوط الجوية", partOfSpeech: "noun", difficulty: "medium", example: "I found a airways in my bag.", exampleTranslation: "وجدت الخطوط الجوية في حقيبتي." },
  { word: "alfalfa", translation: "البرسيم", partOfSpeech: "noun", difficulty: "medium", example: "The alfalfa is on the table.", exampleTranslation: "البرسيم على الطاولة." },
  { word: "almanac", translation: "تقويم", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small almanac.", exampleTranslation: "أعطتني تقويم صغيراً." },
  { word: "armband", translation: "شارة", partOfSpeech: "noun", difficulty: "medium", example: "We packed a armband for the trip.", exampleTranslation: "حزمنا شارة للرحلة." },
  { word: "armrest", translation: "مسند للذراعين", partOfSpeech: "noun", difficulty: "medium", example: "I like this armrest very much.", exampleTranslation: "أحب هذا مسند للذراعين كثيراً." },
  { word: "arugula", translation: "جرجير", partOfSpeech: "noun", difficulty: "medium", example: "I saw a arugula at the park today.", exampleTranslation: "رأيت جرجير في الحديقة اليوم." },
  { word: "ashtray", translation: "منفضة سجائر", partOfSpeech: "noun", difficulty: "medium", example: "We bought a ashtray at the store.", exampleTranslation: "اشترينا منفضة سجائر من المتجر." },
  { word: "axolotl", translation: "قنفذ البحر", partOfSpeech: "noun", difficulty: "medium", example: "There is a axolotl in our kitchen.", exampleTranslation: "يوجد قنفذ البحر في مطبخنا." },
  { word: "backhoe", translation: "حفار", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a backhoe.", exampleTranslation: "أراني صديقي حفار." },
  { word: "backlit", translation: "بإضاءة خلفية", partOfSpeech: "noun", difficulty: "medium", example: "We use a backlit every day at home.", exampleTranslation: "نستخدم بإضاءة خلفية كل يوم في البيت." },
  { word: "bagpipe", translation: "مزمار القربة", partOfSpeech: "noun", difficulty: "medium", example: "I found a bagpipe in my bag.", exampleTranslation: "وجدت مزمار القربة في حقيبتي." },
  { word: "ballast", translation: "الصابورة", partOfSpeech: "noun", difficulty: "medium", example: "The ballast is on the table.", exampleTranslation: "الصابورة على الطاولة." },
  { word: "ballboy", translation: "فتى الكرة", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small ballboy.", exampleTranslation: "أعطتني فتى الكرة صغيراً." },
  { word: "bracelet", translation: "إسورة", partOfSpeech: "noun", difficulty: "medium", example: "We packed a bracelet for the trip.", exampleTranslation: "حزمنا إسورة للرحلة." },
  { word: "daylight", translation: "ضوء النهار", partOfSpeech: "noun", difficulty: "medium", example: "I like this daylight very much.", exampleTranslation: "أحب هذا ضوء النهار كثيراً." },
  { word: "doghouse", translation: "بيت الكلب", partOfSpeech: "noun", difficulty: "medium", example: "I saw a doghouse at the park today.", exampleTranslation: "رأيت بيت الكلب في الحديقة اليوم." },
  { word: "doughnut", translation: "كعكة محلاة", partOfSpeech: "noun", difficulty: "medium", example: "We bought a doughnut at the store.", exampleTranslation: "اشترينا كعكة محلاة من المتجر." },
  { word: "duckling", translation: "البطيطة", partOfSpeech: "adjective", difficulty: "medium", example: "That was a duckling day.", exampleTranslation: "كان ذلك يوماً البطيطة." },
  { word: "dumpling", translation: "زلابية", partOfSpeech: "adjective", difficulty: "medium", example: "The weather feels dumpling.", exampleTranslation: "الطقس يبدو زلابية." },
  { word: "eggplant", translation: "باذنجان", partOfSpeech: "noun", difficulty: "medium", example: "We use a eggplant every day at home.", exampleTranslation: "نستخدم باذنجان كل يوم في البيت." },
  { word: "firework", translation: "ألعاب نارية", partOfSpeech: "noun", difficulty: "medium", example: "I found a firework in my bag.", exampleTranslation: "وجدت ألعاب نارية في حقيبتي." },
  { word: "fishbowl", translation: "حوض السمك", partOfSpeech: "noun", difficulty: "medium", example: "The fishbowl is on the table.", exampleTranslation: "حوض السمك على الطاولة." },
  { word: "flagpole", translation: "سارية العلم", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small flagpole.", exampleTranslation: "أعطتني سارية العلم صغيراً." },
  { word: "haystack", translation: "كومة قش", partOfSpeech: "noun", difficulty: "medium", example: "We packed a haystack for the trip.", exampleTranslation: "حزمنا كومة قش للرحلة." },
  { word: "headband", translation: "عقال", partOfSpeech: "noun", difficulty: "medium", example: "I like this headband very much.", exampleTranslation: "أحب هذا عقال كثيراً." },
  { word: "hillside", translation: "التلال", partOfSpeech: "noun", difficulty: "medium", example: "I saw a hillside at the park today.", exampleTranslation: "رأيت التلال في الحديقة اليوم." },
  { word: "homeroom", translation: "com.homeroom", partOfSpeech: "noun", difficulty: "medium", example: "We bought a homeroom at the store.", exampleTranslation: "اشترينا com.homeroom من المتجر." },
  { word: "lemonade", translation: "عصير الليمون", partOfSpeech: "noun", difficulty: "medium", example: "There is a lemonade in our kitchen.", exampleTranslation: "يوجد عصير الليمون في مطبخنا." },
  { word: "lipstick", translation: "أحمر الشفاه", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a lipstick.", exampleTranslation: "أراني صديقي أحمر الشفاه." },
  { word: "lollipop", translation: "مصاصة", partOfSpeech: "noun", difficulty: "medium", example: "We use a lollipop every day at home.", exampleTranslation: "نستخدم مصاصة كل يوم في البيت." },
  { word: "mischief", translation: "الأذى", partOfSpeech: "noun", difficulty: "medium", example: "I found a mischief in my bag.", exampleTranslation: "وجدت الأذى في حقيبتي." },
  { word: "movement", translation: "حركة", partOfSpeech: "noun", difficulty: "medium", example: "The movement is on the table.", exampleTranslation: "حركة على الطاولة." },
  { word: "mulberry", translation: "التوت", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small mulberry.", exampleTranslation: "أعطتني التوت صغيراً." },
  { word: "mushroom", translation: "فطر", partOfSpeech: "noun", difficulty: "medium", example: "We packed a mushroom for the trip.", exampleTranslation: "حزمنا فطر للرحلة." },
  { word: "necklace", translation: "قلادة", partOfSpeech: "noun", difficulty: "medium", example: "I like this necklace very much.", exampleTranslation: "أحب هذا قلادة كثيراً." },
  { word: "pacifier", translation: "مصاصة", partOfSpeech: "verb", difficulty: "medium", example: "I pacifier every morning.", exampleTranslation: "أمصاصة كل صباح." },
  { word: "pamphlet", translation: "كتيب", partOfSpeech: "noun", difficulty: "medium", example: "We bought a pamphlet at the store.", exampleTranslation: "اشترينا كتيب من المتجر." },
  { word: "railroad", translation: "السكك الحديدية", partOfSpeech: "noun", difficulty: "medium", example: "There is a railroad in our kitchen.", exampleTranslation: "يوجد السكك الحديدية في مطبخنا." },
  { word: "register", translation: "يسجل", partOfSpeech: "verb", difficulty: "medium", example: "They register in the garden.", exampleTranslation: "هم ييسجل في الحديقة." },
  { word: "rickshaw", translation: "عربة يد", partOfSpeech: "noun", difficulty: "medium", example: "We use a rickshaw every day at home.", exampleTranslation: "نستخدم عربة يد كل يوم في البيت." },
  { word: "splinter", translation: "شظية", partOfSpeech: "verb", difficulty: "medium", example: "We splinter together as a family.", exampleTranslation: "نشظية معاً كعائلة." },
  { word: "stairway", translation: "درج", partOfSpeech: "noun", difficulty: "medium", example: "The stairway is on the table.", exampleTranslation: "درج على الطاولة." },
  { word: "stampede", translation: "تدافع", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small stampede.", exampleTranslation: "أعطتني تدافع صغيراً." },
  { word: "streamer", translation: "غاسل", partOfSpeech: "verb", difficulty: "medium", example: "He streamer before he sleeps.", exampleTranslation: "هو يغاسل قبل أن ينام." },
  { word: "surround", translation: "محيط", partOfSpeech: "noun", difficulty: "medium", example: "I like this surround very much.", exampleTranslation: "أحب هذا محيط كثيراً." },
  { word: "tailgate", translation: "الباب الخلفي", partOfSpeech: "verb", difficulty: "medium", example: "I tailgate every morning.", exampleTranslation: "أالباب الخلفي كل صباح." },
  { word: "tapestry", translation: "نسيج", partOfSpeech: "noun", difficulty: "medium", example: "We bought a tapestry at the store.", exampleTranslation: "اشترينا نسيج من المتجر." },
  { word: "teenager", translation: "مراهق", partOfSpeech: "verb", difficulty: "medium", example: "Please teenager before dinner.", exampleTranslation: "من فضلك مراهق قبل العشاء." },
  { word: "telegram", translation: "برقية", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a telegram.", exampleTranslation: "أراني صديقي برقية." },
  { word: "tortilla", translation: "التورتيا", partOfSpeech: "noun", difficulty: "medium", example: "We use a tortilla every day at home.", exampleTranslation: "نستخدم التورتيا كل يوم في البيت." },
  { word: "township", translation: "بلدة", partOfSpeech: "noun", difficulty: "medium", example: "I found a township in my bag.", exampleTranslation: "وجدت بلدة في حقيبتي." },
  { word: "traveler", translation: "مسافر", partOfSpeech: "verb", difficulty: "medium", example: "She will traveler later today.", exampleTranslation: "ستمسافر لاحقاً اليوم." },
  { word: "tricycle", translation: "دراجة ثلاثية العجلات", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small tricycle.", exampleTranslation: "أعطتني دراجة ثلاثية العجلات صغيراً." },
  { word: "vacation", translation: "أجازة", partOfSpeech: "noun", difficulty: "medium", example: "We packed a vacation for the trip.", exampleTranslation: "حزمنا أجازة للرحلة." },
  { word: "westward", translation: "غربا", partOfSpeech: "noun", difficulty: "medium", example: "I like this westward very much.", exampleTranslation: "أحب هذا غربا كثيراً." },
  { word: "discount", translation: "تخفيض", partOfSpeech: "noun", difficulty: "medium", example: "I saw a discount at the park today.", exampleTranslation: "رأيت تخفيض في الحديقة اليوم." },
  { word: "notation", translation: "تدوين", partOfSpeech: "noun", difficulty: "medium", example: "We bought a notation at the store.", exampleTranslation: "اشترينا تدوين من المتجر." },
  { word: "cellular", translation: "الخلوية", partOfSpeech: "noun", difficulty: "medium", example: "There is a cellular in our kitchen.", exampleTranslation: "يوجد الخلوية في مطبخنا." },
  { word: "volcanic", translation: "بركاني", partOfSpeech: "adjective", difficulty: "medium", example: "The weather feels volcanic.", exampleTranslation: "الطقس يبدو بركاني." },
  { word: "relation", translation: "علاقة", partOfSpeech: "noun", difficulty: "medium", example: "We use a relation every day at home.", exampleTranslation: "نستخدم علاقة كل يوم في البيت." },
  { word: "literacy", translation: "معرفة القراءة والكتابة", partOfSpeech: "noun", difficulty: "medium", example: "I found a literacy in my bag.", exampleTranslation: "وجدت معرفة القراءة والكتابة في حقيبتي." },
  { word: "checking", translation: "التحقق", partOfSpeech: "adjective", difficulty: "medium", example: "The movie was checking.", exampleTranslation: "كان الفيلم التحقق." },
  { word: "ellipsis", translation: "القطع الناقص", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small ellipsis.", exampleTranslation: "أعطتني القطع الناقص صغيراً." },
  { word: "fragment", translation: "جزء", partOfSpeech: "noun", difficulty: "medium", example: "We packed a fragment for the trip.", exampleTranslation: "حزمنا جزء للرحلة." },
  { word: "spotting", translation: "اكتشاف", partOfSpeech: "adjective", difficulty: "medium", example: "He seems spotting today.", exampleTranslation: "يبدو اكتشاف اليوم." },
  { word: "memorial", translation: "نصب تذكاري", partOfSpeech: "adjective", difficulty: "medium", example: "The soup tastes memorial.", exampleTranslation: "الحساء طعمه نصب تذكاري." },
  { word: "farewell", translation: "وداع", partOfSpeech: "noun", difficulty: "medium", example: "We bought a farewell at the store.", exampleTranslation: "اشترينا وداع من المتجر." },
  { word: "airbrush", translation: "البخاخة", partOfSpeech: "noun", difficulty: "medium", example: "There is a airbrush in our kitchen.", exampleTranslation: "يوجد البخاخة في مطبخنا." },
  { word: "airfield", translation: "مطار", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a airfield.", exampleTranslation: "أراني صديقي مطار." },
  { word: "amethyst", translation: "جمشت", partOfSpeech: "noun", difficulty: "medium", example: "We use a amethyst every day at home.", exampleTranslation: "نستخدم جمشت كل يوم في البيت." },
  { word: "backache", translation: "آلام الظهر", partOfSpeech: "noun", difficulty: "medium", example: "I found a backache in my bag.", exampleTranslation: "وجدت آلام الظهر في حقيبتي." },
  { word: "backfire", translation: "نتائج عكسية", partOfSpeech: "noun", difficulty: "medium", example: "The backfire is on the table.", exampleTranslation: "نتائج عكسية على الطاولة." },
  { word: "backhand", translation: "ضربة خلفية", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small backhand.", exampleTranslation: "أعطتني ضربة خلفية صغيراً." },
  { word: "backrest", translation: "مسند الظهر", partOfSpeech: "noun", difficulty: "medium", example: "We packed a backrest for the trip.", exampleTranslation: "حزمنا مسند الظهر للرحلة." },
  { word: "backseat", translation: "المقعد الخلفي", partOfSpeech: "noun", difficulty: "medium", example: "I like this backseat very much.", exampleTranslation: "أحب هذا المقعد الخلفي كثيراً." },
  { word: "backside", translation: "المؤخر", partOfSpeech: "noun", difficulty: "medium", example: "I saw a backside at the park today.", exampleTranslation: "رأيت المؤخر في الحديقة اليوم." },
  { word: "backstop", translation: "مساندة", partOfSpeech: "noun", difficulty: "medium", example: "We bought a backstop at the store.", exampleTranslation: "اشترينا مساندة من المتجر." },
  { word: "backtalk", translation: "الحديث الخلفي", partOfSpeech: "noun", difficulty: "medium", example: "There is a backtalk in our kitchen.", exampleTranslation: "يوجد الحديث الخلفي في مطبخنا." },
  { word: "backwash", translation: "الغسيل العكسي", partOfSpeech: "noun", difficulty: "medium", example: "My friend showed me a backwash.", exampleTranslation: "أراني صديقي الغسيل العكسي." },
  { word: "backyard", translation: "الفناء الخلفي", partOfSpeech: "noun", difficulty: "medium", example: "We use a backyard every day at home.", exampleTranslation: "نستخدم الفناء الخلفي كل يوم في البيت." },
  { word: "bakeware", translation: "خبز", partOfSpeech: "noun", difficulty: "medium", example: "I found a bakeware in my bag.", exampleTranslation: "وجدت خبز في حقيبتي." },
  { word: "ballgame", translation: "لعبة الكرة", partOfSpeech: "noun", difficulty: "medium", example: "The ballgame is on the table.", exampleTranslation: "لعبة الكرة على الطاولة." },
  { word: "ballpark", translation: "ملعب كرة قدم", partOfSpeech: "noun", difficulty: "medium", example: "She gave me a small ballpark.", exampleTranslation: "أعطتني ملعب كرة قدم صغيراً." },
  { word: "ballroom", translation: "قاعة رقص", partOfSpeech: "noun", difficulty: "medium", example: "We packed a ballroom for the trip.", exampleTranslation: "حزمنا قاعة رقص للرحلة." },
  { word: "banister", translation: "درابزين", partOfSpeech: "noun", difficulty: "medium", example: "I like this banister very much.", exampleTranslation: "أحب هذا درابزين كثيراً." },
  { word: "ballpoint", translation: "نقطة حبر جاف", partOfSpeech: "noun", difficulty: "medium", example: "I saw a ballpoint at the park today.", exampleTranslation: "رأيت نقطة حبر جاف في الحديقة اليوم." },
  { word: "chopstick", translation: "عود", partOfSpeech: "noun", difficulty: "hard", example: "We bought a chopstick at the store.", exampleTranslation: "اشترينا عود من المتجر." },
  { word: "croissant", translation: "كرواسون", partOfSpeech: "noun", difficulty: "hard", example: "There is a croissant in our kitchen.", exampleTranslation: "يوجد كرواسون في مطبخنا." },
  { word: "dashboard", translation: "لوحة القيادة", partOfSpeech: "noun", difficulty: "hard", example: "My friend showed me a dashboard.", exampleTranslation: "أراني صديقي لوحة القيادة." },
  { word: "dishcloth", translation: "قماشة الصحون", partOfSpeech: "noun", difficulty: "hard", example: "We use a dishcloth every day at home.", exampleTranslation: "نستخدم قماشة الصحون كل يوم في البيت." },
  { word: "farmhouse", translation: "مزرعة", partOfSpeech: "noun", difficulty: "hard", example: "I found a farmhouse in my bag.", exampleTranslation: "وجدت مزرعة في حقيبتي." },
  { word: "handshake", translation: "مصافحة", partOfSpeech: "noun", difficulty: "hard", example: "The handshake is on the table.", exampleTranslation: "مصافحة على الطاولة." },
  { word: "hopscotch", translation: "الحجلة", partOfSpeech: "noun", difficulty: "hard", example: "She gave me a small hopscotch.", exampleTranslation: "أعطتني الحجلة صغيراً." },
  { word: "hourglass", translation: "الساعة الرملية", partOfSpeech: "noun", difficulty: "hard", example: "We packed a hourglass for the trip.", exampleTranslation: "حزمنا الساعة الرملية للرحلة." },
  { word: "housewife", translation: "ربة منزل", partOfSpeech: "noun", difficulty: "hard", example: "I like this housewife very much.", exampleTranslation: "أحب هذا ربة منزل كثيراً." },
  { word: "pistachio", translation: "الفستق", partOfSpeech: "noun", difficulty: "hard", example: "I saw a pistachio at the park today.", exampleTranslation: "رأيت الفستق في الحديقة اليوم." },
  { word: "snowflake", translation: "ندفة الثلج", partOfSpeech: "noun", difficulty: "hard", example: "We bought a snowflake at the store.", exampleTranslation: "اشترينا ندفة الثلج من المتجر." },
  { word: "spiderweb", translation: "شبكة العنكبوت", partOfSpeech: "noun", difficulty: "hard", example: "There is a spiderweb in our kitchen.", exampleTranslation: "يوجد شبكة العنكبوت في مطبخنا." },
  { word: "stockpile", translation: "مخزون", partOfSpeech: "noun", difficulty: "hard", example: "My friend showed me a stockpile.", exampleTranslation: "أراني صديقي مخزون." },
  { word: "sugarcane", translation: "قصب السكر", partOfSpeech: "noun", difficulty: "hard", example: "We use a sugarcane every day at home.", exampleTranslation: "نستخدم قصب السكر كل يوم في البيت." },
  { word: "sunflower", translation: "عباد الشمس", partOfSpeech: "verb", difficulty: "hard", example: "We sunflower together as a family.", exampleTranslation: "نعباد الشمس معاً كعائلة." },
  { word: "surfboard", translation: "لوح ركوب الأمواج", partOfSpeech: "noun", difficulty: "hard", example: "The surfboard is on the table.", exampleTranslation: "لوح ركوب الأمواج على الطاولة." },
  { word: "tangerine", translation: "اليوسفي", partOfSpeech: "noun", difficulty: "hard", example: "She gave me a small tangerine.", exampleTranslation: "أعطتني اليوسفي صغيراً." },
  { word: "treadmill", translation: "جهاز المشي", partOfSpeech: "noun", difficulty: "hard", example: "We packed a treadmill for the trip.", exampleTranslation: "حزمنا جهاز المشي للرحلة." },
  { word: "workplace", translation: "مكان العمل", partOfSpeech: "noun", difficulty: "hard", example: "I like this workplace very much.", exampleTranslation: "أحب هذا مكان العمل كثيراً." },
  { word: "wristband", translation: "معصمه", partOfSpeech: "noun", difficulty: "hard", example: "I saw a wristband at the park today.", exampleTranslation: "رأيت معصمه في الحديقة اليوم." },
  { word: "statement", translation: "إفادة", partOfSpeech: "noun", difficulty: "hard", example: "We bought a statement at the store.", exampleTranslation: "اشترينا إفادة من المتجر." },
  { word: "recycling", translation: "إعادة التدوير", partOfSpeech: "adjective", difficulty: "hard", example: "That was a recycling day.", exampleTranslation: "كان ذلك يوماً إعادة التدوير." },
  { word: "geometric", translation: "هندسي", partOfSpeech: "adjective", difficulty: "hard", example: "The weather feels geometric.", exampleTranslation: "الطقس يبدو هندسي." },
  { word: "operation", translation: "عملية", partOfSpeech: "noun", difficulty: "hard", example: "We use a operation every day at home.", exampleTranslation: "نستخدم عملية كل يوم في البيت." },
  { word: "genealogy", translation: "علم الأنساب", partOfSpeech: "noun", difficulty: "hard", example: "I found a genealogy in my bag.", exampleTranslation: "وجدت علم الأنساب في حقيبتي." },
  { word: "agreement", translation: "اتفاق", partOfSpeech: "noun", difficulty: "hard", example: "The agreement is on the table.", exampleTranslation: "اتفاق على الطاولة." },
  { word: "placement", translation: "التنسيب", partOfSpeech: "noun", difficulty: "hard", example: "She gave me a small placement.", exampleTranslation: "أعطتني التنسيب صغيراً." },
  { word: "formation", translation: "تشكيل", partOfSpeech: "noun", difficulty: "hard", example: "We packed a formation for the trip.", exampleTranslation: "حزمنا تشكيل للرحلة." },
  { word: "imitation", translation: "تقليد", partOfSpeech: "noun", difficulty: "hard", example: "I like this imitation very much.", exampleTranslation: "أحب هذا تقليد كثيراً." },
  { word: "impromptu", translation: "مرتجلة", partOfSpeech: "noun", difficulty: "hard", example: "I saw a impromptu at the park today.", exampleTranslation: "رأيت مرتجلة في الحديقة اليوم." },
  { word: "memorized", translation: "حفظها", partOfSpeech: "adjective", difficulty: "hard", example: "My room looks memorized today.", exampleTranslation: "غرفتي تبدو حفظها اليوم." },
  { word: "arrowhead", translation: "رأس السهم", partOfSpeech: "noun", difficulty: "hard", example: "There is a arrowhead in our kitchen.", exampleTranslation: "يوجد رأس السهم في مطبخنا." },
  { word: "artichoke", translation: "خرشوف", partOfSpeech: "noun", difficulty: "hard", example: "My friend showed me a artichoke.", exampleTranslation: "أراني صديقي خرشوف." },
  { word: "asparagus", translation: "الهليون", partOfSpeech: "noun", difficulty: "hard", example: "We use a asparagus every day at home.", exampleTranslation: "نستخدم الهليون كل يوم في البيت." },
  { word: "audiobook", translation: "كتاب مسموع", partOfSpeech: "noun", difficulty: "hard", example: "I found a audiobook in my bag.", exampleTranslation: "وجدت كتاب مسموع في حقيبتي." },
  { word: "backboard", translation: "اللوحة الخلفية", partOfSpeech: "noun", difficulty: "hard", example: "The backboard is on the table.", exampleTranslation: "اللوحة الخلفية على الطاولة." },
  { word: "backwoods", translation: "غابات خلفية", partOfSpeech: "noun", difficulty: "hard", example: "She gave me a small backwoods.", exampleTranslation: "أعطتني غابات خلفية صغيراً." },
  { word: "friendship", translation: "الصداقة", partOfSpeech: "noun", difficulty: "hard", example: "We packed a friendship for the trip.", exampleTranslation: "حزمنا الصداقة للرحلة." },
  { word: "smokestack", translation: "مدخنة", partOfSpeech: "noun", difficulty: "hard", example: "I like this smokestack very much.", exampleTranslation: "أحب هذا مدخنة كثيراً." },
  { word: "tambourine", translation: "دف صغير", partOfSpeech: "noun", difficulty: "hard", example: "I saw a tambourine at the park today.", exampleTranslation: "رأيت دف صغير في الحديقة اليوم." },
  { word: "trampoline", translation: "الترامبولين", partOfSpeech: "noun", difficulty: "hard", example: "We bought a trampoline at the store.", exampleTranslation: "اشترينا الترامبولين من المتجر." },
  { word: "typewriter", translation: "آلة كاتبة", partOfSpeech: "verb", difficulty: "hard", example: "Please typewriter before dinner.", exampleTranslation: "من فضلك آلة كاتبة قبل العشاء." },
  { word: "wilderness", translation: "البرية", partOfSpeech: "noun", difficulty: "hard", example: "My friend showed me a wilderness.", exampleTranslation: "أراني صديقي البرية." },
  { word: "operations", translation: "العمليات", partOfSpeech: "noun", difficulty: "hard", example: "We use a operations every day at home.", exampleTranslation: "نستخدم العمليات كل يوم في البيت." },
  { word: "arithmetic", translation: "الحساب", partOfSpeech: "adjective", difficulty: "hard", example: "This shirt is too arithmetic.", exampleTranslation: "هذا القميص الحساب جداً." },
  { word: "propaganda", translation: "دعاية", partOfSpeech: "noun", difficulty: "hard", example: "The propaganda is on the table.", exampleTranslation: "دعاية على الطاولة." },
  { word: "publishing", translation: "نشر", partOfSpeech: "adjective", difficulty: "hard", example: "Our trip was publishing.", exampleTranslation: "كانت رحلتنا نشر." },
  { word: "discussion", translation: "مناقشة", partOfSpeech: "noun", difficulty: "hard", example: "We packed a discussion for the trip.", exampleTranslation: "حزمنا مناقشة للرحلة." },
  { word: "censorship", translation: "الرقابة", partOfSpeech: "noun", difficulty: "hard", example: "I like this censorship very much.", exampleTranslation: "أحب هذا الرقابة كثيراً." },
  { word: "storyboard", translation: "القصة المصورة", partOfSpeech: "noun", difficulty: "hard", example: "I saw a storyboard at the park today.", exampleTranslation: "رأيت القصة المصورة في الحديقة اليوم." },
  { word: "fingerprint", translation: "بصمة", partOfSpeech: "noun", difficulty: "hard", example: "We bought a fingerprint at the store.", exampleTranslation: "اشترينا بصمة من المتجر." },
  { word: "marshmallow", translation: "مارشميلو", partOfSpeech: "noun", difficulty: "hard", example: "There is a marshmallow in our kitchen.", exampleTranslation: "يوجد مارشميلو في مطبخنا." },
  { word: "supermarket", translation: "سوبر ماركت", partOfSpeech: "noun", difficulty: "hard", example: "My friend showed me a supermarket.", exampleTranslation: "أراني صديقي سوبر ماركت." },
  { word: "switchboard", translation: "لوحة التبديل", partOfSpeech: "noun", difficulty: "hard", example: "We use a switchboard every day at home.", exampleTranslation: "نستخدم لوحة التبديل كل يوم في البيت." },
  { word: "engineering", translation: "هندسة", partOfSpeech: "adjective", difficulty: "hard", example: "This shirt is too engineering.", exampleTranslation: "هذا القميص هندسة جداً." },
  { word: "replication", translation: "النسخ المتماثل", partOfSpeech: "noun", difficulty: "hard", example: "The replication is on the table.", exampleTranslation: "النسخ المتماثل على الطاولة." },
  { word: "chronometer", translation: "الكرونومتر", partOfSpeech: "verb", difficulty: "hard", example: "Do you chronometer at home?", exampleTranslation: "هل الكرونومتر في البيت؟" },
  { word: "examination", translation: "فحص", partOfSpeech: "noun", difficulty: "hard", example: "We packed a examination for the trip.", exampleTranslation: "حزمنا فحص للرحلة." },
  { word: "handkerchief", translation: "منديل", partOfSpeech: "noun", difficulty: "hard", example: "I like this handkerchief very much.", exampleTranslation: "أحب هذا منديل كثيراً." },
];
