/** Grade 6 chunk C — social studies, civics, geography & general vocabulary. */
export const GRADE6_CHUNK_C = [
  { word: "society", translation: "مجتمع", partOfSpeech: "noun", difficulty: "medium", example: "A fair society treats people equally.", exampleTranslation: "المجتمع العادل يعامل الناس بالتساوي." },
  { word: "culture", translation: "ثقافة", partOfSpeech: "noun", difficulty: "medium", example: "Every country has its own culture.", exampleTranslation: "لكل بلد ثقافته الخاصة." },
  { word: "tradition", translation: "تقليد", partOfSpeech: "noun", difficulty: "medium", example: "Sharing food is an old tradition.", exampleTranslation: "مشاركة الطعام تقليد قديم." },
  { word: "civilization", translation: "حضارة", partOfSpeech: "noun", difficulty: "hard", example: "The ancient civilization built great temples.", exampleTranslation: "بنت الحضارة القديمة معابد عظيمة." },
  { word: "government", translation: "حكومة", partOfSpeech: "noun", difficulty: "medium", example: "The government makes laws for the country.", exampleTranslation: "تسنّ الحكومة قوانين للبلاد." },
  { word: "democracy", translation: "ديمقراطية", partOfSpeech: "noun", difficulty: "hard", example: "In a democracy, people choose their leaders.", exampleTranslation: "في الديمقراطية يختار الناس قادتهم." },
  { word: "citizen", translation: "مواطن", partOfSpeech: "noun", difficulty: "medium", example: "Every citizen has rights and duties.", exampleTranslation: "لكل مواطن حقوق وواجبات." },
  { word: "community", translation: "مجتمع محلي", partOfSpeech: "noun", difficulty: "medium", example: "Our community cleaned the park together.", exampleTranslation: "نظّف مجتمعنا المحلي الحديقة معاً." },
  { word: "economy", translation: "اقتصاد", partOfSpeech: "noun", difficulty: "hard", example: "Trade helps the country's economy grow.", exampleTranslation: "تساعد التجارة اقتصاد البلاد على النمو." },
  { word: "trade", translation: "تجارة", partOfSpeech: "noun", difficulty: "medium", example: "Trade brings goods from far away.", exampleTranslation: "تجلب التجارة البضائع من أماكن بعيدة." },
  { word: "industry", translation: "صناعة", partOfSpeech: "noun", difficulty: "medium", example: "The car industry employs many workers.", exampleTranslation: "توظّف صناعة السيارات كثيراً من العمال." },
  { word: "agriculture", translation: "زراعة", partOfSpeech: "noun", difficulty: "hard", example: "Agriculture feeds the whole nation.", exampleTranslation: "تُطعم الزراعة الأمة بأكملها." },
  { word: "geography", translation: "جغرافيا", partOfSpeech: "noun", difficulty: "medium", example: "We study rivers and mountains in geography.", exampleTranslation: "ندرس الأنهار والجبال في الجغرافيا." },
  { word: "region", translation: "إقليم/منطقة", partOfSpeech: "noun", difficulty: "medium", example: "This region is famous for its olives.", exampleTranslation: "تشتهر هذه المنطقة بزيتونها." },
  { word: "continent", translation: "قارة", partOfSpeech: "noun", difficulty: "medium", example: "Africa is a large continent.", exampleTranslation: "إفريقيا قارة كبيرة." },
  { word: "nation", translation: "أمة", partOfSpeech: "noun", difficulty: "medium", example: "The whole nation celebrated the victory.", exampleTranslation: "احتفلت الأمة كلها بالنصر." },
  { word: "border", translation: "حدود", partOfSpeech: "noun", difficulty: "medium", example: "A river forms the border between them.", exampleTranslation: "يشكّل نهر الحدود بينهما." },
  { word: "migration", translation: "هجرة", partOfSpeech: "noun", difficulty: "hard", example: "The migration of people changed the city.", exampleTranslation: "غيّرت هجرة الناس المدينة." },
  { word: "history", translation: "تاريخ", partOfSpeech: "noun", difficulty: "easy", example: "We learn history to understand the past.", exampleTranslation: "ندرس التاريخ لفهم الماضي." },
  { word: "ancestor", translation: "سلف/جدّ", partOfSpeech: "noun", difficulty: "hard", example: "Our ancestors lived near this river.", exampleTranslation: "عاش أسلافنا قرب هذا النهر." },
  { word: "heritage", translation: "تراث", partOfSpeech: "noun", difficulty: "hard", example: "The old city is part of our heritage.", exampleTranslation: "المدينة القديمة جزء من تراثنا." },
  { word: "monument", translation: "نصب تذكاري", partOfSpeech: "noun", difficulty: "hard", example: "The monument honors brave heroes.", exampleTranslation: "يكرّم النصب التذكاري الأبطال الشجعان." },
  { word: "empire", translation: "إمبراطورية", partOfSpeech: "noun", difficulty: "hard", example: "The empire ruled many lands.", exampleTranslation: "حكمت الإمبراطورية أراضيَ كثيرة." },
  { word: "conflict", translation: "صراع/نزاع", partOfSpeech: "noun", difficulty: "hard", example: "Talking can end a long conflict.", exampleTranslation: "يمكن للحوار أن ينهي صراعاً طويلاً." },
  { word: "treaty", translation: "معاهدة", partOfSpeech: "noun", difficulty: "hard", example: "The two nations signed a peace treaty.", exampleTranslation: "وقّعت الأمتان معاهدة سلام." },
  { word: "revolution", translation: "ثورة", partOfSpeech: "noun", difficulty: "hard", example: "The revolution changed the country forever.", exampleTranslation: "غيّرت الثورة البلاد إلى الأبد." },
  { word: "independence", translation: "استقلال", partOfSpeech: "noun", difficulty: "hard", example: "The colony won its independence.", exampleTranslation: "نالت المستعمرة استقلالها." },
  { word: "freedom", translation: "حرية", partOfSpeech: "noun", difficulty: "medium", example: "Freedom of speech is important.", exampleTranslation: "حرية التعبير مهمة." },
  { word: "justice", translation: "عدالة", partOfSpeech: "noun", difficulty: "hard", example: "The court works to bring justice.", exampleTranslation: "تعمل المحكمة على تحقيق العدالة." },
  { word: "equality", translation: "مساواة", partOfSpeech: "noun", difficulty: "hard", example: "Equality means fair treatment for all.", exampleTranslation: "تعني المساواة معاملة عادلة للجميع." },
  { word: "rights", translation: "حقوق", partOfSpeech: "noun", difficulty: "medium", example: "Children have the right to learn.", exampleTranslation: "للأطفال الحق في التعلّم." },
  { word: "responsibility", translation: "مسؤولية", partOfSpeech: "noun", difficulty: "medium", example: "Caring for pets is a responsibility.", exampleTranslation: "الاعتناء بالحيوانات الأليفة مسؤولية." },
  { word: "law", translation: "قانون", partOfSpeech: "noun", difficulty: "easy", example: "We must obey the traffic law.", exampleTranslation: "علينا أن نطيع قانون المرور." },
  { word: "policy", translation: "سياسة/نهج", partOfSpeech: "noun", difficulty: "hard", example: "The school has a clear policy on safety.", exampleTranslation: "لدى المدرسة سياسة واضحة بشأن السلامة." },
  { word: "election", translation: "انتخاب", partOfSpeech: "noun", difficulty: "hard", example: "The election will be held next month.", exampleTranslation: "ستُجرى الانتخابات الشهر المقبل." },
  { word: "vote", translation: "يصوّت", partOfSpeech: "verb", difficulty: "easy", example: "Citizens vote to choose a leader.", exampleTranslation: "يصوّت المواطنون لاختيار قائد." },
  { word: "leader", translation: "قائد", partOfSpeech: "noun", difficulty: "easy", example: "A good leader listens to people.", exampleTranslation: "القائد الجيد يستمع إلى الناس." },
  { word: "representative", translation: "ممثّل/نائب", partOfSpeech: "noun", difficulty: "hard", example: "Each class chose a representative.", exampleTranslation: "اختار كل صف ممثّلاً." },
  { word: "council", translation: "مجلس", partOfSpeech: "noun", difficulty: "hard", example: "The city council met on Monday.", exampleTranslation: "اجتمع مجلس المدينة يوم الاثنين." },
  { word: "constitution", translation: "دستور", partOfSpeech: "noun", difficulty: "hard", example: "The constitution protects our rights.", exampleTranslation: "يحمي الدستور حقوقنا." },
  { word: "ambassador", translation: "سفير", partOfSpeech: "noun", difficulty: "hard", example: "The ambassador spoke for her country.", exampleTranslation: "تحدّثت السفيرة باسم بلدها." },
  { word: "diplomat", translation: "دبلوماسي", partOfSpeech: "noun", difficulty: "hard", example: "A skilled diplomat avoids war.", exampleTranslation: "يتجنّب الدبلوماسي الماهر الحرب." },
  { word: "settlement", translation: "مستوطنة", partOfSpeech: "noun", difficulty: "hard", example: "The early settlement grew into a town.", exampleTranslation: "نمت المستوطنة المبكرة لتصبح بلدة." },
  { word: "exploration", translation: "استكشاف", partOfSpeech: "noun", difficulty: "hard", example: "Space exploration teaches us new things.", exampleTranslation: "يعلّمنا استكشاف الفضاء أشياء جديدة." },
  { word: "colony", translation: "مستعمرة", partOfSpeech: "noun", difficulty: "hard", example: "The colony depended on the home country.", exampleTranslation: "اعتمدت المستعمرة على البلد الأم." },
  { word: "boundary", translation: "حدّ", partOfSpeech: "noun", difficulty: "hard", example: "The fence marks the boundary of the farm.", exampleTranslation: "يحدّد السياج حدود المزرعة." },
  { word: "territory", translation: "إقليم", partOfSpeech: "noun", difficulty: "hard", example: "The lion guards its own territory.", exampleTranslation: "يحرس الأسد إقليمه الخاص." },
  { word: "capital", translation: "عاصمة", partOfSpeech: "noun", difficulty: "medium", example: "Cairo is the capital of Egypt.", exampleTranslation: "القاهرة عاصمة مصر." },
  { word: "rural", translation: "ريفي", partOfSpeech: "adjective", difficulty: "hard", example: "Life in rural areas is quiet.", exampleTranslation: "الحياة في المناطق الريفية هادئة." },
  { word: "urban", translation: "حضري", partOfSpeech: "adjective", difficulty: "hard", example: "Urban streets are often busy.", exampleTranslation: "شوارع المدن الحضرية مزدحمة غالباً." },
  { word: "census", translation: "تعداد سكاني", partOfSpeech: "noun", difficulty: "hard", example: "The census counts everyone in the country.", exampleTranslation: "يحصي التعداد السكاني كل فرد في البلاد." },
  { word: "resource", translation: "مورد", partOfSpeech: "noun", difficulty: "medium", example: "Water is a precious resource.", exampleTranslation: "الماء مورد ثمين." },
  { word: "import", translation: "يستورد", partOfSpeech: "verb", difficulty: "hard", example: "The country imports oil from abroad.", exampleTranslation: "تستورد البلاد النفط من الخارج." },
  { word: "export", translation: "يصدّر", partOfSpeech: "verb", difficulty: "hard", example: "Farmers export fruit to other countries.", exampleTranslation: "يصدّر المزارعون الفاكهة إلى بلدان أخرى." },
  { word: "currency", translation: "عملة", partOfSpeech: "noun", difficulty: "hard", example: "Each country has its own currency.", exampleTranslation: "لكل بلد عملته الخاصة." },
  { word: "budget", translation: "ميزانية", partOfSpeech: "noun", difficulty: "hard", example: "We made a budget for the school trip.", exampleTranslation: "أعددنا ميزانية للرحلة المدرسية." },
  { word: "income", translation: "دخل", partOfSpeech: "noun", difficulty: "hard", example: "A monthly income pays the bills.", exampleTranslation: "يسدّد الدخل الشهري الفواتير." },
  { word: "profit", translation: "ربح", partOfSpeech: "noun", difficulty: "medium", example: "The shop made a small profit.", exampleTranslation: "حقّق المتجر ربحاً صغيراً." },
  { word: "demand", translation: "طلب", partOfSpeech: "noun", difficulty: "medium", example: "There is high demand for water in summer.", exampleTranslation: "هناك طلب كبير على الماء في الصيف." },
  { word: "supply", translation: "عرض/إمداد", partOfSpeech: "noun", difficulty: "medium", example: "The supply of food was enough for all.", exampleTranslation: "كان إمداد الطعام كافياً للجميع." },
  { word: "transport", translation: "نقل", partOfSpeech: "noun", difficulty: "medium", example: "Buses are a cheap form of transport.", exampleTranslation: "الحافلات وسيلة نقل رخيصة." },
  { word: "communication", translation: "تواصل/اتصال", partOfSpeech: "noun", difficulty: "hard", example: "Clear communication prevents mistakes.", exampleTranslation: "يمنع التواصل الواضح الأخطاء." },
  { word: "technology", translation: "تقنية", partOfSpeech: "noun", difficulty: "medium", example: "Technology changes the way we learn.", exampleTranslation: "تغيّر التقنية طريقة تعلّمنا." },
  { word: "ancient", translation: "قديم", partOfSpeech: "adjective", difficulty: "medium", example: "We visited an ancient castle.", exampleTranslation: "زرنا قلعة قديمة." },
  { word: "modern", translation: "حديث", partOfSpeech: "adjective", difficulty: "easy", example: "The city has many modern buildings.", exampleTranslation: "في المدينة مبانٍ حديثة كثيرة." },
  { word: "complex", translation: "معقّد", partOfSpeech: "adjective", difficulty: "hard", example: "The puzzle was too complex for me.", exampleTranslation: "كان اللغز معقّداً جداً بالنسبة لي." },
  { word: "crucial", translation: "حاسم", partOfSpeech: "adjective", difficulty: "hard", example: "Water is crucial for life.", exampleTranslation: "الماء حاسم للحياة." },
  { word: "delicate", translation: "رقيق/حسّاس", partOfSpeech: "adjective", difficulty: "hard", example: "The glass vase is very delicate.", exampleTranslation: "المزهرية الزجاجية رقيقة جداً." },
  { word: "distinct", translation: "متميّز/واضح", partOfSpeech: "adjective", difficulty: "hard", example: "Each twin has a distinct voice.", exampleTranslation: "لكل توأم صوت متميّز." },
  { word: "diverse", translation: "متنوّع", partOfSpeech: "adjective", difficulty: "hard", example: "Our school has a diverse group of students.", exampleTranslation: "في مدرستنا مجموعة متنوّعة من الطلاب." },
  { word: "enormous", translation: "هائل", partOfSpeech: "adjective", difficulty: "medium", example: "The whale is an enormous animal.", exampleTranslation: "الحوت حيوان هائل." },
  { word: "essential", translation: "أساسي", partOfSpeech: "adjective", difficulty: "hard", example: "Sleep is essential for health.", exampleTranslation: "النوم أساسي للصحة." },
  { word: "fragile", translation: "هشّ", partOfSpeech: "adjective", difficulty: "hard", example: "Handle the fragile box with care.", exampleTranslation: "تعامل مع الصندوق الهشّ بحذر." },
  { word: "frequent", translation: "متكرّر", partOfSpeech: "adjective", difficulty: "hard", example: "There are frequent buses to the city.", exampleTranslation: "هناك حافلات متكرّرة إلى المدينة." },
  { word: "generous", translation: "كريم", partOfSpeech: "adjective", difficulty: "medium", example: "She is generous with her time.", exampleTranslation: "هي كريمة بوقتها." },
  { word: "genuine", translation: "أصيل/حقيقي", partOfSpeech: "adjective", difficulty: "hard", example: "He showed a genuine interest in art.", exampleTranslation: "أظهر اهتماماً حقيقياً بالفن." },
  { word: "gradual", translation: "تدريجي", partOfSpeech: "adjective", difficulty: "hard", example: "There was a gradual rise in temperature.", exampleTranslation: "كان هناك ارتفاع تدريجي في درجة الحرارة." },
  { word: "immense", translation: "ضخم", partOfSpeech: "adjective", difficulty: "hard", example: "The desert is an immense space.", exampleTranslation: "الصحراء مساحة ضخمة." },
  { word: "intense", translation: "شديد", partOfSpeech: "adjective", difficulty: "hard", example: "The summer heat was intense.", exampleTranslation: "كان حرّ الصيف شديداً." },
  { word: "obvious", translation: "واضح", partOfSpeech: "adjective", difficulty: "medium", example: "The answer was obvious to everyone.", exampleTranslation: "كانت الإجابة واضحة للجميع." },
  { word: "permanent", translation: "دائم", partOfSpeech: "adjective", difficulty: "hard", example: "They made a permanent home here.", exampleTranslation: "أقاموا منزلاً دائماً هنا." },
  { word: "precious", translation: "ثمين", partOfSpeech: "adjective", difficulty: "medium", example: "Time is a precious gift.", exampleTranslation: "الوقت هدية ثمينة." },
  { word: "rapid", translation: "سريع", partOfSpeech: "adjective", difficulty: "medium", example: "The town saw rapid growth.", exampleTranslation: "شهدت البلدة نمواً سريعاً." },
  { word: "rare", translation: "نادر", partOfSpeech: "adjective", difficulty: "medium", example: "This is a rare and old coin.", exampleTranslation: "هذه عملة نادرة وقديمة." },
  { word: "reliable", translation: "موثوق", partOfSpeech: "adjective", difficulty: "hard", example: "He is a reliable friend.", exampleTranslation: "هو صديق موثوق." },
  { word: "remote", translation: "نائٍ", partOfSpeech: "adjective", difficulty: "hard", example: "They live in a remote village.", exampleTranslation: "يعيشون في قرية نائية." },
  { word: "severe", translation: "قاسٍ/شديد", partOfSpeech: "adjective", difficulty: "hard", example: "A severe storm hit the coast.", exampleTranslation: "ضربت عاصفة شديدة الساحل." },
  { word: "sincere", translation: "صادق/مخلص", partOfSpeech: "adjective", difficulty: "hard", example: "She gave a sincere apology.", exampleTranslation: "قدّمت اعتذاراً صادقاً." },
  { word: "smooth", translation: "أملس/سلس", partOfSpeech: "adjective", difficulty: "easy", example: "The road was flat and smooth.", exampleTranslation: "كان الطريق مستوياً وأملس." },
  { word: "sturdy", translation: "متين", partOfSpeech: "adjective", difficulty: "hard", example: "The table is sturdy and strong.", exampleTranslation: "الطاولة متينة وقوية." },
  { word: "subtle", translation: "خفيّ/دقيق", partOfSpeech: "adjective", difficulty: "hard", example: "There was a subtle change in his voice.", exampleTranslation: "كان هناك تغيّر خفيّ في صوته." },
  { word: "sufficient", translation: "كافٍ", partOfSpeech: "adjective", difficulty: "hard", example: "We had sufficient food for the week.", exampleTranslation: "كان لدينا طعام كافٍ للأسبوع." },
  { word: "superior", translation: "متفوّق/أعلى", partOfSpeech: "adjective", difficulty: "hard", example: "This tool is superior to the old one.", exampleTranslation: "هذه الأداة متفوّقة على القديمة." },
  { word: "temporary", translation: "مؤقّت", partOfSpeech: "adjective", difficulty: "hard", example: "The job was only temporary.", exampleTranslation: "كانت الوظيفة مؤقّتة فقط." },
  { word: "thorough", translation: "شامل/دقيق", partOfSpeech: "adjective", difficulty: "hard", example: "She did a thorough job cleaning.", exampleTranslation: "قامت بعمل شامل في التنظيف." },
  { word: "typical", translation: "نموذجي/معتاد", partOfSpeech: "adjective", difficulty: "hard", example: "This is a typical school day.", exampleTranslation: "هذا يوم دراسي معتاد." },
  { word: "ultimate", translation: "نهائي/أقصى", partOfSpeech: "adjective", difficulty: "hard", example: "Winning was their ultimate goal.", exampleTranslation: "كان الفوز هدفهم النهائي." },
  { word: "unique", translation: "فريد", partOfSpeech: "adjective", difficulty: "medium", example: "Each snowflake has a unique shape.", exampleTranslation: "لكل ندفة ثلج شكل فريد." },
  { word: "urgent", translation: "عاجل", partOfSpeech: "adjective", difficulty: "medium", example: "The message was marked urgent.", exampleTranslation: "وُضعت على الرسالة علامة عاجل." },
  { word: "valuable", translation: "قيّم", partOfSpeech: "adjective", difficulty: "medium", example: "Her advice was very valuable.", exampleTranslation: "كانت نصيحتها قيّمة جداً." },
  { word: "various", translation: "متنوّع/عديد", partOfSpeech: "adjective", difficulty: "medium", example: "The shop sells various kinds of bread.", exampleTranslation: "يبيع المتجر أنواعاً عديدة من الخبز." },
  { word: "vast", translation: "شاسع", partOfSpeech: "adjective", difficulty: "hard", example: "A vast ocean stretched ahead.", exampleTranslation: "امتدّ محيط شاسع أمامنا." },
  { word: "vital", translation: "حيوي/جوهري", partOfSpeech: "adjective", difficulty: "hard", example: "Clean air is vital for everyone.", exampleTranslation: "الهواء النظيف حيوي للجميع." },
  { word: "vivid", translation: "زاهٍ/حيّ", partOfSpeech: "adjective", difficulty: "hard", example: "The painting had vivid colors.", exampleTranslation: "كانت ألوان اللوحة زاهية." },
  { word: "weary", translation: "متعب", partOfSpeech: "adjective", difficulty: "hard", example: "The travelers were weary after the long walk.", exampleTranslation: "كان المسافرون متعبين بعد المشي الطويل." },
  { word: "ambitious", translation: "طموح", partOfSpeech: "adjective", difficulty: "hard", example: "She has an ambitious plan for the future.", exampleTranslation: "لديها خطة طموحة للمستقبل." },
  { word: "anxious", translation: "قلق", partOfSpeech: "adjective", difficulty: "hard", example: "He felt anxious before the test.", exampleTranslation: "شعر بالقلق قبل الاختبار." },
  { word: "cautious", translation: "حذِر", partOfSpeech: "adjective", difficulty: "hard", example: "Be cautious when you cross the road.", exampleTranslation: "كن حذِراً عند عبور الطريق." },
  { word: "courageous", translation: "شجاع", partOfSpeech: "adjective", difficulty: "hard", example: "The courageous girl helped the lost child.", exampleTranslation: "ساعدت الفتاة الشجاعة الطفل التائه." },
  { word: "humble", translation: "متواضع", partOfSpeech: "adjective", difficulty: "medium", example: "The champion stayed humble after winning.", exampleTranslation: "بقي البطل متواضعاً بعد الفوز." },
  { word: "patient", translation: "صبور", partOfSpeech: "adjective", difficulty: "medium", example: "A patient teacher repeats the lesson.", exampleTranslation: "يكرّر المعلّم الصبور الدرس." },
  { word: "polite", translation: "مهذّب", partOfSpeech: "adjective", difficulty: "easy", example: "Always be polite to guests.", exampleTranslation: "كن مهذّباً دائماً مع الضيوف." },
  { word: "honest", translation: "أمين/صادق", partOfSpeech: "adjective", difficulty: "easy", example: "An honest person tells the truth.", exampleTranslation: "الشخص الأمين يقول الحقيقة." },
  { word: "loyal", translation: "وفيّ", partOfSpeech: "adjective", difficulty: "medium", example: "A dog is a loyal friend.", exampleTranslation: "الكلب صديق وفيّ." },
  { word: "diligent", translation: "مجتهد", partOfSpeech: "adjective", difficulty: "hard", example: "The diligent student never gives up.", exampleTranslation: "الطالب المجتهد لا يستسلم أبداً." },
  { word: "cheerful", translation: "مرِح", partOfSpeech: "adjective", difficulty: "medium", example: "Her cheerful smile lifts our mood.", exampleTranslation: "ابتسامتها المرِحة ترفع معنوياتنا." },
  { word: "grateful", translation: "ممتنّ", partOfSpeech: "adjective", difficulty: "medium", example: "I am grateful for your help.", exampleTranslation: "أنا ممتنّ لمساعدتك." },
  { word: "determined", translation: "عازم/مصمّم", partOfSpeech: "adjective", difficulty: "hard", example: "He is determined to finish the race.", exampleTranslation: "هو مصمّم على إنهاء السباق." },
  { word: "independent", translation: "مستقلّ", partOfSpeech: "adjective", difficulty: "hard", example: "She is an independent young writer.", exampleTranslation: "هي كاتبة شابة مستقلّة." },
  { word: "cooperative", translation: "متعاون", partOfSpeech: "adjective", difficulty: "hard", example: "The class was very cooperative today.", exampleTranslation: "كان الصف متعاوناً جداً اليوم." },
  { word: "considerate", translation: "مراعٍ", partOfSpeech: "adjective", difficulty: "hard", example: "It was considerate of you to call.", exampleTranslation: "كان من المراعاة أن تتّصل." },
  { word: "optimistic", translation: "متفائل", partOfSpeech: "adjective", difficulty: "hard", example: "She stayed optimistic about the result.", exampleTranslation: "بقيت متفائلة بشأن النتيجة." },
  { word: "pessimistic", translation: "متشائم", partOfSpeech: "adjective", difficulty: "hard", example: "Try not to be pessimistic about exams.", exampleTranslation: "حاول ألا تكون متشائماً بشأن الامتحانات." },
  { word: "achievement", translation: "إنجاز", partOfSpeech: "noun", difficulty: "medium", example: "Finishing the book was a big achievement.", exampleTranslation: "كان إنهاء الكتاب إنجازاً كبيراً." },
  { word: "ability", translation: "قدرة", partOfSpeech: "noun", difficulty: "medium", example: "She has the ability to lead the team.", exampleTranslation: "لديها القدرة على قيادة الفريق." },
  { word: "attitude", translation: "موقف/سلوك", partOfSpeech: "noun", difficulty: "hard", example: "A positive attitude helps you learn.", exampleTranslation: "الموقف الإيجابي يساعدك على التعلّم." },
  { word: "behavior", translation: "سلوك", partOfSpeech: "noun", difficulty: "medium", example: "Good behavior earns rewards.", exampleTranslation: "السلوك الجيد يكسب المكافآت." },
  { word: "decision", translation: "قرار", partOfSpeech: "noun", difficulty: "medium", example: "Making a decision takes time.", exampleTranslation: "اتخاذ القرار يحتاج إلى وقت." },
  { word: "effort", translation: "جهد", partOfSpeech: "noun", difficulty: "medium", example: "Great effort leads to success.", exampleTranslation: "الجهد الكبير يؤدّي إلى النجاح." },
  { word: "goal", translation: "هدف", partOfSpeech: "noun", difficulty: "easy", example: "Set a clear goal for the year.", exampleTranslation: "ضع هدفاً واضحاً للعام." },
  { word: "habit", translation: "عادة", partOfSpeech: "noun", difficulty: "medium", example: "Reading daily is a good habit.", exampleTranslation: "القراءة يومياً عادة جيدة." },
  { word: "method", translation: "طريقة", partOfSpeech: "noun", difficulty: "medium", example: "This method saves a lot of time.", exampleTranslation: "توفّر هذه الطريقة الكثير من الوقت." },
  { word: "obstacle", translation: "عقبة", partOfSpeech: "noun", difficulty: "hard", example: "Fear can be a big obstacle.", exampleTranslation: "قد يكون الخوف عقبة كبيرة." },
  { word: "opportunity", translation: "فرصة", partOfSpeech: "noun", difficulty: "hard", example: "This trip is a great opportunity.", exampleTranslation: "هذه الرحلة فرصة رائعة." },
  { word: "progress", translation: "تقدّم", partOfSpeech: "noun", difficulty: "medium", example: "She made good progress in math.", exampleTranslation: "أحرزت تقدّماً جيداً في الرياضيات." },
  { word: "approach", translation: "نهج/أسلوب", partOfSpeech: "noun", difficulty: "hard", example: "We tried a new approach to the problem.", exampleTranslation: "جرّبنا نهجاً جديداً للمشكلة." },
  { word: "strategy", translation: "استراتيجية", partOfSpeech: "noun", difficulty: "hard", example: "The team planned a winning strategy.", exampleTranslation: "خطّط الفريق لاستراتيجية رابحة." },
  { word: "success", translation: "نجاح", partOfSpeech: "noun", difficulty: "easy", example: "Hard work brings success.", exampleTranslation: "العمل الجاد يجلب النجاح." },
  { word: "talent", translation: "موهبة", partOfSpeech: "noun", difficulty: "medium", example: "He has a talent for music.", exampleTranslation: "لديه موهبة في الموسيقى." },
  { word: "value", translation: "قيمة", partOfSpeech: "noun", difficulty: "medium", example: "Honesty is an important value.", exampleTranslation: "الأمانة قيمة مهمة." },
  { word: "wisdom", translation: "حكمة", partOfSpeech: "noun", difficulty: "hard", example: "We learn wisdom from experience.", exampleTranslation: "نتعلّم الحكمة من التجربة." },
  { word: "ceremony", translation: "حفل/مراسم", partOfSpeech: "noun", difficulty: "hard", example: "The school held a graduation ceremony.", exampleTranslation: "أقامت المدرسة حفل تخرّج." },
  { word: "festival", translation: "مهرجان", partOfSpeech: "noun", difficulty: "medium", example: "The spring festival lasts three days.", exampleTranslation: "يستمرّ مهرجان الربيع ثلاثة أيام." },
  { word: "religion", translation: "دين", partOfSpeech: "noun", difficulty: "medium", example: "People of every religion lived in peace.", exampleTranslation: "عاش أهل كل دين في سلام." },
  { word: "language", translation: "لغة", partOfSpeech: "noun", difficulty: "easy", example: "Arabic is a rich language.", exampleTranslation: "العربية لغة غنية." },
  { word: "custom", translation: "عُرف/عادة", partOfSpeech: "noun", difficulty: "hard", example: "Removing shoes indoors is their custom.", exampleTranslation: "خلع الأحذية في الداخل من عاداتهم." },
  { word: "generation", translation: "جيل", partOfSpeech: "noun", difficulty: "hard", example: "Each generation shares its stories.", exampleTranslation: "يشارك كل جيل قصصه." },
  { word: "neighborhood", translation: "حيّ", partOfSpeech: "noun", difficulty: "medium", example: "Our neighborhood has a small library.", exampleTranslation: "في حيّنا مكتبة صغيرة." },
  { word: "volunteer", translation: "متطوّع", partOfSpeech: "noun", difficulty: "medium", example: "A volunteer helped at the shelter.", exampleTranslation: "ساعد متطوّع في الملجأ." },
  { word: "charity", translation: "صدقة/عمل خيري", partOfSpeech: "noun", difficulty: "medium", example: "They gave food to a local charity.", exampleTranslation: "تبرّعوا بالطعام لجمعية خيرية محلية." },
  { word: "cooperation", translation: "تعاون", partOfSpeech: "noun", difficulty: "hard", example: "The project needs cooperation from all.", exampleTranslation: "يحتاج المشروع إلى تعاون الجميع." },
  { word: "tolerance", translation: "تسامح", partOfSpeech: "noun", difficulty: "hard", example: "Tolerance helps people of different cultures live together.", exampleTranslation: "يساعد التسامح أهل الثقافات المختلفة على العيش معاً." },
  { word: "harmony", translation: "انسجام/وئام", partOfSpeech: "noun", difficulty: "hard", example: "The neighbors lived in harmony for years.", exampleTranslation: "عاش الجيران في وئام لسنوات." },
  { word: "prosperity", translation: "ازدهار", partOfSpeech: "noun", difficulty: "hard", example: "Trade brought prosperity to the city.", exampleTranslation: "جلبت التجارة الازدهار إلى المدينة." },
  { word: "stability", translation: "استقرار", partOfSpeech: "noun", difficulty: "hard", example: "Peace brings stability to a country.", exampleTranslation: "يجلب السلام الاستقرار للبلاد." }
];
