/** Grade 6 chunk I — advanced descriptive words & verbs (cards 1001-1500, batch 3). */
export const GRADE6_CHUNK_I = [
  { word: "abundant", translation: "وفير", partOfSpeech: "adjective", difficulty: "hard", example: "Water is abundant near the river.", exampleTranslation: "الماء وفير قرب النهر." },
  { word: "adequate", translation: "كافٍ", partOfSpeech: "adjective", difficulty: "hard", example: "We had adequate food for the trip.", exampleTranslation: "كان لدينا طعام كافٍ للرحلة." },
  { word: "adjacent", translation: "مجاور", partOfSpeech: "adjective", difficulty: "hard", example: "The library is adjacent to the lab.", exampleTranslation: "المكتبة مجاورة للمختبر." },
  { word: "artificial", translation: "اصطناعي", partOfSpeech: "adjective", difficulty: "hard", example: "The lake is artificial, not natural.", exampleTranslation: "البحيرة اصطناعية وليست طبيعية." },
  { word: "automatic", translation: "تلقائي", partOfSpeech: "adjective", difficulty: "medium", example: "The door has an automatic lock.", exampleTranslation: "للباب قفل تلقائي." },
  { word: "awkward", translation: "محرج/أخرق", partOfSpeech: "adjective", difficulty: "hard", example: "There was an awkward silence.", exampleTranslation: "ساد صمت محرج." },
  { word: "appropriate", translation: "مناسب", partOfSpeech: "adjective", difficulty: "hard", example: "Wear appropriate shoes for the hike.", exampleTranslation: "ارتدِ حذاءً مناسباً للرحلة." },
  { word: "constant", translation: "ثابت/مستمرّ", partOfSpeech: "adjective", difficulty: "medium", example: "The fan made a constant hum.", exampleTranslation: "أصدرت المروحة طنيناً مستمرّاً." },
  { word: "continuous", translation: "متواصل", partOfSpeech: "adjective", difficulty: "hard", example: "We heard the continuous sound of rain.", exampleTranslation: "سمعنا صوت المطر المتواصل." },
  { word: "dense", translation: "كثيف", partOfSpeech: "adjective", difficulty: "hard", example: "The forest was dark and dense.", exampleTranslation: "كانت الغابة مظلمة وكثيفة." },
  { word: "durable", translation: "متين/مُعمِّر", partOfSpeech: "adjective", difficulty: "hard", example: "These boots are strong and durable.", exampleTranslation: "هذا الحذاء قوي ومتين." },
  { word: "dynamic", translation: "ديناميكي/نشِط", partOfSpeech: "adjective", difficulty: "hard", example: "She is a dynamic young leader.", exampleTranslation: "هي قائدة شابة نشِطة." },
  { word: "evident", translation: "جليّ/واضح", partOfSpeech: "adjective", difficulty: "hard", example: "His joy was evident to all.", exampleTranslation: "كان فرحه جليّاً للجميع." },
  { word: "exotic", translation: "غريب/غير مألوف", partOfSpeech: "adjective", difficulty: "hard", example: "The market sold exotic fruit.", exampleTranslation: "باع السوق فاكهة غير مألوفة." },
  { word: "external", translation: "خارجي", partOfSpeech: "adjective", difficulty: "hard", example: "The external wall needs paint.", exampleTranslation: "يحتاج الجدار الخارجي إلى طلاء." },
  { word: "internal", translation: "داخلي", partOfSpeech: "adjective", difficulty: "hard", example: "The internal parts stayed clean.", exampleTranslation: "بقيت الأجزاء الداخلية نظيفة." },
  { word: "fertile", translation: "خصب", partOfSpeech: "adjective", difficulty: "hard", example: "The valley has fertile soil.", exampleTranslation: "للوادي تربة خصبة." },
  { word: "fundamental", translation: "أساسي", partOfSpeech: "adjective", difficulty: "hard", example: "Reading is a fundamental skill.", exampleTranslation: "القراءة مهارة أساسية." },
  { word: "gigantic", translation: "هائل/ضخم", partOfSpeech: "adjective", difficulty: "hard", example: "A gigantic wave hit the shore.", exampleTranslation: "ضربت موجة هائلة الشاطئ." },
  { word: "hollow", translation: "أجوف", partOfSpeech: "adjective", difficulty: "hard", example: "The old tree was hollow inside.", exampleTranslation: "كانت الشجرة العجوز جوفاء من الداخل." },
  { word: "identical", translation: "متطابق", partOfSpeech: "adjective", difficulty: "hard", example: "The twins wore identical hats.", exampleTranslation: "ارتدى التوأمان قبّعتين متطابقتين." },
  { word: "infinite", translation: "لا نهائي", partOfSpeech: "adjective", difficulty: "hard", example: "The night sky seemed infinite.", exampleTranslation: "بدت سماء الليل لا نهائية." },
  { word: "initial", translation: "أوّلي/مبدئي", partOfSpeech: "adjective", difficulty: "hard", example: "My initial plan was too simple.", exampleTranslation: "كانت خطتي الأوّلية بسيطة جداً." },
  { word: "invisible", translation: "غير مرئي", partOfSpeech: "adjective", difficulty: "medium", example: "Air is invisible but real.", exampleTranslation: "الهواء غير مرئي لكنه حقيقي." },
  { word: "massive", translation: "ضخم/هائل", partOfSpeech: "adjective", difficulty: "medium", example: "A massive rock blocked the path.", exampleTranslation: "سدّت صخرة ضخمة الطريق." },
  { word: "mature", translation: "ناضج", partOfSpeech: "adjective", difficulty: "hard", example: "He is mature for his age.", exampleTranslation: "هو ناضج بالنسبة لعمره." },
  { word: "mobile", translation: "متنقّل/محمول", partOfSpeech: "adjective", difficulty: "medium", example: "The clinic uses a mobile unit.", exampleTranslation: "تستخدم العيادة وحدة متنقّلة." },
  { word: "moderate", translation: "معتدل", partOfSpeech: "adjective", difficulty: "hard", example: "The weather today is moderate.", exampleTranslation: "الطقس اليوم معتدل." },
  { word: "mutual", translation: "متبادل", partOfSpeech: "adjective", difficulty: "hard", example: "They share a mutual respect.", exampleTranslation: "يتشاركان احتراماً متبادلاً." },
  { word: "numerous", translation: "عديد", partOfSpeech: "adjective", difficulty: "hard", example: "She asked numerous questions.", exampleTranslation: "طرحت أسئلة عديدة." },
  { word: "optimal", translation: "أمثل", partOfSpeech: "adjective", difficulty: "hard", example: "Noon is the optimal time to plant.", exampleTranslation: "الظهر هو الوقت الأمثل للزراعة." },
  { word: "partial", translation: "جزئي", partOfSpeech: "adjective", difficulty: "hard", example: "We had only partial success.", exampleTranslation: "حقّقنا نجاحاً جزئياً فقط." },
  { word: "peculiar", translation: "غريب/شاذّ", partOfSpeech: "adjective", difficulty: "hard", example: "The plant had a peculiar smell.", exampleTranslation: "كان للنبات رائحة غريبة." },
  { word: "portable", translation: "محمول/قابل للنقل", partOfSpeech: "adjective", difficulty: "hard", example: "A portable radio fits in a bag.", exampleTranslation: "يتّسع راديو محمول في حقيبة." },
  { word: "potential", translation: "كامن/محتمل", partOfSpeech: "adjective", difficulty: "hard", example: "She has great potential in math.", exampleTranslation: "لديها إمكانات كبيرة في الرياضيات." },
  { word: "practical", translation: "عملي", partOfSpeech: "adjective", difficulty: "medium", example: "Give me a practical solution.", exampleTranslation: "أعطني حلّاً عملياً." },
  { word: "precise", translation: "دقيق", partOfSpeech: "adjective", difficulty: "hard", example: "We need a precise measurement.", exampleTranslation: "نحتاج إلى قياس دقيق." },
  { word: "prominent", translation: "بارز", partOfSpeech: "adjective", difficulty: "hard", example: "He is a prominent scientist.", exampleTranslation: "هو عالِم بارز." },
  { word: "prompt", translation: "سريع/فوري", partOfSpeech: "adjective", difficulty: "hard", example: "Thank you for your prompt reply.", exampleTranslation: "شكراً على ردّك السريع." },
  { word: "random", translation: "عشوائي", partOfSpeech: "adjective", difficulty: "medium", example: "She picked a random card.", exampleTranslation: "اختارت بطاقة عشوائية." },
  { word: "remarkable", translation: "لافت/مدهش", partOfSpeech: "adjective", difficulty: "hard", example: "The team made remarkable progress.", exampleTranslation: "أحرز الفريق تقدّماً مدهشاً." },
  { word: "rigid", translation: "صلب/جامد", partOfSpeech: "adjective", difficulty: "hard", example: "The frame is rigid and firm.", exampleTranslation: "الإطار صلب وثابت." },
  { word: "robust", translation: "قوي/متين", partOfSpeech: "adjective", difficulty: "hard", example: "The bridge has a robust design.", exampleTranslation: "للجسر تصميم متين." },
  { word: "scarce", translation: "نادر/شحيح", partOfSpeech: "adjective", difficulty: "hard", example: "Clean water is scarce in the desert.", exampleTranslation: "الماء النظيف شحيح في الصحراء." },
  { word: "sensitive", translation: "حسّاس", partOfSpeech: "adjective", difficulty: "medium", example: "Eyes are sensitive to bright light.", exampleTranslation: "العيون حسّاسة للضوء الساطع." },
  { word: "sole", translation: "وحيد", partOfSpeech: "adjective", difficulty: "hard", example: "He was the sole winner.", exampleTranslation: "كان الفائز الوحيد." },
  { word: "spacious", translation: "فسيح", partOfSpeech: "adjective", difficulty: "hard", example: "The new hall is bright and spacious.", exampleTranslation: "القاعة الجديدة مضيئة وفسيحة." },
  { word: "stable", translation: "مستقرّ/ثابت", partOfSpeech: "adjective", difficulty: "medium", example: "The ladder must be stable.", exampleTranslation: "يجب أن يكون السلّم ثابتاً." },
  { word: "steep", translation: "شديد الانحدار", partOfSpeech: "adjective", difficulty: "medium", example: "We climbed a steep path.", exampleTranslation: "تسلّقنا درباً شديد الانحدار." },
  { word: "substantial", translation: "كبير/جوهري", partOfSpeech: "adjective", difficulty: "hard", example: "They made a substantial change.", exampleTranslation: "أحدثوا تغييراً كبيراً." },
  { word: "sustainable", translation: "مستدام", partOfSpeech: "adjective", difficulty: "hard", example: "Solar power is a sustainable choice.", exampleTranslation: "الطاقة الشمسية خيار مستدام." },
  { word: "synthetic", translation: "صناعي/مُصنّع", partOfSpeech: "adjective", difficulty: "hard", example: "The rope is made of synthetic fiber.", exampleTranslation: "الحبل مصنوع من ألياف صناعية." },
  { word: "systematic", translation: "منهجي/منظّم", partOfSpeech: "adjective", difficulty: "hard", example: "We took a systematic approach.", exampleTranslation: "اتّبعنا نهجاً منهجياً." },
  { word: "tangible", translation: "ملموس", partOfSpeech: "adjective", difficulty: "hard", example: "We saw tangible results.", exampleTranslation: "رأينا نتائج ملموسة." },
  { word: "theoretical", translation: "نظري", partOfSpeech: "adjective", difficulty: "hard", example: "The idea is only theoretical so far.", exampleTranslation: "الفكرة نظرية فقط حتى الآن." },
  { word: "tropical", translation: "استوائي", partOfSpeech: "adjective", difficulty: "medium", example: "Bananas grow in tropical climates.", exampleTranslation: "ينمو الموز في المناخات الاستوائية." },
  { word: "uniform", translation: "موحّد/منتظم", partOfSpeech: "adjective", difficulty: "hard", example: "The tiles are a uniform size.", exampleTranslation: "البلاط بحجم موحّد." },
  { word: "universal", translation: "عالمي/شامل", partOfSpeech: "adjective", difficulty: "hard", example: "Music is a universal language.", exampleTranslation: "الموسيقى لغة عالمية." },
  { word: "vacant", translation: "شاغر/خالٍ", partOfSpeech: "adjective", difficulty: "hard", example: "The seat beside me was vacant.", exampleTranslation: "كان المقعد بجانبي شاغراً." },
  { word: "vague", translation: "غامض/مبهم", partOfSpeech: "adjective", difficulty: "hard", example: "His answer was too vague.", exampleTranslation: "كانت إجابته مبهمة جداً." },
  { word: "versatile", translation: "متعدّد الاستخدامات", partOfSpeech: "adjective", difficulty: "hard", example: "A spoon is a versatile tool.", exampleTranslation: "الملعقة أداة متعدّدة الاستخدامات." },
  { word: "vigorous", translation: "قوي/نشيط", partOfSpeech: "adjective", difficulty: "hard", example: "He took a vigorous morning walk.", exampleTranslation: "قام بمشي صباحي نشيط." },
  { word: "visible", translation: "مرئي/ظاهر", partOfSpeech: "adjective", difficulty: "medium", example: "The stars are visible tonight.", exampleTranslation: "النجوم مرئية الليلة." },
  { word: "accelerate", translation: "يسرّع", partOfSpeech: "verb", difficulty: "hard", example: "The car began to accelerate.", exampleTranslation: "بدأت السيارة تتسارع." },
  { word: "accommodate", translation: "يستوعب/يؤوي", partOfSpeech: "verb", difficulty: "hard", example: "The hall can accommodate two hundred people.", exampleTranslation: "تستوعب القاعة مئتي شخص." },
  { word: "activate", translation: "يفعّل", partOfSpeech: "verb", difficulty: "hard", example: "Press the button to activate the alarm.", exampleTranslation: "اضغط الزر لتفعيل الإنذار." },
  { word: "ascend", translation: "يصعد", partOfSpeech: "verb", difficulty: "hard", example: "The climbers ascend the steep cliff.", exampleTranslation: "يصعد المتسلّقون المنحدر الحادّ." },
  { word: "descend", translation: "ينزل", partOfSpeech: "verb", difficulty: "hard", example: "We descend the stairs slowly.", exampleTranslation: "ننزل الدرج ببطء." },
  { word: "aspire", translation: "يطمح", partOfSpeech: "verb", difficulty: "hard", example: "She aspires to become a doctor.", exampleTranslation: "تطمح لأن تصبح طبيبة." },
  { word: "assert", translation: "يؤكّد بحزم", partOfSpeech: "verb", difficulty: "hard", example: "He asserted that the plan would work.", exampleTranslation: "أكّد بحزم أن الخطة ستنجح." },
  { word: "coincide", translation: "يتزامن", partOfSpeech: "verb", difficulty: "hard", example: "The festival coincides with the harvest.", exampleTranslation: "يتزامن المهرجان مع الحصاد." },
  { word: "collapse", translation: "ينهار", partOfSpeech: "verb", difficulty: "hard", example: "The old shed began to collapse.", exampleTranslation: "بدأ السقيفة القديمة تنهار." },
  { word: "comply", translation: "يمتثل", partOfSpeech: "verb", difficulty: "hard", example: "Drivers must comply with the rules.", exampleTranslation: "يجب على السائقين الامتثال للقواعد." },
  { word: "conceal", translation: "يخفي", partOfSpeech: "verb", difficulty: "hard", example: "The fog conceals the mountains.", exampleTranslation: "يخفي الضباب الجبال." },
  { word: "confront", translation: "يواجه", partOfSpeech: "verb", difficulty: "hard", example: "She had to confront her fear.", exampleTranslation: "كان عليها أن تواجه خوفها." },
  { word: "conquer", translation: "يقهر/يفتح", partOfSpeech: "verb", difficulty: "hard", example: "They worked hard to conquer the peak.", exampleTranslation: "عملوا بجدّ لقهر القمة." },
  { word: "coordinate", translation: "ينسّق", partOfSpeech: "verb", difficulty: "hard", example: "She will coordinate the school trip.", exampleTranslation: "ستنسّق الرحلة المدرسية." },
  { word: "dedicate", translation: "يكرّس/يهدي", partOfSpeech: "verb", difficulty: "hard", example: "He dedicated the book to his teacher.", exampleTranslation: "أهدى الكتاب إلى معلّمه." },
  { word: "depict", translation: "يصوّر", partOfSpeech: "verb", difficulty: "hard", example: "The painting depicts a calm sea.", exampleTranslation: "تصوّر اللوحة بحراً هادئاً." },
  { word: "diminish", translation: "يتناقص/يقلّل", partOfSpeech: "verb", difficulty: "hard", example: "The noise began to diminish.", exampleTranslation: "بدأت الضوضاء تتناقص." },
  { word: "dominate", translation: "يهيمن", partOfSpeech: "verb", difficulty: "hard", example: "Tall trees dominate the forest.", exampleTranslation: "تهيمن الأشجار الطويلة على الغابة." },
  { word: "eliminate", translation: "يزيل/يستبعد", partOfSpeech: "verb", difficulty: "hard", example: "We must eliminate the errors.", exampleTranslation: "علينا أن نزيل الأخطاء." },
  { word: "emerge", translation: "يظهر/يبرز", partOfSpeech: "verb", difficulty: "hard", example: "The sun emerged from the clouds.", exampleTranslation: "برزت الشمس من الغيوم." },
  { word: "emit", translation: "يطلق/يبعث", partOfSpeech: "verb", difficulty: "hard", example: "The lamp emits a warm glow.", exampleTranslation: "يبعث المصباح توهّجاً دافئاً." },
  { word: "encounter", translation: "يصادف/يلتقي", partOfSpeech: "verb", difficulty: "hard", example: "We may encounter deer in the woods.", exampleTranslation: "قد نصادف غزلاناً في الغابة." },
  { word: "endorse", translation: "يؤيّد/يصادق", partOfSpeech: "verb", difficulty: "hard", example: "Many teachers endorse the new book.", exampleTranslation: "يؤيّد كثير من المعلّمين الكتاب الجديد." },
  { word: "enforce", translation: "يطبّق/يفرض", partOfSpeech: "verb", difficulty: "hard", example: "Guards enforce the park rules.", exampleTranslation: "يطبّق الحرّاس قواعد الحديقة." },
  { word: "enhance", translation: "يعزّز/يحسّن", partOfSpeech: "verb", difficulty: "hard", example: "Music can enhance your mood.", exampleTranslation: "يمكن للموسيقى أن تحسّن مزاجك." },
  { word: "enrich", translation: "يُثري", partOfSpeech: "verb", difficulty: "hard", example: "Travel can enrich your mind.", exampleTranslation: "يمكن للسفر أن يُثري عقلك." },
  { word: "ensure", translation: "يضمن", partOfSpeech: "verb", difficulty: "hard", example: "Check twice to ensure safety.", exampleTranslation: "تحقّق مرتين لتضمن السلامة." },
  { word: "exceed", translation: "يتجاوز", partOfSpeech: "verb", difficulty: "hard", example: "Do not exceed the speed limit.", exampleTranslation: "لا تتجاوز حدّ السرعة." },
  { word: "exhibit", translation: "يعرض", partOfSpeech: "verb", difficulty: "hard", example: "The gallery exhibits new art.", exampleTranslation: "تعرض الصالة فنّاً جديداً." },
  { word: "facilitate", translation: "يسهّل", partOfSpeech: "verb", difficulty: "hard", example: "Good tools facilitate the work.", exampleTranslation: "تسهّل الأدوات الجيدة العمل." },
  { word: "fascinate", translation: "يفتن/يبهر", partOfSpeech: "verb", difficulty: "hard", example: "Space stories fascinate children.", exampleTranslation: "تبهر قصص الفضاء الأطفال." },
  { word: "flourish", translation: "يزدهر", partOfSpeech: "verb", difficulty: "hard", example: "Plants flourish in rich soil.", exampleTranslation: "تزدهر النباتات في التربة الغنية." },
  { word: "foster", translation: "يرعى/يعزّز", partOfSpeech: "verb", difficulty: "hard", example: "Reading clubs foster a love of books.", exampleTranslation: "تعزّز أندية القراءة حبّ الكتب." },
  { word: "fulfill", translation: "يحقّق/يفي بـ", partOfSpeech: "verb", difficulty: "hard", example: "She worked hard to fulfill her dream.", exampleTranslation: "عملت بجدّ لتحقيق حلمها." },
  { word: "grasp", translation: "يمسك/يستوعب", partOfSpeech: "verb", difficulty: "hard", example: "He quickly grasped the idea.", exampleTranslation: "استوعب الفكرة بسرعة." },
  { word: "hinder", translation: "يعرقل", partOfSpeech: "verb", difficulty: "hard", example: "Heavy bags hinder the climbers.", exampleTranslation: "تعرقل الحقائب الثقيلة المتسلّقين." },
  { word: "ignite", translation: "يشعل", partOfSpeech: "verb", difficulty: "hard", example: "A spark can ignite dry grass.", exampleTranslation: "قد تشعل شرارة العشب الجاف." },
  { word: "illuminate", translation: "يضيء", partOfSpeech: "verb", difficulty: "hard", example: "Lamps illuminate the dark hall.", exampleTranslation: "تضيء المصابيح القاعة المظلمة." },
  { word: "impose", translation: "يفرض", partOfSpeech: "verb", difficulty: "hard", example: "They impose a fine for litter.", exampleTranslation: "يفرضون غرامة على رمي القمامة." },
  { word: "induce", translation: "يحفّز/يستحثّ", partOfSpeech: "verb", difficulty: "hard", example: "Warm milk can induce sleep.", exampleTranslation: "قد يستحثّ الحليب الدافئ النوم." },
  { word: "inhabit", translation: "يسكن/يقطن", partOfSpeech: "verb", difficulty: "hard", example: "Penguins inhabit cold lands.", exampleTranslation: "تقطن البطاريق الأراضي الباردة." },
  { word: "initiate", translation: "يبدأ/يستهلّ", partOfSpeech: "verb", difficulty: "hard", example: "They will initiate the cleanup today.", exampleTranslation: "سيبدأون عملية التنظيف اليوم." },
  { word: "innovate", translation: "يبتكر", partOfSpeech: "verb", difficulty: "hard", example: "Good companies always innovate.", exampleTranslation: "تبتكر الشركات الجيدة دائماً." },
  { word: "inquire", translation: "يستفسر", partOfSpeech: "verb", difficulty: "hard", example: "She inquired about the train time.", exampleTranslation: "استفسرت عن موعد القطار." },
  { word: "intervene", translation: "يتدخّل", partOfSpeech: "verb", difficulty: "hard", example: "A teacher intervened to stop the fight.", exampleTranslation: "تدخّل معلّم لإيقاف الشجار." },
  { word: "isolate", translation: "يعزل", partOfSpeech: "verb", difficulty: "hard", example: "We isolate the sick plant from the rest.", exampleTranslation: "نعزل النبتة المريضة عن البقية." },
  { word: "magnify", translation: "يكبّر", partOfSpeech: "verb", difficulty: "hard", example: "A lens can magnify small print.", exampleTranslation: "تستطيع العدسة تكبير الطباعة الصغيرة." },
  { word: "manipulate", translation: "يتلاعب/يتحكّم", partOfSpeech: "verb", difficulty: "hard", example: "She can manipulate the puppet's strings.", exampleTranslation: "تستطيع التحكّم بخيوط الدمية." },
  { word: "mediate", translation: "يتوسّط", partOfSpeech: "verb", difficulty: "hard", example: "The teacher mediated between the two boys.", exampleTranslation: "توسّط المعلّم بين الصبيين." },
  { word: "merge", translation: "يدمج/يندمج", partOfSpeech: "verb", difficulty: "hard", example: "The two rivers merge near the town.", exampleTranslation: "يندمج النهران قرب البلدة." },
  { word: "motivate", translation: "يحفّز", partOfSpeech: "verb", difficulty: "hard", example: "A good coach can motivate the team.", exampleTranslation: "يستطيع المدرّب الجيد تحفيز الفريق." },
  { word: "nourish", translation: "يغذّي", partOfSpeech: "verb", difficulty: "hard", example: "Fresh food nourishes the body.", exampleTranslation: "يغذّي الطعام الطازج الجسم." },
  { word: "obscure", translation: "يحجب/غامض", partOfSpeech: "verb", difficulty: "hard", example: "Clouds obscure the moon tonight.", exampleTranslation: "تحجب الغيوم القمر الليلة." },
  { word: "originate", translation: "ينشأ/يبدأ من", partOfSpeech: "verb", difficulty: "hard", example: "The river originates in the mountains.", exampleTranslation: "ينبع النهر من الجبال." },
  { word: "overlap", translation: "يتداخل", partOfSpeech: "verb", difficulty: "hard", example: "The two schedules overlap on Monday.", exampleTranslation: "يتداخل الجدولان يوم الاثنين." },
  { word: "overwhelm", translation: "يغمر/يطغى", partOfSpeech: "verb", difficulty: "hard", example: "The huge task can overwhelm a beginner.", exampleTranslation: "قد تطغى المهمة الضخمة على المبتدئ." },
  { word: "penetrate", translation: "يخترق", partOfSpeech: "verb", difficulty: "hard", example: "Sunlight cannot penetrate the thick roof.", exampleTranslation: "لا يستطيع ضوء الشمس اختراق السقف السميك." },
  { word: "portray", translation: "يصوّر/يجسّد", partOfSpeech: "verb", difficulty: "hard", example: "The actor portrays a brave hero.", exampleTranslation: "يجسّد الممثّل بطلاً شجاعاً." },
  { word: "postpone", translation: "يؤجّل", partOfSpeech: "verb", difficulty: "hard", example: "They had to postpone the game.", exampleTranslation: "اضطروا إلى تأجيل المباراة." },
  { word: "proceed", translation: "يتابع/يمضي", partOfSpeech: "verb", difficulty: "hard", example: "Please proceed to the next step.", exampleTranslation: "من فضلك انتقل إلى الخطوة التالية." },
  { word: "prohibit", translation: "يمنع/يحظر", partOfSpeech: "verb", difficulty: "hard", example: "Signs prohibit swimming here.", exampleTranslation: "تحظر اللافتات السباحة هنا." },
  { word: "prolong", translation: "يطيل", partOfSpeech: "verb", difficulty: "hard", example: "Rest can prolong the life of the engine.", exampleTranslation: "قد تطيل الراحة عمر المحرّك." },
  { word: "prosper", translation: "يزدهر/يفلح", partOfSpeech: "verb", difficulty: "hard", example: "The town began to prosper after the road opened.", exampleTranslation: "بدأت البلدة تزدهر بعد افتتاح الطريق." },
  { word: "provoke", translation: "يستفزّ/يثير", partOfSpeech: "verb", difficulty: "hard", example: "Do not provoke the guard dog.", exampleTranslation: "لا تستفزّ الكلب الحارس." },
  { word: "reinforce", translation: "يعزّز/يقوّي", partOfSpeech: "verb", difficulty: "hard", example: "Steel bars reinforce the wall.", exampleTranslation: "تقوّي القضبان الفولاذية الجدار." },
  { word: "render", translation: "يجعل/يقدّم", partOfSpeech: "verb", difficulty: "hard", example: "The storm rendered the road unsafe.", exampleTranslation: "جعلت العاصفة الطريق غير آمن." },
  { word: "replicate", translation: "يكرّر/يستنسخ", partOfSpeech: "verb", difficulty: "hard", example: "We tried to replicate the experiment.", exampleTranslation: "حاولنا تكرار التجربة." },
  { word: "resemble", translation: "يشبه", partOfSpeech: "verb", difficulty: "hard", example: "The cloud resembles a ship.", exampleTranslation: "تشبه السحابة سفينة." },
  { word: "restore", translation: "يرمّم/يستعيد", partOfSpeech: "verb", difficulty: "hard", example: "They restored the old painting.", exampleTranslation: "رمّموا اللوحة القديمة." },
  { word: "retain", translation: "يحتفظ بـ", partOfSpeech: "verb", difficulty: "hard", example: "Dry soil cannot retain water.", exampleTranslation: "لا تستطيع التربة الجافة الاحتفاظ بالماء." },
  { word: "retrieve", translation: "يسترجع", partOfSpeech: "verb", difficulty: "hard", example: "The dog retrieves the ball.", exampleTranslation: "يسترجع الكلب الكرة." },
  { word: "simulate", translation: "يحاكي", partOfSpeech: "verb", difficulty: "hard", example: "The game can simulate real flying.", exampleTranslation: "تستطيع اللعبة محاكاة الطيران الحقيقي." },
  { word: "specialize", translation: "يتخصّص", partOfSpeech: "verb", difficulty: "hard", example: "She wants to specialize in biology.", exampleTranslation: "تريد أن تتخصّص في الأحياء." },
  { word: "stimulate", translation: "يحفّز/ينشّط", partOfSpeech: "verb", difficulty: "hard", example: "Puzzles stimulate the brain.", exampleTranslation: "تنشّط الألغاز الدماغ." },
  { word: "strive", translation: "يجاهد/يسعى", partOfSpeech: "verb", difficulty: "hard", example: "We strive to do our best.", exampleTranslation: "نسعى لنفعل أفضل ما لدينا." },
  { word: "substitute", translation: "يستبدل/بديل", partOfSpeech: "verb", difficulty: "hard", example: "You can substitute honey for sugar.", exampleTranslation: "يمكنك استبدال العسل بالسكّر." },
  { word: "supervise", translation: "يشرف على", partOfSpeech: "verb", difficulty: "hard", example: "A teacher supervises the playground.", exampleTranslation: "يشرف معلّم على الملعب." },
  { word: "suppress", translation: "يكبت/يقمع", partOfSpeech: "verb", difficulty: "hard", example: "He tried to suppress a laugh.", exampleTranslation: "حاول أن يكبت ضحكة." },
  { word: "sustain", translation: "يديم/يحافظ على", partOfSpeech: "verb", difficulty: "hard", example: "Rain helps sustain the forest.", exampleTranslation: "يساعد المطر على إدامة الغابة." },
  { word: "terminate", translation: "ينهي", partOfSpeech: "verb", difficulty: "hard", example: "They will terminate the contract.", exampleTranslation: "سينهون العقد." },
  { word: "thrive", translation: "يزدهر/ينمو جيداً", partOfSpeech: "verb", difficulty: "hard", example: "Cacti thrive in dry places.", exampleTranslation: "يزدهر الصبّار في الأماكن الجافة." },
  { word: "transmit", translation: "ينقل/يبثّ", partOfSpeech: "verb", difficulty: "hard", example: "The tower transmits a clear signal.", exampleTranslation: "يبثّ البرج إشارة واضحة." },
  { word: "undergo", translation: "يخضع لـ", partOfSpeech: "verb", difficulty: "hard", example: "The bridge will undergo repairs.", exampleTranslation: "سيخضع الجسر للإصلاحات." },
  { word: "undermine", translation: "يقوّض", partOfSpeech: "verb", difficulty: "hard", example: "Doubt can undermine your effort.", exampleTranslation: "قد يقوّض الشكّ جهدك." },
  { word: "unify", translation: "يوحّد", partOfSpeech: "verb", difficulty: "hard", example: "A common goal can unify the team.", exampleTranslation: "قد يوحّد هدف مشترك الفريق." },
  { word: "uphold", translation: "يدعم/يصون", partOfSpeech: "verb", difficulty: "hard", example: "Judges uphold the law.", exampleTranslation: "يصون القضاة القانون." },
  { word: "withstand", translation: "يصمد أمام", partOfSpeech: "verb", difficulty: "hard", example: "The tent can withstand strong wind.", exampleTranslation: "تستطيع الخيمة الصمود أمام الرياح القوية." },
  { word: "diagnose", translation: "يشخّص", partOfSpeech: "verb", difficulty: "hard", example: "The doctor will diagnose the illness.", exampleTranslation: "سيشخّص الطبيب المرض." },
  { word: "evolve", translation: "يتطوّر", partOfSpeech: "verb", difficulty: "hard", example: "Languages evolve over many years.", exampleTranslation: "تتطوّر اللغات عبر سنوات كثيرة." },
  { word: "exploit", translation: "يستغلّ", partOfSpeech: "verb", difficulty: "hard", example: "We should not exploit natural resources.", exampleTranslation: "يجب ألا نستغلّ الموارد الطبيعية." },
  { word: "speculate", translation: "يتكهّن", partOfSpeech: "verb", difficulty: "hard", example: "People speculate about the result.", exampleTranslation: "يتكهّن الناس بالنتيجة." },
  { word: "yearn", translation: "يتوق", partOfSpeech: "verb", difficulty: "hard", example: "The sailors yearn for home.", exampleTranslation: "يتوق البحّارة إلى الوطن." },
  { word: "withhold", translation: "يحجب/يمتنع عن", partOfSpeech: "verb", difficulty: "hard", example: "Do not withhold important facts.", exampleTranslation: "لا تحجب الحقائق المهمة." },
  { word: "testify", translation: "يشهد", partOfSpeech: "verb", difficulty: "hard", example: "A witness will testify in court.", exampleTranslation: "سيشهد شاهد في المحكمة." },
  { word: "traverse", translation: "يجتاز/يعبر", partOfSpeech: "verb", difficulty: "hard", example: "They traverse the wide desert by camel.", exampleTranslation: "يجتازون الصحراء الواسعة على الجِمال." },
  { word: "summon", translation: "يستدعي", partOfSpeech: "verb", difficulty: "hard", example: "The king summoned his advisors.", exampleTranslation: "استدعى الملك مستشاريه." },
  { word: "reconcile", translation: "يصالح/يوفّق", partOfSpeech: "verb", difficulty: "hard", example: "The friends reconciled after the quarrel.", exampleTranslation: "تصالح الصديقان بعد الخصام." },
  { word: "advocate", translation: "يناصر/يدعو إلى", partOfSpeech: "verb", difficulty: "hard", example: "They advocate for cleaner streets.", exampleTranslation: "يناصرون نظافة الشوارع." }
];
