/** Grade 6 chunk E — earth, weather, animals, body & health (cards 501-1000, batch 2). */
export const GRADE6_CHUNK_E = [
  { word: "breeze", translation: "نسيم", partOfSpeech: "noun", difficulty: "medium", example: "A cool breeze blew across the beach.", exampleTranslation: "هبّ نسيم بارد عبر الشاطئ." },
  { word: "drought", translation: "جفاف", partOfSpeech: "noun", difficulty: "hard", example: "The long drought dried up the river.", exampleTranslation: "جفّف الجفاف الطويل النهر." },
  { word: "flood", translation: "فيضان", partOfSpeech: "noun", difficulty: "medium", example: "The flood covered the low fields.", exampleTranslation: "غطّى الفيضان الحقول المنخفضة." },
  { word: "frost", translation: "صقيع", partOfSpeech: "noun", difficulty: "hard", example: "Frost covered the grass at dawn.", exampleTranslation: "غطّى الصقيع العشب عند الفجر." },
  { word: "humidity", translation: "رطوبة", partOfSpeech: "noun", difficulty: "hard", example: "The humidity made the air feel heavy.", exampleTranslation: "جعلت الرطوبة الهواء ثقيلاً." },
  { word: "hurricane", translation: "إعصار", partOfSpeech: "noun", difficulty: "hard", example: "The hurricane tore the roofs off houses.", exampleTranslation: "اقتلع الإعصار أسقف المنازل." },
  { word: "lightning", translation: "برق", partOfSpeech: "noun", difficulty: "medium", example: "Lightning flashed across the dark sky.", exampleTranslation: "ومض البرق عبر السماء المظلمة." },
  { word: "thunder", translation: "رعد", partOfSpeech: "noun", difficulty: "medium", example: "The thunder was loud after the flash.", exampleTranslation: "كان الرعد عالياً بعد الومضة." },
  { word: "tornado", translation: "زوبعة", partOfSpeech: "noun", difficulty: "hard", example: "A tornado spun across the open plain.", exampleTranslation: "دارت زوبعة عبر السهل المفتوح." },
  { word: "blizzard", translation: "عاصفة ثلجية", partOfSpeech: "noun", difficulty: "hard", example: "The blizzard closed every road in town.", exampleTranslation: "أغلقت العاصفة الثلجية كل طرق البلدة." },
  { word: "mist", translation: "ضباب خفيف", partOfSpeech: "noun", difficulty: "medium", example: "A thin mist hung over the lake.", exampleTranslation: "علّق ضباب خفيف فوق البحيرة." },
  { word: "fog", translation: "ضباب", partOfSpeech: "noun", difficulty: "easy", example: "Thick fog hid the mountain road.", exampleTranslation: "أخفى الضباب الكثيف طريق الجبل." },
  { word: "rainbow", translation: "قوس قزح", partOfSpeech: "noun", difficulty: "easy", example: "A rainbow appeared after the rain.", exampleTranslation: "ظهر قوس قزح بعد المطر." },
  { word: "canyon", translation: "وادٍ سحيق", partOfSpeech: "noun", difficulty: "hard", example: "The river cut a deep canyon over time.", exampleTranslation: "حفر النهر وادياً سحيقاً مع الوقت." },
  { word: "cliff", translation: "منحدر صخري", partOfSpeech: "noun", difficulty: "medium", example: "Birds nested high on the cliff.", exampleTranslation: "عشّشت الطيور عالياً على المنحدر الصخري." },
  { word: "coast", translation: "ساحل", partOfSpeech: "noun", difficulty: "medium", example: "We drove along the rocky coast.", exampleTranslation: "قُدنا السيارة على طول الساحل الصخري." },
  { word: "dune", translation: "كثيب رملي", partOfSpeech: "noun", difficulty: "hard", example: "The wind shaped a tall sand dune.", exampleTranslation: "شكّلت الرياح كثيباً رملياً عالياً." },
  { word: "harbor", translation: "ميناء", partOfSpeech: "noun", difficulty: "medium", example: "Boats rested safely in the harbor.", exampleTranslation: "رست القوارب بأمان في الميناء." },
  { word: "island", translation: "جزيرة", partOfSpeech: "noun", difficulty: "easy", example: "A small island sat in the bay.", exampleTranslation: "كانت جزيرة صغيرة في الخليج." },
  { word: "lake", translation: "بحيرة", partOfSpeech: "noun", difficulty: "easy", example: "We rowed across the calm lake.", exampleTranslation: "جدّفنا عبر البحيرة الهادئة." },
  { word: "meadow", translation: "مرج", partOfSpeech: "noun", difficulty: "hard", example: "Cows grazed in the green meadow.", exampleTranslation: "رعت الأبقار في المرج الأخضر." },
  { word: "mountain", translation: "جبل", partOfSpeech: "noun", difficulty: "easy", example: "Snow covered the tall mountain.", exampleTranslation: "غطّى الثلج الجبل العالي." },
  { word: "ocean", translation: "محيط", partOfSpeech: "noun", difficulty: "easy", example: "The ocean stretched to the horizon.", exampleTranslation: "امتدّ المحيط حتى الأفق." },
  { word: "peninsula", translation: "شبه جزيرة", partOfSpeech: "noun", difficulty: "hard", example: "The town sits on a narrow peninsula.", exampleTranslation: "تقع البلدة على شبه جزيرة ضيّقة." },
  { word: "plateau", translation: "هضبة", partOfSpeech: "noun", difficulty: "hard", example: "The village lies on a high plateau.", exampleTranslation: "تقع القرية على هضبة عالية." },
  { word: "reef", translation: "شعاب مرجانية", partOfSpeech: "noun", difficulty: "hard", example: "Colorful fish swim near the reef.", exampleTranslation: "تسبح أسماك ملوّنة قرب الشعاب المرجانية." },
  { word: "ridge", translation: "حافة جبلية", partOfSpeech: "noun", difficulty: "hard", example: "We hiked along the rocky ridge.", exampleTranslation: "تنزّهنا على طول الحافة الجبلية الصخرية." },
  { word: "shore", translation: "شاطئ", partOfSpeech: "noun", difficulty: "medium", example: "Waves washed shells onto the shore.", exampleTranslation: "جرفت الأمواج الأصداف إلى الشاطئ." },
  { word: "slope", translation: "منحدر", partOfSpeech: "noun", difficulty: "medium", example: "We slid down the snowy slope.", exampleTranslation: "انزلقنا أسفل المنحدر الثلجي." },
  { word: "stream", translation: "جدول", partOfSpeech: "noun", difficulty: "medium", example: "A clear stream ran through the woods.", exampleTranslation: "جرى جدول صافٍ عبر الغابة." },
  { word: "summit", translation: "قمة", partOfSpeech: "noun", difficulty: "hard", example: "They reached the summit at sunrise.", exampleTranslation: "بلغوا القمة عند الشروق." },
  { word: "swamp", translation: "مستنقع", partOfSpeech: "noun", difficulty: "hard", example: "Frogs live in the muddy swamp.", exampleTranslation: "تعيش الضفادع في المستنقع الموحل." },
  { word: "valley", translation: "وادٍ", partOfSpeech: "noun", difficulty: "easy", example: "Farms fill the green valley.", exampleTranslation: "تملأ المزارع الوادي الأخضر." },
  { word: "waterfall", translation: "شلّال", partOfSpeech: "noun", difficulty: "medium", example: "The waterfall roared over the rocks.", exampleTranslation: "هدر الشلّال فوق الصخور." },
  { word: "desert", translation: "صحراء", partOfSpeech: "noun", difficulty: "easy", example: "Few plants grow in the dry desert.", exampleTranslation: "تنمو نباتات قليلة في الصحراء الجافة." },
  { word: "river", translation: "نهر", partOfSpeech: "noun", difficulty: "easy", example: "A wide river flows past the city.", exampleTranslation: "يجري نهر واسع بجانب المدينة." },
  { word: "amphibian", translation: "برمائي", partOfSpeech: "noun", difficulty: "hard", example: "A frog is a common amphibian.", exampleTranslation: "الضفدع برمائي شائع." },
  { word: "reptile", translation: "زاحف", partOfSpeech: "noun", difficulty: "hard", example: "A snake is a cold-blooded reptile.", exampleTranslation: "الثعبان زاحف من ذوات الدم البارد." },
  { word: "mammal", translation: "ثديي", partOfSpeech: "noun", difficulty: "hard", example: "A whale is the largest mammal.", exampleTranslation: "الحوت أكبر الثدييات." },
  { word: "camel", translation: "جمل", partOfSpeech: "noun", difficulty: "easy", example: "The camel crossed the hot sand.", exampleTranslation: "عبر الجمل الرمل الحار." },
  { word: "dolphin", translation: "دلفين", partOfSpeech: "noun", difficulty: "medium", example: "A dolphin leaped beside the boat.", exampleTranslation: "قفز دلفين بجانب القارب." },
  { word: "eagle", translation: "نسر", partOfSpeech: "noun", difficulty: "medium", example: "The eagle soared above the cliffs.", exampleTranslation: "حلّق النسر فوق المنحدرات." },
  { word: "giraffe", translation: "زرافة", partOfSpeech: "noun", difficulty: "easy", example: "The giraffe reached the high leaves.", exampleTranslation: "وصلت الزرافة إلى الأوراق العالية." },
  { word: "leopard", translation: "فهد/نمر", partOfSpeech: "noun", difficulty: "medium", example: "The leopard hid in the tall grass.", exampleTranslation: "اختبأ الفهد في العشب الطويل." },
  { word: "kangaroo", translation: "كنغر", partOfSpeech: "noun", difficulty: "medium", example: "A kangaroo hopped across the field.", exampleTranslation: "قفز الكنغر عبر الحقل." },
  { word: "penguin", translation: "بطريق", partOfSpeech: "noun", difficulty: "medium", example: "The penguin waddled on the ice.", exampleTranslation: "تهادى البطريق على الجليد." },
  { word: "octopus", translation: "أخطبوط", partOfSpeech: "noun", difficulty: "medium", example: "An octopus has eight long arms.", exampleTranslation: "للأخطبوط ثماني أذرع طويلة." },
  { word: "scorpion", translation: "عقرب", partOfSpeech: "noun", difficulty: "hard", example: "A scorpion hid under the warm rock.", exampleTranslation: "اختبأ عقرب تحت الصخرة الدافئة." },
  { word: "tortoise", translation: "سلحفاة برّية", partOfSpeech: "noun", difficulty: "hard", example: "The slow tortoise won the race.", exampleTranslation: "فازت السلحفاة البطيئة بالسباق." },
  { word: "sparrow", translation: "عصفور دوري", partOfSpeech: "noun", difficulty: "medium", example: "A sparrow built a nest in the tree.", exampleTranslation: "بنى عصفور دوري عشّاً في الشجرة." },
  { word: "squirrel", translation: "سنجاب", partOfSpeech: "noun", difficulty: "medium", example: "The squirrel hid nuts for winter.", exampleTranslation: "خبّأ السنجاب المكسّرات للشتاء." },
  { word: "butterfly", translation: "فراشة", partOfSpeech: "noun", difficulty: "easy", example: "A butterfly landed on the flower.", exampleTranslation: "حطّت فراشة على الزهرة." },
  { word: "wolf", translation: "ذئب", partOfSpeech: "noun", difficulty: "medium", example: "The wolf howled at the moon.", exampleTranslation: "عوى الذئب نحو القمر." },
  { word: "zebra", translation: "حمار وحشي", partOfSpeech: "noun", difficulty: "easy", example: "The zebra has black and white stripes.", exampleTranslation: "للحمار الوحشي خطوط سوداء وبيضاء." },
  { word: "crocodile", translation: "تمساح", partOfSpeech: "noun", difficulty: "medium", example: "A crocodile rested by the river.", exampleTranslation: "استراح تمساح بجانب النهر." },
  { word: "bone", translation: "عظمة", partOfSpeech: "noun", difficulty: "easy", example: "The dog buried a large bone.", exampleTranslation: "دفن الكلب عظمة كبيرة." },
  { word: "brain", translation: "دماغ", partOfSpeech: "noun", difficulty: "medium", example: "The brain controls the whole body.", exampleTranslation: "يتحكّم الدماغ في الجسم كله." },
  { word: "lung", translation: "رئة", partOfSpeech: "noun", difficulty: "medium", example: "Each lung fills with fresh air.", exampleTranslation: "تمتلئ كل رئة بالهواء النقي." },
  { word: "vein", translation: "وريد", partOfSpeech: "noun", difficulty: "hard", example: "A vein carries blood to the heart.", exampleTranslation: "يحمل الوريد الدم إلى القلب." },
  { word: "artery", translation: "شريان", partOfSpeech: "noun", difficulty: "hard", example: "An artery carries blood from the heart.", exampleTranslation: "يحمل الشريان الدم من القلب." },
  { word: "joint", translation: "مفصل", partOfSpeech: "noun", difficulty: "medium", example: "The knee is a strong joint.", exampleTranslation: "الركبة مفصل قوي." },
  { word: "spine", translation: "عمود فقري", partOfSpeech: "noun", difficulty: "hard", example: "The spine keeps the back straight.", exampleTranslation: "يحافظ العمود الفقري على استقامة الظهر." },
  { word: "throat", translation: "حلق", partOfSpeech: "noun", difficulty: "medium", example: "A sore throat made it hard to talk.", exampleTranslation: "جعل التهاب الحلق الكلام صعباً." },
  { word: "tongue", translation: "لسان", partOfSpeech: "noun", difficulty: "medium", example: "The tongue helps us taste food.", exampleTranslation: "يساعدنا اللسان على تذوّق الطعام." },
  { word: "shoulder", translation: "كتف", partOfSpeech: "noun", difficulty: "easy", example: "He carried the bag on one shoulder.", exampleTranslation: "حمل الحقيبة على كتف واحد." },
  { word: "elbow", translation: "مرفق", partOfSpeech: "noun", difficulty: "medium", example: "She rested her elbow on the table.", exampleTranslation: "أسندت مرفقها على الطاولة." },
  { word: "wrist", translation: "معصم", partOfSpeech: "noun", difficulty: "medium", example: "He wears a watch on his wrist.", exampleTranslation: "يرتدي ساعة على معصمه." },
  { word: "ankle", translation: "كاحل", partOfSpeech: "noun", difficulty: "medium", example: "She hurt her ankle while running.", exampleTranslation: "آذت كاحلها أثناء الجري." },
  { word: "pulse", translation: "نبض", partOfSpeech: "noun", difficulty: "hard", example: "The nurse checked the boy's pulse.", exampleTranslation: "فحصت الممرّضة نبض الصبي." },
  { word: "allergy", translation: "حساسية", partOfSpeech: "noun", difficulty: "hard", example: "He has an allergy to dust.", exampleTranslation: "لديه حساسية من الغبار." },
  { word: "bandage", translation: "ضمادة", partOfSpeech: "noun", difficulty: "medium", example: "She put a bandage on the cut.", exampleTranslation: "وضعت ضمادة على الجرح." },
  { word: "clinic", translation: "عيادة", partOfSpeech: "noun", difficulty: "medium", example: "We visited the clinic for a checkup.", exampleTranslation: "زرنا العيادة لإجراء فحص." },
  { word: "diet", translation: "نظام غذائي", partOfSpeech: "noun", difficulty: "medium", example: "A healthy diet includes vegetables.", exampleTranslation: "يتضمّن النظام الغذائي الصحي الخضراوات." },
  { word: "disease", translation: "مرض", partOfSpeech: "noun", difficulty: "medium", example: "Clean water prevents many diseases.", exampleTranslation: "يمنع الماء النظيف أمراضاً كثيرة." },
  { word: "fever", translation: "حمّى", partOfSpeech: "noun", difficulty: "medium", example: "He stayed home with a high fever.", exampleTranslation: "بقي في المنزل مصاباً بحمّى مرتفعة." },
  { word: "germ", translation: "جرثومة", partOfSpeech: "noun", difficulty: "medium", example: "Soap kills germs on your hands.", exampleTranslation: "يقتل الصابون الجراثيم على يديك." },
  { word: "hygiene", translation: "نظافة", partOfSpeech: "noun", difficulty: "hard", example: "Good hygiene keeps us healthy.", exampleTranslation: "تحافظ النظافة الجيدة على صحتنا." },
  { word: "infection", translation: "عدوى", partOfSpeech: "noun", difficulty: "hard", example: "The cut caused a small infection.", exampleTranslation: "سبّب الجرح عدوى صغيرة." },
  { word: "injury", translation: "إصابة", partOfSpeech: "noun", difficulty: "medium", example: "The player left with a knee injury.", exampleTranslation: "غادر اللاعب بإصابة في الركبة." },
  { word: "medicine", translation: "دواء", partOfSpeech: "noun", difficulty: "easy", example: "Take the medicine after lunch.", exampleTranslation: "تناول الدواء بعد الغداء." },
  { word: "nutrition", translation: "تغذية", partOfSpeech: "noun", difficulty: "hard", example: "Good nutrition helps children grow.", exampleTranslation: "تساعد التغذية الجيدة الأطفال على النمو." },
  { word: "remedy", translation: "علاج", partOfSpeech: "noun", difficulty: "hard", example: "Honey is an old remedy for coughs.", exampleTranslation: "العسل علاج قديم للسعال." },
  { word: "symptom", translation: "عَرَض", partOfSpeech: "noun", difficulty: "hard", example: "A cough can be a symptom of a cold.", exampleTranslation: "قد يكون السعال عَرَضاً للزكام." },
  { word: "treatment", translation: "معالجة", partOfSpeech: "noun", difficulty: "hard", example: "The treatment lasted two weeks.", exampleTranslation: "استمرّت المعالجة أسبوعين." },
  { word: "vaccine", translation: "لقاح", partOfSpeech: "noun", difficulty: "hard", example: "The vaccine protects against the flu.", exampleTranslation: "يحمي اللقاح من الإنفلونزا." },
  { word: "vitamin", translation: "فيتامين", partOfSpeech: "noun", difficulty: "medium", example: "Oranges are full of vitamin C.", exampleTranslation: "البرتقال غني بفيتامين سي." },
  { word: "fitness", translation: "لياقة", partOfSpeech: "noun", difficulty: "medium", example: "Running improves your fitness.", exampleTranslation: "يحسّن الجري لياقتك." },
  { word: "posture", translation: "وضعية الجسم", partOfSpeech: "noun", difficulty: "hard", example: "Good posture protects your back.", exampleTranslation: "تحمي الوضعية الجيدة ظهرك." },
  { word: "recovery", translation: "تعافٍ", partOfSpeech: "noun", difficulty: "hard", example: "Rest speeds up your recovery.", exampleTranslation: "تسرّع الراحة تعافيك." },
  { word: "harvest", translation: "حصاد", partOfSpeech: "noun", difficulty: "medium", example: "The farmers gather the autumn harvest.", exampleTranslation: "يجمع المزارعون حصاد الخريف." },
  { word: "orchard", translation: "بستان", partOfSpeech: "noun", difficulty: "hard", example: "Apples grow in the orchard.", exampleTranslation: "ينمو التفاح في البستان." },
  { word: "vegetable", translation: "خضار", partOfSpeech: "noun", difficulty: "easy", example: "Carrots are a healthy vegetable.", exampleTranslation: "الجزر خضار صحي." },
  { word: "ingredient", translation: "مكوّن", partOfSpeech: "noun", difficulty: "hard", example: "Flour is the main ingredient in bread.", exampleTranslation: "الدقيق المكوّن الرئيسي في الخبز." },
  { word: "recipe", translation: "وصفة", partOfSpeech: "noun", difficulty: "medium", example: "She followed the recipe carefully.", exampleTranslation: "اتبعت الوصفة بعناية." },
  { word: "flour", translation: "دقيق", partOfSpeech: "noun", difficulty: "medium", example: "We need flour to bake a cake.", exampleTranslation: "نحتاج إلى الدقيق لخبز كعكة." },
  { word: "honey", translation: "عسل", partOfSpeech: "noun", difficulty: "easy", example: "Bees make sweet honey.", exampleTranslation: "يصنع النحل العسل الحلو." },
  { word: "spice", translation: "بهار", partOfSpeech: "noun", difficulty: "medium", example: "A little spice adds great flavor.", exampleTranslation: "يضيف القليل من البهار نكهة رائعة." },
  { word: "wheat", translation: "قمح", partOfSpeech: "noun", difficulty: "medium", example: "Farmers grow wheat in wide fields.", exampleTranslation: "يزرع المزارعون القمح في حقول واسعة." },
  { word: "seed", translation: "بذرة", partOfSpeech: "noun", difficulty: "easy", example: "Plant the seed in soft soil.", exampleTranslation: "ازرع البذرة في تربة ليّنة." },
  { word: "blossom", translation: "زهرة/يزهر", partOfSpeech: "noun", difficulty: "hard", example: "The cherry blossom opened in spring.", exampleTranslation: "تفتّحت زهرة الكرز في الربيع." },
  { word: "sprout", translation: "برعم/ينبت", partOfSpeech: "noun", difficulty: "hard", example: "A tiny sprout pushed through the soil.", exampleTranslation: "اندفع برعم صغير عبر التربة." },
  { word: "soil", translation: "تربة", partOfSpeech: "noun", difficulty: "easy", example: "Rich soil helps plants grow tall.", exampleTranslation: "تساعد التربة الغنية النباتات على النمو طويلة." },
  { word: "root", translation: "جذر", partOfSpeech: "noun", difficulty: "easy", example: "The root holds the tree in place.", exampleTranslation: "يثبّت الجذر الشجرة في مكانها." },
  { word: "branch", translation: "غصن", partOfSpeech: "noun", difficulty: "easy", example: "A bird sat on the highest branch.", exampleTranslation: "جلس طائر على أعلى غصن." },
  { word: "trunk", translation: "جذع", partOfSpeech: "noun", difficulty: "medium", example: "The trunk of the tree is very thick.", exampleTranslation: "جذع الشجرة سميك جداً." },
  { word: "forest", translation: "غابة", partOfSpeech: "noun", difficulty: "easy", example: "Tall pines fill the quiet forest.", exampleTranslation: "تملأ أشجار الصنوبر الطويلة الغابة الهادئة." },
  { word: "jungle", translation: "أدغال", partOfSpeech: "noun", difficulty: "medium", example: "Monkeys live high in the jungle.", exampleTranslation: "تعيش القرود عالياً في الأدغال." },
  { word: "prairie", translation: "سهول عشبية", partOfSpeech: "noun", difficulty: "hard", example: "Wild horses roam the open prairie.", exampleTranslation: "تجوب الخيول البرية السهول العشبية المفتوحة." },
  { word: "wetland", translation: "أرض رطبة", partOfSpeech: "noun", difficulty: "hard", example: "Many birds nest in the wetland.", exampleTranslation: "تعشّش طيور كثيرة في الأرض الرطبة." },
  { word: "tide", translation: "مدّ وجزر", partOfSpeech: "noun", difficulty: "hard", example: "The high tide covered the rocks.", exampleTranslation: "غطّى المدّ المرتفع الصخور." },
  { word: "wave", translation: "موجة", partOfSpeech: "noun", difficulty: "easy", example: "A big wave crashed on the sand.", exampleTranslation: "تحطّمت موجة كبيرة على الرمل." },
  { word: "shadow", translation: "ظلّ", partOfSpeech: "noun", difficulty: "easy", example: "The tree cast a long shadow.", exampleTranslation: "ألقت الشجرة ظلّاً طويلاً." },
  { word: "sunlight", translation: "ضوء الشمس", partOfSpeech: "noun", difficulty: "medium", example: "Plants need sunlight to grow.", exampleTranslation: "تحتاج النباتات إلى ضوء الشمس لتنمو." },
  { word: "moisture", translation: "رطوبة", partOfSpeech: "noun", difficulty: "hard", example: "The sponge holds a lot of moisture.", exampleTranslation: "تحمل الإسفنجة كثيراً من الرطوبة." },
  { word: "drizzle", translation: "رذاذ", partOfSpeech: "noun", difficulty: "hard", example: "A light drizzle fell all morning.", exampleTranslation: "تساقط رذاذ خفيف طوال الصباح." },
  { word: "hail", translation: "بَرَد", partOfSpeech: "noun", difficulty: "hard", example: "Hail bounced off the car roof.", exampleTranslation: "ارتدّ البَرَد عن سقف السيارة." },
  { word: "lizard", translation: "سحلية", partOfSpeech: "noun", difficulty: "medium", example: "A lizard sat still on the wall.", exampleTranslation: "جلست سحلية ساكنة على الجدار." },
  { word: "seal", translation: "فقمة", partOfSpeech: "noun", difficulty: "medium", example: "A seal rested on the cold rock.", exampleTranslation: "استراحت فقمة على الصخرة الباردة." },
  { word: "shark", translation: "قرش", partOfSpeech: "noun", difficulty: "medium", example: "A shark swam deep below the boat.", exampleTranslation: "سبح قرش عميقاً أسفل القارب." },
  { word: "whale", translation: "حوت", partOfSpeech: "noun", difficulty: "easy", example: "The whale dived under the waves.", exampleTranslation: "غاص الحوت تحت الأمواج." },
  { word: "antelope", translation: "ظبي", partOfSpeech: "noun", difficulty: "hard", example: "An antelope raced across the plain.", exampleTranslation: "ركض ظبي عبر السهل." },
  { word: "beaver", translation: "قندس", partOfSpeech: "noun", difficulty: "hard", example: "A beaver built a dam on the stream.", exampleTranslation: "بنى قندس سدّاً على الجدول." },
  { word: "cheetah", translation: "فهد صيّاد", partOfSpeech: "noun", difficulty: "medium", example: "The cheetah is the fastest land animal.", exampleTranslation: "الفهد الصيّاد أسرع حيوان برّي." },
  { word: "falcon", translation: "صقر", partOfSpeech: "noun", difficulty: "medium", example: "The falcon dived to catch its prey.", exampleTranslation: "انقضّ الصقر ليمسك فريسته." },
  { word: "gazelle", translation: "غزال", partOfSpeech: "noun", difficulty: "medium", example: "A gazelle leaped over the bushes.", exampleTranslation: "قفز غزال فوق الشجيرات." },
  { word: "hedgehog", translation: "قنفذ", partOfSpeech: "noun", difficulty: "hard", example: "The hedgehog curled into a ball.", exampleTranslation: "تكوّر القنفذ على شكل كرة." },
  { word: "ostrich", translation: "نعامة", partOfSpeech: "noun", difficulty: "medium", example: "The ostrich runs faster than a horse.", exampleTranslation: "تجري النعامة أسرع من الحصان." },
  { word: "swan", translation: "بجعة", partOfSpeech: "noun", difficulty: "medium", example: "A white swan glided on the lake.", exampleTranslation: "انزلقت بجعة بيضاء على البحيرة." },
  { word: "vulture", translation: "نسر/عُقاب", partOfSpeech: "noun", difficulty: "hard", example: "A vulture circled high in the sky.", exampleTranslation: "حام عُقاب عالياً في السماء." },
  { word: "skin", translation: "جلد", partOfSpeech: "noun", difficulty: "easy", example: "Sunscreen protects your skin.", exampleTranslation: "يحمي واقي الشمس جلدك." },
  { word: "rib", translation: "ضلع", partOfSpeech: "noun", difficulty: "hard", example: "Each rib protects the lungs.", exampleTranslation: "يحمي كل ضلع الرئتين." },
  { word: "jaw", translation: "فكّ", partOfSpeech: "noun", difficulty: "hard", example: "The strong jaw helps animals chew.", exampleTranslation: "يساعد الفكّ القوي الحيوانات على المضغ." },
  { word: "heel", translation: "كعب", partOfSpeech: "noun", difficulty: "medium", example: "The new shoe hurt his heel.", exampleTranslation: "آذى الحذاء الجديد كعبه." },
  { word: "thumb", translation: "إبهام", partOfSpeech: "noun", difficulty: "medium", example: "She pressed the clay with her thumb.", exampleTranslation: "ضغطت الطين بإبهامها." },
  { word: "chin", translation: "ذقن", partOfSpeech: "noun", difficulty: "easy", example: "He rested his chin on his hand.", exampleTranslation: "أسند ذقنه على يده." },
  { word: "eyebrow", translation: "حاجب", partOfSpeech: "noun", difficulty: "medium", example: "She raised one eyebrow in surprise.", exampleTranslation: "رفعت حاجباً واحداً في دهشة." },
  { word: "fatigue", translation: "إرهاق", partOfSpeech: "noun", difficulty: "hard", example: "Long study caused great fatigue.", exampleTranslation: "سبّبت الدراسة الطويلة إرهاقاً كبيراً." },
  { word: "pharmacy", translation: "صيدلية", partOfSpeech: "noun", difficulty: "hard", example: "We bought the medicine at the pharmacy.", exampleTranslation: "اشترينا الدواء من الصيدلية." },
  { word: "dentist", translation: "طبيب أسنان", partOfSpeech: "noun", difficulty: "medium", example: "The dentist checked my teeth.", exampleTranslation: "فحص طبيب الأسنان أسناني." },
  { word: "bruise", translation: "كدمة", partOfSpeech: "noun", difficulty: "hard", example: "He got a small bruise on his knee.", exampleTranslation: "أصيب بكدمة صغيرة على ركبته." },
  { word: "therapy", translation: "علاج تأهيلي", partOfSpeech: "noun", difficulty: "hard", example: "Therapy helped her walk again.", exampleTranslation: "ساعدها العلاج التأهيلي على المشي مجدداً." },
  { word: "almond", translation: "لوز", partOfSpeech: "noun", difficulty: "medium", example: "An almond is a healthy snack.", exampleTranslation: "اللوز وجبة خفيفة صحية." },
  { word: "apricot", translation: "مشمش", partOfSpeech: "noun", difficulty: "medium", example: "The apricot tasted sweet and soft.", exampleTranslation: "كان طعم المشمش حلواً وطرياً." },
  { word: "cabbage", translation: "ملفوف", partOfSpeech: "noun", difficulty: "medium", example: "We added cabbage to the salad.", exampleTranslation: "أضفنا الملفوف إلى السلطة." },
  { word: "cucumber", translation: "خيار", partOfSpeech: "noun", difficulty: "medium", example: "A cucumber is cool and crunchy.", exampleTranslation: "الخيار بارد ومقرمش." },
  { word: "ginger", translation: "زنجبيل", partOfSpeech: "noun", difficulty: "hard", example: "Ginger gives the tea a warm taste.", exampleTranslation: "يمنح الزنجبيل الشاي طعماً دافئاً." },
  { word: "lentil", translation: "عدس", partOfSpeech: "noun", difficulty: "hard", example: "Lentil soup is warm and filling.", exampleTranslation: "حساء العدس دافئ ومشبع." },
  { word: "mango", translation: "مانجو", partOfSpeech: "noun", difficulty: "easy", example: "A ripe mango is juicy and sweet.", exampleTranslation: "المانجو الناضجة كثيرة العصير وحلوة." },
  { word: "pepper", translation: "فلفل", partOfSpeech: "noun", difficulty: "easy", example: "Add a little pepper to the soup.", exampleTranslation: "أضف قليلاً من الفلفل إلى الحساء." },
  { word: "pumpkin", translation: "يقطين", partOfSpeech: "noun", difficulty: "medium", example: "We carved a big orange pumpkin.", exampleTranslation: "نحتنا يقطينة برتقالية كبيرة." },
  { word: "spinach", translation: "سبانخ", partOfSpeech: "noun", difficulty: "medium", example: "Spinach is rich in iron.", exampleTranslation: "السبانخ غني بالحديد." },
  { word: "vinegar", translation: "خلّ", partOfSpeech: "noun", difficulty: "hard", example: "A drop of vinegar sharpened the taste.", exampleTranslation: "قطرة خلّ زادت الطعم حدّة." },
  { word: "yogurt", translation: "زبادي", partOfSpeech: "noun", difficulty: "medium", example: "She ate yogurt with fresh fruit.", exampleTranslation: "أكلت الزبادي مع فاكهة طازجة." },
  { word: "cereal", translation: "حبوب الإفطار", partOfSpeech: "noun", difficulty: "medium", example: "He eats cereal with milk for breakfast.", exampleTranslation: "يأكل حبوب الإفطار مع الحليب." },
  { word: "barley", translation: "شعير", partOfSpeech: "noun", difficulty: "hard", example: "Farmers store barley for the winter.", exampleTranslation: "يخزّن المزارعون الشعير للشتاء." },
  { word: "coconut", translation: "جوز هند", partOfSpeech: "noun", difficulty: "medium", example: "The coconut fell from the tall palm.", exampleTranslation: "سقط جوز الهند من النخلة العالية." },
  { word: "peach", translation: "خوخ", partOfSpeech: "noun", difficulty: "easy", example: "The peach felt soft and fuzzy.", exampleTranslation: "كان الخوخ ناعماً وزغبياً." },
  { word: "herb", translation: "عُشب طبّي", partOfSpeech: "noun", difficulty: "hard", example: "Mint is a fresh-smelling herb.", exampleTranslation: "النعناع عُشب ذو رائحة منعشة." },
  { word: "nectar", translation: "رحيق", partOfSpeech: "noun", difficulty: "hard", example: "Bees gather nectar from flowers.", exampleTranslation: "يجمع النحل الرحيق من الأزهار." },
  { word: "panther", translation: "فهد أسود", partOfSpeech: "noun", difficulty: "hard", example: "The black panther moved without a sound.", exampleTranslation: "تحرّك الفهد الأسود دون صوت." },
  { word: "jaguar", translation: "يغور", partOfSpeech: "noun", difficulty: "hard", example: "The jaguar swam across the wide river.", exampleTranslation: "سبح اليغور عبر النهر الواسع." },
  { word: "walrus", translation: "فظّ", partOfSpeech: "noun", difficulty: "hard", example: "The walrus rested on the icy shore.", exampleTranslation: "استراح الفظّ على الشاطئ الجليدي." }
];
