/** Grade 6 chunk G — academic, analytical & reasoning vocabulary (cards 1001-1500, batch 1). */
export const GRADE6_CHUNK_G = [
  { word: "analysis", translation: "تحليل", partOfSpeech: "noun", difficulty: "hard", example: "Her analysis of the data was clear.", exampleTranslation: "كان تحليلها للبيانات واضحاً." },
  { word: "assumption", translation: "افتراض", partOfSpeech: "noun", difficulty: "hard", example: "Do not base your plan on a weak assumption.", exampleTranslation: "لا تَبنِ خطتك على افتراض ضعيف." },
  { word: "aspect", translation: "جانب", partOfSpeech: "noun", difficulty: "hard", example: "We studied every aspect of the topic.", exampleTranslation: "درسنا كل جانب من جوانب الموضوع." },
  { word: "category", translation: "فئة", partOfSpeech: "noun", difficulty: "medium", example: "Sort the books into each category.", exampleTranslation: "صنّف الكتب في كل فئة." },
  { word: "criterion", translation: "معيار", partOfSpeech: "noun", difficulty: "hard", example: "Neatness is one criterion for the prize.", exampleTranslation: "الترتيب أحد معايير الجائزة." },
  { word: "framework", translation: "إطار عمل", partOfSpeech: "noun", difficulty: "hard", example: "The plan gives us a clear framework.", exampleTranslation: "تمنحنا الخطة إطار عمل واضحاً." },
  { word: "parameter", translation: "ضابط/معطى", partOfSpeech: "noun", difficulty: "hard", example: "Set the parameter before you run the test.", exampleTranslation: "اضبط المعطى قبل إجراء الاختبار." },
  { word: "correlation", translation: "ارتباط", partOfSpeech: "noun", difficulty: "hard", example: "There is a correlation between sleep and focus.", exampleTranslation: "هناك ارتباط بين النوم والتركيز." },
  { word: "derive", translation: "يشتقّ/يستمدّ", partOfSpeech: "verb", difficulty: "hard", example: "We derive the rule from many examples.", exampleTranslation: "نشتقّ القاعدة من أمثلة كثيرة." },
  { word: "outcome", translation: "نتيجة", partOfSpeech: "noun", difficulty: "medium", example: "The outcome of the match surprised us.", exampleTranslation: "فاجأتنا نتيجة المباراة." },
  { word: "insight", translation: "بصيرة/فهم عميق", partOfSpeech: "noun", difficulty: "hard", example: "The book gave me a new insight.", exampleTranslation: "منحني الكتاب فهماً عميقاً جديداً." },
  { word: "perspective", translation: "منظور", partOfSpeech: "noun", difficulty: "hard", example: "Try to see it from another perspective.", exampleTranslation: "حاول أن تراه من منظور آخر." },
  { word: "phenomenon", translation: "ظاهرة", partOfSpeech: "noun", difficulty: "hard", example: "Thunder is a natural phenomenon.", exampleTranslation: "الرعد ظاهرة طبيعية." },
  { word: "precision", translation: "دقّة", partOfSpeech: "noun", difficulty: "hard", example: "The clock keeps time with precision.", exampleTranslation: "تحفظ الساعة الوقت بدقّة." },
  { word: "probability", translation: "احتمال", partOfSpeech: "noun", difficulty: "hard", example: "The probability of rain is high today.", exampleTranslation: "احتمال المطر مرتفع اليوم." },
  { word: "trend", translation: "اتجاه/نزعة", partOfSpeech: "noun", difficulty: "medium", example: "The graph shows an upward trend.", exampleTranslation: "يُظهر الرسم البياني اتجاهاً صاعداً." },
  { word: "tendency", translation: "ميل", partOfSpeech: "noun", difficulty: "hard", example: "He has a tendency to arrive early.", exampleTranslation: "لديه ميل إلى الوصول مبكراً." },
  { word: "threshold", translation: "عتبة/حدّ أدنى", partOfSpeech: "noun", difficulty: "hard", example: "The sound passed the hearing threshold.", exampleTranslation: "تجاوز الصوت عتبة السمع." },
  { word: "scope", translation: "نطاق", partOfSpeech: "noun", difficulty: "hard", example: "That topic is beyond the scope of the lesson.", exampleTranslation: "هذا الموضوع خارج نطاق الدرس." },
  { word: "segment", translation: "جزء/قطاع", partOfSpeech: "noun", difficulty: "hard", example: "Each segment of the line is equal.", exampleTranslation: "كل جزء من الخط متساوٍ." },
  { word: "sample", translation: "عيّنة", partOfSpeech: "noun", difficulty: "medium", example: "We tested a small sample of water.", exampleTranslation: "اختبرنا عيّنة صغيرة من الماء." },
  { word: "survey", translation: "استبيان/مسح", partOfSpeech: "noun", difficulty: "medium", example: "The class filled out a short survey.", exampleTranslation: "ملأ الصف استبياناً قصيراً." },
  { word: "statistic", translation: "إحصائية", partOfSpeech: "noun", difficulty: "hard", example: "That statistic shocked the readers.", exampleTranslation: "صدمت تلك الإحصائية القرّاء." },
  { word: "diagram", translation: "رسم تخطيطي", partOfSpeech: "noun", difficulty: "medium", example: "The diagram explains the water cycle.", exampleTranslation: "يشرح الرسم التخطيطي دورة الماء." },
  { word: "data", translation: "بيانات", partOfSpeech: "noun", difficulty: "medium", example: "We collected data for a week.", exampleTranslation: "جمعنا البيانات لمدة أسبوع." },
  { word: "database", translation: "قاعدة بيانات", partOfSpeech: "noun", difficulty: "hard", example: "The library stores titles in a database.", exampleTranslation: "تخزّن المكتبة العناوين في قاعدة بيانات." },
  { word: "indicator", translation: "مؤشّر", partOfSpeech: "noun", difficulty: "hard", example: "A red light is an indicator of danger.", exampleTranslation: "الضوء الأحمر مؤشّر على الخطر." },
  { word: "input", translation: "مُدخَل", partOfSpeech: "noun", difficulty: "hard", example: "The machine needs an input to start.", exampleTranslation: "تحتاج الآلة إلى مُدخَل لتبدأ." },
  { word: "output", translation: "مُخرَج", partOfSpeech: "noun", difficulty: "hard", example: "The output of the printer was a clear page.", exampleTranslation: "كان مُخرَج الطابعة صفحة واضحة." },
  { word: "overview", translation: "نظرة عامة", partOfSpeech: "noun", difficulty: "hard", example: "She gave an overview of the project.", exampleTranslation: "قدّمت نظرة عامة عن المشروع." },
  { word: "synopsis", translation: "موجز/خلاصة", partOfSpeech: "noun", difficulty: "hard", example: "Read the synopsis before the film.", exampleTranslation: "اقرأ الموجز قبل الفيلم." },
  { word: "metric", translation: "مقياس", partOfSpeech: "noun", difficulty: "hard", example: "Speed is the main metric in this test.", exampleTranslation: "السرعة هي المقياس الرئيسي في هذا الاختبار." },
  { word: "evaluation", translation: "تقييم", partOfSpeech: "noun", difficulty: "hard", example: "The teacher wrote an evaluation of my essay.", exampleTranslation: "كتب المعلّم تقييماً لمقالي." },
  { word: "assessment", translation: "تقدير/تقويم", partOfSpeech: "noun", difficulty: "hard", example: "The end-of-term assessment was fair.", exampleTranslation: "كان تقويم نهاية الفصل عادلاً." },
  { word: "comparison", translation: "مقارنة", partOfSpeech: "noun", difficulty: "medium", example: "The chart makes the comparison easy.", exampleTranslation: "يجعل الجدول المقارنة سهلة." },
  { word: "distinction", translation: "تمييز/فرق", partOfSpeech: "noun", difficulty: "hard", example: "There is a clear distinction between them.", exampleTranslation: "هناك فرق واضح بينهما." },
  { word: "implication", translation: "تبعة/دلالة", partOfSpeech: "noun", difficulty: "hard", example: "The new rule has a big implication.", exampleTranslation: "للقاعدة الجديدة تبعة كبيرة." },
  { word: "inference", translation: "استنباط", partOfSpeech: "noun", difficulty: "hard", example: "She made an inference from the clues.", exampleTranslation: "استنبطت نتيجة من القرائن." },
  { word: "interpretation", translation: "تفسير", partOfSpeech: "noun", difficulty: "hard", example: "His interpretation of the poem was unusual.", exampleTranslation: "كان تفسيره للقصيدة غير مألوف." },
  { word: "limitation", translation: "قيد/حدّ", partOfSpeech: "noun", difficulty: "hard", example: "Time was the main limitation of the study.", exampleTranslation: "كان الوقت القيد الرئيسي للدراسة." },
  { word: "mechanism", translation: "آلية", partOfSpeech: "noun", difficulty: "hard", example: "The lock has a simple mechanism.", exampleTranslation: "للقفل آلية بسيطة." },
  { word: "methodology", translation: "منهجية", partOfSpeech: "noun", difficulty: "hard", example: "Their methodology was easy to follow.", exampleTranslation: "كانت منهجيتهم سهلة المتابعة." },
  { word: "phase", translation: "مرحلة", partOfSpeech: "noun", difficulty: "medium", example: "The first phase of the plan is done.", exampleTranslation: "اكتملت المرحلة الأولى من الخطة." },
  { word: "priority", translation: "أولوية", partOfSpeech: "noun", difficulty: "medium", example: "Safety is our top priority.", exampleTranslation: "السلامة أولويتنا القصوى." },
  { word: "requirement", translation: "متطلّب", partOfSpeech: "noun", difficulty: "hard", example: "Reading is a requirement for the course.", exampleTranslation: "القراءة متطلّب للمقرّر." },
  { word: "restriction", translation: "قيد/تقييد", partOfSpeech: "noun", difficulty: "hard", example: "There is a restriction on loud noise.", exampleTranslation: "هناك قيد على الضوضاء العالية." },
  { word: "constraint", translation: "عائق/قيد", partOfSpeech: "noun", difficulty: "hard", example: "A tight budget was a real constraint.", exampleTranslation: "كانت الميزانية الضيّقة قيداً حقيقياً." },
  { word: "exception", translation: "استثناء", partOfSpeech: "noun", difficulty: "hard", example: "Every rule has an exception.", exampleTranslation: "لكل قاعدة استثناء." },
  { word: "consistency", translation: "اتّساق/ثبات", partOfSpeech: "noun", difficulty: "hard", example: "Consistency in practice builds skill.", exampleTranslation: "يبني الثبات في التدريب المهارة." },
  { word: "accuracy", translation: "دقّة", partOfSpeech: "noun", difficulty: "hard", example: "The map's accuracy impressed us.", exampleTranslation: "أبهرتنا دقّة الخريطة." },
  { word: "efficiency", translation: "كفاءة", partOfSpeech: "noun", difficulty: "hard", example: "New tools improved our efficiency.", exampleTranslation: "حسّنت الأدوات الجديدة كفاءتنا." },
  { word: "alternative", translation: "بديل", partOfSpeech: "noun", difficulty: "hard", example: "We need an alternative to plastic bags.", exampleTranslation: "نحتاج إلى بديل لأكياس البلاستيك." },
  { word: "component", translation: "مكوّن", partOfSpeech: "noun", difficulty: "hard", example: "Each component of the engine matters.", exampleTranslation: "كل مكوّن من مكوّنات المحرّك مهم." },
  { word: "determinant", translation: "محدِّد/عامل حاسم", partOfSpeech: "noun", difficulty: "hard", example: "Weather is a key determinant of the trip.", exampleTranslation: "الطقس عامل حاسم في الرحلة." },
  { word: "variation", translation: "تباين/اختلاف", partOfSpeech: "noun", difficulty: "hard", example: "There is some variation in the results.", exampleTranslation: "هناك بعض التباين في النتائج." },
  { word: "deviation", translation: "انحراف", partOfSpeech: "noun", difficulty: "hard", example: "A small deviation can change the path.", exampleTranslation: "قد يغيّر انحراف صغير المسار." },
  { word: "distribution", translation: "توزيع", partOfSpeech: "noun", difficulty: "hard", example: "The distribution of food was fair.", exampleTranslation: "كان توزيع الطعام عادلاً." },
  { word: "expansion", translation: "توسّع", partOfSpeech: "noun", difficulty: "hard", example: "Heat causes the expansion of metal.", exampleTranslation: "تسبّب الحرارة توسّع المعدن." },
  { word: "projection", translation: "توقّع/إسقاط", partOfSpeech: "noun", difficulty: "hard", example: "The sales projection looks strong.", exampleTranslation: "يبدو توقّع المبيعات قوياً." },
  { word: "prediction", translation: "تنبّؤ", partOfSpeech: "noun", difficulty: "medium", example: "Her prediction about the weather was right.", exampleTranslation: "كان تنبّؤها بالطقس صحيحاً." },
  { word: "rationale", translation: "مسوّغ/أساس منطقي", partOfSpeech: "noun", difficulty: "hard", example: "Explain the rationale behind your choice.", exampleTranslation: "اشرح الأساس المنطقي وراء اختيارك." },
  { word: "reference", translation: "مرجع", partOfSpeech: "noun", difficulty: "medium", example: "List every reference at the end.", exampleTranslation: "اذكر كل مرجع في النهاية." },
  { word: "scenario", translation: "سيناريو/فرضية", partOfSpeech: "noun", difficulty: "hard", example: "Imagine a scenario with no internet.", exampleTranslation: "تخيّل سيناريو بلا إنترنت." },
  { word: "simulation", translation: "محاكاة", partOfSpeech: "noun", difficulty: "hard", example: "The flight simulation felt real.", exampleTranslation: "بدت محاكاة الطيران حقيقية." },
  { word: "specification", translation: "مواصفة", partOfSpeech: "noun", difficulty: "hard", example: "The specification lists every part.", exampleTranslation: "تسرد المواصفة كل جزء." },
  { word: "verification", translation: "تحقّق", partOfSpeech: "noun", difficulty: "hard", example: "The bank needs verification of your name.", exampleTranslation: "يحتاج البنك إلى التحقّق من اسمك." },
  { word: "validation", translation: "إثبات الصحّة", partOfSpeech: "noun", difficulty: "hard", example: "The test gave validation to the idea.", exampleTranslation: "أعطى الاختبار إثباتاً لصحّة الفكرة." },
  { word: "refinement", translation: "تحسين/صقل", partOfSpeech: "noun", difficulty: "hard", example: "The design needed one more refinement.", exampleTranslation: "احتاج التصميم إلى صقل إضافي." },
  { word: "conversion", translation: "تحويل", partOfSpeech: "noun", difficulty: "hard", example: "The conversion from miles to kilometers is easy.", exampleTranslation: "التحويل من الأميال إلى الكيلومترات سهل." },
  { word: "classification", translation: "تصنيف", partOfSpeech: "noun", difficulty: "hard", example: "The classification of animals helps science.", exampleTranslation: "يساعد تصنيف الحيوانات العلم." },
  { word: "representation", translation: "تمثيل", partOfSpeech: "noun", difficulty: "hard", example: "A map is a representation of the land.", exampleTranslation: "الخريطة تمثيل للأرض." },
  { word: "documentation", translation: "توثيق", partOfSpeech: "noun", difficulty: "hard", example: "Good documentation explains the steps.", exampleTranslation: "يشرح التوثيق الجيد الخطوات." },
  { word: "guideline", translation: "إرشاد/توجيه", partOfSpeech: "noun", difficulty: "hard", example: "Follow the safety guideline closely.", exampleTranslation: "اتبع إرشاد السلامة بدقّة." },
  { word: "domain", translation: "مجال/نطاق", partOfSpeech: "noun", difficulty: "hard", example: "Music is her favorite domain.", exampleTranslation: "الموسيقى مجالها المفضّل." },
  { word: "module", translation: "وحدة", partOfSpeech: "noun", difficulty: "hard", example: "The course has six learning modules.", exampleTranslation: "يضمّ المقرّر ست وحدات تعليمية." },
  { word: "prototype", translation: "نموذج أوّلي", partOfSpeech: "noun", difficulty: "hard", example: "They built a prototype of the robot.", exampleTranslation: "بنوا نموذجاً أوّلياً للروبوت." },
  { word: "circumstance", translation: "ظرف/حالة", partOfSpeech: "noun", difficulty: "hard", example: "He stayed calm in a hard circumstance.", exampleTranslation: "بقي هادئاً في ظرف صعب." },
  { word: "contradiction", translation: "تناقض", partOfSpeech: "noun", difficulty: "hard", example: "There was a contradiction in his story.", exampleTranslation: "كان هناك تناقض في قصته." },
  { word: "generalization", translation: "تعميم", partOfSpeech: "noun", difficulty: "hard", example: "Avoid a quick generalization about people.", exampleTranslation: "تجنّب التعميم السريع عن الناس." },
  { word: "emphasis", translation: "تشديد/تركيز", partOfSpeech: "noun", difficulty: "hard", example: "She put emphasis on the last word.", exampleTranslation: "وضعت تشديداً على الكلمة الأخيرة." },
  { word: "resolution", translation: "حلّ/وضوح", partOfSpeech: "noun", difficulty: "hard", example: "They found a peaceful resolution.", exampleTranslation: "وجدوا حلّاً سلمياً." },
  { word: "allocate", translation: "يخصّص", partOfSpeech: "verb", difficulty: "hard", example: "We allocate ten minutes to each task.", exampleTranslation: "نخصّص عشر دقائق لكل مهمة." },
  { word: "tally", translation: "إحصاء/يحصي", partOfSpeech: "noun", difficulty: "hard", example: "Keep a tally of the votes.", exampleTranslation: "احتفظ بإحصاء للأصوات." },
  { word: "monitor", translation: "يراقب", partOfSpeech: "verb", difficulty: "hard", example: "Doctors monitor the patient's heart.", exampleTranslation: "يراقب الأطباء قلب المريض." },
  { word: "tabulate", translation: "يجدول", partOfSpeech: "verb", difficulty: "hard", example: "Tabulate the scores in a neat table.", exampleTranslation: "جدوِل الدرجات في جدول مرتّب." },
  { word: "deduce", translation: "يستنتج", partOfSpeech: "verb", difficulty: "hard", example: "From the clues we deduce the answer.", exampleTranslation: "من القرائن نستنتج الإجابة." },
  { word: "forecast", translation: "يتنبّأ", partOfSpeech: "verb", difficulty: "hard", example: "They forecast a sunny weekend.", exampleTranslation: "تنبّأوا بعطلة مشمسة." },
  { word: "minimize", translation: "يقلّل إلى أدنى حدّ", partOfSpeech: "verb", difficulty: "hard", example: "We try to minimize waste.", exampleTranslation: "نحاول تقليل النفايات إلى أدنى حدّ." },
  { word: "maximize", translation: "يزيد إلى أقصى حدّ", partOfSpeech: "verb", difficulty: "hard", example: "Open the blinds to maximize light.", exampleTranslation: "افتح الستائر لزيادة الضوء إلى أقصى حدّ." },
  { word: "optimize", translation: "يحسّن إلى الأمثل", partOfSpeech: "verb", difficulty: "hard", example: "Engineers optimize the engine for speed.", exampleTranslation: "يحسّن المهندسون المحرّك للسرعة." },
  { word: "specify", translation: "يحدّد", partOfSpeech: "verb", difficulty: "hard", example: "Please specify the exact time.", exampleTranslation: "من فضلك حدّد الوقت بالضبط." },
  { word: "verify", translation: "يتحقّق", partOfSpeech: "verb", difficulty: "hard", example: "Verify the answer with a calculator.", exampleTranslation: "تحقّق من الإجابة بالآلة الحاسبة." },
  { word: "compute", translation: "يحوسب/يحسب", partOfSpeech: "verb", difficulty: "hard", example: "The program can compute large sums.", exampleTranslation: "يستطيع البرنامج حساب مبالغ كبيرة." },
  { word: "categorize", translation: "يصنّف ضمن فئات", partOfSpeech: "verb", difficulty: "hard", example: "Categorize the words by their type.", exampleTranslation: "صنّف الكلمات حسب نوعها." },
  { word: "correlate", translation: "يربط/يرتبط", partOfSpeech: "verb", difficulty: "hard", example: "The results correlate with the temperature.", exampleTranslation: "ترتبط النتائج بدرجة الحرارة." },
  { word: "decode", translation: "يفكّ الشيفرة", partOfSpeech: "verb", difficulty: "hard", example: "Scientists decode the strange signal.", exampleTranslation: "يفكّ العلماء شيفرة الإشارة الغريبة." },
  { word: "probe", translation: "يستقصي", partOfSpeech: "verb", difficulty: "hard", example: "The robot will probe the deep cave.", exampleTranslation: "سيستقصي الروبوت الكهف العميق." },
  { word: "investment", translation: "استثمار", partOfSpeech: "noun", difficulty: "hard", example: "Education is a wise investment.", exampleTranslation: "التعليم استثمار حكيم." },
  { word: "expense", translation: "نفقة", partOfSpeech: "noun", difficulty: "medium", example: "Travel is the biggest expense.", exampleTranslation: "السفر أكبر نفقة." },
  { word: "revenue", translation: "إيراد", partOfSpeech: "noun", difficulty: "hard", example: "The shop's revenue grew this year.", exampleTranslation: "نما إيراد المتجر هذا العام." },
  { word: "transaction", translation: "معاملة", partOfSpeech: "noun", difficulty: "hard", example: "The bank recorded every transaction.", exampleTranslation: "سجّل البنك كل معاملة." },
  { word: "investor", translation: "مستثمِر", partOfSpeech: "noun", difficulty: "hard", example: "The investor backed the new factory.", exampleTranslation: "دعم المستثمِر المصنع الجديد." },
  { word: "consumer", translation: "مستهلِك", partOfSpeech: "noun", difficulty: "hard", example: "The consumer chose the cheaper brand.", exampleTranslation: "اختار المستهلِك العلامة الأرخص." },
  { word: "producer", translation: "منتِج", partOfSpeech: "noun", difficulty: "medium", example: "The country is a major oil producer.", exampleTranslation: "البلد منتِج رئيسي للنفط." },
  { word: "manufacturer", translation: "مُصنِّع", partOfSpeech: "noun", difficulty: "hard", example: "The manufacturer tested every part.", exampleTranslation: "اختبر المُصنِّع كل قطعة." },
  { word: "wholesale", translation: "بيع بالجملة", partOfSpeech: "noun", difficulty: "hard", example: "They buy fruit at wholesale prices.", exampleTranslation: "يشترون الفاكهة بأسعار الجملة." },
  { word: "retail", translation: "بيع بالتجزئة", partOfSpeech: "noun", difficulty: "hard", example: "The retail price includes tax.", exampleTranslation: "يشمل سعر التجزئة الضريبة." },
  { word: "inflation", translation: "تضخّم", partOfSpeech: "noun", difficulty: "hard", example: "Inflation made bread more expensive.", exampleTranslation: "جعل التضخّم الخبز أغلى." },
  { word: "tax", translation: "ضريبة", partOfSpeech: "noun", difficulty: "medium", example: "Shops add a small tax to the price.", exampleTranslation: "تضيف المتاجر ضريبة صغيرة إلى السعر." },
  { word: "loan", translation: "قرض", partOfSpeech: "noun", difficulty: "medium", example: "The family took a loan for the house.", exampleTranslation: "أخذت العائلة قرضاً لشراء المنزل." },
  { word: "fund", translation: "تمويل/صندوق مالي", partOfSpeech: "noun", difficulty: "hard", example: "They started a fund for the new library.", exampleTranslation: "أنشأوا صندوقاً مالياً للمكتبة الجديدة." },
  { word: "asset", translation: "أصل/ممتلك", partOfSpeech: "noun", difficulty: "hard", example: "The truck is the company's main asset.", exampleTranslation: "الشاحنة هي الأصل الرئيسي للشركة." },
  { word: "debt", translation: "دَين", partOfSpeech: "noun", difficulty: "medium", example: "He paid off his debt slowly.", exampleTranslation: "سدّد دَينه ببطء." },
  { word: "salary", translation: "راتب", partOfSpeech: "noun", difficulty: "medium", example: "She saves part of her salary.", exampleTranslation: "تدّخر جزءاً من راتبها." },
  { word: "highlight", translation: "يبرز/يسلّط الضوء", partOfSpeech: "verb", difficulty: "hard", example: "Please highlight the key points.", exampleTranslation: "من فضلك أبرز النقاط الرئيسية." },
  { word: "scrutinize", translation: "يدقّق", partOfSpeech: "verb", difficulty: "hard", example: "The judges scrutinize each entry.", exampleTranslation: "يدقّق الحكّام في كل مشاركة." },
  { word: "appraise", translation: "يثمّن/يقدّر", partOfSpeech: "verb", difficulty: "hard", example: "An expert came to appraise the painting.", exampleTranslation: "جاء خبير ليثمّن اللوحة." },
  { word: "premise", translation: "مقدّمة منطقية/فرضية", partOfSpeech: "noun", difficulty: "hard", example: "The whole argument rests on one premise.", exampleTranslation: "تقوم الحجّة كلها على مقدّمة واحدة." },
  { word: "theorem", translation: "نظرية رياضية/مبرهنة", partOfSpeech: "noun", difficulty: "hard", example: "We proved the theorem in class.", exampleTranslation: "أثبتنا المبرهنة في الصف." },
  { word: "axiom", translation: "بديهية", partOfSpeech: "noun", difficulty: "hard", example: "An axiom is accepted without proof.", exampleTranslation: "البديهية تُقبل دون برهان." },
  { word: "paradigm", translation: "نموذج/نمط", partOfSpeech: "noun", difficulty: "hard", example: "The discovery created a new paradigm.", exampleTranslation: "أوجد الاكتشاف نموذجاً جديداً." },
  { word: "thesis", translation: "أطروحة/فرضية رئيسية", partOfSpeech: "noun", difficulty: "hard", example: "State your thesis in the first line.", exampleTranslation: "اذكر أطروحتك في السطر الأول." },
  { word: "excerpt", translation: "مقتطف", partOfSpeech: "noun", difficulty: "hard", example: "She read an excerpt from the novel.", exampleTranslation: "قرأت مقتطفاً من الرواية." },
  { word: "citation", translation: "اقتباس مرجعي", partOfSpeech: "noun", difficulty: "hard", example: "Add a citation for every quote.", exampleTranslation: "أضف اقتباساً مرجعياً لكل اقتباس." },
  { word: "appendix", translation: "ملحق", partOfSpeech: "noun", difficulty: "hard", example: "The maps are in the appendix.", exampleTranslation: "توجد الخرائط في الملحق." },
  { word: "bibliography", translation: "ثبت المراجع", partOfSpeech: "noun", difficulty: "hard", example: "List your books in the bibliography.", exampleTranslation: "اذكر كتبك في ثبت المراجع." },
  { word: "manuscript", translation: "مخطوطة", partOfSpeech: "noun", difficulty: "hard", example: "The old manuscript was hard to read.", exampleTranslation: "كانت المخطوطة القديمة صعبة القراءة." },
  { word: "syntax", translation: "نحو/تركيب الجملة", partOfSpeech: "noun", difficulty: "hard", example: "Correct syntax makes a clear sentence.", exampleTranslation: "النحو الصحيح يجعل الجملة واضحة." },
  { word: "dialect", translation: "لهجة", partOfSpeech: "noun", difficulty: "hard", example: "Each region has its own dialect.", exampleTranslation: "لكل منطقة لهجتها الخاصة." },
  { word: "lexicon", translation: "معجم/مفردات", partOfSpeech: "noun", difficulty: "hard", example: "New words enter our lexicon each year.", exampleTranslation: "تدخل كلمات جديدة معجمنا كل عام." },
  { word: "terminology", translation: "مصطلحات", partOfSpeech: "noun", difficulty: "hard", example: "Science uses precise terminology.", exampleTranslation: "يستخدم العلم مصطلحات دقيقة." },
  { word: "rhetoric", translation: "بلاغة/خطابة", partOfSpeech: "noun", difficulty: "hard", example: "The speech was full of rhetoric.", exampleTranslation: "كان الخطاب مليئاً بالبلاغة." },
  { word: "clarity", translation: "وضوح", partOfSpeech: "noun", difficulty: "hard", example: "Write with clarity and order.", exampleTranslation: "اكتب بوضوح وترتيب." },
  { word: "ambiguity", translation: "غموض/التباس", partOfSpeech: "noun", difficulty: "hard", example: "Avoid ambiguity in your instructions.", exampleTranslation: "تجنّب الغموض في تعليماتك." },
  { word: "nuance", translation: "فارق دقيق", partOfSpeech: "noun", difficulty: "hard", example: "A small nuance changed the meaning.", exampleTranslation: "غيّر فارق دقيق المعنى." },
  { word: "paradox", translation: "مفارقة", partOfSpeech: "noun", difficulty: "hard", example: "The riddle hides a clever paradox.", exampleTranslation: "يخفي اللغز مفارقة ذكية." },
  { word: "fallacy", translation: "مغالطة", partOfSpeech: "noun", difficulty: "hard", example: "That belief is a common fallacy.", exampleTranslation: "ذلك الاعتقاد مغالطة شائعة." },
  { word: "feasibility", translation: "جدوى/إمكانية", partOfSpeech: "noun", difficulty: "hard", example: "They studied the feasibility of the plan.", exampleTranslation: "درسوا جدوى الخطة." },
  { word: "credibility", translation: "مصداقية", partOfSpeech: "noun", difficulty: "hard", example: "Honest sources have more credibility.", exampleTranslation: "المصادر الصادقة أكثر مصداقية." },
  { word: "objectivity", translation: "موضوعية", partOfSpeech: "noun", difficulty: "hard", example: "A judge needs objectivity.", exampleTranslation: "يحتاج القاضي إلى الموضوعية." },
  { word: "reasoning", translation: "استدلال/تفكير منطقي", partOfSpeech: "noun", difficulty: "hard", example: "Show the reasoning behind your answer.", exampleTranslation: "أظهر الاستدلال وراء إجابتك." },
  { word: "intuition", translation: "حدس", partOfSpeech: "noun", difficulty: "hard", example: "Her intuition told her to wait.", exampleTranslation: "أخبرها حدسها أن تنتظر." },
  { word: "comprehension", translation: "استيعاب/فهم", partOfSpeech: "noun", difficulty: "hard", example: "Reading slowly aids comprehension.", exampleTranslation: "تساعد القراءة البطيئة على الاستيعاب." },
  { word: "retention", translation: "احتفاظ/استبقاء", partOfSpeech: "noun", difficulty: "hard", example: "Review improves retention of facts.", exampleTranslation: "تحسّن المراجعة الاحتفاظ بالمعلومات." },
  { word: "recall", translation: "استرجاع/يتذكّر", partOfSpeech: "noun", difficulty: "hard", example: "Quick recall of words helps in tests.", exampleTranslation: "يساعد الاسترجاع السريع للكلمات في الاختبارات." },
  { word: "curriculum", translation: "منهج دراسي", partOfSpeech: "noun", difficulty: "hard", example: "Science is part of our curriculum.", exampleTranslation: "العلوم جزء من منهجنا الدراسي." },
  { word: "syllabus", translation: "مقرّر/خطة المادة", partOfSpeech: "noun", difficulty: "hard", example: "The teacher handed out the syllabus.", exampleTranslation: "وزّع المعلّم خطة المادة." },
  { word: "seminar", translation: "ندوة", partOfSpeech: "noun", difficulty: "hard", example: "We joined a science seminar.", exampleTranslation: "انضممنا إلى ندوة علمية." },
  { word: "lecture", translation: "محاضرة", partOfSpeech: "noun", difficulty: "medium", example: "The lecture lasted one hour.", exampleTranslation: "استمرّت المحاضرة ساعة واحدة." },
  { word: "tutorial", translation: "درس تعليمي مصغّر", partOfSpeech: "noun", difficulty: "hard", example: "The tutorial showed us each step.", exampleTranslation: "أرانا الدرس التعليمي كل خطوة." },
  { word: "abstraction", translation: "تجريد", partOfSpeech: "noun", difficulty: "hard", example: "A map is an abstraction of a place.", exampleTranslation: "الخريطة تجريد لمكان ما." },
  { word: "synthesis", translation: "تركيب/توليف", partOfSpeech: "noun", difficulty: "hard", example: "The essay was a synthesis of many ideas.", exampleTranslation: "كان المقال توليفاً لأفكار كثيرة." },
  { word: "rubric", translation: "معيار تقويم", partOfSpeech: "noun", difficulty: "hard", example: "The rubric shows how we earn marks.", exampleTranslation: "يبيّن معيار التقويم كيف نكسب الدرجات." },
  { word: "annotation", translation: "تعليق توضيحي", partOfSpeech: "noun", difficulty: "hard", example: "She added an annotation to the map.", exampleTranslation: "أضافت تعليقاً توضيحياً على الخريطة." },
  { word: "footnote", translation: "حاشية", partOfSpeech: "noun", difficulty: "hard", example: "A footnote explains the rare word.", exampleTranslation: "تشرح الحاشية الكلمة النادرة." },
  { word: "transcript", translation: "نسخة مكتوبة", partOfSpeech: "noun", difficulty: "hard", example: "We read the transcript of the speech.", exampleTranslation: "قرأنا النسخة المكتوبة للخطاب." },
  { word: "corollary", translation: "نتيجة لازمة", partOfSpeech: "noun", difficulty: "hard", example: "Lower cost is a corollary of the new plan.", exampleTranslation: "انخفاض التكلفة نتيجة لازمة للخطة الجديدة." },
  { word: "semantics", translation: "علم الدلالة", partOfSpeech: "noun", difficulty: "hard", example: "Semantics studies the meaning of words.", exampleTranslation: "يدرس علم الدلالة معاني الكلمات." },
  { word: "jargon", translation: "مصطلحات مهنية", partOfSpeech: "noun", difficulty: "hard", example: "Avoid jargon when you teach beginners.", exampleTranslation: "تجنّب المصطلحات المهنية عند تعليم المبتدئين." },
  { word: "eloquence", translation: "فصاحة", partOfSpeech: "noun", difficulty: "hard", example: "Her eloquence won the debate.", exampleTranslation: "أكسبتها فصاحتها النقاش." }
];
