/** Grade 6 chunk H — jobs, places, buildings, transport & materials (cards 1001-1500, batch 2). */
export const GRADE6_CHUNK_H = [
  { word: "architect", translation: "مهندس معماري", partOfSpeech: "noun", difficulty: "hard", example: "The architect drew the new school.", exampleTranslation: "رسم المهندس المعماري المدرسة الجديدة." },
  { word: "astronaut", translation: "رائد فضاء", partOfSpeech: "noun", difficulty: "medium", example: "The astronaut floated in the spacecraft.", exampleTranslation: "طاف رائد الفضاء داخل المركبة." },
  { word: "carpenter", translation: "نجّار", partOfSpeech: "noun", difficulty: "medium", example: "The carpenter built a wooden table.", exampleTranslation: "صنع النجّار طاولة خشبية." },
  { word: "chemist", translation: "كيميائي", partOfSpeech: "noun", difficulty: "medium", example: "The chemist mixed two safe liquids.", exampleTranslation: "مزج الكيميائي سائلين آمنين." },
  { word: "engineer", translation: "مهندس", partOfSpeech: "noun", difficulty: "medium", example: "The engineer fixed the broken bridge.", exampleTranslation: "أصلح المهندس الجسر المكسور." },
  { word: "scientist", translation: "عالِم", partOfSpeech: "noun", difficulty: "easy", example: "The scientist studied the tiny cells.", exampleTranslation: "درس العالِم الخلايا الصغيرة." },
  { word: "surgeon", translation: "جرّاح", partOfSpeech: "noun", difficulty: "hard", example: "The surgeon worked for three hours.", exampleTranslation: "عمل الجرّاح ثلاث ساعات." },
  { word: "pilot", translation: "طيّار", partOfSpeech: "noun", difficulty: "medium", example: "The pilot landed the plane safely.", exampleTranslation: "أنزل الطيّار الطائرة بأمان." },
  { word: "sailor", translation: "بحّار", partOfSpeech: "noun", difficulty: "medium", example: "The sailor tied the boat to the dock.", exampleTranslation: "ربط البحّار القارب بالرصيف." },
  { word: "mechanic", translation: "ميكانيكي", partOfSpeech: "noun", difficulty: "medium", example: "The mechanic checked the car engine.", exampleTranslation: "فحص الميكانيكي محرّك السيارة." },
  { word: "electrician", translation: "كهربائي", partOfSpeech: "noun", difficulty: "hard", example: "The electrician repaired the wires.", exampleTranslation: "أصلح الكهربائي الأسلاك." },
  { word: "plumber", translation: "سبّاك", partOfSpeech: "noun", difficulty: "hard", example: "The plumber stopped the leak.", exampleTranslation: "أوقف السبّاك التسرّب." },
  { word: "tailor", translation: "خيّاط", partOfSpeech: "noun", difficulty: "medium", example: "The tailor sewed a fine suit.", exampleTranslation: "خاط الخيّاط بدلة أنيقة." },
  { word: "baker", translation: "خبّاز", partOfSpeech: "noun", difficulty: "easy", example: "The baker sells warm bread.", exampleTranslation: "يبيع الخبّاز خبزاً دافئاً." },
  { word: "butcher", translation: "جزّار", partOfSpeech: "noun", difficulty: "medium", example: "The butcher cut the fresh meat.", exampleTranslation: "قطع الجزّار اللحم الطازج." },
  { word: "farmer", translation: "مزارع", partOfSpeech: "noun", difficulty: "easy", example: "The farmer plowed the wide field.", exampleTranslation: "حرث المزارع الحقل الواسع." },
  { word: "gardener", translation: "بستاني", partOfSpeech: "noun", difficulty: "medium", example: "The gardener watered the roses.", exampleTranslation: "سقى البستاني الورود." },
  { word: "fisherman", translation: "صيّاد سمك", partOfSpeech: "noun", difficulty: "medium", example: "The fisherman cast his net at dawn.", exampleTranslation: "ألقى صيّاد السمك شبكته عند الفجر." },
  { word: "miner", translation: "عامل منجم", partOfSpeech: "noun", difficulty: "hard", example: "The miner dug deep for gold.", exampleTranslation: "حفر عامل المنجم عميقاً بحثاً عن الذهب." },
  { word: "journalist", translation: "صحفي", partOfSpeech: "noun", difficulty: "hard", example: "The journalist wrote about the flood.", exampleTranslation: "كتب الصحفي عن الفيضان." },
  { word: "lawyer", translation: "محامٍ", partOfSpeech: "noun", difficulty: "medium", example: "The lawyer defended her client.", exampleTranslation: "دافعت المحامية عن موكّلها." },
  { word: "librarian", translation: "أمين مكتبة", partOfSpeech: "noun", difficulty: "medium", example: "The librarian shelved the new books.", exampleTranslation: "رتّب أمين المكتبة الكتب الجديدة." },
  { word: "musician", translation: "موسيقي", partOfSpeech: "noun", difficulty: "medium", example: "The musician played a gentle song.", exampleTranslation: "عزف الموسيقي أغنية رقيقة." },
  { word: "professor", translation: "أستاذ جامعي", partOfSpeech: "noun", difficulty: "hard", example: "The professor explained the theory well.", exampleTranslation: "شرح الأستاذ الجامعي النظرية جيداً." },
  { word: "detective", translation: "محقّق", partOfSpeech: "noun", difficulty: "medium", example: "The detective found the missing ring.", exampleTranslation: "وجد المحقّق الخاتم المفقود." },
  { word: "merchant", translation: "تاجر", partOfSpeech: "noun", difficulty: "hard", example: "The merchant sold silk and spices.", exampleTranslation: "باع التاجر الحرير والبهارات." },
  { word: "sculptor", translation: "نحّات", partOfSpeech: "noun", difficulty: "hard", example: "The sculptor carved a marble lion.", exampleTranslation: "نحت النحّات أسداً من الرخام." },
  { word: "veterinarian", translation: "طبيب بيطري", partOfSpeech: "noun", difficulty: "hard", example: "The veterinarian healed the sick dog.", exampleTranslation: "عالج الطبيب البيطري الكلب المريض." },
  { word: "geologist", translation: "جيولوجي", partOfSpeech: "noun", difficulty: "hard", example: "The geologist studied the old rocks.", exampleTranslation: "درس الجيولوجي الصخور القديمة." },
  { word: "technician", translation: "فنّي", partOfSpeech: "noun", difficulty: "hard", example: "The technician set up the computers.", exampleTranslation: "جهّز الفنّي الحواسيب." },
  { word: "apprentice", translation: "متدرّب", partOfSpeech: "noun", difficulty: "hard", example: "The young apprentice learned from the baker.", exampleTranslation: "تعلّم المتدرّب الصغير من الخبّاز." },
  { word: "airport", translation: "مطار", partOfSpeech: "noun", difficulty: "easy", example: "We met our cousins at the airport.", exampleTranslation: "قابلنا أبناء عمومتنا في المطار." },
  { word: "stadium", translation: "ملعب/استاد", partOfSpeech: "noun", difficulty: "medium", example: "The stadium was full of fans.", exampleTranslation: "كان الملعب مليئاً بالمشجّعين." },
  { word: "museum", translation: "متحف", partOfSpeech: "noun", difficulty: "easy", example: "The museum displays ancient tools.", exampleTranslation: "يعرض المتحف أدوات قديمة." },
  { word: "hospital", translation: "مستشفى", partOfSpeech: "noun", difficulty: "easy", example: "The new hospital opened last week.", exampleTranslation: "افتُتح المستشفى الجديد الأسبوع الماضي." },
  { word: "library", translation: "مكتبة", partOfSpeech: "noun", difficulty: "easy", example: "The library is quiet in the morning.", exampleTranslation: "المكتبة هادئة في الصباح." },
  { word: "factory", translation: "مصنع", partOfSpeech: "noun", difficulty: "medium", example: "The factory makes paper from wood.", exampleTranslation: "يصنع المصنع الورق من الخشب." },
  { word: "warehouse", translation: "مستودع", partOfSpeech: "noun", difficulty: "hard", example: "The goods are stored in a warehouse.", exampleTranslation: "تُخزَّن البضائع في مستودع." },
  { word: "workshop", translation: "ورشة", partOfSpeech: "noun", difficulty: "medium", example: "He repairs bikes in his workshop.", exampleTranslation: "يصلح الدرّاجات في ورشته." },
  { word: "palace", translation: "قصر", partOfSpeech: "noun", difficulty: "medium", example: "The old palace had golden gates.", exampleTranslation: "كان للقصر القديم بوّابات ذهبية." },
  { word: "castle", translation: "قلعة", partOfSpeech: "noun", difficulty: "easy", example: "The castle stood on a tall hill.", exampleTranslation: "وقفت القلعة على تلّ عالٍ." },
  { word: "fortress", translation: "حصن", partOfSpeech: "noun", difficulty: "hard", example: "Thick walls protected the fortress.", exampleTranslation: "حمت الجدران السميكة الحصن." },
  { word: "temple", translation: "معبد", partOfSpeech: "noun", difficulty: "medium", example: "The ancient temple had stone pillars.", exampleTranslation: "كان للمعبد القديم أعمدة حجرية." },
  { word: "tower", translation: "برج", partOfSpeech: "noun", difficulty: "easy", example: "The clock tower rings every hour.", exampleTranslation: "يدقّ برج الساعة كل ساعة." },
  { word: "bridge", translation: "جسر", partOfSpeech: "noun", difficulty: "easy", example: "A long bridge crosses the river.", exampleTranslation: "يعبر جسر طويل النهر." },
  { word: "tunnel", translation: "نفق", partOfSpeech: "noun", difficulty: "medium", example: "The train sped through the dark tunnel.", exampleTranslation: "اندفع القطار عبر النفق المظلم." },
  { word: "lighthouse", translation: "منارة", partOfSpeech: "noun", difficulty: "hard", example: "The lighthouse guides ships at night.", exampleTranslation: "ترشد المنارة السفن في الليل." },
  { word: "pyramid", translation: "هرم", partOfSpeech: "noun", difficulty: "medium", example: "The great pyramid amazed the visitors.", exampleTranslation: "أذهل الهرم العظيم الزوّار." },
  { word: "cathedral", translation: "كاتدرائية", partOfSpeech: "noun", difficulty: "hard", example: "The cathedral has tall stained windows.", exampleTranslation: "للكاتدرائية نوافذ زجاجية ملوّنة عالية." },
  { word: "mosque", translation: "مسجد", partOfSpeech: "noun", difficulty: "easy", example: "The mosque has a beautiful dome.", exampleTranslation: "للمسجد قبّة جميلة." },
  { word: "barn", translation: "حظيرة", partOfSpeech: "noun", difficulty: "medium", example: "The cows sleep in the red barn.", exampleTranslation: "تنام الأبقار في الحظيرة الحمراء." },
  { word: "cottage", translation: "كوخ ريفي", partOfSpeech: "noun", difficulty: "hard", example: "They rented a cottage by the lake.", exampleTranslation: "استأجروا كوخاً ريفياً بجانب البحيرة." },
  { word: "cabin", translation: "مقصورة/كوخ", partOfSpeech: "noun", difficulty: "medium", example: "We slept in a wooden cabin.", exampleTranslation: "نمنا في كوخ خشبي." },
  { word: "apartment", translation: "شقّة", partOfSpeech: "noun", difficulty: "easy", example: "Their apartment is on the third floor.", exampleTranslation: "شقّتهم في الطابق الثالث." },
  { word: "basement", translation: "قبو", partOfSpeech: "noun", difficulty: "medium", example: "We keep old boxes in the basement.", exampleTranslation: "نحتفظ بالصناديق القديمة في القبو." },
  { word: "corridor", translation: "ممرّ", partOfSpeech: "noun", difficulty: "medium", example: "A long corridor leads to the lab.", exampleTranslation: "يؤدّي ممرّ طويل إلى المختبر." },
  { word: "courtyard", translation: "فناء", partOfSpeech: "noun", difficulty: "hard", example: "The children play in the courtyard.", exampleTranslation: "يلعب الأطفال في الفناء." },
  { word: "fountain", translation: "نافورة", partOfSpeech: "noun", difficulty: "medium", example: "A stone fountain stood in the square.", exampleTranslation: "وقفت نافورة حجرية في الساحة." },
  { word: "garage", translation: "كراج", partOfSpeech: "noun", difficulty: "easy", example: "The car is parked in the garage.", exampleTranslation: "السيارة متوقّفة في الكراج." },
  { word: "market", translation: "سوق", partOfSpeech: "noun", difficulty: "easy", example: "The market is busy on Friday.", exampleTranslation: "السوق مزدحم يوم الجمعة." },
  { word: "restaurant", translation: "مطعم", partOfSpeech: "noun", difficulty: "easy", example: "We ate dinner at a small restaurant.", exampleTranslation: "تناولنا العشاء في مطعم صغير." },
  { word: "studio", translation: "استوديو", partOfSpeech: "noun", difficulty: "medium", example: "The artist works in a bright studio.", exampleTranslation: "يعمل الفنان في استوديو مضيء." },
  { word: "university", translation: "جامعة", partOfSpeech: "noun", difficulty: "medium", example: "She hopes to study at a good university.", exampleTranslation: "تأمل أن تدرس في جامعة جيدة." },
  { word: "aircraft", translation: "طائرة", partOfSpeech: "noun", difficulty: "medium", example: "The aircraft rose above the clouds.", exampleTranslation: "ارتفعت الطائرة فوق الغيوم." },
  { word: "helicopter", translation: "مروحية", partOfSpeech: "noun", difficulty: "medium", example: "The helicopter landed on the roof.", exampleTranslation: "هبطت المروحية على السطح." },
  { word: "submarine", translation: "غوّاصة", partOfSpeech: "noun", difficulty: "medium", example: "The submarine dived beneath the waves.", exampleTranslation: "غاصت الغوّاصة تحت الأمواج." },
  { word: "ambulance", translation: "سيارة إسعاف", partOfSpeech: "noun", difficulty: "medium", example: "The ambulance rushed to the scene.", exampleTranslation: "أسرعت سيارة الإسعاف إلى الموقع." },
  { word: "bicycle", translation: "درّاجة هوائية", partOfSpeech: "noun", difficulty: "easy", example: "He rides his bicycle to school.", exampleTranslation: "يركب درّاجته الهوائية إلى المدرسة." },
  { word: "motorcycle", translation: "درّاجة نارية", partOfSpeech: "noun", difficulty: "medium", example: "The motorcycle roared down the road.", exampleTranslation: "هدرت الدرّاجة النارية على الطريق." },
  { word: "tractor", translation: "جرّار", partOfSpeech: "noun", difficulty: "medium", example: "The tractor pulled the heavy plow.", exampleTranslation: "جرّ الجرّار المحراث الثقيل." },
  { word: "truck", translation: "شاحنة", partOfSpeech: "noun", difficulty: "easy", example: "The truck carried sand to the site.", exampleTranslation: "حملت الشاحنة الرمل إلى الموقع." },
  { word: "canoe", translation: "زورق", partOfSpeech: "noun", difficulty: "hard", example: "We paddled the canoe across the lake.", exampleTranslation: "جدّفنا الزورق عبر البحيرة." },
  { word: "ferry", translation: "عبّارة", partOfSpeech: "noun", difficulty: "medium", example: "The ferry carried cars across the bay.", exampleTranslation: "نقلت العبّارة السيارات عبر الخليج." },
  { word: "yacht", translation: "يخت", partOfSpeech: "noun", difficulty: "hard", example: "A white yacht sailed near the shore.", exampleTranslation: "أبحر يخت أبيض قرب الشاطئ." },
  { word: "vessel", translation: "سفينة/وعاء", partOfSpeech: "noun", difficulty: "hard", example: "The fishing vessel returned at sunset.", exampleTranslation: "عادت سفينة الصيد عند الغروب." },
  { word: "voyage", translation: "رحلة بحرية", partOfSpeech: "noun", difficulty: "hard", example: "The long voyage lasted many weeks.", exampleTranslation: "استمرّت الرحلة البحرية الطويلة أسابيع." },
  { word: "wagon", translation: "عربة", partOfSpeech: "noun", difficulty: "medium", example: "The horse pulled a wooden wagon.", exampleTranslation: "جرّ الحصان عربة خشبية." },
  { word: "parachute", translation: "مظلّة هبوط", partOfSpeech: "noun", difficulty: "hard", example: "The parachute opened high in the air.", exampleTranslation: "فُتحت مظلّة الهبوط عالياً في الهواء." },
  { word: "subway", translation: "مترو الأنفاق", partOfSpeech: "noun", difficulty: "medium", example: "We took the subway downtown.", exampleTranslation: "أخذنا مترو الأنفاق إلى وسط المدينة." },
  { word: "concrete", translation: "خرسانة", partOfSpeech: "noun", difficulty: "hard", example: "The wall is made of solid concrete.", exampleTranslation: "الجدار مصنوع من خرسانة صلبة." },
  { word: "marble", translation: "رخام", partOfSpeech: "noun", difficulty: "medium", example: "The floor was cool white marble.", exampleTranslation: "كانت الأرضية رخاماً أبيض بارداً." },
  { word: "copper", translation: "نحاس", partOfSpeech: "noun", difficulty: "medium", example: "Copper wires carry the current.", exampleTranslation: "تحمل أسلاك النحاس التيار." },
  { word: "steel", translation: "فولاذ", partOfSpeech: "noun", difficulty: "medium", example: "The beams are made of strong steel.", exampleTranslation: "العوارض مصنوعة من فولاذ قوي." },
  { word: "aluminum", translation: "ألومنيوم", partOfSpeech: "noun", difficulty: "hard", example: "Cans are often made of aluminum.", exampleTranslation: "تُصنع العلب غالباً من الألومنيوم." },
  { word: "bronze", translation: "برونز", partOfSpeech: "noun", difficulty: "hard", example: "The medal was made of bronze.", exampleTranslation: "كانت الميدالية مصنوعة من البرونز." },
  { word: "ceramic", translation: "خزف", partOfSpeech: "noun", difficulty: "hard", example: "The cup is made of white ceramic.", exampleTranslation: "الكوب مصنوع من خزف أبيض." },
  { word: "cotton", translation: "قطن", partOfSpeech: "noun", difficulty: "easy", example: "The shirt is made of soft cotton.", exampleTranslation: "القميص مصنوع من قطن ناعم." },
  { word: "fabric", translation: "نسيج/قماش", partOfSpeech: "noun", difficulty: "medium", example: "She chose a light fabric for summer.", exampleTranslation: "اختارت قماشاً خفيفاً للصيف." },
  { word: "fiber", translation: "ألياف", partOfSpeech: "noun", difficulty: "hard", example: "The rope is made of strong fiber.", exampleTranslation: "الحبل مصنوع من ألياف قوية." },
  { word: "leather", translation: "جلد", partOfSpeech: "noun", difficulty: "medium", example: "His shoes are made of brown leather.", exampleTranslation: "حذاؤه مصنوع من جلد بنّي." },
  { word: "silk", translation: "حرير", partOfSpeech: "noun", difficulty: "medium", example: "The scarf is woven from fine silk.", exampleTranslation: "الوشاح منسوج من حرير ناعم." },
  { word: "wool", translation: "صوف", partOfSpeech: "noun", difficulty: "easy", example: "The warm sweater is made of wool.", exampleTranslation: "السترة الدافئة مصنوعة من الصوف." },
  { word: "plastic", translation: "بلاستيك", partOfSpeech: "noun", difficulty: "easy", example: "The toy is made of hard plastic.", exampleTranslation: "اللعبة مصنوعة من بلاستيك صلب." },
  { word: "timber", translation: "أخشاب", partOfSpeech: "noun", difficulty: "hard", example: "They built the roof from timber.", exampleTranslation: "بنوا السقف من الأخشاب." },
  { word: "granite", translation: "غرانيت", partOfSpeech: "noun", difficulty: "hard", example: "The statue stands on a granite base.", exampleTranslation: "يقف التمثال على قاعدة من الغرانيت." },
  { word: "clay", translation: "صلصال/طين", partOfSpeech: "noun", difficulty: "easy", example: "The pot was shaped from wet clay.", exampleTranslation: "شُكّل الإناء من طين رطب." },
  { word: "glass", translation: "زجاج", partOfSpeech: "noun", difficulty: "easy", example: "The window is made of clear glass.", exampleTranslation: "النافذة مصنوعة من زجاج صافٍ." },
  { word: "rubber", translation: "مطّاط", partOfSpeech: "noun", difficulty: "easy", example: "The tires are made of tough rubber.", exampleTranslation: "الإطارات مصنوعة من مطّاط متين." },
  { word: "iron", translation: "حديد", partOfSpeech: "noun", difficulty: "easy", example: "The gate is made of heavy iron.", exampleTranslation: "البوّابة مصنوعة من حديد ثقيل." },
  { word: "village", translation: "قرية", partOfSpeech: "noun", difficulty: "easy", example: "The small village sits near the hills.", exampleTranslation: "تقع القرية الصغيرة قرب التلال." },
  { word: "suburb", translation: "ضاحية", partOfSpeech: "noun", difficulty: "hard", example: "They moved to a quiet suburb.", exampleTranslation: "انتقلوا إلى ضاحية هادئة." },
  { word: "downtown", translation: "وسط المدينة", partOfSpeech: "noun", difficulty: "medium", example: "The shops downtown stay open late.", exampleTranslation: "تبقى متاجر وسط المدينة مفتوحة حتى وقت متأخّر." },
  { word: "outskirts", translation: "أطراف المدينة", partOfSpeech: "noun", difficulty: "hard", example: "The farm lies on the outskirts of town.", exampleTranslation: "تقع المزرعة على أطراف المدينة." },
  { word: "neighbor", translation: "جار", partOfSpeech: "noun", difficulty: "easy", example: "Our neighbor lent us a ladder.", exampleTranslation: "أعارنا جارنا سلّماً." },
  { word: "resident", translation: "ساكن/مقيم", partOfSpeech: "noun", difficulty: "hard", example: "Every resident received a letter.", exampleTranslation: "تلقّى كل مقيم رسالة." },
  { word: "passenger", translation: "راكب", partOfSpeech: "noun", difficulty: "medium", example: "Each passenger showed a ticket.", exampleTranslation: "أظهر كل راكب تذكرة." },
  { word: "pedestrian", translation: "مشاة", partOfSpeech: "noun", difficulty: "hard", example: "The pedestrian crossed at the light.", exampleTranslation: "عبر المشاة عند الإشارة." },
  { word: "tourist", translation: "سائح", partOfSpeech: "noun", difficulty: "medium", example: "A tourist asked for directions.", exampleTranslation: "سأل سائح عن الاتجاهات." },
  { word: "customer", translation: "زبون", partOfSpeech: "noun", difficulty: "medium", example: "The customer paid for the bread.", exampleTranslation: "دفع الزبون ثمن الخبز." },
  { word: "highway", translation: "طريق سريع", partOfSpeech: "noun", difficulty: "medium", example: "The highway leads to the coast.", exampleTranslation: "يؤدّي الطريق السريع إلى الساحل." },
  { word: "avenue", translation: "جادّة", partOfSpeech: "noun", difficulty: "hard", example: "Tall trees line the wide avenue.", exampleTranslation: "تصطفّ الأشجار الطويلة على طول الجادّة الواسعة." },
  { word: "alley", translation: "زقاق", partOfSpeech: "noun", difficulty: "medium", example: "A narrow alley runs behind the shops.", exampleTranslation: "يمتدّ زقاق ضيّق خلف المتاجر." },
  { word: "square", translation: "ساحة", partOfSpeech: "noun", difficulty: "easy", example: "People gather in the town square.", exampleTranslation: "يتجمّع الناس في ساحة البلدة." },
  { word: "landmark", translation: "معلم بارز", partOfSpeech: "noun", difficulty: "hard", example: "The tower is a famous landmark.", exampleTranslation: "البرج معلم بارز مشهور." },
  { word: "dock", translation: "رصيف بحري", partOfSpeech: "noun", difficulty: "medium", example: "The ship tied up at the dock.", exampleTranslation: "رست السفينة عند الرصيف البحري." },
  { word: "pier", translation: "رصيف ممتدّ", partOfSpeech: "noun", difficulty: "hard", example: "We walked to the end of the pier.", exampleTranslation: "مشينا إلى نهاية الرصيف الممتدّ." },
  { word: "runway", translation: "مدرّج", partOfSpeech: "noun", difficulty: "hard", example: "The plane sped along the runway.", exampleTranslation: "اندفعت الطائرة على المدرّج." },
  { word: "platform", translation: "رصيف القطار/منصّة", partOfSpeech: "noun", difficulty: "medium", example: "We waited on the train platform.", exampleTranslation: "انتظرنا على رصيف القطار." },
  { word: "station", translation: "محطة", partOfSpeech: "noun", difficulty: "easy", example: "The bus left the station on time.", exampleTranslation: "غادرت الحافلة المحطة في موعدها." },
  { word: "intersection", translation: "تقاطع", partOfSpeech: "noun", difficulty: "hard", example: "Stop at the busy intersection.", exampleTranslation: "توقّف عند التقاطع المزدحم." },
  { word: "sidewalk", translation: "رصيف المشاة", partOfSpeech: "noun", difficulty: "medium", example: "Children chalk pictures on the sidewalk.", exampleTranslation: "يرسم الأطفال بالطباشير على رصيف المشاة." },
  { word: "lane", translation: "حارة/ممرّ", partOfSpeech: "noun", difficulty: "medium", example: "Stay in the right lane.", exampleTranslation: "ابقَ في الحارة اليمنى." },
  { word: "route", translation: "مسار/طريق", partOfSpeech: "noun", difficulty: "medium", example: "The bus follows the same route daily.", exampleTranslation: "تتبع الحافلة المسار نفسه يومياً." },
  { word: "trail", translation: "درب/مسلك", partOfSpeech: "noun", difficulty: "medium", example: "The hiking trail climbs the hill.", exampleTranslation: "يصعد درب المشي التلّ." },
  { word: "elevator", translation: "مصعد", partOfSpeech: "noun", difficulty: "medium", example: "The elevator stopped on the top floor.", exampleTranslation: "توقّف المصعد في الطابق العلوي." },
  { word: "staircase", translation: "درج", partOfSpeech: "noun", difficulty: "medium", example: "A wide staircase led to the hall.", exampleTranslation: "أدّى درج واسع إلى القاعة." },
  { word: "balcony", translation: "شرفة", partOfSpeech: "noun", difficulty: "medium", example: "We watched the parade from the balcony.", exampleTranslation: "شاهدنا الاستعراض من الشرفة." },
  { word: "ceiling", translation: "سقف", partOfSpeech: "noun", difficulty: "easy", example: "A fan hangs from the ceiling.", exampleTranslation: "تتدلّى مروحة من السقف." },
  { word: "chimney", translation: "مدخنة", partOfSpeech: "noun", difficulty: "medium", example: "Smoke rose from the chimney.", exampleTranslation: "ارتفع الدخان من المدخنة." },
  { word: "pillar", translation: "عمود/دعامة", partOfSpeech: "noun", difficulty: "hard", example: "Stone pillars hold up the roof.", exampleTranslation: "تحمل الأعمدة الحجرية السقف." },
  { word: "arch", translation: "قوس", partOfSpeech: "noun", difficulty: "medium", example: "A stone arch framed the gate.", exampleTranslation: "أطّر قوس حجري البوّابة." },
  { word: "dome", translation: "قبّة", partOfSpeech: "noun", difficulty: "medium", example: "The golden dome shone in the sun.", exampleTranslation: "لمعت القبّة الذهبية في الشمس." },
  { word: "fence", translation: "سياج", partOfSpeech: "noun", difficulty: "easy", example: "A wooden fence surrounds the yard.", exampleTranslation: "يحيط سياج خشبي بالفناء." },
  { word: "gate", translation: "بوّابة", partOfSpeech: "noun", difficulty: "easy", example: "The iron gate creaked open.", exampleTranslation: "صرّت البوّابة الحديدية وهي تُفتح." },
  { word: "hall", translation: "قاعة/ردهة", partOfSpeech: "noun", difficulty: "easy", example: "The meeting was held in the main hall.", exampleTranslation: "عُقد الاجتماع في القاعة الرئيسية." },
  { word: "hammer", translation: "مطرقة", partOfSpeech: "noun", difficulty: "easy", example: "He drove the nail with a hammer.", exampleTranslation: "دقّ المسمار بمطرقة." },
  { word: "wrench", translation: "مفتاح ربط", partOfSpeech: "noun", difficulty: "hard", example: "Tighten the bolt with a wrench.", exampleTranslation: "اربط الصامولة بمفتاح الربط." },
  { word: "drill", translation: "مثقاب", partOfSpeech: "noun", difficulty: "medium", example: "The drill made a neat hole.", exampleTranslation: "صنع المثقاب ثقباً مرتّباً." },
  { word: "shovel", translation: "مجرفة", partOfSpeech: "noun", difficulty: "medium", example: "She dug the soil with a shovel.", exampleTranslation: "حفرت التربة بمجرفة." },
  { word: "ladder", translation: "سلّم", partOfSpeech: "noun", difficulty: "easy", example: "He climbed the ladder to the roof.", exampleTranslation: "صعد السلّم إلى السطح." },
  { word: "nail", translation: "مسمار", partOfSpeech: "noun", difficulty: "easy", example: "Hammer the nail into the board.", exampleTranslation: "دقّ المسمار في اللوح." },
  { word: "screw", translation: "برغي", partOfSpeech: "noun", difficulty: "medium", example: "Turn the screw to tighten it.", exampleTranslation: "أدر البرغي لإحكامه." },
  { word: "blade", translation: "نصل/شفرة", partOfSpeech: "noun", difficulty: "medium", example: "The knife has a sharp blade.", exampleTranslation: "للسكين نصل حادّ." },
  { word: "axe", translation: "فأس", partOfSpeech: "noun", difficulty: "medium", example: "He split the log with an axe.", exampleTranslation: "شقّ الجذع بالفأس." },
  { word: "rope", translation: "حبل", partOfSpeech: "noun", difficulty: "easy", example: "They pulled the boat with a rope.", exampleTranslation: "سحبوا القارب بحبل." },
  { word: "chain", translation: "سلسلة", partOfSpeech: "noun", difficulty: "easy", example: "A heavy chain locked the gate.", exampleTranslation: "أقفلت سلسلة ثقيلة البوّابة." },
  { word: "bucket", translation: "دلو", partOfSpeech: "noun", difficulty: "easy", example: "She filled the bucket with water.", exampleTranslation: "ملأت الدلو بالماء." },
  { word: "torch", translation: "مشعل/كشّاف", partOfSpeech: "noun", difficulty: "medium", example: "He lit the cave with a torch.", exampleTranslation: "أضاء الكهف بمشعل." },
  { word: "compass", translation: "بوصلة", partOfSpeech: "noun", difficulty: "medium", example: "A compass points to the north.", exampleTranslation: "تشير البوصلة إلى الشمال." },
  { word: "wardrobe", translation: "خزانة ملابس", partOfSpeech: "noun", difficulty: "medium", example: "She hung the coat in the wardrobe.", exampleTranslation: "علّقت المعطف في خزانة الملابس." },
  { word: "cupboard", translation: "خزانة", partOfSpeech: "noun", difficulty: "medium", example: "The cups are in the kitchen cupboard.", exampleTranslation: "الأكواب في خزانة المطبخ." },
  { word: "drawer", translation: "درج", partOfSpeech: "noun", difficulty: "medium", example: "He keeps pens in the top drawer.", exampleTranslation: "يحتفظ بالأقلام في الدرج العلوي." },
  { word: "carpet", translation: "سجّادة", partOfSpeech: "noun", difficulty: "easy", example: "A soft carpet covers the floor.", exampleTranslation: "تغطّي سجّادة ناعمة الأرضية." },
  { word: "curtain", translation: "ستارة", partOfSpeech: "noun", difficulty: "easy", example: "She drew the curtain at night.", exampleTranslation: "أسدلت الستارة في الليل." },
  { word: "cushion", translation: "وسادة", partOfSpeech: "noun", difficulty: "medium", example: "He rested on a soft cushion.", exampleTranslation: "استراح على وسادة ناعمة." },
  { word: "lantern", translation: "فانوس", partOfSpeech: "noun", difficulty: "medium", example: "A lantern lit the dark tent.", exampleTranslation: "أضاء فانوس الخيمة المظلمة." },
  { word: "mattress", translation: "فراش", partOfSpeech: "noun", difficulty: "medium", example: "The new mattress is firm and warm.", exampleTranslation: "الفراش الجديد متين ودافئ." }
];
