/** Grade 1 lesson — 300 cards in 30 image batches of 10 */
export const GRADE1_LESSON_TITLE = "grade 1";

const GRADE1_CARDS_RAW = [
  // batch 1 — colors
  { word: "red", translation: "أحمر", partOfSpeech: "adjective", difficulty: "easy", example: "The apple is red.", exampleTranslation: "التفاحة حمراء." },
  { word: "blue", translation: "أزرق", partOfSpeech: "adjective", difficulty: "easy", example: "The sky is blue.", exampleTranslation: "السماء زرقاء." },
  { word: "green", translation: "أخضر", partOfSpeech: "adjective", difficulty: "easy", example: "The grass is green.", exampleTranslation: "العشب أخضر." },
  { word: "yellow", translation: "أصفر", partOfSpeech: "adjective", difficulty: "easy", example: "The sun is yellow.", exampleTranslation: "الشمس صفراء." },
  { word: "orange", translation: "برتقالي", partOfSpeech: "adjective", difficulty: "easy", example: "I eat an orange fruit.", exampleTranslation: "آكل ثمرة برتقالية." },
  { word: "purple", translation: "بنفسجي", partOfSpeech: "adjective", difficulty: "easy", example: "The flower is purple.", exampleTranslation: "الزهرة بنفسجية." },
  { word: "pink", translation: "وردي", partOfSpeech: "adjective", difficulty: "easy", example: "She has a pink dress.", exampleTranslation: "لديها فستان وردي." },
  { word: "black", translation: "أسود", partOfSpeech: "adjective", difficulty: "easy", example: "The cat is black.", exampleTranslation: "القطة سوداء." },
  { word: "white", translation: "أبيض", partOfSpeech: "adjective", difficulty: "easy", example: "The snow is white.", exampleTranslation: "الثلج أبيض." },
  { word: "brown", translation: "بني", partOfSpeech: "adjective", difficulty: "easy", example: "The bear is brown.", exampleTranslation: "الدب بني." },
  // batch 2 — animals 1
  { word: "cat", translation: "قطة", partOfSpeech: "noun", difficulty: "easy", example: "The cat sleeps on the mat.", exampleTranslation: "القطة تنام على السجادة." },
  { word: "dog", translation: "كلب", partOfSpeech: "noun", difficulty: "easy", example: "The dog runs in the park.", exampleTranslation: "الكلب يركض في الحديقة." },
  { word: "bird", translation: "طائر", partOfSpeech: "noun", difficulty: "easy", example: "A bird sings in the tree.", exampleTranslation: "طائر يغني في الشجرة." },
  { word: "fish", translation: "سمكة", partOfSpeech: "noun", difficulty: "easy", example: "The fish swims in the water.", exampleTranslation: "السمكة تسبح في الماء." },
  { word: "cow", translation: "بقرة", partOfSpeech: "noun", difficulty: "easy", example: "The cow eats green grass.", exampleTranslation: "البقرة تأكل العشب الأخضر." },
  { word: "pig", translation: "خنزير", partOfSpeech: "noun", difficulty: "easy", example: "The pig plays in the mud.", exampleTranslation: "الخنزير يلعب في الوحل." },
  { word: "horse", translation: "حصان", partOfSpeech: "noun", difficulty: "easy", example: "The horse runs very fast.", exampleTranslation: "الحصان يركض بسرعة كبيرة." },
  { word: "duck", translation: "بطة", partOfSpeech: "noun", difficulty: "easy", example: "The duck swims on the pond.", exampleTranslation: "البطة تسبح في البركة." },
  { word: "sheep", translation: "خروف", partOfSpeech: "noun", difficulty: "easy", example: "White sheep stand on the hill.", exampleTranslation: "أغنام بيضاء تقف على التل." },
  { word: "lion", translation: "أسد", partOfSpeech: "noun", difficulty: "easy", example: "The lion has a big mane.", exampleTranslation: "للأسد عرف كبير." },
  // batch 3 — animals 2 + numbers 1–5
  { word: "elephant", translation: "فيل", partOfSpeech: "noun", difficulty: "easy", example: "The elephant has a long trunk.", exampleTranslation: "للفيل خرطوم طويل." },
  { word: "monkey", translation: "قرد", partOfSpeech: "noun", difficulty: "easy", example: "The monkey climbs the tree.", exampleTranslation: "القرد يتسلق الشجرة." },
  { word: "rabbit", translation: "أرنب", partOfSpeech: "noun", difficulty: "easy", example: "The rabbit hops in the garden.", exampleTranslation: "الأرنب يقفز في الحديقة." },
  { word: "frog", translation: "ضفدع", partOfSpeech: "noun", difficulty: "easy", example: "The frog jumps near the pond.", exampleTranslation: "الضفدع يقفز قرب البركة." },
  { word: "bear", translation: "دب", partOfSpeech: "noun", difficulty: "easy", example: "The bear eats sweet honey.", exampleTranslation: "الدب يأكل العسل الحلو." },
  { word: "one", translation: "واحد", partOfSpeech: "number", difficulty: "easy", example: "I have one red balloon.", exampleTranslation: "لدي بالون أحمر واحد." },
  { word: "two", translation: "اثنان", partOfSpeech: "number", difficulty: "easy", example: "She has two little cats.", exampleTranslation: "لديها قطتان صغيرتان." },
  { word: "three", translation: "ثلاثة", partOfSpeech: "number", difficulty: "easy", example: "We see three yellow ducks.", exampleTranslation: "نرى ثلاث بطات صفراء." },
  { word: "four", translation: "أربعة", partOfSpeech: "number", difficulty: "easy", example: "Four birds sit on the wire.", exampleTranslation: "أربعة طيور تجلس على السلك." },
  { word: "five", translation: "خمسة", partOfSpeech: "number", difficulty: "easy", example: "He holds five colorful pencils.", exampleTranslation: "يمسك خمسة أقلام ملونة." },
  // batch 4 — numbers 6–10 + family
  { word: "six", translation: "ستة", partOfSpeech: "number", difficulty: "easy", example: "Six apples are in the box.", exampleTranslation: "ست تفاحات في الصندوق." },
  { word: "seven", translation: "سبعة", partOfSpeech: "number", difficulty: "easy", example: "Seven stars shine at night.", exampleTranslation: "سبع نجوم تلمع في الليل." },
  { word: "eight", translation: "ثمانية", partOfSpeech: "number", difficulty: "easy", example: "Eight fish swim together.", exampleTranslation: "ثماني أسماك تسبح معاً." },
  { word: "nine", translation: "تسعة", partOfSpeech: "number", difficulty: "easy", example: "Nine children play outside.", exampleTranslation: "تسعة أطفال يلعبون في الخارج." },
  { word: "ten", translation: "عشرة", partOfSpeech: "number", difficulty: "easy", example: "Ten fingers are on my hands.", exampleTranslation: "عشر أصابع على يديّ." },
  { word: "mother", translation: "أم", partOfSpeech: "noun", difficulty: "easy", example: "My mother cooks good food.", exampleTranslation: "أمي تطبخ طعاماً جيداً." },
  { word: "father", translation: "أب", partOfSpeech: "noun", difficulty: "easy", example: "My father reads me a story.", exampleTranslation: "أبي يقرأ لي قصة." },
  { word: "sister", translation: "أخت", partOfSpeech: "noun", difficulty: "easy", example: "My sister draws a pretty flower.", exampleTranslation: "أختي ترسم زهرة جميلة." },
  { word: "brother", translation: "أخ", partOfSpeech: "noun", difficulty: "easy", example: "My brother plays with a ball.", exampleTranslation: "أخي يلعب بالكرة." },
  { word: "baby", translation: "رضيع", partOfSpeech: "noun", difficulty: "easy", example: "The baby sleeps in the crib.", exampleTranslation: "الرضيع ينام في المهد." },
  // batch 5 — body
  { word: "head", translation: "رأس", partOfSpeech: "noun", difficulty: "easy", example: "I wear a hat on my head.", exampleTranslation: "أرتدي قبعة على رأسي." },
  { word: "hand", translation: "يد", partOfSpeech: "noun", difficulty: "easy", example: "Wash your hand with soap.", exampleTranslation: "اغسل يدك بالصابون." },
  { word: "foot", translation: "قدم", partOfSpeech: "noun", difficulty: "easy", example: "My foot hurts a little today.", exampleTranslation: "قدمي تؤلمني قليلاً اليوم." },
  { word: "eye", translation: "عين", partOfSpeech: "noun", difficulty: "easy", example: "She has a bright blue eye.", exampleTranslation: "لديها عين زرقاء لامعة." },
  { word: "ear", translation: "أذن", partOfSpeech: "noun", difficulty: "easy", example: "I hear music with my ear.", exampleTranslation: "أسمع الموسيقى بأذني." },
  { word: "nose", translation: "أنف", partOfSpeech: "noun", difficulty: "easy", example: "The flower smells nice to my nose.", exampleTranslation: "الزهرة رائحتها جميلة لأنفي." },
  { word: "mouth", translation: "فم", partOfSpeech: "noun", difficulty: "easy", example: "Open your mouth and smile.", exampleTranslation: "افتح فمك وابتسم." },
  { word: "hair", translation: "شعر", partOfSpeech: "noun", difficulty: "easy", example: "Her hair is long and curly.", exampleTranslation: "شعرها طويل ومجعد." },
  { word: "arm", translation: "ذراع", partOfSpeech: "noun", difficulty: "easy", example: "He waves with his right arm.", exampleTranslation: "يلوّح بذراعه اليمنى." },
  { word: "leg", translation: "ساق", partOfSpeech: "noun", difficulty: "easy", example: "The boy kicks the ball with his leg.", exampleTranslation: "الولد يركل الكرة بساقه." },
  // batch 6 — food
  { word: "apple", translation: "تفاحة", partOfSpeech: "noun", difficulty: "easy", example: "I eat a crunchy red apple.", exampleTranslation: "آكل تفاحة حمراء مقرمشة." },
  { word: "banana", translation: "موزة", partOfSpeech: "noun", difficulty: "easy", example: "The monkey likes a yellow banana.", exampleTranslation: "القرد يحب موزة صفراء." },
  { word: "bread", translation: "خبز", partOfSpeech: "noun", difficulty: "easy", example: "We buy fresh bread every morning.", exampleTranslation: "نشتري خبزاً طازجاً كل صباح." },
  { word: "milk", translation: "حليب", partOfSpeech: "noun", difficulty: "easy", example: "The cat drinks cold milk.", exampleTranslation: "القطة تشرب حليباً بارداً." },
  { word: "egg", translation: "بيضة", partOfSpeech: "noun", difficulty: "easy", example: "Mom cooks one egg for breakfast.", exampleTranslation: "أمي تطبخ بيضة واحدة للفطور." },
  { word: "rice", translation: "أرز", partOfSpeech: "noun", difficulty: "easy", example: "We eat rice with our dinner.", exampleTranslation: "نأكل الأرز مع العشاء." },
  { word: "cake", translation: "كعكة", partOfSpeech: "noun", difficulty: "easy", example: "Happy birthday! Here is your cake.", exampleTranslation: "عيد ميلاد سعيد! هذه كعكتك." },
  { word: "water", translation: "ماء", partOfSpeech: "noun", difficulty: "easy", example: "Please drink some cold water.", exampleTranslation: "من فضلك اشرب بعض الماء البارد." },
  { word: "juice", translation: "عصير", partOfSpeech: "noun", difficulty: "easy", example: "Orange juice is sweet and tasty.", exampleTranslation: "عصير البرتقال حلو ولذيذ." },
  { word: "pizza", translation: "بيتزا", partOfSpeech: "noun", difficulty: "easy", example: "We share a hot cheese pizza.", exampleTranslation: "نتشارك بيتزا جبن ساخنة." },
  // batch 7 — school
  { word: "book", translation: "كتاب", partOfSpeech: "noun", difficulty: "easy", example: "I read a story book at school.", exampleTranslation: "أقرأ كتاب قصص في المدرسة." },
  { word: "pen", translation: "قلم حبر", partOfSpeech: "noun", difficulty: "easy", example: "She writes her name with a pen.", exampleTranslation: "تكتب اسمها بقلم حبر." },
  { word: "pencil", translation: "قلم رصاص", partOfSpeech: "noun", difficulty: "easy", example: "Draw a house with your pencil.", exampleTranslation: "ارسم بيتاً بقلم الرصاص." },
  { word: "desk", translation: "مكتب", partOfSpeech: "noun", difficulty: "easy", example: "Books sit on my school desk.", exampleTranslation: "الكتب على مكتبي المدرسي." },
  { word: "chair", translation: "كرسي", partOfSpeech: "noun", difficulty: "easy", example: "Please sit on the blue chair.", exampleTranslation: "من فضلك اجلس على الكرسي الأزرق." },
  { word: "school", translation: "مدرسة", partOfSpeech: "noun", difficulty: "easy", example: "Children go to school every day.", exampleTranslation: "الأطفال يذهبون إلى المدرسة كل يوم." },
  { word: "teacher", translation: "معلم", partOfSpeech: "noun", difficulty: "easy", example: "The teacher helps us learn English.", exampleTranslation: "المعلم يساعدنا على تعلم الإنجليزية." },
  { word: "student", translation: "طالب", partOfSpeech: "noun", difficulty: "easy", example: "Every student raises a hand.", exampleTranslation: "كل طالب يرفع يده." },
  { word: "bag", translation: "حقيبة", partOfSpeech: "noun", difficulty: "easy", example: "My bag has books and pencils.", exampleTranslation: "حقيبتي فيها كتب وأقلام." },
  { word: "classroom", translation: "فصل", partOfSpeech: "noun", difficulty: "easy", example: "Our classroom is bright and clean.", exampleTranslation: "فصلنا مضيء ونظيف." },
  // batch 8 — actions
  { word: "run", translation: "يجري", partOfSpeech: "verb", difficulty: "easy", example: "The children run in the playground.", exampleTranslation: "الأطفال يجرون في الملعب." },
  { word: "jump", translation: "يقفز", partOfSpeech: "verb", difficulty: "easy", example: "The rabbit can jump very high.", exampleTranslation: "الأرنب يقفز عالياً جداً." },
  { word: "eat", translation: "يأكل", partOfSpeech: "verb", difficulty: "easy", example: "We eat lunch at twelve o'clock.", exampleTranslation: "نأكل الغداء في الساعة الثانية عشرة." },
  { word: "drink", translation: "يشرب", partOfSpeech: "verb", difficulty: "easy", example: "Birds drink water from the bowl.", exampleTranslation: "الطيور تشرب الماء من الوعاء." },
  { word: "sleep", translation: "ينام", partOfSpeech: "verb", difficulty: "easy", example: "The baby sleeps all afternoon.", exampleTranslation: "الرضيع ينام طوال بعد الظهر." },
  { word: "play", translation: "يلعب", partOfSpeech: "verb", difficulty: "easy", example: "Friends play games after school.", exampleTranslation: "الأصدقاء يلعبون ألعاباً بعد المدرسة." },
  { word: "read", translation: "يقرأ", partOfSpeech: "verb", difficulty: "easy", example: "Dad likes to read at night.", exampleTranslation: "أبي يحب القراءة في الليل." },
  { word: "write", translation: "يكتب", partOfSpeech: "verb", difficulty: "easy", example: "I write my name on the paper.", exampleTranslation: "أكتب اسمي على الورقة." },
  { word: "walk", translation: "يمشي", partOfSpeech: "verb", difficulty: "easy", example: "We walk to school together.", exampleTranslation: "نمشي إلى المدرسة معاً." },
  { word: "sit", translation: "يجلس", partOfSpeech: "verb", difficulty: "easy", example: "Please sit down and listen.", exampleTranslation: "من فضلك اجلس واستمع." },
  // batch 9 — nature & weather
  { word: "sun", translation: "شمس", partOfSpeech: "noun", difficulty: "easy", example: "The sun is hot in summer.", exampleTranslation: "الشمس حارة في الصيف." },
  { word: "rain", translation: "مطر", partOfSpeech: "noun", difficulty: "easy", example: "Rain falls from gray clouds.", exampleTranslation: "المطر يسقط من غيوم رمادية." },
  { word: "tree", translation: "شجرة", partOfSpeech: "noun", difficulty: "easy", example: "A tall tree grows in our yard.", exampleTranslation: "شجرة طويلة تنمو في فنائنا." },
  { word: "flower", translation: "زهرة", partOfSpeech: "noun", difficulty: "easy", example: "A red flower blooms in spring.", exampleTranslation: "زهرة حمراء تتفتح في الربيع." },
  { word: "sky", translation: "سماء", partOfSpeech: "noun", difficulty: "easy", example: "Birds fly high in the sky.", exampleTranslation: "الطيور تطير عالياً في السماء." },
  { word: "cloud", translation: "سحابة", partOfSpeech: "noun", difficulty: "easy", example: "A white cloud floats slowly.", exampleTranslation: "سحابة بيضاء تطفو ببطء." },
  { word: "wind", translation: "ريح", partOfSpeech: "noun", difficulty: "easy", example: "The wind blows the kite away.", exampleTranslation: "الريح تطير الطائرة الورقية بعيداً." },
  { word: "snow", translation: "ثلج", partOfSpeech: "noun", difficulty: "easy", example: "Soft snow covers the ground.", exampleTranslation: "ثلج ناعم يغطي الأرض." },
  { word: "house", translation: "بيت", partOfSpeech: "noun", difficulty: "easy", example: "Our house has a red door.", exampleTranslation: "بيتنا له باب أحمر." },
  { word: "bed", translation: "سرير", partOfSpeech: "noun", difficulty: "easy", example: "I go to bed at eight o'clock.", exampleTranslation: "أذهب إلى السرير في الساعة الثامنة." },
  // batch 10 — home, places, adjectives, clothes
  { word: "door", translation: "باب", partOfSpeech: "noun", difficulty: "easy", example: "Please close the door quietly.", exampleTranslation: "من فضلك أغلق الباب بهدوء." },
  { word: "window", translation: "نافذة", partOfSpeech: "noun", difficulty: "easy", example: "Look out the open window.", exampleTranslation: "انظر من النافذة المفتوحة." },
  { word: "table", translation: "طاولة", partOfSpeech: "noun", difficulty: "easy", example: "Food is on the kitchen table.", exampleTranslation: "الطعام على طاولة المطبخ." },
  { word: "room", translation: "غرفة", partOfSpeech: "noun", difficulty: "easy", example: "My room is small but cozy.", exampleTranslation: "غرفتي صغيرة لكنها مريحة." },
  { word: "park", translation: "حديقة", partOfSpeech: "noun", difficulty: "easy", example: "We play in the city park.", exampleTranslation: "نلعب في حديقة المدينة." },
  { word: "big", translation: "كبير", partOfSpeech: "adjective", difficulty: "easy", example: "The elephant is very big.", exampleTranslation: "الفيل كبير جداً." },
  { word: "small", translation: "صغير", partOfSpeech: "adjective", difficulty: "easy", example: "The mouse is very small.", exampleTranslation: "الفأر صغير جداً." },
  { word: "happy", translation: "سعيد", partOfSpeech: "adjective", difficulty: "easy", example: "The happy child laughs loudly.", exampleTranslation: "الطفل السعيد يضحك بصوت عالٍ." },
  { word: "shirt", translation: "قميص", partOfSpeech: "noun", difficulty: "easy", example: "He wears a clean blue shirt.", exampleTranslation: "يرتدي قميصاً أزرق نظيفاً." },
  { word: "shoes", translation: "حذاء", partOfSpeech: "noun", difficulty: "easy", example: "Put on your shoes before school.", exampleTranslation: "ارتدِ حذاءك قبل المدرسة." },
  // batch 11 — family & people
  { word: "grandma", translation: "جدة", partOfSpeech: "noun", difficulty: "easy", example: "Grandma bakes cookies for us.", exampleTranslation: "جدتي تخبز لنا بسكويت." },
  { word: "grandpa", translation: "جد", partOfSpeech: "noun", difficulty: "easy", example: "Grandpa tells funny stories.", exampleTranslation: "جدي يروي قصصاً مضحكة." },
  { word: "aunt", translation: "عمة", partOfSpeech: "noun", difficulty: "easy", example: "My aunt visits us on Sunday.", exampleTranslation: "عمتي تزورنا يوم الأحد." },
  { word: "uncle", translation: "عم", partOfSpeech: "noun", difficulty: "easy", example: "Uncle Tom plays soccer with me.", exampleTranslation: "عمي توم يلعب كرة القدم معي." },
  { word: "cousin", translation: "ابن عم", partOfSpeech: "noun", difficulty: "easy", example: "My cousin and I share toys.", exampleTranslation: "أنا وابن عمي نتشارك الألعاب." },
  { word: "friend", translation: "صديق", partOfSpeech: "noun", difficulty: "easy", example: "My best friend sits next to me.", exampleTranslation: "أفضل صديق لي يجلس بجانبي." },
  { word: "boy", translation: "ولد", partOfSpeech: "noun", difficulty: "easy", example: "The boy kicks a red ball.", exampleTranslation: "الولد يركل كرة حمراء." },
  { word: "girl", translation: "بنت", partOfSpeech: "noun", difficulty: "easy", example: "The girl reads a picture book.", exampleTranslation: "البنت تقرأ كتاب صور." },
  { word: "man", translation: "رجل", partOfSpeech: "noun", difficulty: "easy", example: "The man walks his dog.", exampleTranslation: "الرجل يمشي مع كلبه." },
  { word: "woman", translation: "امرأة", partOfSpeech: "noun", difficulty: "easy", example: "The woman buys fresh bread.", exampleTranslation: "المرأة تشتري خبزاً طازجاً." },
  // batch 12 — more animals
  { word: "chicken", translation: "دجاجة", partOfSpeech: "noun", difficulty: "easy", example: "The chicken pecks seeds on the farm.", exampleTranslation: "الدجاجة تلتقط الحبوب في المزرعة." },
  { word: "goat", translation: "ماعز", partOfSpeech: "noun", difficulty: "easy", example: "A white goat eats grass on the hill.", exampleTranslation: "ماعز أبيض يأكل العشب على التل." },
  { word: "mouse", translation: "فأر", partOfSpeech: "noun", difficulty: "easy", example: "A tiny mouse hides in the hole.", exampleTranslation: "فأر صغير يختبئ في الجحر." },
  { word: "snake", translation: "ثعبان", partOfSpeech: "noun", difficulty: "easy", example: "The green snake slides in the grass.", exampleTranslation: "الثعبان الأخضر ينزلق في العشب." },
  { word: "turtle", translation: "سلحفاة", partOfSpeech: "noun", difficulty: "easy", example: "The turtle moves slowly on the sand.", exampleTranslation: "السلحفاة تتحرك ببطء على الرمل." },
  { word: "butterfly", translation: "فراشة", partOfSpeech: "noun", difficulty: "easy", example: "A colorful butterfly lands on a flower.", exampleTranslation: "فراشة ملونة تحط على زهرة." },
  { word: "bee", translation: "نحلة", partOfSpeech: "noun", difficulty: "easy", example: "The bee buzzes around the hive.", exampleTranslation: "النحلة تطن حول الخلية." },
  { word: "ant", translation: "نملة", partOfSpeech: "noun", difficulty: "easy", example: "A small ant carries a crumb home.", exampleTranslation: "نملة صغيرة تحمل فتاتاً إلى بيتها." },
  { word: "chick", translation: "كتكوت", partOfSpeech: "noun", difficulty: "easy", example: "The yellow chick follows the hen.", exampleTranslation: "الكتكوت الأصفر يتبع الدجاجة." },
  { word: "owl", translation: "بومة", partOfSpeech: "noun", difficulty: "easy", example: "The owl watches from the tree at night.", exampleTranslation: "البومة تراقب من الشجرة في الليل." },
  // batch 13 — fruits, vegetables & more food
  { word: "cheese", translation: "جبن", partOfSpeech: "noun", difficulty: "easy", example: "I like cheese on my bread.", exampleTranslation: "أحب الجبن على خبزي." },
  { word: "carrot", translation: "جزر", partOfSpeech: "noun", difficulty: "easy", example: "The rabbit eats a long orange carrot.", exampleTranslation: "الأرنب يأكل جزراً برتقالياً طويلاً." },
  { word: "tomato", translation: "طماطم", partOfSpeech: "noun", difficulty: "easy", example: "Mom cuts a red tomato for salad.", exampleTranslation: "أمي تقطع طماطم حمراء للسلطة." },
  { word: "potato", translation: "بطاطا", partOfSpeech: "noun", difficulty: "easy", example: "We grow potatoes in the garden.", exampleTranslation: "نزرع البطاطا في الحديقة." },
  { word: "soup", translation: "شوربة", partOfSpeech: "noun", difficulty: "easy", example: "Hot soup keeps me warm.", exampleTranslation: "الشوربة الساخنة تدفئني." },
  { word: "cookie", translation: "بسكويت", partOfSpeech: "noun", difficulty: "easy", example: "Grandma gives me one chocolate cookie.", exampleTranslation: "جدتي تعطيني بسكويتة شوكولاتة واحدة." },
  { word: "candy", translation: "حلوى", partOfSpeech: "noun", difficulty: "easy", example: "The child gets candy after school.", exampleTranslation: "الطفل يحصل على حلوى بعد المدرسة." },
  { word: "tea", translation: "شاي", partOfSpeech: "noun", difficulty: "easy", example: "Mom drinks hot tea in the morning.", exampleTranslation: "أمي تشرب شاياً ساخناً في الصباح." },
  { word: "corn", translation: "ذرة", partOfSpeech: "noun", difficulty: "easy", example: "Yellow corn grows tall on the farm.", exampleTranslation: "الذرة الصفراء تنمو طويلة في المزرعة." },
  { word: "grape", translation: "عنب", partOfSpeech: "noun", difficulty: "easy", example: "I eat sweet purple grapes.", exampleTranslation: "آكل عنباً بنفسجياً حلواً." },
  // batch 14 — clothes
  { word: "dress", translation: "فستان", partOfSpeech: "noun", difficulty: "easy", example: "She wears a pretty red dress.", exampleTranslation: "ترتدي فستاناً أحمر جميلاً." },
  { word: "pants", translation: "بنطلون", partOfSpeech: "noun", difficulty: "easy", example: "He puts on blue pants every day.", exampleTranslation: "يرتدي بنطلوناً أزرق كل يوم." },
  { word: "hat", translation: "قبعة", partOfSpeech: "noun", difficulty: "easy", example: "Wear your hat in the hot sun.", exampleTranslation: "ارتدِ قبعتك في الشمس الحارة." },
  { word: "coat", translation: "معطف", partOfSpeech: "noun", difficulty: "easy", example: "Put on your coat—it is cold outside.", exampleTranslation: "ارتدِ معطفك—الجو بارد في الخارج." },
  { word: "socks", translation: "جوارب", partOfSpeech: "noun", difficulty: "easy", example: "My socks are warm and striped.", exampleTranslation: "جواربي دافئة ومخططة." },
  { word: "skirt", translation: "تنورة", partOfSpeech: "noun", difficulty: "easy", example: "The girl twirls in her pink skirt.", exampleTranslation: "البنت تدور في تنورتها الوردية." },
  { word: "jacket", translation: "سترة", partOfSpeech: "noun", difficulty: "easy", example: "He zips up his green jacket.", exampleTranslation: "يزرّر سترته الخضراء." },
  { word: "gloves", translation: "قفازات", partOfSpeech: "noun", difficulty: "easy", example: "Wear gloves when you play in snow.", exampleTranslation: "ارتدِ قفازات عندما تلعب في الثلج." },
  { word: "scarf", translation: "وشاح", partOfSpeech: "noun", difficulty: "easy", example: "She wraps a warm scarf around her neck.", exampleTranslation: "تلتف وشاحاً دافئاً حول رقبتها." },
  { word: "boots", translation: "حذاء طويل", partOfSpeech: "noun", difficulty: "easy", example: "Rain boots keep my feet dry.", exampleTranslation: "حذاء المطر يبقي قدمي جافتين." },
  // batch 15 — home rooms & furniture
  { word: "kitchen", translation: "مطبخ", partOfSpeech: "noun", difficulty: "easy", example: "Mom cooks soup in the kitchen.", exampleTranslation: "أمي تطبخ الشوربة في المطبخ." },
  { word: "bathroom", translation: "حمام", partOfSpeech: "noun", difficulty: "easy", example: "I brush my teeth in the bathroom.", exampleTranslation: "أفرش أسناني في الحمام." },
  { word: "sofa", translation: "أريكة", partOfSpeech: "noun", difficulty: "easy", example: "We sit on the soft sofa and watch TV.", exampleTranslation: "نجلس على الأريكة الناعمة ونشاهد التلفاز." },
  { word: "lamp", translation: "مصباح", partOfSpeech: "noun", difficulty: "easy", example: "Turn on the lamp when it gets dark.", exampleTranslation: "أشعل المصباح عندما يحل الظلام." },
  { word: "floor", translation: "أرضية", partOfSpeech: "noun", difficulty: "easy", example: "The cat sleeps on the warm floor.", exampleTranslation: "القطة تنام على الأرضية الدافئة." },
  { word: "wall", translation: "جدار", partOfSpeech: "noun", difficulty: "easy", example: "A picture hangs on the wall.", exampleTranslation: "صورة معلقة على الجدار." },
  { word: "garden", translation: "حديقة منزل", partOfSpeech: "noun", difficulty: "easy", example: "Flowers grow in our little garden.", exampleTranslation: "الزهور تنمو في حديقتنا الصغيرة." },
  { word: "fence", translation: "سياج", partOfSpeech: "noun", difficulty: "easy", example: "A white fence goes around the yard.", exampleTranslation: "سياج أبيض يحيط بالفناء." },
  { word: "stairs", translation: "سلالم", partOfSpeech: "noun", difficulty: "easy", example: "Be careful on the stairs.", exampleTranslation: "كن حذراً على السلالم." },
  { word: "clock", translation: "ساعة", partOfSpeech: "noun", difficulty: "easy", example: "The clock shows three o'clock.", exampleTranslation: "الساعة تُظهر الساعة الثالثة." },
  // batch 16 — adjectives & opposites
  { word: "hot", translation: "حار", partOfSpeech: "adjective", difficulty: "easy", example: "The soup is too hot to eat.", exampleTranslation: "الشوربة حارة جداً للأكل." },
  { word: "cold", translation: "بارد", partOfSpeech: "adjective", difficulty: "easy", example: "Ice water feels very cold.", exampleTranslation: "ماء الثلج بارد جداً." },
  { word: "old", translation: "قديم", partOfSpeech: "adjective", difficulty: "easy", example: "Grandpa has an old wooden chair.", exampleTranslation: "جدي لديه كرسي خشبي قديم." },
  { word: "new", translation: "جديد", partOfSpeech: "adjective", difficulty: "easy", example: "I got a new pencil for school.", exampleTranslation: "حصلت على قلم رصاص جديد للمدرسة." },
  { word: "fast", translation: "سريع", partOfSpeech: "adjective", difficulty: "easy", example: "The fast rabbit runs away from the fox.", exampleTranslation: "الأرنب السريع يركض بسرعة من الثعلب." },
  { word: "slow", translation: "بطيء", partOfSpeech: "adjective", difficulty: "easy", example: "The turtle is slow but steady.", exampleTranslation: "السلحفاة بطيئة لكنها ثابتة." },
  { word: "tall", translation: "طويل", partOfSpeech: "adjective", difficulty: "easy", example: "The tall tree touches the sky.", exampleTranslation: "الشجرة الطويلة تلامس السماء." },
  { word: "short", translation: "قصير", partOfSpeech: "adjective", difficulty: "easy", example: "My little brother is short.", exampleTranslation: "أخي الصغير قصير." },
  { word: "good", translation: "جيد", partOfSpeech: "adjective", difficulty: "easy", example: "You did a good job today.", exampleTranslation: "أحسنت عملاً جيداً اليوم." },
  { word: "sad", translation: "حزين", partOfSpeech: "adjective", difficulty: "easy", example: "The sad boy misses his friend.", exampleTranslation: "الولد الحزين يشتاق إلى صديقه." },
  // batch 17 — time & seasons
  { word: "morning", translation: "صباح", partOfSpeech: "noun", difficulty: "easy", example: "I eat breakfast in the morning.", exampleTranslation: "آكل الفطور في الصباح." },
  { word: "afternoon", translation: "بعد الظهر", partOfSpeech: "noun", difficulty: "easy", example: "We play outside in the afternoon.", exampleTranslation: "نلعب في الخارج بعد الظهر." },
  { word: "evening", translation: "مساء", partOfSpeech: "noun", difficulty: "easy", example: "Stars come out in the evening.", exampleTranslation: "النجوم تظهر في المساء." },
  { word: "night", translation: "ليل", partOfSpeech: "noun", difficulty: "easy", example: "The moon shines at night.", exampleTranslation: "القمر يلمع في الليل." },
  { word: "today", translation: "اليوم", partOfSpeech: "noun", difficulty: "easy", example: "Today is a sunny day.", exampleTranslation: "اليوم يوم مشمس." },
  { word: "spring", translation: "ربيع", partOfSpeech: "noun", difficulty: "easy", example: "Flowers bloom in spring.", exampleTranslation: "الزهور تتفتح في الربيع." },
  { word: "summer", translation: "صيف", partOfSpeech: "noun", difficulty: "easy", example: "We swim in summer.", exampleTranslation: "نسبح في الصيف." },
  { word: "winter", translation: "شتاء", partOfSpeech: "noun", difficulty: "easy", example: "It snows a lot in winter.", exampleTranslation: "الثلج يتساقط كثيراً في الشتاء." },
  { word: "fall", translation: "خريف", partOfSpeech: "noun", difficulty: "easy", example: "Leaves turn orange in fall.", exampleTranslation: "الأوراق تصبح برتقالية في الخريف." },
  { word: "Monday", translation: "الاثنين", partOfSpeech: "noun", difficulty: "easy", example: "School starts again on Monday.", exampleTranslation: "المدرسة تبدأ من جديد يوم الاثنين." },
  // batch 18 — more verbs
  { word: "swim", translation: "يسبح", partOfSpeech: "verb", difficulty: "easy", example: "Fish swim in the blue lake.", exampleTranslation: "الأسماك تسبح في البحيرة الزرقاء." },
  { word: "fly", translation: "يطير", partOfSpeech: "verb", difficulty: "easy", example: "Birds fly south in fall.", exampleTranslation: "الطيور تطير جنوباً في الخريف." },
  { word: "sing", translation: "يغني", partOfSpeech: "verb", difficulty: "easy", example: "The girl likes to sing songs.", exampleTranslation: "البنت تحب أن تغني الأغاني." },
  { word: "dance", translation: "يرقص", partOfSpeech: "verb", difficulty: "easy", example: "We dance at the school party.", exampleTranslation: "نرقص في حفلة المدرسة." },
  { word: "draw", translation: "يرسم", partOfSpeech: "verb", difficulty: "easy", example: "I draw a cat with my crayons.", exampleTranslation: "أرسم قطة بأقلامي الملونة." },
  { word: "cook", translation: "يطبخ", partOfSpeech: "verb", difficulty: "easy", example: "Dad likes to cook dinner.", exampleTranslation: "أبي يحب أن يطبخ العشاء." },
  { word: "wash", translation: "يغسل", partOfSpeech: "verb", difficulty: "easy", example: "Wash your hands before you eat.", exampleTranslation: "اغسل يديك قبل أن تأكل." },
  { word: "clean", translation: "ينظف", partOfSpeech: "verb", difficulty: "easy", example: "We clean our classroom every Friday.", exampleTranslation: "ننظف فصلنا كل يوم جمعة." },
  { word: "open", translation: "يفتح", partOfSpeech: "verb", difficulty: "easy", example: "Please open the window for fresh air.", exampleTranslation: "من فضلك افتح النافذة للهواء النقي." },
  { word: "close", translation: "يغلق", partOfSpeech: "verb", difficulty: "easy", example: "Close your book when class ends.", exampleTranslation: "أغلق كتابك عندما ينتهي الدرس." },
  // batch 19 — transport & places
  { word: "car", translation: "سيارة", partOfSpeech: "noun", difficulty: "easy", example: "Dad drives the car to work.", exampleTranslation: "أبي يقود السيارة إلى العمل." },
  { word: "bus", translation: "حافلة", partOfSpeech: "noun", difficulty: "easy", example: "Children ride the yellow school bus.", exampleTranslation: "الأطفال يركبون حافلة المدرسة الصفراء." },
  { word: "bike", translation: "دراجة", partOfSpeech: "noun", difficulty: "easy", example: "I ride my bike to the park.", exampleTranslation: "أركب دراجتي إلى الحديقة." },
  { word: "boat", translation: "قارب", partOfSpeech: "noun", difficulty: "easy", example: "A small boat floats on the lake.", exampleTranslation: "قارب صغير يطفو على البحيرة." },
  { word: "train", translation: "قطار", partOfSpeech: "noun", difficulty: "easy", example: "The train goes choo-choo on the tracks.", exampleTranslation: "القطار يذهب على القضبان." },
  { word: "street", translation: "شارع", partOfSpeech: "noun", difficulty: "easy", example: "Look both ways before you cross the street.", exampleTranslation: "انظر إلى الجانبين قبل أن تعبر الشارع." },
  { word: "shop", translation: "محل", partOfSpeech: "noun", difficulty: "easy", example: "Mom buys milk at the shop.", exampleTranslation: "أمي تشتري الحليب من المحل." },
  { word: "library", translation: "مكتبة", partOfSpeech: "noun", difficulty: "easy", example: "We borrow books from the library.", exampleTranslation: "نستعير الكتب من المكتبة." },
  { word: "beach", translation: "شاطئ", partOfSpeech: "noun", difficulty: "easy", example: "We build sand castles at the beach.", exampleTranslation: "نبني قلاع رمل على الشاطئ." },
  { word: "farm", translation: "مزرعة", partOfSpeech: "noun", difficulty: "easy", example: "Cows and chickens live on the farm.", exampleTranslation: "الأبقار والدجاج تعيش في المزرعة." },
  // batch 20 — everyday objects
  { word: "ball", translation: "كرة", partOfSpeech: "noun", difficulty: "easy", example: "Throw the ball to your friend.", exampleTranslation: "ارمِ الكرة إلى صديقك." },
  { word: "toy", translation: "لعبة", partOfSpeech: "noun", difficulty: "easy", example: "My favorite toy is a teddy bear.", exampleTranslation: "لعبتي المفضلة دب محشو." },
  { word: "game", translation: "لعبة", partOfSpeech: "noun", difficulty: "easy", example: "Let's play a fun board game.", exampleTranslation: "هيا نلعب لعبة لوحية ممتعة." },
  { word: "box", translation: "صندوق", partOfSpeech: "noun", difficulty: "easy", example: "Toys are in the big red box.", exampleTranslation: "الألعاب في الصندوق الأحمر الكبير." },
  { word: "cup", translation: "كوب", partOfSpeech: "noun", difficulty: "easy", example: "Fill your cup with cold water.", exampleTranslation: "املأ كوبك بماء بارد." },
  { word: "spoon", translation: "ملعقة", partOfSpeech: "noun", difficulty: "easy", example: "Use a spoon to eat your soup.", exampleTranslation: "استخدم ملعقة لتأكل شوربتك." },
  { word: "fork", translation: "شوكة", partOfSpeech: "noun", difficulty: "easy", example: "Pick up the pasta with a fork.", exampleTranslation: "التقط المعكرونة بالشوكة." },
  { word: "plate", translation: "طبق", partOfSpeech: "noun", difficulty: "easy", example: "Put your food on a clean plate.", exampleTranslation: "ضع طعامك على طبق نظيف." },
  { word: "star", translation: "نجمة", partOfSpeech: "noun", difficulty: "easy", example: "I see a bright star tonight.", exampleTranslation: "أرى نجمة لامعة الليلة." },
  { word: "moon", translation: "قمر", partOfSpeech: "noun", difficulty: "easy", example: "The round moon lights up the night.", exampleTranslation: "القمر المدور ينير الليل." },
  // batch 21 — days & time
  { word: "Tuesday", translation: "الثلاثاء", partOfSpeech: "noun", difficulty: "easy", example: "We have art class on Tuesday.", exampleTranslation: "لدينا حصة رسم يوم الثلاثاء." },
  { word: "Wednesday", translation: "الأربعاء", partOfSpeech: "noun", difficulty: "easy", example: "Wednesday is the middle of the week.", exampleTranslation: "الأربعاء في منتصف الأسبوع." },
  { word: "Thursday", translation: "الخميس", partOfSpeech: "noun", difficulty: "easy", example: "We go to the library on Thursday.", exampleTranslation: "نذهب إلى المكتبة يوم الخميس." },
  { word: "Friday", translation: "الجمعة", partOfSpeech: "noun", difficulty: "easy", example: "Friday is the last school day.", exampleTranslation: "الجمعة آخر يوم دراسي." },
  { word: "Saturday", translation: "السبت", partOfSpeech: "noun", difficulty: "easy", example: "We play soccer on Saturday.", exampleTranslation: "نلعب كرة القدم يوم السبت." },
  { word: "Sunday", translation: "الأحد", partOfSpeech: "noun", difficulty: "easy", example: "Grandma visits us on Sunday.", exampleTranslation: "جدتي تزورنا يوم الأحد." },
  { word: "hour", translation: "ساعة", partOfSpeech: "noun", difficulty: "easy", example: "The movie lasts one hour.", exampleTranslation: "الفيلم يستمر ساعة واحدة." },
  { word: "minute", translation: "دقيقة", partOfSpeech: "noun", difficulty: "easy", example: "Wait one minute, please.", exampleTranslation: "انتظر دقيقة واحدة من فضلك." },
  { word: "week", translation: "أسبوع", partOfSpeech: "noun", difficulty: "easy", example: "There are seven days in a week.", exampleTranslation: "هناك سبعة أيام في الأسبوع." },
  { word: "month", translation: "شهر", partOfSpeech: "noun", difficulty: "easy", example: "My birthday is next month.", exampleTranslation: "عيد ميلادي في الشهر القادم." },
  // batch 22 — feelings & more adjectives
  { word: "angry", translation: "غاضب", partOfSpeech: "adjective", difficulty: "easy", example: "The boy is angry about the broken toy.", exampleTranslation: "الولد غاضب بسبب اللعبة المكسورة." },
  { word: "tired", translation: "متعب", partOfSpeech: "adjective", difficulty: "easy", example: "I feel tired after a long day.", exampleTranslation: "أشعر بالتعب بعد يوم طويل." },
  { word: "hungry", translation: "جائع", partOfSpeech: "adjective", difficulty: "easy", example: "I am hungry—let's eat lunch.", exampleTranslation: "أنا جائع—هيا نأكل الغداء." },
  { word: "thirsty", translation: "عطشان", partOfSpeech: "adjective", difficulty: "easy", example: "The runner is thirsty after the race.", exampleTranslation: "العدّاء عطشان بعد السباق." },
  { word: "pretty", translation: "جميل", partOfSpeech: "adjective", difficulty: "easy", example: "What a pretty butterfly in the garden!", exampleTranslation: "يا لها من فراشة جميلة في الحديقة!" },
  { word: "funny", translation: "مضحك", partOfSpeech: "adjective", difficulty: "easy", example: "Grandpa tells a funny joke.", exampleTranslation: "جدي يروي نكتة مضحكة." },
  { word: "kind", translation: "لطيف", partOfSpeech: "adjective", difficulty: "easy", example: "The kind teacher helps every student.", exampleTranslation: "المعلم اللطيف يساعد كل طالب." },
  { word: "brave", translation: "شجاع", partOfSpeech: "adjective", difficulty: "easy", example: "The brave firefighter saves the cat.", exampleTranslation: "رجل الإطفاء الشجاع ينقذ القطة." },
  { word: "quiet", translation: "هادئ", partOfSpeech: "adjective", difficulty: "easy", example: "Please be quiet in the library.", exampleTranslation: "من فضلك كن هادئاً في المكتبة." },
  { word: "wet", translation: "مبلل", partOfSpeech: "adjective", difficulty: "easy", example: "My shoes are wet from the rain.", exampleTranslation: "حذائي مبلل من المطر." },
  // batch 23 — more animals
  { word: "fox", translation: "ثعلب", partOfSpeech: "noun", difficulty: "easy", example: "The red fox runs through the forest.", exampleTranslation: "الثعلب الأحمر يركض في الغابة." },
  { word: "deer", translation: "غزال", partOfSpeech: "noun", difficulty: "easy", example: "A gentle deer drinks from the river.", exampleTranslation: "غزال لطيف يشرب من النهر." },
  { word: "zebra", translation: "حمار وحشي", partOfSpeech: "noun", difficulty: "easy", example: "The zebra has black and white stripes.", exampleTranslation: "الحمار الوحشي له خطوط سوداء وبيضاء." },
  { word: "giraffe", translation: "زرافة", partOfSpeech: "noun", difficulty: "easy", example: "The tall giraffe eats leaves from the tree.", exampleTranslation: "الزرافة الطويلة تأكل أوراق الشجرة." },
  { word: "panda", translation: "باندا", partOfSpeech: "noun", difficulty: "easy", example: "The panda eats bamboo all day.", exampleTranslation: "الباندا يأكل الخيزران طوال اليوم." },
  { word: "whale", translation: "حوت", partOfSpeech: "noun", difficulty: "easy", example: "A big whale swims in the deep ocean.", exampleTranslation: "حوت كبير يسبح في المحيط العميق." },
  { word: "dolphin", translation: "دلفين", partOfSpeech: "noun", difficulty: "easy", example: "The dolphin jumps out of the water.", exampleTranslation: "الدلفين يقفز خارج الماء." },
  { word: "crab", translation: "سلطعون", partOfSpeech: "noun", difficulty: "easy", example: "A small crab walks on the sandy beach.", exampleTranslation: "سلطعون صغير يمشي على الشاطئ الرملي." },
  { word: "snail", translation: "حلزون", partOfSpeech: "noun", difficulty: "easy", example: "The snail moves slowly on the leaf.", exampleTranslation: "الحلزون يتحرك ببطء على الورقة." },
  { word: "worm", translation: "دودة", partOfSpeech: "noun", difficulty: "easy", example: "A worm lives in the wet garden soil.", exampleTranslation: "دودة تعيش في تربة الحديقة الرطبة." },
  // batch 24 — more food
  { word: "lemon", translation: "ليمون", partOfSpeech: "noun", difficulty: "easy", example: "The lemon tastes sour but fresh.", exampleTranslation: "الليمون طعمه حامض لكنه منعش." },
  { word: "pear", translation: "كمثرى", partOfSpeech: "noun", difficulty: "easy", example: "I eat a sweet green pear.", exampleTranslation: "آكل كمثرى خضراء حلوة." },
  { word: "peach", translation: "خوخ", partOfSpeech: "noun", difficulty: "easy", example: "The peach is soft and juicy.", exampleTranslation: "الخوخ ناعم وعصيري." },
  { word: "melon", translation: "بطيخ", partOfSpeech: "noun", difficulty: "easy", example: "We share a cold melon in summer.", exampleTranslation: "نتشارك بطيخاً بارداً في الصيف." },
  { word: "onion", translation: "بصل", partOfSpeech: "noun", difficulty: "easy", example: "Mom chops an onion for the soup.", exampleTranslation: "أمي تقطع بصلة للشوربة." },
  { word: "pepper", translation: "فلفل", partOfSpeech: "noun", difficulty: "easy", example: "A red pepper grows in the garden.", exampleTranslation: "فلفل أحمر ينمو في الحديقة." },
  { word: "salad", translation: "سلطة", partOfSpeech: "noun", difficulty: "easy", example: "We eat fresh salad with dinner.", exampleTranslation: "نأكل سلطة طازجة مع العشاء." },
  { word: "honey", translation: "عسل", partOfSpeech: "noun", difficulty: "easy", example: "The bear loves sweet honey.", exampleTranslation: "الدب يحب العسل الحلو." },
  { word: "butter", translation: "زبدة", partOfSpeech: "noun", difficulty: "easy", example: "Spread butter on warm bread.", exampleTranslation: "ادهن الزبدة على الخبز الدافئ." },
  { word: "noodle", translation: "معكرونة", partOfSpeech: "noun", difficulty: "easy", example: "I eat hot noodles with a fork.", exampleTranslation: "آكل معكرونة ساخنة بالشوكة." },
  // batch 25 — school supplies
  { word: "paper", translation: "ورقة", partOfSpeech: "noun", difficulty: "easy", example: "Draw a flower on white paper.", exampleTranslation: "ارسم زهرة على ورقة بيضاء." },
  { word: "crayon", translation: "قلم تلوين", partOfSpeech: "noun", difficulty: "easy", example: "Color the sky blue with a crayon.", exampleTranslation: "لون السماء بالأزرق بقلم التلوين." },
  { word: "eraser", translation: "ممحاة", partOfSpeech: "noun", difficulty: "easy", example: "Use an eraser to fix your mistake.", exampleTranslation: "استخدم الممحاة لتصحيح خطئك." },
  { word: "ruler", translation: "مسطرة", partOfSpeech: "noun", difficulty: "easy", example: "Measure the line with a ruler.", exampleTranslation: "قِس الخط بالمسطرة." },
  { word: "glue", translation: "غراء", partOfSpeech: "noun", difficulty: "easy", example: "Put glue on the paper and stick it.", exampleTranslation: "ضع الغراء على الورقة والصقها." },
  { word: "scissors", translation: "مقص", partOfSpeech: "noun", difficulty: "easy", example: "Cut the paper carefully with scissors.", exampleTranslation: "اقطع الورقة بحذر بالمقص." },
  { word: "homework", translation: "واجب", partOfSpeech: "noun", difficulty: "easy", example: "I do my homework after school.", exampleTranslation: "أنجز واجبي بعد المدرسة." },
  { word: "lesson", translation: "درس", partOfSpeech: "noun", difficulty: "easy", example: "Today's lesson is about animals.", exampleTranslation: "درس اليوم عن الحيوانات." },
  { word: "answer", translation: "إجابة", partOfSpeech: "noun", difficulty: "easy", example: "She knows the right answer.", exampleTranslation: "هي تعرف الإجابة الصحيحة." },
  { word: "question", translation: "سؤال", partOfSpeech: "noun", difficulty: "easy", example: "Raise your hand if you have a question.", exampleTranslation: "ارفع يدك إذا لديك سؤال." },
  // batch 26 — more verbs
  { word: "listen", translation: "يستمع", partOfSpeech: "verb", difficulty: "easy", example: "Listen to the teacher carefully.", exampleTranslation: "استمع إلى المعلم بانتباه." },
  { word: "speak", translation: "يتكلم", partOfSpeech: "verb", difficulty: "easy", example: "Please speak slowly and clearly.", exampleTranslation: "من فضلك تكلم ببطء ووضوح." },
  { word: "talk", translation: "يتحدث", partOfSpeech: "verb", difficulty: "easy", example: "Friends talk on the way home.", exampleTranslation: "الأصدقاء يتحدثون في طريق العودة." },
  { word: "help", translation: "يساعد", partOfSpeech: "verb", difficulty: "easy", example: "Can you help me carry this box?", exampleTranslation: "هل يمكنك مساعدتي في حمل هذا الصندوق؟" },
  { word: "share", translation: "يشارك", partOfSpeech: "verb", difficulty: "easy", example: "Good friends share their toys.", exampleTranslation: "الأصدقاء الطيبون يشاركون ألعابهم." },
  { word: "wait", translation: "ينتظر", partOfSpeech: "verb", difficulty: "easy", example: "Wait in line for your turn.", exampleTranslation: "انتظر في الطابور لدورك." },
  { word: "stop", translation: "يتوقف", partOfSpeech: "verb", difficulty: "easy", example: "Stop at the red light.", exampleTranslation: "توقف عند الإشارة الحمراء." },
  { word: "start", translation: "يبدأ", partOfSpeech: "verb", difficulty: "easy", example: "Class starts at eight o'clock.", exampleTranslation: "الدرس يبدأ في الساعة الثامنة." },
  { word: "look", translation: "ينظر", partOfSpeech: "verb", difficulty: "easy", example: "Look at the beautiful rainbow.", exampleTranslation: "انظر إلى قوس قزح الجميل." },
  { word: "see", translation: "يرى", partOfSpeech: "verb", difficulty: "easy", example: "I see a bird in the tree.", exampleTranslation: "أرى طائراً في الشجرة." },
  // batch 27 — nature & outdoors
  { word: "river", translation: "نهر", partOfSpeech: "noun", difficulty: "easy", example: "Fish swim in the clear river.", exampleTranslation: "الأسماك تسبح في النهر الصافي." },
  { word: "lake", translation: "بحيرة", partOfSpeech: "noun", difficulty: "easy", example: "We picnic by the quiet lake.", exampleTranslation: "نتنزه بجانب البحيرة الهادئة." },
  { word: "hill", translation: "تل", partOfSpeech: "noun", difficulty: "easy", example: "We roll down the green hill.", exampleTranslation: "نتدحرج على التل الأخضر." },
  { word: "rock", translation: "صخرة", partOfSpeech: "noun", difficulty: "easy", example: "The boy skips a flat rock on water.", exampleTranslation: "الولد يرمي صخرة مسطحة على الماء." },
  { word: "sand", translation: "رمل", partOfSpeech: "noun", difficulty: "easy", example: "Warm sand feels nice on the beach.", exampleTranslation: "الرمل الدافئ جميل على الشاطئ." },
  { word: "leaf", translation: "ورقة شجر", partOfSpeech: "noun", difficulty: "easy", example: "A yellow leaf falls from the tree.", exampleTranslation: "ورقة صفراء تسقط من الشجرة." },
  { word: "grass", translation: "عشب", partOfSpeech: "noun", difficulty: "easy", example: "Green grass covers the whole field.", exampleTranslation: "العشب الأخضر يغطي الحقل كله." },
  { word: "seed", translation: "بذرة", partOfSpeech: "noun", difficulty: "easy", example: "Plant a seed and water it every day.", exampleTranslation: "ازرع بذرة واسقها كل يوم." },
  { word: "fire", translation: "نار", partOfSpeech: "noun", difficulty: "easy", example: "We sit by a small campfire at night.", exampleTranslation: "نجلس بجانب نار صغيرة في الليل." },
  { word: "ice", translation: "جليد", partOfSpeech: "noun", difficulty: "easy", example: "Ice cubes keep the drink cold.", exampleTranslation: "مكعبات الجليد تبقي الشراب بارداً." },
  // batch 28 — home & daily items
  { word: "phone", translation: "هاتف", partOfSpeech: "noun", difficulty: "easy", example: "Dad talks on the phone after work.", exampleTranslation: "أبي يتحدث في الهاتف بعد العمل." },
  { word: "key", translation: "مفتاح", partOfSpeech: "noun", difficulty: "easy", example: "Use the key to open the door.", exampleTranslation: "استخدم المفتاح لفتح الباب." },
  { word: "bell", translation: "جرس", partOfSpeech: "noun", difficulty: "easy", example: "The school bell rings at three.", exampleTranslation: "جرس المدرسة يرن في الثالثة." },
  { word: "towel", translation: "منشفة", partOfSpeech: "noun", difficulty: "easy", example: "Dry your hands with a clean towel.", exampleTranslation: "جفف يديك بمنشفة نظيفة." },
  { word: "soap", translation: "صابون", partOfSpeech: "noun", difficulty: "easy", example: "Wash with soap and warm water.", exampleTranslation: "اغسل بالصابون والماء الدافئ." },
  { word: "brush", translation: "فرشاة", partOfSpeech: "noun", difficulty: "easy", example: "Brush your teeth every morning.", exampleTranslation: "فرش أسنانك كل صباح." },
  { word: "comb", translation: "مشط", partOfSpeech: "noun", difficulty: "easy", example: "She combs her long hair gently.", exampleTranslation: "تمشط شعرها الطويل بلطف." },
  { word: "mirror", translation: "مرآة", partOfSpeech: "noun", difficulty: "easy", example: "Look at yourself in the mirror.", exampleTranslation: "انظر إلى نفسك في المرآة." },
  { word: "trash", translation: "قمامة", partOfSpeech: "noun", difficulty: "easy", example: "Put the trash in the bin, please.", exampleTranslation: "ضع القمامة في السلة من فضلك." },
  { word: "gift", translation: "هدية", partOfSpeech: "noun", difficulty: "easy", example: "I got a birthday gift from my friend.", exampleTranslation: "حصلت على هدية عيد ميلاد من صديقي." },
  // batch 29 — jobs & community
  { word: "doctor", translation: "طبيب", partOfSpeech: "noun", difficulty: "easy", example: "The doctor helps sick people feel better.", exampleTranslation: "الطبيب يساعد المرضى على الشفاء." },
  { word: "nurse", translation: "ممرضة", partOfSpeech: "noun", difficulty: "easy", example: "The kind nurse gives me medicine.", exampleTranslation: "الممرضة اللطيفة تعطيني الدواء." },
  { word: "farmer", translation: "مزارع", partOfSpeech: "noun", difficulty: "easy", example: "The farmer grows corn on the farm.", exampleTranslation: "المزارع يزرع الذرة في المزرعة." },
  { word: "baker", translation: "خباز", partOfSpeech: "noun", difficulty: "easy", example: "The baker makes fresh bread every day.", exampleTranslation: "الخباز يصنع خبزاً طازجاً كل يوم." },
  { word: "driver", translation: "سائق", partOfSpeech: "noun", difficulty: "easy", example: "The bus driver stops at our street.", exampleTranslation: "سائق الحافلة يتوقف في شارعنا." },
  { word: "child", translation: "طفل", partOfSpeech: "noun", difficulty: "easy", example: "Every child loves to play outside.", exampleTranslation: "كل طفل يحب اللعب في الخارج." },
  { word: "people", translation: "ناس", partOfSpeech: "noun", difficulty: "easy", example: "Many people walk in the park.", exampleTranslation: "كثير من الناس يمشون في الحديقة." },
  { word: "team", translation: "فريق", partOfSpeech: "noun", difficulty: "easy", example: "Our team won the soccer game.", exampleTranslation: "فريقنا فاز في مباراة كرة القدم." },
  { word: "name", translation: "اسم", partOfSpeech: "noun", difficulty: "easy", example: "Write your name at the top.", exampleTranslation: "اكتب اسمك في الأعلى." },
  { word: "age", translation: "عمر", partOfSpeech: "noun", difficulty: "easy", example: "I am six years of age.", exampleTranslation: "عمري ست سنوات." },
  // batch 30 — polite words & basics
  { word: "yes", translation: "نعم", partOfSpeech: "interjection", difficulty: "easy", example: "Yes, I would like some water.", exampleTranslation: "نعم، أريد بعض الماء." },
  { word: "no", translation: "لا", partOfSpeech: "interjection", difficulty: "easy", example: "No, thank you—I am not hungry.", exampleTranslation: "لا شكراً—لست جائعاً." },
  { word: "please", translation: "من فضلك", partOfSpeech: "interjection", difficulty: "easy", example: "May I have some juice, please?", exampleTranslation: "هل لي ببعض العصير من فضلك؟" },
  { word: "sorry", translation: "آسف", partOfSpeech: "interjection", difficulty: "easy", example: "I am sorry—I broke your crayon.", exampleTranslation: "أنا آسف—كسرت قلم التلوين." },
  { word: "hello", translation: "مرحباً", partOfSpeech: "interjection", difficulty: "easy", example: "Hello! Nice to meet you.", exampleTranslation: "مرحباً! سعيد بلقائك." },
  { word: "goodbye", translation: "وداعاً", partOfSpeech: "interjection", difficulty: "easy", example: "Goodbye! See you at school.", exampleTranslation: "وداعاً! أراك في المدرسة." },
  { word: "love", translation: "يحب", partOfSpeech: "verb", difficulty: "easy", example: "I love my family very much.", exampleTranslation: "أحب عائلتي كثيراً." },
  { word: "like", translation: "يحب / يعجب", partOfSpeech: "verb", difficulty: "easy", example: "I like to read story books.", exampleTranslation: "أحب قراءة كتب القصص." },
  { word: "want", translation: "يريد", partOfSpeech: "verb", difficulty: "easy", example: "I want a glass of cold milk.", exampleTranslation: "أريد كوباً من الحليب البارد." },
  { word: "nice", translation: "لطيف", partOfSpeech: "adjective", difficulty: "easy", example: "What a nice day for a picnic!", exampleTranslation: "يا له من يوم لطيف للنزهة!" },
];

/** One card per English word (first occurrence wins). */
export const GRADE1_CARDS = (() => {
  const seen = new Set();
  const out = [];
  for (const card of GRADE1_CARDS_RAW) {
    const key = card.word.toLowerCase().trim();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(card);
  }
  if (out.length !== GRADE1_CARDS_RAW.length) {
    const dupCount = GRADE1_CARDS_RAW.length - out.length;
    console.warn(`grade1-cards: dropped ${dupCount} duplicate word(s).`);
  }
  return out;
})();

export function batchWords(batchNum) {
  const start = (batchNum - 1) * 10;
  return GRADE1_CARDS.slice(start, start + 10).map((c) => c.word);
}
