/** Grade 5 chunk C — literature, writing (simple daily vocabulary) (250 cards). */
export const GRADE5_CHUNK_C = [
  { word: "holdup", translation: "أصمد", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word holdup in class today.", exampleTranslation: "تعلّمنا كلمة أصمد في الحصة اليوم." },
  { word: "holster", translation: "الحافظة", partOfSpeech: "verb", difficulty: "medium", example: "Can you use holster in a sentence?", exampleTranslation: "هل يمكنك استخدام الحافظة في جملة؟" },
  { word: "homemaker", translation: "ربة منزل", partOfSpeech: "verb", difficulty: "hard", example: "The story mentioned homemaker on page ten.", exampleTranslation: "ذكرت القصة ربة منزل في الصفحة العاشرة." },
  { word: "honeybee", translation: "نحلة العسل", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote honeybee on the board.", exampleTranslation: "كتب معلمنا نحلة العسل على السبورة." },
  { word: "honeymoon", translation: "شهر العسل", partOfSpeech: "noun", difficulty: "hard", example: "I spelled honeymoon correctly on the quiz.", exampleTranslation: "تهجّيت شهر العسل بشكل صحيح في الاختبار." },
  { word: "honeycomb", translation: "قرص العسل", partOfSpeech: "noun", difficulty: "hard", example: "The picture helps explain honeycomb.", exampleTranslation: "تساعد الصورة على شرح قرص العسل." },
  { word: "hookworm", translation: "الدودة الشصية", partOfSpeech: "noun", difficulty: "medium", example: "We found hookworm in our reading book.", exampleTranslation: "وجدنا الدودة الشصية في كتاب القراءة." },
  { word: "hornet", translation: "زنبور", partOfSpeech: "noun", difficulty: "medium", example: "Hornet is a new word for our unit.", exampleTranslation: "زنبور كلمة جديدة لوحدتنا." },
  { word: "horoscope", translation: "ابراج", partOfSpeech: "noun", difficulty: "hard", example: "My partner and I discussed horoscope.", exampleTranslation: "ناقشت ابراج مع زميلي." },
  { word: "horsefly", translation: "ذبابة الخيل", partOfSpeech: "adverb", difficulty: "medium", example: "The worksheet asks about horsefly.", exampleTranslation: "يسأل ورق العمل عن ذبابة الخيل." },
  { word: "horseman", translation: "فارس", partOfSpeech: "noun", difficulty: "medium", example: "We heard horseman in the science video.", exampleTranslation: "سمعنا فارس في فيلم العلوم." },
  { word: "horseshoe", translation: "حدوة حصان", partOfSpeech: "noun", difficulty: "hard", example: "Please copy horseshoe into your notebook.", exampleTranslation: "من فضلك انسخ حدوة حصان في دفترك." },
  { word: "horseradish", translation: "الفجل", partOfSpeech: "adjective", difficulty: "hard", example: "The chart shows an example of horseradish.", exampleTranslation: "يُظهر المخطط مثالاً عن الفجل." },
  { word: "hotline", translation: "الخط الساخن", partOfSpeech: "noun", difficulty: "medium", example: "Our group used hotline in the project.", exampleTranslation: "استخدمت مجموعتنا الخط الساخن في المشروع." },
  { word: "hotplate", translation: "موقد", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with hotplate.", exampleTranslation: "أعطى المعلم مثالاً بـموقد." },
  { word: "houseboat", translation: "المركب", partOfSpeech: "noun", difficulty: "hard", example: "I underlined houseboat in the paragraph.", exampleTranslation: "وضعت خطاً تحت المركب في الفقرة." },
  { word: "housecat", translation: "قطة منزلية", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying housecat aloud.", exampleTranslation: "تدرّبنا على نطق قطة منزلية بصوت عالٍ." },
  { word: "housecoat", translation: "معطف المنزل", partOfSpeech: "noun", difficulty: "hard", example: "The poster explains housecoat with a drawing.", exampleTranslation: "يشرح الملصق معطف المنزل برسم." },
  { word: "housefly", translation: "ذبابة منزلية", partOfSpeech: "adverb", difficulty: "medium", example: "Everyone shared a sentence with housefly.", exampleTranslation: "شارك الجميع جملة فيها ذبابة منزلية." },
  { word: "housekeeper", translation: "مدبرة منزل", partOfSpeech: "verb", difficulty: "hard", example: "The quiz included the word housekeeper.", exampleTranslation: "تضمّن الاختبار كلمة مدبرة منزل." },
  { word: "housetop", translation: "سطح المنزل", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word housetop in class today.", exampleTranslation: "تعلّمنا كلمة سطح المنزل في الحصة اليوم." },
  { word: "hovercraft", translation: "الحوامات", partOfSpeech: "noun", difficulty: "hard", example: "Can you use hovercraft in a sentence?", exampleTranslation: "هل يمكنك استخدام الحوامات في جملة؟" },
  { word: "hubcap", translation: "إطار العجلة", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned hubcap on page ten.", exampleTranslation: "ذكرت القصة إطار العجلة في الصفحة العاشرة." },
  { word: "huckleberry", translation: "التوت", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote huckleberry on the board.", exampleTranslation: "كتب معلمنا التوت على السبورة." },
  { word: "hula", translation: "حولا", partOfSpeech: "noun", difficulty: "easy", example: "I spelled hula correctly on the quiz.", exampleTranslation: "تهجّيت حولا بشكل صحيح في الاختبار." },
  { word: "hoop", translation: "طارة", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain hoop.", exampleTranslation: "تساعد الصورة على شرح طارة." },
  { word: "humanoid", translation: "android", partOfSpeech: "noun", difficulty: "medium", example: "We found humanoid in our reading book.", exampleTranslation: "وجدنا android في كتاب القراءة." },
  { word: "hunchback", translation: "أحدب", partOfSpeech: "noun", difficulty: "hard", example: "Hunchback is a new word for our unit.", exampleTranslation: "أحدب كلمة جديدة لوحدتنا." },
  { word: "husky", translation: "أجش", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed husky.", exampleTranslation: "ناقشت أجش مع زميلي." },
  { word: "icebox", translation: "ثلاجة", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about icebox.", exampleTranslation: "يسأل ورق العمل عن ثلاجة." },
  { word: "icebreaker", translation: "كاسحة الجليد", partOfSpeech: "verb", difficulty: "hard", example: "We heard icebreaker in the science video.", exampleTranslation: "سمعنا كاسحة الجليد في فيلم العلوم." },
  { word: "icecap", translation: "com.icecap", partOfSpeech: "noun", difficulty: "medium", example: "Please copy icecap into your notebook.", exampleTranslation: "من فضلك انسخ com.icecap في دفترك." },
  { word: "icecream", translation: "بوظة", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of icecream.", exampleTranslation: "يُظهر المخطط مثالاً عن بوظة." },
  { word: "icemaker", translation: "صانع الجليد", partOfSpeech: "verb", difficulty: "medium", example: "Our group used icemaker in the project.", exampleTranslation: "استخدمت مجموعتنا صانع الجليد في المشروع." },
  { word: "iconoclast", translation: "تحطيم الأيقونات", partOfSpeech: "noun", difficulty: "hard", example: "The teacher gave an example with iconoclast.", exampleTranslation: "أعطى المعلم مثالاً بـتحطيم الأيقونات." },
  { word: "imagemaker", translation: "صانع الصور", partOfSpeech: "verb", difficulty: "hard", example: "I underlined imagemaker in the paragraph.", exampleTranslation: "وضعت خطاً تحت صانع الصور في الفقرة." },
  { word: "impala", translation: "إمبالا", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying impala aloud.", exampleTranslation: "تدرّبنا على نطق إمبالا بصوت عالٍ." },
  { word: "inchworm", translation: "دودة بوصة", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains inchworm with a drawing.", exampleTranslation: "يشرح الملصق دودة بوصة برسم." },
  { word: "infirmary", translation: "المستوصف", partOfSpeech: "noun", difficulty: "hard", example: "Everyone shared a sentence with infirmary.", exampleTranslation: "شارك الجميع جملة فيها المستوصف." },
  { word: "inkblot", translation: "بقعة الحبر", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word inkblot.", exampleTranslation: "تضمّن الاختبار كلمة بقعة الحبر." },
  { word: "inkjet", translation: "النافثة للحبر", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word inkjet in class today.", exampleTranslation: "تعلّمنا كلمة النافثة للحبر في الحصة اليوم." },
  { word: "inkwell", translation: "محبرة", partOfSpeech: "noun", difficulty: "medium", example: "Can you use inkwell in a sentence?", exampleTranslation: "هل يمكنك استخدام محبرة في جملة؟" },
  { word: "innkeeper", translation: "صاحب الحانة", partOfSpeech: "verb", difficulty: "hard", example: "The story mentioned innkeeper on page ten.", exampleTranslation: "ذكرت القصة صاحب الحانة في الصفحة العاشرة." },
  { word: "insecticide", translation: "مبيد حشري", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote insecticide on the board.", exampleTranslation: "كتب معلمنا مبيد حشري على السبورة." },
  { word: "insideout", translation: "من الداخل إلى الخارج", partOfSpeech: "noun", difficulty: "hard", example: "I spelled insideout correctly on the quiz.", exampleTranslation: "تهجّيت من الداخل إلى الخارج بشكل صحيح في الاختبار." },
  { word: "inspector", translation: "مفتش", partOfSpeech: "noun", difficulty: "hard", example: "The picture helps explain inspector.", exampleTranslation: "تساعد الصورة على شرح مفتش." },
  { word: "instep", translation: "مشط القدم", partOfSpeech: "noun", difficulty: "medium", example: "We found instep in our reading book.", exampleTranslation: "وجدنا مشط القدم في كتاب القراءة." },
  { word: "intercom", translation: "الاتصال الداخلي", partOfSpeech: "noun", difficulty: "medium", example: "Intercom is a new word for our unit.", exampleTranslation: "الاتصال الداخلي كلمة جديدة لوحدتنا." },
  { word: "internist", translation: "طبيب باطني", partOfSpeech: "noun", difficulty: "hard", example: "My partner and I discussed internist.", exampleTranslation: "ناقشت طبيب باطني مع زميلي." },
  { word: "introvert", translation: "منطوي", partOfSpeech: "noun", difficulty: "hard", example: "The worksheet asks about introvert.", exampleTranslation: "يسأل ورق العمل عن منطوي." },
  { word: "ironclad", translation: "مدرع", partOfSpeech: "noun", difficulty: "medium", example: "We heard ironclad in the science video.", exampleTranslation: "سمعنا مدرع في فيلم العلوم." },
  { word: "ironwork", translation: "أعمال حديدية", partOfSpeech: "noun", difficulty: "medium", example: "Please copy ironwork into your notebook.", exampleTranslation: "من فضلك انسخ أعمال حديدية في دفترك." },
  { word: "irrigate", translation: "ري", partOfSpeech: "verb", difficulty: "medium", example: "The chart shows an example of irrigate.", exampleTranslation: "يُظهر المخطط مثالاً عن ري." },
  { word: "islander", translation: "سكان الجزيرة", partOfSpeech: "verb", difficulty: "medium", example: "Our group used islander in the project.", exampleTranslation: "استخدمت مجموعتنا سكان الجزيرة في المشروع." },
  { word: "jawbone", translation: "عظم الفك", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with jawbone.", exampleTranslation: "أعطى المعلم مثالاً بـعظم الفك." },
  { word: "jawbreaker", translation: "com.jawbreaker", partOfSpeech: "verb", difficulty: "hard", example: "I underlined jawbreaker in the paragraph.", exampleTranslation: "وضعت خطاً تحت com.jawbreaker في الفقرة." },
  { word: "jazzband", translation: "موسيقى الجاز", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying jazzband aloud.", exampleTranslation: "تدرّبنا على نطق موسيقى الجاز بصوت عالٍ." },
  { word: "jellybean", translation: "هلام الفول", partOfSpeech: "noun", difficulty: "hard", example: "The poster explains jellybean with a drawing.", exampleTranslation: "يشرح الملصق هلام الفول برسم." },
  { word: "jigsaw", translation: "بانوراما", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with jigsaw.", exampleTranslation: "شارك الجميع جملة فيها بانوراما." },
  { word: "jingle", translation: "جلجل", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word jingle.", exampleTranslation: "تضمّن الاختبار كلمة جلجل." },
  { word: "jobholder", translation: "صاحب العمل", partOfSpeech: "verb", difficulty: "hard", example: "We learned the word jobholder in class today.", exampleTranslation: "تعلّمنا كلمة صاحب العمل في الحصة اليوم." },
  { word: "jockey", translation: "الفارس", partOfSpeech: "noun", difficulty: "medium", example: "Can you use jockey in a sentence?", exampleTranslation: "هل يمكنك استخدام الفارس في جملة؟" },
  { word: "jogger", translation: "عداء ببطء", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned jogger on page ten.", exampleTranslation: "ذكرت القصة عداء ببطء في الصفحة العاشرة." },
  { word: "joiner", translation: "نجار", partOfSpeech: "verb", difficulty: "medium", example: "Our teacher wrote joiner on the board.", exampleTranslation: "كتب معلمنا نجار على السبورة." },
  { word: "joystick", translation: "عصا التحكم", partOfSpeech: "noun", difficulty: "medium", example: "I spelled joystick correctly on the quiz.", exampleTranslation: "تهجّيت عصا التحكم بشكل صحيح في الاختبار." },
  { word: "juggler", translation: "المشعوذ", partOfSpeech: "verb", difficulty: "medium", example: "The picture helps explain juggler.", exampleTranslation: "تساعد الصورة على شرح المشعوذ." },
  { word: "jukebox", translation: "com.jukebox", partOfSpeech: "noun", difficulty: "medium", example: "We found jukebox in our reading book.", exampleTranslation: "وجدنا com.jukebox في كتاب القراءة." },
  { word: "jumpsuit", translation: "بذلة", partOfSpeech: "noun", difficulty: "medium", example: "Jumpsuit is a new word for our unit.", exampleTranslation: "بذلة كلمة جديدة لوحدتنا." },
  { word: "junkfood", translation: "الوجبات السريعة", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed junkfood.", exampleTranslation: "ناقشت الوجبات السريعة مع زميلي." },
  { word: "junkyard", translation: "ساحة الخردة", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about junkyard.", exampleTranslation: "يسأل ورق العمل عن ساحة الخردة." },
  { word: "kayaker", translation: "كايكر", partOfSpeech: "verb", difficulty: "medium", example: "We heard kayaker in the science video.", exampleTranslation: "سمعنا كايكر في فيلم العلوم." },
  { word: "kebab", translation: "كباب", partOfSpeech: "noun", difficulty: "easy", example: "Please copy kebab into your notebook.", exampleTranslation: "من فضلك انسخ كباب في دفترك." },
  { word: "kennel", translation: "بيت الكلب", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of kennel.", exampleTranslation: "يُظهر المخطط مثالاً عن بيت الكلب." },
  { word: "keychain", translation: "سلسلة المفاتيح", partOfSpeech: "noun", difficulty: "medium", example: "Our group used keychain in the project.", exampleTranslation: "استخدمت مجموعتنا سلسلة المفاتيح في المشروع." },
  { word: "keyhole", translation: "ثقب المفتاح", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with keyhole.", exampleTranslation: "أعطى المعلم مثالاً بـثقب المفتاح." },
  { word: "keynote", translation: "الكلمة الرئيسية", partOfSpeech: "noun", difficulty: "medium", example: "I underlined keynote in the paragraph.", exampleTranslation: "وضعت خطاً تحت الكلمة الرئيسية في الفقرة." },
  { word: "kickball", translation: "ركل الكرة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying kickball aloud.", exampleTranslation: "تدرّبنا على نطق ركل الكرة بصوت عالٍ." },
  { word: "kickstand", translation: "مسنده", partOfSpeech: "noun", difficulty: "hard", example: "The poster explains kickstand with a drawing.", exampleTranslation: "يشرح الملصق مسنده برسم." },
  { word: "kidnapper", translation: "الخاطف", partOfSpeech: "verb", difficulty: "hard", example: "Everyone shared a sentence with kidnapper.", exampleTranslation: "شارك الجميع جملة فيها الخاطف." },
  { word: "kimono", translation: "كيمونو", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word kimono.", exampleTranslation: "تضمّن الاختبار كلمة كيمونو." },
  { word: "kindergartener", translation: "روضة أطفال", partOfSpeech: "verb", difficulty: "hard", example: "We learned the word kindergartener in class today.", exampleTranslation: "تعلّمنا كلمة روضة أطفال في الحصة اليوم." },
  { word: "kingfish", translation: "كنعد", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use kingfish in a sentence?", exampleTranslation: "هل يمكنك استخدام كنعد في جملة؟" },
  { word: "kingpin", translation: "الملك", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned kingpin on page ten.", exampleTranslation: "ذكرت القصة الملك في الصفحة العاشرة." },
  { word: "kios", translation: "أكشاك", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote kios on the board.", exampleTranslation: "كتب معلمنا أكشاك على السبورة." },
  { word: "kiosk", translation: "كشك", partOfSpeech: "noun", difficulty: "easy", example: "I spelled kiosk correctly on the quiz.", exampleTranslation: "تهجّيت كشك بشكل صحيح في الاختبار." },
  { word: "kitchenware", translation: "أدوات المطبخ", partOfSpeech: "noun", difficulty: "hard", example: "The picture helps explain kitchenware.", exampleTranslation: "تساعد الصورة على شرح أدوات المطبخ." },
  { word: "knapsack", translation: "حقيبة", partOfSpeech: "noun", difficulty: "medium", example: "We found knapsack in our reading book.", exampleTranslation: "وجدنا حقيبة في كتاب القراءة." },
  { word: "kneecap", translation: "الرضفة", partOfSpeech: "noun", difficulty: "medium", example: "Kneecap is a new word for our unit.", exampleTranslation: "الرضفة كلمة جديدة لوحدتنا." },
  { word: "kneepad", translation: "نيباد", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed kneepad.", exampleTranslation: "ناقشت نيباد مع زميلي." },
  { word: "knockdown", translation: "صرع", partOfSpeech: "noun", difficulty: "hard", example: "The worksheet asks about knockdown.", exampleTranslation: "يسأل ورق العمل عن صرع." },
  { word: "knocker", translation: "مطرقة", partOfSpeech: "verb", difficulty: "medium", example: "We heard knocker in the science video.", exampleTranslation: "سمعنا مطرقة في فيلم العلوم." },
  { word: "knothole", translation: "عقدة", partOfSpeech: "noun", difficulty: "medium", example: "Please copy knothole into your notebook.", exampleTranslation: "من فضلك انسخ عقدة في دفترك." },
  { word: "koi", translation: "كوي", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of koi.", exampleTranslation: "يُظهر المخطط مثالاً عن كوي." },
  { word: "kryptonite", translation: "الكريبتونيت", partOfSpeech: "noun", difficulty: "hard", example: "Our group used kryptonite in the project.", exampleTranslation: "استخدمت مجموعتنا الكريبتونيت في المشروع." },
  { word: "labrador", translation: "لابرادور", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with labrador.", exampleTranslation: "أعطى المعلم مثالاً بـلابرادور." },
  { word: "ladybird", translation: "الدعسوقة", partOfSpeech: "noun", difficulty: "medium", example: "I underlined ladybird in the paragraph.", exampleTranslation: "وضعت خطاً تحت الدعسوقة في الفقرة." },
  { word: "lakeshore", translation: "شاطئ البحيرة", partOfSpeech: "noun", difficulty: "hard", example: "We practiced saying lakeshore aloud.", exampleTranslation: "تدرّبنا على نطق شاطئ البحيرة بصوت عالٍ." },
  { word: "lakeside", translation: "على ضفاف البحيرة", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains lakeside with a drawing.", exampleTranslation: "يشرح الملصق على ضفاف البحيرة برسم." },
  { word: "lamppost", translation: "عمود اضاءة", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with lamppost.", exampleTranslation: "شارك الجميع جملة فيها عمود اضاءة." },
  { word: "landform", translation: "شكل الأرض", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word landform.", exampleTranslation: "تضمّن الاختبار كلمة شكل الأرض." },
  { word: "landlady", translation: "صاحبة المنزل", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word landlady in class today.", exampleTranslation: "تعلّمنا كلمة صاحبة المنزل في الحصة اليوم." },
  { word: "landlord", translation: "المالك", partOfSpeech: "noun", difficulty: "medium", example: "Can you use landlord in a sentence?", exampleTranslation: "هل يمكنك استخدام المالك في جملة؟" },
  { word: "landmine", translation: "لغم أرضي", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned landmine on page ten.", exampleTranslation: "ذكرت القصة لغم أرضي في الصفحة العاشرة." },
  { word: "landslide", translation: "انهيار أرضي", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote landslide on the board.", exampleTranslation: "كتب معلمنا انهيار أرضي على السبورة." },
  { word: "langoustine", translation: "لانجوستين", partOfSpeech: "noun", difficulty: "hard", example: "I spelled langoustine correctly on the quiz.", exampleTranslation: "تهجّيت لانجوستين بشكل صحيح في الاختبار." },
  { word: "lanternfish", translation: "سمكة الفانوس", partOfSpeech: "adjective", difficulty: "hard", example: "The picture helps explain lanternfish.", exampleTranslation: "تساعد الصورة على شرح سمكة الفانوس." },
  { word: "larkspur", translation: "لاركسبور", partOfSpeech: "noun", difficulty: "medium", example: "We found larkspur in our reading book.", exampleTranslation: "وجدنا لاركسبور في كتاب القراءة." },
  { word: "lasagna", translation: "لازانيا", partOfSpeech: "noun", difficulty: "medium", example: "Lasagna is a new word for our unit.", exampleTranslation: "لازانيا كلمة جديدة لوحدتنا." },
  { word: "lasso", translation: "لاسو", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed lasso.", exampleTranslation: "ناقشت لاسو مع زميلي." },
  { word: "latchkey", translation: "مفتاح المزلاج", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about latchkey.", exampleTranslation: "يسأل ورق العمل عن مفتاح المزلاج." },
  { word: "stressed", translation: "متوتر", partOfSpeech: "adjective", difficulty: "medium", example: "We heard stressed in the science video.", exampleTranslation: "سمعنا متوتر في فيلم العلوم." },
  { word: "ashamed", translation: "خجلان", partOfSpeech: "adjective", difficulty: "medium", example: "Please copy ashamed into your notebook.", exampleTranslation: "من فضلك انسخ خجلان في دفترك." },
  { word: "guilty", translation: "مذنب", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of guilty.", exampleTranslation: "يُظهر المخطط مثالاً عن مذنب." },
  { word: "thankful", translation: "شاكر", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used thankful in the project.", exampleTranslation: "استخدمت مجموعتنا شاكر في المشروع." },
  { word: "hopeful", translation: "متفائل", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with hopeful.", exampleTranslation: "أعطى المعلم مثالاً بـمتفائل." },
  { word: "hopeless", translation: "يائس", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined hopeless in the paragraph.", exampleTranslation: "وضعت خطاً تحت يائس في الفقرة." },
  { word: "doubtful", translation: "متردد", partOfSpeech: "adjective", difficulty: "medium", example: "We practiced saying doubtful aloud.", exampleTranslation: "تدرّبنا على نطق متردد بصوت عالٍ." },
  { word: "surprised", translation: "مندهش", partOfSpeech: "adjective", difficulty: "easy", example: "The poster explains surprised with a drawing.", exampleTranslation: "يشرح الملصق مندهش برسم." },
  { word: "shocked", translation: "مصدوم", partOfSpeech: "adjective", difficulty: "medium", example: "Everyone shared a sentence with shocked.", exampleTranslation: "شارك الجميع جملة فيها مصدوم." },
  { word: "amazed", translation: "مندهش", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word amazed.", exampleTranslation: "تضمّن الاختبار كلمة مندهش." },
  { word: "confused", translation: "مرتبك", partOfSpeech: "adjective", difficulty: "easy", example: "We learned the word confused in class today.", exampleTranslation: "تعلّمنا كلمة مرتبك في الحصة اليوم." },
  { word: "envious", translation: "حاسد", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use envious in a sentence?", exampleTranslation: "هل يمكنك استخدام حاسد في جملة؟" },
  { word: "loving", translation: "محب", partOfSpeech: "adjective", difficulty: "easy", example: "The story mentioned loving on page ten.", exampleTranslation: "ذكرت القصة محب في الصفحة العاشرة." },
  { word: "caring", translation: "مهتم", partOfSpeech: "adjective", difficulty: "medium", example: "Our teacher wrote caring on the board.", exampleTranslation: "كتب معلمنا مهتم على السبورة." },
  { word: "friendly", translation: "ودود", partOfSpeech: "adjective", difficulty: "easy", example: "I spelled friendly correctly on the quiz.", exampleTranslation: "تهجّيت ودود بشكل صحيح في الاختبار." },
  { word: "rude", translation: "وقح", partOfSpeech: "adjective", difficulty: "easy", example: "The picture helps explain rude.", exampleTranslation: "تساعد الصورة على شرح وقح." },
  { word: "cruel", translation: "قاسٍ", partOfSpeech: "adjective", difficulty: "medium", example: "We found cruel in our reading book.", exampleTranslation: "وجدنا قاسٍ في كتاب القراءة." },
  { word: "impatient", translation: "غير صبور", partOfSpeech: "adjective", difficulty: "medium", example: "Impatient is a new word for our unit.", exampleTranslation: "غير صبور كلمة جديدة لوحدتنا." },
  { word: "faithful", translation: "مخلص", partOfSpeech: "adjective", difficulty: "medium", example: "My partner and I discussed faithful.", exampleTranslation: "ناقشت مخلص مع زميلي." },
  { word: "trustworthy", translation: "جدير بالثقة", partOfSpeech: "adjective", difficulty: "medium", example: "The worksheet asks about trustworthy.", exampleTranslation: "يسأل ورق العمل عن جدير بالثقة." },
  { word: "reliable", translation: "موثوق", partOfSpeech: "adjective", difficulty: "medium", example: "We heard reliable in the science video.", exampleTranslation: "سمعنا موثوق في فيلم العلوم." },
  { word: "careless", translation: "مهمل", partOfSpeech: "adjective", difficulty: "medium", example: "Please copy careless into your notebook.", exampleTranslation: "من فضلك انسخ مهمل في دفترك." },
  { word: "cautious", translation: "حذر", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of cautious.", exampleTranslation: "يُظهر المخطط مثالاً عن حذر." },
  { word: "aware", translation: "واعٍ", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used aware in the project.", exampleTranslation: "استخدمت مجموعتنا واعٍ في المشروع." },
  { word: "thoughtful", translation: "مدروس", partOfSpeech: "adjective", difficulty: "medium", example: "The teacher gave an example with thoughtful.", exampleTranslation: "أعطى المعلم مثالاً بـمدروس." },
  { word: "sensible", translation: "معقول", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined sensible in the paragraph.", exampleTranslation: "وضعت خطاً تحت معقول في الفقرة." },
  { word: "silly", translation: "سخيف", partOfSpeech: "adjective", difficulty: "easy", example: "We practiced saying silly aloud.", exampleTranslation: "تدرّبنا على نطق سخيف بصوت عالٍ." },
  { word: "humorous", translation: "فكاهي", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains humorous with a drawing.", exampleTranslation: "يشرح الملصق فكاهي برسم." },
  { word: "serious", translation: "جدي", partOfSpeech: "adjective", difficulty: "easy", example: "Everyone shared a sentence with serious.", exampleTranslation: "شارك الجميع جملة فيها جدي." },
  { word: "solemn", translation: "وقور", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word solemn.", exampleTranslation: "تضمّن الاختبار كلمة وقور." },
  { word: "eager", translation: "متحمس", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word eager in class today.", exampleTranslation: "تعلّمنا كلمة متحمس في الحصة اليوم." },
  { word: "enthusiastic", translation: "متحمس", partOfSpeech: "adjective", difficulty: "medium", example: "Can you use enthusiastic in a sentence?", exampleTranslation: "هل يمكنك استخدام متحمس في جملة؟" },
  { word: "satisfied", translation: "راضٍ", partOfSpeech: "adjective", difficulty: "medium", example: "The story mentioned satisfied on page ten.", exampleTranslation: "ذكرت القصة راضٍ في الصفحة العاشرة." },
  { word: "pleased", translation: "مسرور", partOfSpeech: "adjective", difficulty: "easy", example: "Our teacher wrote pleased on the board.", exampleTranslation: "كتب معلمنا مسرور على السبورة." },
  { word: "miserable", translation: "بائس", partOfSpeech: "adjective", difficulty: "medium", example: "I spelled miserable correctly on the quiz.", exampleTranslation: "تهجّيت بائس بشكل صحيح في الاختبار." },
  { word: "gloomy", translation: "كئيب", partOfSpeech: "adjective", difficulty: "medium", example: "The picture helps explain gloomy.", exampleTranslation: "تساعد الصورة على شرح كئيب." },
  { word: "moody", translation: "متقلب المزاج", partOfSpeech: "adjective", difficulty: "medium", example: "We found moody in our reading book.", exampleTranslation: "وجدنا متقلب المزاج في كتاب القراءة." },
  { word: "grumpy", translation: "نكد", partOfSpeech: "adjective", difficulty: "medium", example: "Grumpy is a new word for our unit.", exampleTranslation: "نكد كلمة جديدة لوحدتنا." },
  { word: "upset", translation: "منزعج", partOfSpeech: "adjective", difficulty: "easy", example: "My partner and I discussed upset.", exampleTranslation: "ناقشت منزعج مع زميلي." },
  { word: "annoyed", translation: "منزعج", partOfSpeech: "adjective", difficulty: "medium", example: "The worksheet asks about annoyed.", exampleTranslation: "يسأل ورق العمل عن منزعج." },
  { word: "irritated", translation: "منزعج", partOfSpeech: "adjective", difficulty: "medium", example: "We heard irritated in the science video.", exampleTranslation: "سمعنا منزعج في فيلم العلوم." },
  { word: "outraged", translation: "غاضب جداً", partOfSpeech: "adjective", difficulty: "medium", example: "Please copy outraged into your notebook.", exampleTranslation: "من فضلك انسخ غاضب جداً في دفترك." },
  { word: "terrified", translation: "مرعوب", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of terrified.", exampleTranslation: "يُظهر المخطط مثالاً عن مرعوب." },
  { word: "panicked", translation: "مرعوب", partOfSpeech: "adjective", difficulty: "medium", example: "Our group used panicked in the project.", exampleTranslation: "استخدمت مجموعتنا مرعوب في المشروع." },
  { word: "comfortable", translation: "مريح", partOfSpeech: "adjective", difficulty: "easy", example: "The teacher gave an example with comfortable.", exampleTranslation: "أعطى المعلم مثالاً بـمريح." },
  { word: "uncomfortable", translation: "غير مريح", partOfSpeech: "adjective", difficulty: "medium", example: "I underlined uncomfortable in the paragraph.", exampleTranslation: "وضعت خطاً تحت غير مريح في الفقرة." },
  { word: "cozy", translation: "دافئ ومريح", partOfSpeech: "adjective", difficulty: "medium", example: "We practiced saying cozy aloud.", exampleTranslation: "تدرّبنا على نطق دافئ ومريح بصوت عالٍ." },
  { word: "warm", translation: "دافئ", partOfSpeech: "adjective", difficulty: "easy", example: "The poster explains warm with a drawing.", exampleTranslation: "يشرح الملصق دافئ برسم." },
  { word: "cool", translation: "بارد", partOfSpeech: "adjective", difficulty: "easy", example: "Everyone shared a sentence with cool.", exampleTranslation: "شارك الجميع جملة فيها بارد." },
  { word: "freezing", translation: "متجمد", partOfSpeech: "adjective", difficulty: "medium", example: "The quiz included the word freezing.", exampleTranslation: "تضمّن الاختبار كلمة متجمد." },
  { word: "boiling", translation: "مغلي", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word boiling in class today.", exampleTranslation: "تعلّمنا كلمة مغلي في الحصة اليوم." },
  { word: "atom", translation: "ذرة", partOfSpeech: "noun", difficulty: "medium", example: "Can you use atom in a sentence?", exampleTranslation: "هل يمكنك استخدام ذرة في جملة؟" },
  { word: "solid", translation: "صلب", partOfSpeech: "noun", difficulty: "easy", example: "The story mentioned solid on page ten.", exampleTranslation: "ذكرت القصة صلب في الصفحة العاشرة." },
  { word: "liquid", translation: "سائل", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote liquid on the board.", exampleTranslation: "كتب معلمنا سائل على السبورة." },
  { word: "gas", translation: "غاز", partOfSpeech: "noun", difficulty: "easy", example: "I spelled gas correctly on the quiz.", exampleTranslation: "تهجّيت غاز بشكل صحيح في الاختبار." },
  { word: "power", translation: "قدرة", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain power.", exampleTranslation: "تساعد الصورة على شرح قدرة." },
  { word: "work", translation: "شغل", partOfSpeech: "noun", difficulty: "easy", example: "We found work in our reading book.", exampleTranslation: "وجدنا شغل في كتاب القراءة." },
  { word: "heat", translation: "حرارة", partOfSpeech: "noun", difficulty: "easy", example: "Heat is a new word for our unit.", exampleTranslation: "حرارة كلمة جديدة لوحدتنا." },
  { word: "pressure", translation: "ضغط", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed pressure.", exampleTranslation: "ناقشت ضغط مع زميلي." },
  { word: "bulb", translation: "مصباح", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about bulb.", exampleTranslation: "يسأل ورق العمل عن مصباح." },
  { word: "wire", translation: "سلك", partOfSpeech: "noun", difficulty: "easy", example: "We heard wire in the science video.", exampleTranslation: "سمعنا سلك في فيلم العلوم." },
  { word: "switch", translation: "مفتاح", partOfSpeech: "noun", difficulty: "easy", example: "Please copy switch into your notebook.", exampleTranslation: "من فضلك انسخ مفتاح في دفترك." },
  { word: "motor", translation: "محرك", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of motor.", exampleTranslation: "يُظهر المخطط مثالاً عن محرك." },
  { word: "engine", translation: "محرك", partOfSpeech: "noun", difficulty: "easy", example: "Our group used engine in the project.", exampleTranslation: "استخدمت مجموعتنا محرك في المشروع." },
  { word: "machine", translation: "آلة", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with machine.", exampleTranslation: "أعطى المعلم مثالاً بـآلة." },
  { word: "wheel", translation: "عجلة", partOfSpeech: "noun", difficulty: "easy", example: "I underlined wheel in the paragraph.", exampleTranslation: "وضعت خطاً تحت عجلة في الفقرة." },
  { word: "pendulum", translation: "بندول", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying pendulum aloud.", exampleTranslation: "تدرّبنا على نطق بندول بصوت عالٍ." },
  { word: "lens", translation: "عدسة", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains lens with a drawing.", exampleTranslation: "يشرح الملصق عدسة برسم." },
  { word: "light", translation: "ضوء", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with light.", exampleTranslation: "شارك الجميع جملة فيها ضوء." },
  { word: "color", translation: "لون", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word color.", exampleTranslation: "تضمّن الاختبار كلمة لون." },
  { word: "sound", translation: "صوت", partOfSpeech: "noun", difficulty: "easy", example: "We learned the word sound in class today.", exampleTranslation: "تعلّمنا كلمة صوت في الحصة اليوم." },
  { word: "pitch", translation: "طبقة صوتية", partOfSpeech: "noun", difficulty: "medium", example: "Can you use pitch in a sentence?", exampleTranslation: "هل يمكنك استخدام طبقة صوتية في جملة؟" },
  { word: "testtube", translation: "أنبوب اختبار", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned testtube on page ten.", exampleTranslation: "ذكرت القصة أنبوب اختبار في الصفحة العاشرة." },
  { word: "magnetometer", translation: "مقياس مغناطيسية", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote magnetometer on the board.", exampleTranslation: "كتب معلمنا مقياس مغناطيسية على السبورة." },
  { word: "voltmeter", translation: "فولتميتر", partOfSpeech: "noun", difficulty: "medium", example: "I spelled voltmeter correctly on the quiz.", exampleTranslation: "تهجّيت فولتميتر بشكل صحيح في الاختبار." },
  { word: "ammeter", translation: "أميتر", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain ammeter.", exampleTranslation: "تساعد الصورة على شرح أميتر." },
  { word: "reaction", translation: "تفاعل", partOfSpeech: "noun", difficulty: "medium", example: "We found reaction in our reading book.", exampleTranslation: "وجدنا تفاعل في كتاب القراءة." },
  { word: "alkali", translation: "قلوي", partOfSpeech: "noun", difficulty: "medium", example: "Alkali is a new word for our unit.", exampleTranslation: "قلوي كلمة جديدة لوحدتنا." },
  { word: "melting", translation: "انصهار", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed melting.", exampleTranslation: "ناقشت انصهار مع زميلي." },
  { word: "filter", translation: "تصفية", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about filter.", exampleTranslation: "يسأل ورق العمل عن تصفية." },
  { word: "distill", translation: "تقطير", partOfSpeech: "verb", difficulty: "medium", example: "We heard distill in the science video.", exampleTranslation: "سمعنا تقطير في فيلم العلوم." },
  { word: "ferment", translation: "تخمير", partOfSpeech: "verb", difficulty: "medium", example: "Please copy ferment into your notebook.", exampleTranslation: "من فضلك انسخ تخمير في دفترك." },
  { word: "rust", translation: "صدأ", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of rust.", exampleTranslation: "يُظهر المخطط مثالاً عن صدأ." },
  { word: "corrosion", translation: "تآكل", partOfSpeech: "noun", difficulty: "medium", example: "Our group used corrosion in the project.", exampleTranslation: "استخدمت مجموعتنا تآكل في المشروع." },
  { word: "combustion", translation: "احتراق", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with combustion.", exampleTranslation: "أعطى المعلم مثالاً بـاحتراق." },
  { word: "explosion", translation: "انفجار", partOfSpeech: "noun", difficulty: "medium", example: "I underlined explosion in the paragraph.", exampleTranslation: "وضعت خطاً تحت انفجار في الفقرة." },
  { word: "charge", translation: "شحنة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying charge aloud.", exampleTranslation: "تدرّبنا على نطق شحنة بصوت عالٍ." },
  { word: "chip", translation: "رقاقة", partOfSpeech: "noun", difficulty: "easy", example: "The poster explains chip with a drawing.", exampleTranslation: "يشرح الملصق رقاقة برسم." },
  { word: "float", translation: "طفو", partOfSpeech: "verb", difficulty: "easy", example: "Everyone shared a sentence with float.", exampleTranslation: "شارك الجميع جملة فيها طفو." },
  { word: "sink", translation: "غرق", partOfSpeech: "verb", difficulty: "easy", example: "The quiz included the word sink.", exampleTranslation: "تضمّن الاختبار كلمة غرق." },
  { word: "emit", translation: "انبعاث", partOfSpeech: "verb", difficulty: "medium", example: "We learned the word emit in class today.", exampleTranslation: "تعلّمنا كلمة انبعاث في الحصة اليوم." },
  { word: "refract", translation: "انكسار", partOfSpeech: "verb", difficulty: "medium", example: "Can you use refract in a sentence?", exampleTranslation: "هل يمكنك استخدام انكسار في جملة؟" },
  { word: "conduct", translation: "توصيل", partOfSpeech: "verb", difficulty: "medium", example: "The story mentioned conduct on page ten.", exampleTranslation: "ذكرت القصة توصيل في الصفحة العاشرة." },
  { word: "insulate", translation: "عزل", partOfSpeech: "verb", difficulty: "medium", example: "Our teacher wrote insulate on the board.", exampleTranslation: "كتب معلمنا عزل على السبورة." },
  { word: "generate", translation: "توليد", partOfSpeech: "verb", difficulty: "medium", example: "I spelled generate correctly on the quiz.", exampleTranslation: "تهجّيت توليد بشكل صحيح في الاختبار." },
  { word: "convert", translation: "تحويل", partOfSpeech: "verb", difficulty: "medium", example: "The picture helps explain convert.", exampleTranslation: "تساعد الصورة على شرح تحويل." },
  { word: "measure", translation: "قياس", partOfSpeech: "verb", difficulty: "easy", example: "We found measure in our reading book.", exampleTranslation: "وجدنا قياس في كتاب القراءة." },
  { word: "demonstrate", translation: "إثبات", partOfSpeech: "verb", difficulty: "medium", example: "Demonstrate is a new word for our unit.", exampleTranslation: "إثبات كلمة جديدة لوحدتنا." },
  { word: "model", translation: "نموذج", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed model.", exampleTranslation: "ناقشت نموذج مع زميلي." },
  { word: "sample", translation: "عينة", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about sample.", exampleTranslation: "يسأل ورق العمل عن عينة." },
  { word: "organism", translation: "كائن حي", partOfSpeech: "noun", difficulty: "medium", example: "We heard organism in the science video.", exampleTranslation: "سمعنا كائن حي في فيلم العلوم." },
  { word: "insect", translation: "حشرة", partOfSpeech: "noun", difficulty: "easy", example: "Please copy insect into your notebook.", exampleTranslation: "من فضلك انسخ حشرة في دفترك." },
  { word: "digestion", translation: "هضم", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of digestion.", exampleTranslation: "يُظهر المخطط مثالاً عن هضم." },
  { word: "circulation", translation: "دورة دموية", partOfSpeech: "noun", difficulty: "medium", example: "Our group used circulation in the project.", exampleTranslation: "استخدمت مجموعتنا دورة دموية في المشروع." },
  { word: "reproduction", translation: "تكاثر", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with reproduction.", exampleTranslation: "أعطى المعلم مثالاً بـتكاثر." },
  { word: "germ", translation: "جرثومة", partOfSpeech: "noun", difficulty: "easy", example: "I underlined germ in the paragraph.", exampleTranslation: "وضعت خطاً تحت جرثومة في الفقرة." },
  { word: "antigen", translation: "مستضد", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying antigen aloud.", exampleTranslation: "تدرّبنا على نطق مستضد بصوت عالٍ." },
  { word: "immune", translation: "مناعي", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains immune with a drawing.", exampleTranslation: "يشرح الملصق مناعي برسم." },
  { word: "gene", translation: "جين", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with gene.", exampleTranslation: "شارك الجميع جملة فيها جين." },
  { word: "dna", translation: "حمض نووي", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word dna.", exampleTranslation: "تضمّن الاختبار كلمة حمض نووي." },
  { word: "rna", translation: "حمض نووي ريبوزي", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word rna in class today.", exampleTranslation: "تعلّمنا كلمة حمض نووي ريبوزي في الحصة اليوم." },
  { word: "trait", translation: "صفة", partOfSpeech: "noun", difficulty: "medium", example: "Can you use trait in a sentence?", exampleTranslation: "هل يمكنك استخدام صفة في جملة؟" },
  { word: "inheritance", translation: "وراثة", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned inheritance on page ten.", exampleTranslation: "ذكرت القصة وراثة في الصفحة العاشرة." },
  { word: "country", translation: "بلد", partOfSpeech: "noun", difficulty: "easy", example: "Our teacher wrote country on the board.", exampleTranslation: "كتب معلمنا بلد على السبورة." },
  { word: "nation", translation: "أمة", partOfSpeech: "noun", difficulty: "easy", example: "I spelled nation correctly on the quiz.", exampleTranslation: "تهجّيت أمة بشكل صحيح في الاختبار." },
  { word: "state", translation: "ولاية", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain state.", exampleTranslation: "تساعد الصورة على شرح ولاية." },
  { word: "province", translation: "مقاطعة", partOfSpeech: "noun", difficulty: "medium", example: "We found province in our reading book.", exampleTranslation: "وجدنا مقاطعة في كتاب القراءة." },
  { word: "district", translation: "منطقة", partOfSpeech: "noun", difficulty: "easy", example: "District is a new word for our unit.", exampleTranslation: "منطقة كلمة جديدة لوحدتنا." },
  { word: "city", translation: "مدينة", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed city.", exampleTranslation: "ناقشت مدينة مع زميلي." },
  { word: "town", translation: "بلدة", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about town.", exampleTranslation: "يسأل ورق العمل عن بلدة." },
  { word: "capital", translation: "عاصمة", partOfSpeech: "noun", difficulty: "easy", example: "We heard capital in the science video.", exampleTranslation: "سمعنا عاصمة في فيلم العلوم." },
  { word: "boundary", translation: "حدود", partOfSpeech: "noun", difficulty: "medium", example: "Please copy boundary into your notebook.", exampleTranslation: "من فضلك انسخ حدود في دفترك." },
  { word: "statue", translation: "تمثال", partOfSpeech: "noun", difficulty: "easy", example: "The chart shows an example of statue.", exampleTranslation: "يُظهر المخطط مثالاً عن تمثال." },
  { word: "highway", translation: "طريق سريع", partOfSpeech: "noun", difficulty: "easy", example: "Our group used highway in the project.", exampleTranslation: "استخدمت مجموعتنا طريق سريع في المشروع." },
  { word: "road", translation: "طريق", partOfSpeech: "noun", difficulty: "easy", example: "The teacher gave an example with road.", exampleTranslation: "أعطى المعلم مثالاً بـطريق." },
  { word: "avenue", translation: "جادة", partOfSpeech: "noun", difficulty: "medium", example: "I underlined avenue in the paragraph.", exampleTranslation: "وضعت خطاً تحت جادة في الفقرة." },
  { word: "boulevard", translation: "شارع واسع", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying boulevard aloud.", exampleTranslation: "تدرّبنا على نطق شارع واسع بصوت عالٍ." },
  { word: "alley", translation: "زقاق", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains alley with a drawing.", exampleTranslation: "يشرح الملصق زقاق برسم." },
  { word: "path", translation: "مسار", partOfSpeech: "noun", difficulty: "easy", example: "Everyone shared a sentence with path.", exampleTranslation: "شارك الجميع جملة فيها مسار." },
  { word: "trail", translation: "درب", partOfSpeech: "noun", difficulty: "easy", example: "The quiz included the word trail.", exampleTranslation: "تضمّن الاختبار كلمة درب." },
  { word: "junction", translation: "تقاطع", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word junction in class today.", exampleTranslation: "تعلّمنا كلمة تقاطع في الحصة اليوم." },
  { word: "intersection", translation: "تقاطع", partOfSpeech: "noun", difficulty: "medium", example: "Can you use intersection in a sentence?", exampleTranslation: "هل يمكنك استخدام تقاطع في جملة؟" },
  { word: "pavement", translation: "رصيف", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned pavement on page ten.", exampleTranslation: "ذكرت القصة رصيف في الصفحة العاشرة." },
  { word: "plaza", translation: "ساحة", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote plaza on the board.", exampleTranslation: "كتب معلمنا ساحة على السبورة." },
  { word: "zoo", translation: "حديقة حيوان", partOfSpeech: "noun", difficulty: "easy", example: "I spelled zoo correctly on the quiz.", exampleTranslation: "تهجّيت حديقة حيوان بشكل صحيح في الاختبار." },
  { word: "theater", translation: "مسرح", partOfSpeech: "noun", difficulty: "easy", example: "The picture helps explain theater.", exampleTranslation: "تساعد الصورة على شرح مسرح." },
  { word: "bank", translation: "بنك", partOfSpeech: "noun", difficulty: "easy", example: "We found bank in our reading book.", exampleTranslation: "وجدنا بنك في كتاب القراءة." },
  { word: "store", translation: "متجر", partOfSpeech: "noun", difficulty: "easy", example: "Store is a new word for our unit.", exampleTranslation: "متجر كلمة جديدة لوحدتنا." },
  { word: "mall", translation: "مركز تسوق", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed mall.", exampleTranslation: "ناقشت مركز تسوق مع زميلي." },
  { word: "cafe", translation: "مقهى", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about cafe.", exampleTranslation: "يسأل ورق العمل عن مقهى." },
];
