/** Grade 5 chunk B — history, geography, civics (simple daily vocabulary) (250 cards). */
export const GRADE5_CHUNK_B = [
  { word: "eggbeater", translation: "مضرب البيض", partOfSpeech: "verb", difficulty: "hard", example: "We heard eggbeater in the science video.", exampleTranslation: "سمعنا مضرب البيض في فيلم العلوم." },
  { word: "eggnog", translation: "شراب البيض", partOfSpeech: "noun", difficulty: "medium", example: "Please copy eggnog into your notebook.", exampleTranslation: "من فضلك انسخ شراب البيض في دفترك." },
  { word: "eggshell", translation: "قشر البيض", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of eggshell.", exampleTranslation: "يُظهر المخطط مثالاً عن قشر البيض." },
  { word: "eightball", translation: "ثمانية كرات", partOfSpeech: "noun", difficulty: "hard", example: "Our group used eightball in the project.", exampleTranslation: "استخدمت مجموعتنا ثمانية كرات في المشروع." },
  { word: "elbowpad", translation: "لوحة الكوع", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with elbowpad.", exampleTranslation: "أعطى المعلم مثالاً بـلوحة الكوع." },
  { word: "elk", translation: "الأيائل", partOfSpeech: "noun", difficulty: "easy", example: "I underlined elk in the paragraph.", exampleTranslation: "وضعت خطاً تحت الأيائل في الفقرة." },
  { word: "elkhorn", translation: "إلكورن", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying elkhorn aloud.", exampleTranslation: "تدرّبنا على نطق إلكورن بصوت عالٍ." },
  { word: "embankment", translation: "السد", partOfSpeech: "noun", difficulty: "hard", example: "The poster explains embankment with a drawing.", exampleTranslation: "يشرح الملصق السد برسم." },
  { word: "ember", translation: "جمرة", partOfSpeech: "verb", difficulty: "easy", example: "Everyone shared a sentence with ember.", exampleTranslation: "شارك الجميع جملة فيها جمرة." },
  { word: "emptiness", translation: "الفراغ", partOfSpeech: "noun", difficulty: "hard", example: "The quiz included the word emptiness.", exampleTranslation: "تضمّن الاختبار كلمة الفراغ." },
  { word: "enamel", translation: "المينا", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word enamel in class today.", exampleTranslation: "تعلّمنا كلمة المينا في الحصة اليوم." },
  { word: "encampment", translation: "المعسكر", partOfSpeech: "noun", difficulty: "hard", example: "Can you use encampment in a sentence?", exampleTranslation: "هل يمكنك استخدام المعسكر في جملة؟" },
  { word: "enchilada", translation: "الانتشلادا", partOfSpeech: "noun", difficulty: "hard", example: "The story mentioned enchilada on page ten.", exampleTranslation: "ذكرت القصة الانتشلادا في الصفحة العاشرة." },
  { word: "englishman", translation: "إنجليزي", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote englishman on the board.", exampleTranslation: "كتب معلمنا إنجليزي على السبورة." },
  { word: "entree", translation: "دخول", partOfSpeech: "noun", difficulty: "medium", example: "I spelled entree correctly on the quiz.", exampleTranslation: "تهجّيت دخول بشكل صحيح في الاختبار." },
  { word: "espresso", translation: "إسبرسو", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain espresso.", exampleTranslation: "تساعد الصورة على شرح إسبرسو." },
  { word: "eyeglass", translation: "نظارات", partOfSpeech: "noun", difficulty: "medium", example: "We found eyeglass in our reading book.", exampleTranslation: "وجدنا نظارات في كتاب القراءة." },
  { word: "eyepatch", translation: "رقعة العين", partOfSpeech: "noun", difficulty: "medium", example: "Eyepatch is a new word for our unit.", exampleTranslation: "رقعة العين كلمة جديدة لوحدتنا." },
  { word: "fairground", translation: "أرض المعارض", partOfSpeech: "noun", difficulty: "hard", example: "My partner and I discussed fairground.", exampleTranslation: "ناقشت أرض المعارض مع زميلي." },
  { word: "fairway", translation: "الممر السالك", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about fairway.", exampleTranslation: "يسأل ورق العمل عن الممر السالك." },
  { word: "falconer", translation: "صقار", partOfSpeech: "verb", difficulty: "medium", example: "We heard falconer in the science video.", exampleTranslation: "سمعنا صقار في فيلم العلوم." },
  { word: "farmyard", translation: "ساحة المزرعة", partOfSpeech: "noun", difficulty: "medium", example: "Please copy farmyard into your notebook.", exampleTranslation: "من فضلك انسخ ساحة المزرعة في دفترك." },
  { word: "fastball", translation: "كرة سريعة", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of fastball.", exampleTranslation: "يُظهر المخطط مثالاً عن كرة سريعة." },
  { word: "fastfood", translation: "وجبات سريعة", partOfSpeech: "noun", difficulty: "medium", example: "Our group used fastfood in the project.", exampleTranslation: "استخدمت مجموعتنا وجبات سريعة في المشروع." },
  { word: "fatherland", translation: "الوطن", partOfSpeech: "noun", difficulty: "hard", example: "The teacher gave an example with fatherland.", exampleTranslation: "أعطى المعلم مثالاً بـالوطن." },
  { word: "featherbed", translation: "سرير ريش", partOfSpeech: "adjective", difficulty: "hard", example: "I underlined featherbed in the paragraph.", exampleTranslation: "وضعت خطاً تحت سرير ريش في الفقرة." },
  { word: "feedbag", translation: "حقيبة التغذية", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying feedbag aloud.", exampleTranslation: "تدرّبنا على نطق حقيبة التغذية بصوت عالٍ." },
  { word: "fencer", translation: "مبارز", partOfSpeech: "verb", difficulty: "medium", example: "The poster explains fencer with a drawing.", exampleTranslation: "يشرح الملصق مبارز برسم." },
  { word: "fernfield", translation: "فيرنفيلد", partOfSpeech: "noun", difficulty: "hard", example: "Everyone shared a sentence with fernfield.", exampleTranslation: "شارك الجميع جملة فيها فيرنفيلد." },
  { word: "ferryboat", translation: "معدية", partOfSpeech: "noun", difficulty: "hard", example: "The quiz included the word ferryboat.", exampleTranslation: "تضمّن الاختبار كلمة معدية." },
  { word: "fieldhouse", translation: "منزل ميداني", partOfSpeech: "noun", difficulty: "hard", example: "We learned the word fieldhouse in class today.", exampleTranslation: "تعلّمنا كلمة منزل ميداني في الحصة اليوم." },
  { word: "fieldtrip", translation: "رحلة ميدانية", partOfSpeech: "noun", difficulty: "hard", example: "Can you use fieldtrip in a sentence?", exampleTranslation: "هل يمكنك استخدام رحلة ميدانية في جملة؟" },
  { word: "figment", translation: "الشكل", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned figment on page ten.", exampleTranslation: "ذكرت القصة الشكل في الصفحة العاشرة." },
  { word: "filmstrip", translation: "شريط سينمائي", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote filmstrip on the board.", exampleTranslation: "كتب معلمنا شريط سينمائي على السبورة." },
  { word: "fingerboard", translation: "الأصابع", partOfSpeech: "noun", difficulty: "hard", example: "I spelled fingerboard correctly on the quiz.", exampleTranslation: "تهجّيت الأصابع بشكل صحيح في الاختبار." },
  { word: "firecracker", translation: "مفرقعة نارية", partOfSpeech: "verb", difficulty: "hard", example: "The picture helps explain firecracker.", exampleTranslation: "تساعد الصورة على شرح مفرقعة نارية." },
  { word: "firehouse", translation: "محطة الإطفاء", partOfSpeech: "noun", difficulty: "hard", example: "We found firehouse in our reading book.", exampleTranslation: "وجدنا محطة الإطفاء في كتاب القراءة." },
  { word: "fireman", translation: "رجل إطفاء", partOfSpeech: "noun", difficulty: "medium", example: "Fireman is a new word for our unit.", exampleTranslation: "رجل إطفاء كلمة جديدة لوحدتنا." },
  { word: "firepit", translation: "حفرة النار", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed firepit.", exampleTranslation: "ناقشت حفرة النار مع زميلي." },
  { word: "fireplug", translation: "com.fireplug", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about fireplug.", exampleTranslation: "يسأل ورق العمل عن com.fireplug." },
  { word: "firetruck", translation: "عربة إطفاء", partOfSpeech: "noun", difficulty: "hard", example: "We heard firetruck in the science video.", exampleTranslation: "سمعنا عربة إطفاء في فيلم العلوم." },
  { word: "fishhook", translation: "شص", partOfSpeech: "noun", difficulty: "medium", example: "Please copy fishhook into your notebook.", exampleTranslation: "من فضلك انسخ شص في دفترك." },
  { word: "fishnet", translation: "شبكة صيد السمك", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of fishnet.", exampleTranslation: "يُظهر المخطط مثالاً عن شبكة صيد السمك." },
  { word: "fishtail", translation: "ذيل السمكة", partOfSpeech: "noun", difficulty: "medium", example: "Our group used fishtail in the project.", exampleTranslation: "استخدمت مجموعتنا ذيل السمكة في المشروع." },
  { word: "flamenco", translation: "الفلامنكو", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with flamenco.", exampleTranslation: "أعطى المعلم مثالاً بـالفلامنكو." },
  { word: "flapper", translation: "إمرأة شابة", partOfSpeech: "verb", difficulty: "medium", example: "I underlined flapper in the paragraph.", exampleTranslation: "وضعت خطاً تحت إمرأة شابة في الفقرة." },
  { word: "flashbulb", translation: "مصباح يدوي", partOfSpeech: "noun", difficulty: "hard", example: "We practiced saying flashbulb aloud.", exampleTranslation: "تدرّبنا على نطق مصباح يدوي بصوت عالٍ." },
  { word: "flatbed", translation: "مسطحة", partOfSpeech: "adjective", difficulty: "medium", example: "The poster explains flatbed with a drawing.", exampleTranslation: "يشرح الملصق مسطحة برسم." },
  { word: "flatiron", translation: "المكواة", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with flatiron.", exampleTranslation: "شارك الجميع جملة فيها المكواة." },
  { word: "flatware", translation: "أدوات المائدة", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word flatware.", exampleTranslation: "تضمّن الاختبار كلمة أدوات المائدة." },
  { word: "flaxseed", translation: "بذور الكتان", partOfSpeech: "adjective", difficulty: "medium", example: "We learned the word flaxseed in class today.", exampleTranslation: "تعلّمنا كلمة بذور الكتان في الحصة اليوم." },
  { word: "fleabag", translation: "كيس من البراغيث", partOfSpeech: "noun", difficulty: "medium", example: "Can you use fleabag in a sentence?", exampleTranslation: "هل يمكنك استخدام كيس من البراغيث في جملة؟" },
  { word: "floodgate", translation: "بوابة الفيضان", partOfSpeech: "verb", difficulty: "hard", example: "The story mentioned floodgate on page ten.", exampleTranslation: "ذكرت القصة بوابة الفيضان في الصفحة العاشرة." },
  { word: "floodlight", translation: "مصباح", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote floodlight on the board.", exampleTranslation: "كتب معلمنا مصباح على السبورة." },
  { word: "floorboard", translation: "لوح الأرضية", partOfSpeech: "noun", difficulty: "hard", example: "I spelled floorboard correctly on the quiz.", exampleTranslation: "تهجّيت لوح الأرضية بشكل صحيح في الاختبار." },
  { word: "florist", translation: "بائع الزهور", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain florist.", exampleTranslation: "تساعد الصورة على شرح بائع الزهور." },
  { word: "flowerbed", translation: "مشتل أزهار", partOfSpeech: "adjective", difficulty: "hard", example: "We found flowerbed in our reading book.", exampleTranslation: "وجدنا مشتل أزهار في كتاب القراءة." },
  { word: "flowerpot", translation: "زهور", partOfSpeech: "noun", difficulty: "hard", example: "Flowerpot is a new word for our unit.", exampleTranslation: "زهور كلمة جديدة لوحدتنا." },
  { word: "flycatcher", translation: "صائد الذباب", partOfSpeech: "verb", difficulty: "hard", example: "My partner and I discussed flycatcher.", exampleTranslation: "ناقشت صائد الذباب مع زميلي." },
  { word: "flypaper", translation: "صائدة الذباب", partOfSpeech: "verb", difficulty: "medium", example: "The worksheet asks about flypaper.", exampleTranslation: "يسأل ورق العمل عن صائدة الذباب." },
  { word: "flyswatter", translation: "مضرب الذباب", partOfSpeech: "verb", difficulty: "hard", example: "We heard flyswatter in the science video.", exampleTranslation: "سمعنا مضرب الذباب في فيلم العلوم." },
  { word: "foghorn", translation: "قرن الضباب", partOfSpeech: "noun", difficulty: "medium", example: "Please copy foghorn into your notebook.", exampleTranslation: "من فضلك انسخ قرن الضباب في دفترك." },
  { word: "folktale", translation: "الحكاية الشعبية", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of folktale.", exampleTranslation: "يُظهر المخطط مثالاً عن الحكاية الشعبية." },
  { word: "foodcourt", translation: "com.foodcourt", partOfSpeech: "noun", difficulty: "hard", example: "Our group used foodcourt in the project.", exampleTranslation: "استخدمت مجموعتنا com.foodcourt في المشروع." },
  { word: "foodstuff", translation: "مواد غذائية", partOfSpeech: "noun", difficulty: "hard", example: "The teacher gave an example with foodstuff.", exampleTranslation: "أعطى المعلم مثالاً بـمواد غذائية." },
  { word: "footbridge", translation: "جسر المشاة", partOfSpeech: "noun", difficulty: "hard", example: "I underlined footbridge in the paragraph.", exampleTranslation: "وضعت خطاً تحت جسر المشاة في الفقرة." },
  { word: "footpath", translation: "ممر المشاة", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying footpath aloud.", exampleTranslation: "تدرّبنا على نطق ممر المشاة بصوت عالٍ." },
  { word: "footrest", translation: "مسند للقدمين", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains footrest with a drawing.", exampleTranslation: "يشرح الملصق مسند للقدمين برسم." },
  { word: "footstep", translation: "وقع أقدام", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with footstep.", exampleTranslation: "شارك الجميع جملة فيها وقع أقدام." },
  { word: "footstool", translation: "مسند القدمين", partOfSpeech: "noun", difficulty: "hard", example: "The quiz included the word footstool.", exampleTranslation: "تضمّن الاختبار كلمة مسند القدمين." },
  { word: "footwork", translation: "حركة القدمين", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word footwork in class today.", exampleTranslation: "تعلّمنا كلمة حركة القدمين في الحصة اليوم." },
  { word: "foreman", translation: "رئيس العمال", partOfSpeech: "noun", difficulty: "medium", example: "Can you use foreman in a sentence?", exampleTranslation: "هل يمكنك استخدام رئيس العمال في جملة؟" },
  { word: "forestland", translation: "الغابات", partOfSpeech: "noun", difficulty: "hard", example: "The story mentioned forestland on page ten.", exampleTranslation: "ذكرت القصة الغابات في الصفحة العاشرة." },
  { word: "forklift", translation: "رافعة شوكية", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote forklift on the board.", exampleTranslation: "كتب معلمنا رافعة شوكية على السبورة." },
  { word: "formica", translation: "فورميكا", partOfSpeech: "noun", difficulty: "medium", example: "I spelled formica correctly on the quiz.", exampleTranslation: "تهجّيت فورميكا بشكل صحيح في الاختبار." },
  { word: "fortuneteller", translation: "قارئ البخت", partOfSpeech: "verb", difficulty: "hard", example: "The picture helps explain fortuneteller.", exampleTranslation: "تساعد الصورة على شرح قارئ البخت." },
  { word: "foxglove", translation: "قفاز الثعلب", partOfSpeech: "noun", difficulty: "medium", example: "We found foxglove in our reading book.", exampleTranslation: "وجدنا قفاز الثعلب في كتاب القراءة." },
  { word: "foxhole", translation: "حفرة", partOfSpeech: "noun", difficulty: "medium", example: "Foxhole is a new word for our unit.", exampleTranslation: "حفرة كلمة جديدة لوحدتنا." },
  { word: "framehouse", translation: "com.framehouse", partOfSpeech: "noun", difficulty: "hard", example: "My partner and I discussed framehouse.", exampleTranslation: "ناقشت com.framehouse مع زميلي." },
  { word: "freckle", translation: "نمش", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about freckle.", exampleTranslation: "يسأل ورق العمل عن نمش." },
  { word: "freehand", translation: "مرفوعة", partOfSpeech: "noun", difficulty: "medium", example: "We heard freehand in the science video.", exampleTranslation: "سمعنا مرفوعة في فيلم العلوم." },
  { word: "freestyle", translation: "حرة", partOfSpeech: "noun", difficulty: "hard", example: "Please copy freestyle into your notebook.", exampleTranslation: "من فضلك انسخ حرة في دفترك." },
  { word: "freetime", translation: "وقت فراغ", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of freetime.", exampleTranslation: "يُظهر المخطط مثالاً عن وقت فراغ." },
  { word: "freewheel", translation: "عجلة حرة", partOfSpeech: "noun", difficulty: "hard", example: "Our group used freewheel in the project.", exampleTranslation: "استخدمت مجموعتنا عجلة حرة في المشروع." },
  { word: "freshbread", translation: "خبز طازج", partOfSpeech: "noun", difficulty: "hard", example: "The teacher gave an example with freshbread.", exampleTranslation: "أعطى المعلم مثالاً بـخبز طازج." },
  { word: "friar", translation: "الراهب", partOfSpeech: "noun", difficulty: "easy", example: "I underlined friar in the paragraph.", exampleTranslation: "وضعت خطاً تحت الراهب في الفقرة." },
  { word: "frisbee", translation: "الفريسبي", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying frisbee aloud.", exampleTranslation: "تدرّبنا على نطق الفريسبي بصوت عالٍ." },
  { word: "frogman", translation: "الضفدع البشري", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains frogman with a drawing.", exampleTranslation: "يشرح الملصق الضفدع البشري برسم." },
  { word: "frostbite", translation: "قضمة الصقيع", partOfSpeech: "noun", difficulty: "hard", example: "Everyone shared a sentence with frostbite.", exampleTranslation: "شارك الجميع جملة فيها قضمة الصقيع." },
  { word: "fruitcake", translation: "كعكة الفاكهة", partOfSpeech: "noun", difficulty: "hard", example: "The quiz included the word fruitcake.", exampleTranslation: "تضمّن الاختبار كلمة كعكة الفاكهة." },
  { word: "fruitcup", translation: "com.fruitcup", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word fruitcup in class today.", exampleTranslation: "تعلّمنا كلمة com.fruitcup في الحصة اليوم." },
  { word: "fruitfly", translation: "ذبابة الفاكهة", partOfSpeech: "adverb", difficulty: "medium", example: "Can you use fruitfly in a sentence?", exampleTranslation: "هل يمكنك استخدام ذبابة الفاكهة في جملة؟" },
  { word: "fruitloop", translation: "com.fruitloop", partOfSpeech: "noun", difficulty: "hard", example: "The story mentioned fruitloop on page ten.", exampleTranslation: "ذكرت القصة com.fruitloop في الصفحة العاشرة." },
  { word: "fruitstand", translation: "com.fruitstand", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote fruitstand on the board.", exampleTranslation: "كتب معلمنا com.fruitstand على السبورة." },
  { word: "frybread", translation: "خبز مقلي", partOfSpeech: "noun", difficulty: "medium", example: "I spelled frybread correctly on the quiz.", exampleTranslation: "تهجّيت خبز مقلي بشكل صحيح في الاختبار." },
  { word: "fullback", translation: "ظهير", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain fullback.", exampleTranslation: "تساعد الصورة على شرح ظهير." },
  { word: "funnelcake", translation: "com.funnelcake", partOfSpeech: "noun", difficulty: "hard", example: "We found funnelcake in our reading book.", exampleTranslation: "وجدنا com.funnelcake في كتاب القراءة." },
  { word: "furrow", translation: "ثلم", partOfSpeech: "noun", difficulty: "medium", example: "Furrow is a new word for our unit.", exampleTranslation: "ثلم كلمة جديدة لوحدتنا." },
  { word: "gadgetry", translation: "الأدوات", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed gadgetry.", exampleTranslation: "ناقشت الأدوات مع زميلي." },
  { word: "gamekeeper", translation: "حارس اللعبة", partOfSpeech: "verb", difficulty: "hard", example: "The worksheet asks about gamekeeper.", exampleTranslation: "يسأل ورق العمل عن حارس اللعبة." },
  { word: "gangplank", translation: "اللوح الخشبي", partOfSpeech: "noun", difficulty: "hard", example: "We heard gangplank in the science video.", exampleTranslation: "سمعنا اللوح الخشبي في فيلم العلوم." },
  { word: "gargoyle", translation: "مرغول", partOfSpeech: "noun", difficulty: "medium", example: "Please copy gargoyle into your notebook.", exampleTranslation: "من فضلك انسخ مرغول في دفترك." },
  { word: "garland", translation: "إكليل", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of garland.", exampleTranslation: "يُظهر المخطط مثالاً عن إكليل." },
  { word: "garlicbread", translation: "خبز الثوم", partOfSpeech: "noun", difficulty: "hard", example: "Our group used garlicbread in the project.", exampleTranslation: "استخدمت مجموعتنا خبز الثوم في المشروع." },
  { word: "gaslight", translation: "ضوء الغاز", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with gaslight.", exampleTranslation: "أعطى المعلم مثالاً بـضوء الغاز." },
  { word: "gasmask", translation: "قناع غاز", partOfSpeech: "noun", difficulty: "medium", example: "I underlined gasmask in the paragraph.", exampleTranslation: "وضعت خطاً تحت قناع غاز في الفقرة." },
  { word: "gaspump", translation: "com.gaspump", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying gaspump aloud.", exampleTranslation: "تدرّبنا على نطق com.gaspump بصوت عالٍ." },
  { word: "gatehouse", translation: "بوابة الحراسة", partOfSpeech: "noun", difficulty: "hard", example: "The poster explains gatehouse with a drawing.", exampleTranslation: "يشرح الملصق بوابة الحراسة برسم." },
  { word: "gatekeeper", translation: "حارس البوابة", partOfSpeech: "verb", difficulty: "hard", example: "Everyone shared a sentence with gatekeeper.", exampleTranslation: "شارك الجميع جملة فيها حارس البوابة." },
  { word: "gatherer", translation: "جامع", partOfSpeech: "verb", difficulty: "medium", example: "The quiz included the word gatherer.", exampleTranslation: "تضمّن الاختبار كلمة جامع." },
  { word: "gearshift", translation: "ذراع نقل السرعات", partOfSpeech: "noun", difficulty: "hard", example: "We learned the word gearshift in class today.", exampleTranslation: "تعلّمنا كلمة ذراع نقل السرعات في الحصة اليوم." },
  { word: "gearwheel", translation: "عجلة مسننة", partOfSpeech: "noun", difficulty: "hard", example: "Can you use gearwheel in a sentence?", exampleTranslation: "هل يمكنك استخدام عجلة مسننة في جملة؟" },
  { word: "ghosttown", translation: "مدينة الأشباح", partOfSpeech: "noun", difficulty: "hard", example: "The story mentioned ghosttown on page ten.", exampleTranslation: "ذكرت القصة مدينة الأشباح في الصفحة العاشرة." },
  { word: "giftwrap", translation: "التفاف الهدايا", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote giftwrap on the board.", exampleTranslation: "كتب معلمنا التفاف الهدايا على السبورة." },
  { word: "gingerbread", translation: "خبز الزنجبيل", partOfSpeech: "noun", difficulty: "hard", example: "I spelled gingerbread correctly on the quiz.", exampleTranslation: "تهجّيت خبز الزنجبيل بشكل صحيح في الاختبار." },
  { word: "gingham", translation: "القماش القطني", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain gingham.", exampleTranslation: "تساعد الصورة على شرح القماش القطني." },
  { word: "girder", translation: "العارضة", partOfSpeech: "verb", difficulty: "medium", example: "We found girder in our reading book.", exampleTranslation: "وجدنا العارضة في كتاب القراءة." },
  { word: "giveaway", translation: "يتبرع", partOfSpeech: "noun", difficulty: "medium", example: "Giveaway is a new word for our unit.", exampleTranslation: "يتبرع كلمة جديدة لوحدتنا." },
  { word: "glassware", translation: "الأواني الزجاجية", partOfSpeech: "noun", difficulty: "hard", example: "My partner and I discussed glassware.", exampleTranslation: "ناقشت الأواني الزجاجية مع زميلي." },
  { word: "globetrotter", translation: "رحالة", partOfSpeech: "verb", difficulty: "hard", example: "The worksheet asks about globetrotter.", exampleTranslation: "يسأل ورق العمل عن رحالة." },
  { word: "glowstick", translation: "توهج", partOfSpeech: "noun", difficulty: "hard", example: "We heard glowstick in the science video.", exampleTranslation: "سمعنا توهج في فيلم العلوم." },
  { word: "goalpost", translation: "هدف", partOfSpeech: "noun", difficulty: "medium", example: "Please copy goalpost into your notebook.", exampleTranslation: "من فضلك انسخ هدف في دفترك." },
  { word: "goatfish", translation: "سمك الماعز", partOfSpeech: "adjective", difficulty: "medium", example: "The chart shows an example of goatfish.", exampleTranslation: "يُظهر المخطط مثالاً عن سمك الماعز." },
  { word: "goatherd", translation: "راعي الماعز", partOfSpeech: "noun", difficulty: "medium", example: "Our group used goatherd in the project.", exampleTranslation: "استخدمت مجموعتنا راعي الماعز في المشروع." },
  { word: "goldmine", translation: "منجم ذهب", partOfSpeech: "noun", difficulty: "medium", example: "The teacher gave an example with goldmine.", exampleTranslation: "أعطى المعلم مثالاً بـمنجم ذهب." },
  { word: "goldsmith", translation: "صائغ", partOfSpeech: "noun", difficulty: "hard", example: "I underlined goldsmith in the paragraph.", exampleTranslation: "وضعت خطاً تحت صائغ في الفقرة." },
  { word: "gondola", translation: "جندول", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying gondola aloud.", exampleTranslation: "تدرّبنا على نطق جندول بصوت عالٍ." },
  { word: "goodnight", translation: "طاب مساؤك", partOfSpeech: "noun", difficulty: "hard", example: "The poster explains goodnight with a drawing.", exampleTranslation: "يشرح الملصق طاب مساؤك برسم." },
  { word: "gooseberry", translation: "عنب الثعلب", partOfSpeech: "noun", difficulty: "hard", example: "Everyone shared a sentence with gooseberry.", exampleTranslation: "شارك الجميع جملة فيها عنب الثعلب." },
  { word: "gopher", translation: "غوفر", partOfSpeech: "verb", difficulty: "medium", example: "The quiz included the word gopher.", exampleTranslation: "تضمّن الاختبار كلمة غوفر." },
  { word: "goulash", translation: "غولاش", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word goulash in class today.", exampleTranslation: "تعلّمنا كلمة غولاش في الحصة اليوم." },
  { word: "grainfield", translation: "حقل الحبوب", partOfSpeech: "noun", difficulty: "hard", example: "Can you use grainfield in a sentence?", exampleTranslation: "هل يمكنك استخدام حقل الحبوب في جملة؟" },
  { word: "granddad", translation: "جد", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned granddad on page ten.", exampleTranslation: "ذكرت القصة جد في الصفحة العاشرة." },
  { word: "grandkid", translation: "حفيد", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote grandkid on the board.", exampleTranslation: "كتب معلمنا حفيد على السبورة." },
  { word: "grandmom", translation: "جدة", partOfSpeech: "noun", difficulty: "medium", example: "I spelled grandmom correctly on the quiz.", exampleTranslation: "تهجّيت جدة بشكل صحيح في الاختبار." },
  { word: "grapevine", translation: "شجرة العنب", partOfSpeech: "noun", difficulty: "hard", example: "The picture helps explain grapevine.", exampleTranslation: "تساعد الصورة على شرح شجرة العنب." },
  { word: "grassland", translation: "المراعي", partOfSpeech: "noun", difficulty: "hard", example: "We found grassland in our reading book.", exampleTranslation: "وجدنا المراعي في كتاب القراءة." },
  { word: "grassroot", translation: "قاعدة شعبية", partOfSpeech: "noun", difficulty: "hard", example: "Grassroot is a new word for our unit.", exampleTranslation: "قاعدة شعبية كلمة جديدة لوحدتنا." },
  { word: "gravedigger", translation: "حفار القبور", partOfSpeech: "verb", difficulty: "hard", example: "My partner and I discussed gravedigger.", exampleTranslation: "ناقشت حفار القبور مع زميلي." },
  { word: "gravestone", translation: "شاهد القبر", partOfSpeech: "noun", difficulty: "hard", example: "The worksheet asks about gravestone.", exampleTranslation: "يسأل ورق العمل عن شاهد القبر." },
  { word: "graveyard", translation: "مقبرة", partOfSpeech: "noun", difficulty: "hard", example: "We heard graveyard in the science video.", exampleTranslation: "سمعنا مقبرة في فيلم العلوم." },
  { word: "gravyboat", translation: "المرققة", partOfSpeech: "noun", difficulty: "hard", example: "Please copy gravyboat into your notebook.", exampleTranslation: "من فضلك انسخ المرققة في دفترك." },
  { word: "greenbean", translation: "فاصوليا خضراء", partOfSpeech: "noun", difficulty: "hard", example: "The chart shows an example of greenbean.", exampleTranslation: "يُظهر المخطط مثالاً عن فاصوليا خضراء." },
  { word: "greengrocer", translation: "بائع خضار", partOfSpeech: "verb", difficulty: "hard", example: "Our group used greengrocer in the project.", exampleTranslation: "استخدمت مجموعتنا بائع خضار في المشروع." },
  { word: "greyhound", translation: "السلوقي كلب الصيد", partOfSpeech: "noun", difficulty: "hard", example: "The teacher gave an example with greyhound.", exampleTranslation: "أعطى المعلم مثالاً بـالسلوقي كلب الصيد." },
  { word: "griddle", translation: "صينية", partOfSpeech: "noun", difficulty: "medium", example: "I underlined griddle in the paragraph.", exampleTranslation: "وضعت خطاً تحت صينية في الفقرة." },
  { word: "grillroom", translation: "غرفة الشواء", partOfSpeech: "noun", difficulty: "hard", example: "We practiced saying grillroom aloud.", exampleTranslation: "تدرّبنا على نطق غرفة الشواء بصوت عالٍ." },
  { word: "grinch", translation: "غرينش", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains grinch with a drawing.", exampleTranslation: "يشرح الملصق غرينش برسم." },
  { word: "grunion", translation: "جرونيون", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with grunion.", exampleTranslation: "شارك الجميع جملة فيها جرونيون." },
  { word: "guarddog", translation: "كلب الحراسة", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word guarddog.", exampleTranslation: "تضمّن الاختبار كلمة كلب الحراسة." },
  { word: "guardrail", translation: "الدرابزين", partOfSpeech: "noun", difficulty: "hard", example: "We learned the word guardrail in class today.", exampleTranslation: "تعلّمنا كلمة الدرابزين في الحصة اليوم." },
  { word: "guesthouse", translation: "منزل الضيف", partOfSpeech: "noun", difficulty: "hard", example: "Can you use guesthouse in a sentence?", exampleTranslation: "هل يمكنك استخدام منزل الضيف في جملة؟" },
  { word: "guestroom", translation: "غرفة الضيوف", partOfSpeech: "noun", difficulty: "hard", example: "The story mentioned guestroom on page ten.", exampleTranslation: "ذكرت القصة غرفة الضيوف في الصفحة العاشرة." },
  { word: "guidebook", translation: "دليل", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote guidebook on the board.", exampleTranslation: "كتب معلمنا دليل على السبورة." },
  { word: "guidepost", translation: "دليل", partOfSpeech: "noun", difficulty: "hard", example: "I spelled guidepost correctly on the quiz.", exampleTranslation: "تهجّيت دليل بشكل صحيح في الاختبار." },
  { word: "guineapig", translation: "خنزير غينيا", partOfSpeech: "noun", difficulty: "hard", example: "The picture helps explain guineapig.", exampleTranslation: "تساعد الصورة على شرح خنزير غينيا." },
  { word: "guitarcase", translation: "حالة الغيتار", partOfSpeech: "noun", difficulty: "hard", example: "We found guitarcase in our reading book.", exampleTranslation: "وجدنا حالة الغيتار في كتاب القراءة." },
  { word: "gunpowder", translation: "البارود", partOfSpeech: "verb", difficulty: "hard", example: "Gunpowder is a new word for our unit.", exampleTranslation: "البارود كلمة جديدة لوحدتنا." },
  { word: "gusty", translation: "عاصف", partOfSpeech: "noun", difficulty: "easy", example: "My partner and I discussed gusty.", exampleTranslation: "ناقشت عاصف مع زميلي." },
  { word: "gypsy", translation: "غجري", partOfSpeech: "noun", difficulty: "easy", example: "The worksheet asks about gypsy.", exampleTranslation: "يسأل ورق العمل عن غجري." },
  { word: "haberdashery", translation: "الخردوات", partOfSpeech: "noun", difficulty: "hard", example: "We heard haberdashery in the science video.", exampleTranslation: "سمعنا الخردوات في فيلم العلوم." },
  { word: "hairbrush", translation: "فرشاة شعر", partOfSpeech: "noun", difficulty: "hard", example: "Please copy hairbrush into your notebook.", exampleTranslation: "من فضلك انسخ فرشاة شعر في دفترك." },
  { word: "hairclip", translation: "دبوس الشعر", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of hairclip.", exampleTranslation: "يُظهر المخطط مثالاً عن دبوس الشعر." },
  { word: "hairdo", translation: "تسريحة", partOfSpeech: "noun", difficulty: "medium", example: "Our group used hairdo in the project.", exampleTranslation: "استخدمت مجموعتنا تسريحة في المشروع." },
  { word: "hairdryer", translation: "مجفف شعر", partOfSpeech: "verb", difficulty: "hard", example: "The teacher gave an example with hairdryer.", exampleTranslation: "أعطى المعلم مثالاً بـمجفف شعر." },
  { word: "hairline", translation: "شعري", partOfSpeech: "noun", difficulty: "medium", example: "I underlined hairline in the paragraph.", exampleTranslation: "وضعت خطاً تحت شعري في الفقرة." },
  { word: "hairpin", translation: "دبوس الشعر", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying hairpin aloud.", exampleTranslation: "تدرّبنا على نطق دبوس الشعر بصوت عالٍ." },
  { word: "hairspray", translation: "مثبتات الشعر", partOfSpeech: "noun", difficulty: "hard", example: "The poster explains hairspray with a drawing.", exampleTranslation: "يشرح الملصق مثبتات الشعر برسم." },
  { word: "hairstylist", translation: "مصفف شعر", partOfSpeech: "noun", difficulty: "hard", example: "Everyone shared a sentence with hairstylist.", exampleTranslation: "شارك الجميع جملة فيها مصفف شعر." },
  { word: "halibut", translation: "سمكة الهلبوت", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word halibut.", exampleTranslation: "تضمّن الاختبار كلمة سمكة الهلبوت." },
  { word: "hallmark", translation: "السمة المميزة", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word hallmark in class today.", exampleTranslation: "تعلّمنا كلمة السمة المميزة في الحصة اليوم." },
  { word: "halogen", translation: "الهالوجين", partOfSpeech: "verb", difficulty: "medium", example: "Can you use halogen in a sentence?", exampleTranslation: "هل يمكنك استخدام الهالوجين في جملة؟" },
  { word: "hamhock", translation: "أرجوحة", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned hamhock on page ten.", exampleTranslation: "ذكرت القصة أرجوحة في الصفحة العاشرة." },
  { word: "hammerhead", translation: "رأس المطرقة", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote hammerhead on the board.", exampleTranslation: "كتب معلمنا رأس المطرقة على السبورة." },
  { word: "handcart", translation: "عربة اليد", partOfSpeech: "noun", difficulty: "medium", example: "I spelled handcart correctly on the quiz.", exampleTranslation: "تهجّيت عربة اليد بشكل صحيح في الاختبار." },
  { word: "handclap", translation: "تصفيق", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain handclap.", exampleTranslation: "تساعد الصورة على شرح تصفيق." },
  { word: "handcraft", translation: "الحرف اليدوية", partOfSpeech: "noun", difficulty: "hard", example: "We found handcraft in our reading book.", exampleTranslation: "وجدنا الحرف اليدوية في كتاب القراءة." },
  { word: "handcuff", translation: "الأصفاد", partOfSpeech: "noun", difficulty: "medium", example: "Handcuff is a new word for our unit.", exampleTranslation: "الأصفاد كلمة جديدة لوحدتنا." },
  { word: "handgrip", translation: "مقبض", partOfSpeech: "noun", difficulty: "medium", example: "My partner and I discussed handgrip.", exampleTranslation: "ناقشت مقبض مع زميلي." },
  { word: "handhold", translation: "العروة", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about handhold.", exampleTranslation: "يسأل ورق العمل عن العروة." },
  { word: "handiwork", translation: "العمل اليدوي", partOfSpeech: "noun", difficulty: "hard", example: "We heard handiwork in the science video.", exampleTranslation: "سمعنا العمل اليدوي في فيلم العلوم." },
  { word: "handlebar", translation: "المقود", partOfSpeech: "noun", difficulty: "hard", example: "Please copy handlebar into your notebook.", exampleTranslation: "من فضلك انسخ المقود في دفترك." },
  { word: "handprint", translation: "بصمة", partOfSpeech: "noun", difficulty: "hard", example: "The chart shows an example of handprint.", exampleTranslation: "يُظهر المخطط مثالاً عن بصمة." },
  { word: "handrail", translation: "درابزين", partOfSpeech: "noun", difficulty: "medium", example: "Our group used handrail in the project.", exampleTranslation: "استخدمت مجموعتنا درابزين في المشروع." },
  { word: "handstand", translation: "الوقوف على اليدين", partOfSpeech: "noun", difficulty: "hard", example: "The teacher gave an example with handstand.", exampleTranslation: "أعطى المعلم مثالاً بـالوقوف على اليدين." },
  { word: "handtruck", translation: "عربة يدوية", partOfSpeech: "noun", difficulty: "hard", example: "I underlined handtruck in the paragraph.", exampleTranslation: "وضعت خطاً تحت عربة يدوية في الفقرة." },
  { word: "handwash", translation: "غسيل يدوي", partOfSpeech: "noun", difficulty: "medium", example: "We practiced saying handwash aloud.", exampleTranslation: "تدرّبنا على نطق غسيل يدوي بصوت عالٍ." },
  { word: "handwork", translation: "العمل اليدوي", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains handwork with a drawing.", exampleTranslation: "يشرح الملصق العمل اليدوي برسم." },
  { word: "handyman", translation: "بارع", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with handyman.", exampleTranslation: "شارك الجميع جملة فيها بارع." },
  { word: "hangglider", translation: "com.hangglider", partOfSpeech: "verb", difficulty: "hard", example: "The quiz included the word hangglider.", exampleTranslation: "تضمّن الاختبار كلمة com.hangglider." },
  { word: "hangnail", translation: "com.hangnail", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word hangnail in class today.", exampleTranslation: "تعلّمنا كلمة com.hangnail في الحصة اليوم." },
  { word: "hangout", translation: "يتسكع", partOfSpeech: "noun", difficulty: "medium", example: "Can you use hangout in a sentence?", exampleTranslation: "هل يمكنك استخدام يتسكع في جملة؟" },
  { word: "hankie", translation: "هانكي", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned hankie on page ten.", exampleTranslation: "ذكرت القصة هانكي في الصفحة العاشرة." },
  { word: "hardback", translation: "غلاف مقوى", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote hardback on the board.", exampleTranslation: "كتب معلمنا غلاف مقوى على السبورة." },
  { word: "hardcover", translation: "غلاف فني", partOfSpeech: "verb", difficulty: "hard", example: "I spelled hardcover correctly on the quiz.", exampleTranslation: "تهجّيت غلاف فني بشكل صحيح في الاختبار." },
  { word: "hardhat", translation: "هاردهات", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain hardhat.", exampleTranslation: "تساعد الصورة على شرح هاردهات." },
  { word: "hardtop", translation: "سطح صلب", partOfSpeech: "noun", difficulty: "medium", example: "We found hardtop in our reading book.", exampleTranslation: "وجدنا سطح صلب في كتاب القراءة." },
  { word: "hardwire", translation: "سلك صلب", partOfSpeech: "noun", difficulty: "medium", example: "Hardwire is a new word for our unit.", exampleTranslation: "سلك صلب كلمة جديدة لوحدتنا." },
  { word: "harmonica", translation: "هارمونيكا", partOfSpeech: "noun", difficulty: "hard", example: "My partner and I discussed harmonica.", exampleTranslation: "ناقشت هارمونيكا مع زميلي." },
  { word: "harpist", translation: "عازف القيثارة", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about harpist.", exampleTranslation: "يسأل ورق العمل عن عازف القيثارة." },
  { word: "harvester", translation: "حصاد", partOfSpeech: "verb", difficulty: "hard", example: "We heard harvester in the science video.", exampleTranslation: "سمعنا حصاد في فيلم العلوم." },
  { word: "hashbrown", translation: "هاش براون", partOfSpeech: "noun", difficulty: "hard", example: "Please copy hashbrown into your notebook.", exampleTranslation: "من فضلك انسخ هاش براون في دفترك." },
  { word: "hatbox", translation: "هاتبوكس", partOfSpeech: "noun", difficulty: "medium", example: "The chart shows an example of hatbox.", exampleTranslation: "يُظهر المخطط مثالاً عن هاتبوكس." },
  { word: "hatchet", translation: "الأحقاد", partOfSpeech: "noun", difficulty: "medium", example: "Our group used hatchet in the project.", exampleTranslation: "استخدمت مجموعتنا الأحقاد في المشروع." },
  { word: "hatmaker", translation: "صانع القبعات", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with hatmaker.", exampleTranslation: "أعطى المعلم مثالاً بـصانع القبعات." },
  { word: "hayloft", translation: "المتبنى", partOfSpeech: "noun", difficulty: "medium", example: "I underlined hayloft in the paragraph.", exampleTranslation: "وضعت خطاً تحت المتبنى في الفقرة." },
  { word: "haymaker", translation: "تبان", partOfSpeech: "verb", difficulty: "medium", example: "We practiced saying haymaker aloud.", exampleTranslation: "تدرّبنا على نطق تبان بصوت عالٍ." },
  { word: "hayride", translation: "هيرايد", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains hayride with a drawing.", exampleTranslation: "يشرح الملصق هيرايد برسم." },
  { word: "haywire", translation: "أحمق", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with haywire.", exampleTranslation: "شارك الجميع جملة فيها أحمق." },
  { word: "hazelnut", translation: "البندق", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word hazelnut.", exampleTranslation: "تضمّن الاختبار كلمة البندق." },
  { word: "headboard", translation: "اللوح الأمامي", partOfSpeech: "noun", difficulty: "hard", example: "We learned the word headboard in class today.", exampleTranslation: "تعلّمنا كلمة اللوح الأمامي في الحصة اليوم." },
  { word: "headcount", translation: "عدد الموظفين", partOfSpeech: "noun", difficulty: "hard", example: "Can you use headcount in a sentence?", exampleTranslation: "هل يمكنك استخدام عدد الموظفين في جملة؟" },
  { word: "headgear", translation: "أغطية الرأس", partOfSpeech: "noun", difficulty: "medium", example: "The story mentioned headgear on page ten.", exampleTranslation: "ذكرت القصة أغطية الرأس في الصفحة العاشرة." },
  { word: "headlamp", translation: "كشافات", partOfSpeech: "noun", difficulty: "medium", example: "Our teacher wrote headlamp on the board.", exampleTranslation: "كتب معلمنا كشافات على السبورة." },
  { word: "headlock", translation: "قفل الرأس", partOfSpeech: "noun", difficulty: "medium", example: "I spelled headlock correctly on the quiz.", exampleTranslation: "تهجّيت قفل الرأس بشكل صحيح في الاختبار." },
  { word: "headrest", translation: "مسند الرأس", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain headrest.", exampleTranslation: "تساعد الصورة على شرح مسند الرأس." },
  { word: "headroom", translation: "الإرتفاع", partOfSpeech: "noun", difficulty: "medium", example: "We found headroom in our reading book.", exampleTranslation: "وجدنا الإرتفاع في كتاب القراءة." },
  { word: "headscarf", translation: "الحجاب", partOfSpeech: "noun", difficulty: "hard", example: "Headscarf is a new word for our unit.", exampleTranslation: "الحجاب كلمة جديدة لوحدتنا." },
  { word: "headstand", translation: "الوقوف على اليدين", partOfSpeech: "noun", difficulty: "hard", example: "My partner and I discussed headstand.", exampleTranslation: "ناقشت الوقوف على اليدين مع زميلي." },
  { word: "headstone", translation: "شاهد القبر", partOfSpeech: "noun", difficulty: "hard", example: "The worksheet asks about headstone.", exampleTranslation: "يسأل ورق العمل عن شاهد القبر." },
  { word: "headwaiter", translation: "النادل الرئيسي", partOfSpeech: "verb", difficulty: "hard", example: "We heard headwaiter in the science video.", exampleTranslation: "سمعنا النادل الرئيسي في فيلم العلوم." },
  { word: "headwind", translation: "الرياح المعاكسة", partOfSpeech: "noun", difficulty: "medium", example: "Please copy headwind into your notebook.", exampleTranslation: "من فضلك انسخ الرياح المعاكسة في دفترك." },
  { word: "healer", translation: "المعالج", partOfSpeech: "verb", difficulty: "medium", example: "The chart shows an example of healer.", exampleTranslation: "يُظهر المخطط مثالاً عن المعالج." },
  { word: "healthful", translation: "صحية", partOfSpeech: "adjective", difficulty: "hard", example: "Our group used healthful in the project.", exampleTranslation: "استخدمت مجموعتنا صحية في المشروع." },
  { word: "heartrate", translation: "معدل ضربات القلب", partOfSpeech: "verb", difficulty: "hard", example: "The teacher gave an example with heartrate.", exampleTranslation: "أعطى المعلم مثالاً بـمعدل ضربات القلب." },
  { word: "heatwave", translation: "موجة الحر", partOfSpeech: "noun", difficulty: "medium", example: "I underlined heatwave in the paragraph.", exampleTranslation: "وضعت خطاً تحت موجة الحر في الفقرة." },
  { word: "hedgeclip", translation: "مقطع التحوط", partOfSpeech: "noun", difficulty: "hard", example: "We practiced saying hedgeclip aloud.", exampleTranslation: "تدرّبنا على نطق مقطع التحوط بصوت عالٍ." },
  { word: "heiress", translation: "وريثة", partOfSpeech: "noun", difficulty: "medium", example: "The poster explains heiress with a drawing.", exampleTranslation: "يشرح الملصق وريثة برسم." },
  { word: "helipad", translation: "مهبط طائرات الهليكوبتر", partOfSpeech: "noun", difficulty: "medium", example: "Everyone shared a sentence with helipad.", exampleTranslation: "شارك الجميع جملة فيها مهبط طائرات الهليكوبتر." },
  { word: "helpdesk", translation: "مكتب المساعدة", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word helpdesk.", exampleTranslation: "تضمّن الاختبار كلمة مكتب المساعدة." },
  { word: "henhouse", translation: "بيت الدجاج", partOfSpeech: "noun", difficulty: "medium", example: "We learned the word henhouse in class today.", exampleTranslation: "تعلّمنا كلمة بيت الدجاج في الحصة اليوم." },
  { word: "henna", translation: "الحناء", partOfSpeech: "noun", difficulty: "easy", example: "Can you use henna in a sentence?", exampleTranslation: "هل يمكنك استخدام الحناء في جملة؟" },
  { word: "herbicide", translation: "مبيدات الأعشاب", partOfSpeech: "noun", difficulty: "hard", example: "The story mentioned herbicide on page ten.", exampleTranslation: "ذكرت القصة مبيدات الأعشاب في الصفحة العاشرة." },
  { word: "herringbone", translation: "متعرجة", partOfSpeech: "noun", difficulty: "hard", example: "Our teacher wrote herringbone on the board.", exampleTranslation: "كتب معلمنا متعرجة على السبورة." },
  { word: "hibachi", translation: "هيباتشي", partOfSpeech: "noun", difficulty: "medium", example: "I spelled hibachi correctly on the quiz.", exampleTranslation: "تهجّيت هيباتشي بشكل صحيح في الاختبار." },
  { word: "hickory", translation: "جوز", partOfSpeech: "noun", difficulty: "medium", example: "The picture helps explain hickory.", exampleTranslation: "تساعد الصورة على شرح جوز." },
  { word: "hideaway", translation: "مخبأ", partOfSpeech: "noun", difficulty: "medium", example: "We found hideaway in our reading book.", exampleTranslation: "وجدنا مخبأ في كتاب القراءة." },
  { word: "hideout", translation: "مخبأ", partOfSpeech: "noun", difficulty: "medium", example: "Hideout is a new word for our unit.", exampleTranslation: "مخبأ كلمة جديدة لوحدتنا." },
  { word: "highchair", translation: "كرسي مرتفع", partOfSpeech: "noun", difficulty: "hard", example: "My partner and I discussed highchair.", exampleTranslation: "ناقشت كرسي مرتفع مع زميلي." },
  { word: "highheel", translation: "كعب عالي", partOfSpeech: "noun", difficulty: "medium", example: "The worksheet asks about highheel.", exampleTranslation: "يسأل ورق العمل عن كعب عالي." },
  { word: "highrise", translation: "شاهقة", partOfSpeech: "noun", difficulty: "medium", example: "We heard highrise in the science video.", exampleTranslation: "سمعنا شاهقة في فيلم العلوم." },
  { word: "hilltop", translation: "قمة التل", partOfSpeech: "noun", difficulty: "medium", example: "Please copy hilltop into your notebook.", exampleTranslation: "من فضلك انسخ قمة التل في دفترك." },
  { word: "hindquarter", translation: "com.hindquar", partOfSpeech: "verb", difficulty: "hard", example: "The chart shows an example of hindquarter.", exampleTranslation: "يُظهر المخطط مثالاً عن com.hindquar." },
  { word: "hipbone", translation: "العظم الحرقفي", partOfSpeech: "noun", difficulty: "medium", example: "Our group used hipbone in the project.", exampleTranslation: "استخدمت مجموعتنا العظم الحرقفي في المشروع." },
  { word: "hipster", translation: "محب", partOfSpeech: "verb", difficulty: "medium", example: "The teacher gave an example with hipster.", exampleTranslation: "أعطى المعلم مثالاً بـمحب." },
  { word: "hitchhike", translation: "توصيل مجاني", partOfSpeech: "noun", difficulty: "hard", example: "I underlined hitchhike in the paragraph.", exampleTranslation: "وضعت خطاً تحت توصيل مجاني في الفقرة." },
  { word: "hobbyhorse", translation: "هواية", partOfSpeech: "noun", difficulty: "hard", example: "We practiced saying hobbyhorse aloud.", exampleTranslation: "تدرّبنا على نطق هواية بصوت عالٍ." },
  { word: "hobgoblin", translation: "غول", partOfSpeech: "noun", difficulty: "hard", example: "The poster explains hobgoblin with a drawing.", exampleTranslation: "يشرح الملصق غول برسم." },
  { word: "hockeystick", translation: "عصا الهوكي", partOfSpeech: "noun", difficulty: "hard", example: "Everyone shared a sentence with hockeystick.", exampleTranslation: "شارك الجميع جملة فيها عصا الهوكي." },
  { word: "hogwash", translation: "هراء", partOfSpeech: "noun", difficulty: "medium", example: "The quiz included the word hogwash.", exampleTranslation: "تضمّن الاختبار كلمة هراء." },
];
