import { db, lessonsTable, wordsTable } from "@workspace/db";
import { count } from "drizzle-orm";
import { logger } from "./lib/logger";

const SEED_LESSON = {
  title: "Daniel - The Movie",
  text: `The sky was slowly darkening over Jerusalem. But what was approaching was not merely night. It was the third year of the reign of Jehoakim, king of Judah. And on the horizon, beyond the hills and ancient walls, something greater than shadows was advancing. A storm of iron and fire marched relentlessly, as if the very earth had been summoned for judgment. Babylon had awakened. And when Babylon awakened, kingdoms trembled.

`,
  level: "all" as const,
  wordCount: 0,
};

const SEED_WORDS: Array<{
  word: string;
  translation: string;
  example: string | null;
  difficulty: string;
  partOfSpeech: string | null;
}> = [
  { word: "sky", translation: "سماء", example: "The sky is blue today.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "slowly", translation: "ببطء", example: "She walked slowly to school.", difficulty: "easy", partOfSpeech: "adverb" },
  { word: "darken", translation: "يَظْلُم / يُعَتِّم", example: "The room began to darken at night.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "over", translation: "فوق", example: "A bird flew over the house.", difficulty: "easy", partOfSpeech: "preposition" },
  { word: "approach", translation: "يقترب", example: "The bus will approach the stop soon.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "merely", translation: "مجرد", example: "It is merely a small problem.", difficulty: "medium", partOfSpeech: "adverb" },
  { word: "night", translation: "ليل", example: "I sleep at night.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "third", translation: "الثالث", example: "This is my third try.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "year", translation: "سنة", example: "This year is very busy.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "reign", translation: "حُكم / عهد", example: "The king's reign lasted many years.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "king", translation: "ملك", example: "The king lived in a palace.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "horizon", translation: "الأفق", example: "We watched the sun at the horizon.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "beyond", translation: "أبعد من / وراء", example: "The village is beyond the river.", difficulty: "medium", partOfSpeech: "preposition" },
  { word: "hill", translation: "تل", example: "They climbed the hill.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "ancient", translation: "قديم جدًا / عتيق", example: "We visited an ancient city.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "wall", translation: "جدار", example: "There is a picture on the wall.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "something", translation: "شيء ما", example: "I heard something outside.", difficulty: "easy", partOfSpeech: "pronoun" },
  { word: "greater", translation: "أعظم / أكبر", example: "This book is greater than the last one.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "shadow", translation: "ظل", example: "My shadow is on the ground.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "advance", translation: "يتقدم", example: "The soldiers advance carefully.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "storm", translation: "عاصفة", example: "A storm came in the evening.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "iron", translation: "حديد", example: "The gate is made of iron.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "fire", translation: "نار", example: "The fire kept us warm.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "march", translation: "يمشي في صف / يزحف", example: "The army will march at dawn.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "relentlessly", translation: "بلا توقف / بلا رحمة", example: "The rain fell relentlessly all day.", difficulty: "hard", partOfSpeech: "adverb" },
  { word: "as if", translation: "كما لو", example: "He looked at me as if he was angry.", difficulty: "medium", partOfSpeech: "conjunction" },
  { word: "very", translation: "جدًا", example: "This test is very easy.", difficulty: "easy", partOfSpeech: "adverb" },
  { word: "earth", translation: "الأرض", example: "The earth goes around the sun.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "summon", translation: "يستدعي", example: "The teacher will summon the students.", difficulty: "hard", partOfSpeech: "verb" },
  { word: "judgment", translation: "حُكم / قضاء", example: "The judge gave his judgment.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "awaken", translation: "يستيقظ / يوقظ", example: "I awaken early every morning.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "kingdom", translation: "مملكة", example: "The kingdom was large and rich.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "tremble", translation: "يرتجف", example: "My hands tremble when I am scared.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "foreign", translation: "أجنبي", example: "They lived in a foreign country.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "take", translation: "يأخذ", example: "They took him to a new place.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "land", translation: "أرض", example: "They traveled to a far land.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "everything", translation: "كل شيء", example: "Everything changed after the move.", difficulty: "easy", partOfSpeech: "pronoun" },
  { word: "know", translation: "يعرف", example: "I know his name.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "question", translation: "يشكّك / يسأل", example: "People began to question his story.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "name", translation: "اسم", example: "Her name is Sara.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "culture", translation: "ثقافة", example: "We learned about the culture of Japan.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "faith", translation: "إيمان", example: "His faith gave him strength.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "test", translation: "اختبار", example: "The teacher gave a math test.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "heart", translation: "قلب / مركز", example: "They lived in the heart of the city.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "palace", translation: "قصر", example: "The king lived in a big palace.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "gate", translation: "بوابة", example: "They waited at the gate.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "open", translation: "يفتح", example: "Please open the door.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "mouth", translation: "فم", example: "Open your mouth, please.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "starving", translation: "جائع جدًا", example: "The starving man needed food.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "beast", translation: "وحش", example: "In the story, a beast lived in the forest.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "under", translation: "تحت", example: "The cat is under the table.", difficulty: "easy", partOfSpeech: "preposition" },
  { word: "authority", translation: "سلطة", example: "The police have authority in the city.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "chief", translation: "رئيس / كبير", example: "She is the chief officer in the company.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "official", translation: "مسؤول", example: "An official spoke to the crowd.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "calculate", translation: "يحسب", example: "We calculate the total price.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "process", translation: "عملية", example: "Learning a language is a long process.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "transformation", translation: "تحوّل", example: "The city saw a transformation in ten years.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "begin", translation: "يبدأ", example: "Class will begin at nine o'clock.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "conquer", translation: "يغزو / يقهر", example: "The army tried to conquer the city.", difficulty: "hard", partOfSpeech: "verb" },
  { word: "body", translation: "جسم", example: "Exercise is good for your body.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "enough", translation: "كافٍ", example: "I have enough money for lunch.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "mind", translation: "عقل", example: "Reading helps your mind.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "young", translation: "شاب", example: "The young boy ran fast.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "man", translation: "رجل", example: "A man stood near the door.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "give", translation: "يعطي", example: "Please give me the book.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "new", translation: "جديد", example: "She bought a new phone.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "call", translation: "يسمّي / يتصل", example: "They called him by a different name.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "receive", translation: "يتلقى", example: "I received a message from my friend.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "invocation", translation: "ابتهال / استدعاء", example: "The prayer was an invocation for help.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "god", translation: "إله", example: "In many stories, people pray to a god.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "attempt", translation: "محاولة", example: "Her first attempt was not successful.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "erase", translation: "يمحو", example: "Please erase the word on the board.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "identity", translation: "هوية", example: "Your identity is important.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "table", translation: "طاولة", example: "The table was full of food.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "overflow", translation: "يفيض / يتدفق", example: "The cup will overflow if you pour more water.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "delicacy", translation: "طعام شهي / من الأطعمة الفاخرة", example: "Fish can be a delicacy in some countries.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "meat", translation: "لحم", example: "He does not eat meat.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "bread", translation: "خبز", example: "I ate bread with soup.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "wine", translation: "نبيذ", example: "They drank wine at the dinner.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "watch", translation: "يراقب", example: "She watched the children carefully.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "carefully", translation: "بحذر / بعناية", example: "Please drive carefully.", difficulty: "easy", partOfSpeech: "adverb" },
  { word: "food", translation: "طعام", example: "This food is hot.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "consecration", translation: "تكريس / تقديس", example: "The ceremony was a consecration of the temple.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "offer", translation: "يُقدِّم", example: "They offered gifts to the king.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "Babylon", translation: "بابل", example: "Babylon was an ancient city.", difficulty: "medium", partOfSpeech: "proper noun" },
  { word: "eat", translation: "يأكل", example: "We eat lunch at noon.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "mean", translation: "يعني", example: "What does this word mean?", difficulty: "easy", partOfSpeech: "verb" },
  { word: "participate", translation: "يشارك", example: "Students participate in class discussions.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "accept", translation: "يقبل", example: "I accept your apology.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "surrender", translation: "يستسلم", example: "The soldiers decided to surrender.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "quiet", translation: "هادئ", example: "The library is quiet.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "courage", translation: "شجاعة", example: "It takes courage to tell the truth.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "servant", translation: "خادم", example: "The servant cleaned the house.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "day", translation: "يوم", example: "Today is a sunny day.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "vegetable", translation: "خضار", example: "Carrots are a vegetable.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "water", translation: "ماء", example: "Please drink water.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "drink", translation: "يشرب", example: "I drink tea in the morning.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "compare", translation: "يقارن", example: "Compare these two pictures.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "appearance", translation: "مظهر", example: "Her appearance changed after the haircut.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "other", translation: "آخر", example: "I want the other book.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "proposal", translation: "اقتراح", example: "His proposal was simple and clear.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "pass", translation: "يمرّ", example: "Ten minutes passed quickly.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "friend", translation: "صديق", example: "My friend helped me.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "healthy", translation: "صحي", example: "She eats healthy food.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "strong", translation: "قوي", example: "He is strong enough to carry the box.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "clear-minded", translation: "صافي الذهن", example: "After sleeping well, I feel clear-minded.", difficulty: "hard", partOfSpeech: "adjective" },
  { word: "honor", translation: "يكرّم / يشرف", example: "We honor our parents.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "faithfulness", translation: "إخلاص / أمانة", example: "Her faithfulness to her friends was strong.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "excel", translation: "يتفوّق", example: "She excels in math.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "knowledge", translation: "معرفة", example: "Reading gives you knowledge.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "literature", translation: "أدب", example: "He studies English literature.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "wisdom", translation: "حكمة", example: "Grandparents often share wisdom.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "ability", translation: "قدرة", example: "He has the ability to learn fast.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "understand", translation: "يفهم", example: "I understand the lesson now.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "vision", translation: "رؤية / رؤيا", example: "He described a vision he saw at night.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "interpret", translation: "يفسّر", example: "Can you interpret this message?", difficulty: "hard", partOfSpeech: "verb" },
  { word: "dream", translation: "حلم", example: "I had a strange dream.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "silent", translation: "صامت", example: "The house was silent at night.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "awake", translation: "يستيقظ", example: "I awake early every morning.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "terror", translation: "رعب", example: "He felt terror when he heard the loud noise.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "vivid", translation: "واضح جدًا / حيّ", example: "The story gave me a vivid picture in my mind.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "forgotten", translation: "مُنسيّ", example: "The old keys were forgotten in a drawer.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "waking", translation: "استيقاظ", example: "After waking, he drank a glass of water.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "disturbed", translation: "مضطرب / منزعج", example: "She felt disturbed by the bad news.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "demand", translation: "يطلب بشدة", example: "The teacher will demand good behavior in class.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "magician", translation: "ساحر", example: "The magician did a surprising trick.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "astrologer", translation: "منجّم", example: "The astrologer talked about the stars.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "meaning", translation: "معنى", example: "What is the meaning of this word?", difficulty: "easy", partOfSpeech: "noun" },
  { word: "fury", translation: "غضب شديد", example: "He shouted in fury after the argument.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "decree", translation: "مرسوم / يَصدر أمرًا", example: "The leader will decree a new rule.", difficulty: "hard", partOfSpeech: "verb" },
  { word: "death", translation: "موت", example: "The story was about life and death.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "wise", translation: "حكيم", example: "My grandfather is a wise person.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "pray", translation: "يُصلي", example: "They pray together every evening.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "reveal", translation: "يكشف / يعلن", example: "Please reveal the answer to the question.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "mystery", translation: "لغز / سر", example: "The missing book was a mystery.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "stand", translation: "يقف", example: "Please stand near the door.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "heaven", translation: "السماء / الجنة", example: "They looked up at the heaven at night.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "describe", translation: "يصف", example: "Can you describe your favorite place?", difficulty: "easy", partOfSpeech: "verb" },
  { word: "colossal", translation: "ضخم جدًا", example: "They saw a colossal statue in the city.", difficulty: "hard", partOfSpeech: "adjective" },
  { word: "statue", translation: "تمثال", example: "The statue is in the center of the park.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "head", translation: "رأس", example: "He has a hat on his head.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "gold", translation: "ذهب", example: "This ring is made of gold.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "chest", translation: "صدر", example: "He put his hand on his chest.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "silver", translation: "فضة", example: "She wore a silver necklace.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "belly", translation: "بطن", example: "My belly hurts after eating too much.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "bronze", translation: "برونز", example: "The medal was made of bronze.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "leg", translation: "ساق", example: "He hurt his leg while running.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "foot", translation: "قدم", example: "My foot is tired after walking.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "mix", translation: "يخلط", example: "Mix the sugar with the tea.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "clay", translation: "طين / صلصال", example: "The child made a cup from clay.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "explain", translation: "يشرح", example: "Please explain the homework to me.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "arise", translation: "ينشأ / يظهر", example: "Problems can arise if you are late.", difficulty: "hard", partOfSpeech: "verb" },
  { word: "end", translation: "نهاية", example: "At the end of the movie, everyone clapped.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "establish", translation: "يؤسس / يُنشئ", example: "They want to establish a new school.", difficulty: "hard", partOfSpeech: "verb" },
  { word: "eternal", translation: "أبدي", example: "They talked about eternal love in the story.", difficulty: "hard", partOfSpeech: "adjective" },
  { word: "destroy", translation: "يدمّر", example: "The fire can destroy the old house.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "fall", translation: "يسقط", example: "Be careful not to fall on the stairs.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "prostrate", translation: "ساجد / منطرح أرضًا", example: "He lay prostrate on the ground.", difficulty: "hard", partOfSpeech: "adjective" },
  { word: "declare", translation: "يعلن", example: "The principal will declare the winner.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "surely", translation: "بالتأكيد", example: "Surely we can finish the work today.", difficulty: "medium", partOfSpeech: "adverb" },
  { word: "lord", translation: "الرب / السيد", example: "In the story, the lord spoke to the people.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "exalt", translation: "يرفع شأن / يُكرّم", example: "The coach will exalt the best players.", difficulty: "hard", partOfSpeech: "verb" },
  { word: "pride", translation: "كبرياء", example: "His pride made him think he was better than others.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "grow", translation: "ينمو / يزداد", example: "The problem can grow if we do nothing.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "command", translation: "يأمر", example: "The officer will command the soldiers to stop.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "golden", translation: "ذهبي", example: "She wore a golden ring on her finger.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "bow", translation: "ينحني", example: "People bow to show respect.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "whoever", translation: "أيّ شخص", example: "Whoever finishes first can leave early.", difficulty: "medium", partOfSpeech: "pronoun" },
  { word: "refuse", translation: "يرفض", example: "I refuse to lie to my friend.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "cast", translation: "يلقي / يرمي", example: "They cast the net into the sea.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "blazing", translation: "مشتعل", example: "We sat far from the blazing fire.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "furnace", translation: "فرن (كبيرة)", example: "The metal was heated in a furnace.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "appoint", translation: "يحدد / يعيّن", example: "They will appoint a day for the meeting.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "empire", translation: "إمبراطورية", example: "The empire controlled many lands.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "except", translation: "باستثناء", example: "Everyone came except Ali.", difficulty: "easy", partOfSpeech: "preposition" },
  { word: "furious", translation: "غاضب جدًا", example: "He was furious when he heard the news.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "order", translation: "يأمر", example: "The coach ordered the team to practice more.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "heat", translation: "يسخّن / حرارة", example: "Please heat the soup before you eat it.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "hotter", translation: "أكثر حرارة", example: "Today is hotter than yesterday.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "bind", translation: "يربط", example: "They bind the boxes with rope.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "throw", translation: "يرمي", example: "Do not throw stones at the window.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "suddenly", translation: "فجأة", example: "Suddenly, the lights went out.", difficulty: "easy", partOfSpeech: "adverb" },
  { word: "unharmed", translation: "غير مُصاب", example: "The child was unharmed after the accident.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "fourth", translation: "الرابع", example: "This is my fourth lesson today.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "look like", translation: "يبدو مثل", example: "This cloud looks like a bird.", difficulty: "easy", partOfSpeech: "phrase" },
  { word: "son", translation: "ابن", example: "Her son goes to school every day.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "emerge", translation: "يخرج / يظهر", example: "The cat emerged from under the bed.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "untouched", translation: "غير متأثر / لم يُمسّ", example: "The glass was untouched after the fall.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "blessed", translation: "مبارَك", example: "She felt blessed to have good friends.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "send", translation: "يرسل", example: "I will send you a message later.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "angel", translation: "ملاك", example: "The story says an angel helped them.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "deliver", translation: "ينقذ / يسلّم", example: "The firefighters delivered the family from danger.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "tree", translation: "شجرة", example: "The tree is tall and green.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "reach", translation: "يصل", example: "The ladder can reach the roof.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "shelter", translation: "مأوى / يحمي", example: "The big tree can shelter us from the sun.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "creature", translation: "مخلوق", example: "Every creature needs water.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "messenger", translation: "رسول / مبعوث", example: "A messenger brought a letter to the king.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "cut down", translation: "يقطع (شجرة)", example: "They will cut down the old tree.", difficulty: "easy", partOfSpeech: "phrasal verb" },
  { word: "stump", translation: "جذع (باقي الشجرة بعد قطعها)", example: "Only a stump was left after they cut the tree.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "acknowledge", translation: "يعترف بـ / يقرّ", example: "He will acknowledge his mistake.", difficulty: "hard", partOfSpeech: "verb" },
  { word: "rule", translation: "يحكم", example: "A king can rule a country.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "drive away", translation: "يطرد / يبعد بالقوة", example: "The dog barked to drive away the cat.", difficulty: "medium", partOfSpeech: "phrasal verb" },
  { word: "animal", translation: "حيوان", example: "The animal is thirsty.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "sovereignty", translation: "سيادة", example: "The country fought for its sovereignty.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "month", translation: "شهر", example: "One month has four weeks.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "boast", translation: "يتفاخر", example: "Do not boast about your money.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "voice", translation: "صوت", example: "I heard a voice outside.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "downfall", translation: "سقوط / هلاك", example: "His pride led to his downfall.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "reason", translation: "عقل / سبب", example: "She lost her reason because of fear.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "among", translation: "بين / وسط", example: "He sat among his friends.", difficulty: "easy", partOfSpeech: "preposition" },
  { word: "grass", translation: "عشب", example: "The cow eats grass.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "cattle", translation: "ماشية", example: "The farmer keeps cattle on the land.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "time", translation: "مرة / وقت", example: "I visited him three times.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "lift", translation: "يرفع", example: "Please lift the box carefully.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "eye", translation: "عين", example: "My eye hurts today.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "return", translation: "يعود", example: "He will return home soon.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "praise", translation: "يمدح / تسبيح", example: "We praise people for good work.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "dominion", translation: "سلطان / حكم", example: "The king had dominion over the land.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "walk", translation: "يمشي", example: "I walk to school every day.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "able", translation: "قادر", example: "She is able to swim well.", difficulty: "easy", partOfSpeech: "adjective" },
  { word: "humble", translation: "متواضع / يُذلّ", example: "A humble person does not boast.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "grandson", translation: "حفيد", example: "The king's grandson visited the palace.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "hold", translation: "يقيم / يعقد", example: "They will hold a meeting tomorrow.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "banquet", translation: "وليمة", example: "They prepared a big banquet for the guests.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "arrogance", translation: "غرور / تكبّر", example: "His arrogance made people dislike him.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "sacred", translation: "مقدّس", example: "This is a sacred place for many people.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "cup", translation: "كأس", example: "She drank tea from a cup.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "temple", translation: "معبد / هيكل", example: "Many people went to the temple to pray.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "use", translation: "يستخدم", example: "Please use this pen to write your name.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "mock", translation: "يسخر من", example: "It is wrong to mock someone for a mistake.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "appear", translation: "يظهر", example: "A strange light appeared in the sky.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "write", translation: "يكتب", example: "Students write notes during class.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "none", translation: "لا أحد / لا شيء", example: "None of the answers were correct.", difficulty: "easy", partOfSpeech: "pronoun" },
  { word: "until", translation: "حتى", example: "Wait here until I come back.", difficulty: "easy", partOfSpeech: "conjunction" },
  { word: "inscription", translation: "نقش / كتابة محفورة", example: "There is an inscription on the stone.", difficulty: "hard", partOfSpeech: "noun" },
  { word: "number", translation: "يعدّ / يحسب", example: "Can you number the pages from one to ten?", difficulty: "easy", partOfSpeech: "verb" },
  { word: "bring", translation: "يجلب", example: "Please bring your book to class.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "weigh", translation: "يزن", example: "They weigh the fruit at the market.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "wanting", translation: "ناقص / غير كافٍ", example: "His work was found wanting and needed improvement.", difficulty: "hard", partOfSpeech: "adjective" },
  { word: "divide", translation: "يقسّم", example: "Let's divide the cake into four pieces.", difficulty: "easy", partOfSpeech: "verb" },
  { word: "Medes", translation: "الميديون", example: "The Medes were an ancient people in history.", difficulty: "hard", partOfSpeech: "proper noun" },
  { word: "Persians", translation: "الفرس", example: "The Persians built a strong empire long ago.", difficulty: "hard", partOfSpeech: "proper noun" },
  { word: "slain", translation: "مقتول", example: "The soldier was slain in the battle.", difficulty: "hard", partOfSpeech: "adjective" },
  { word: "hand", translation: "يد", example: "He raised his hand to ask a question.", difficulty: "easy", partOfSpeech: "noun" },
  { word: "aged", translation: "مسنّ / متقدّم في السن", example: "The aged man walked slowly with a stick.", difficulty: "medium", partOfSpeech: "adjective" },
  { word: "endure", translation: "يتحمّل / يصمد", example: "She had to endure a long journey.", difficulty: "medium", partOfSpeech: "verb" },
  { word: "rise", translation: "صعود / ارتفاع", example: "We watched the rise of the sun.", difficulty: "medium", partOfSpeech: "noun" },
  { word: "slay", translation: "يقتل", example: "In old stories, heroes sometimes slay monsters.", difficulty: "hard", partOfSpeech: "verb" },
  { word: "unbroken", translation: "غير منقطع / لم ينكسر", example: "Their friendship stayed unbroken for many years.", difficulty: "medium", partOfSpeech: "adjective" },
];

export async function seedIfEmpty(): Promise<void> {
  try {
    const [{ lessonCount }] = await db
      .select({ lessonCount: count() })
      .from(lessonsTable);

    if (Number(lessonCount) > 0) {
      logger.info("[Seed] Database already has lessons — skipping seed.");
      return;
    }

    logger.info("[Seed] No lessons found — seeding default lesson...");

    const [lesson] = await db
      .insert(lessonsTable)
      .values({ ...SEED_LESSON, wordCount: SEED_WORDS.length })
      .returning();

    await db.insert(wordsTable).values(
      SEED_WORDS.map((w) => ({ ...w, lessonId: lesson.id }))
    );

    logger.info(
      { lessonId: lesson.id, wordCount: SEED_WORDS.length },
      "[Seed] Default lesson created successfully."
    );
  } catch (err) {
    logger.error({ err }, "[Seed] Failed to seed database — continuing without seed.");
  }
}
