const colors = {
  light: {
    text: "#1c1a17",
    tint: "#ff7a1a",
    background: "#fffcf0",
    foreground: "#1c1a17",
    card: "#ffffff",
    cardForeground: "#1c1a17",
    primary: "#ff7a1a",
    primaryForeground: "#ffffff",
    secondary: "#0cb8cc",
    secondaryForeground: "#ffffff",
    muted: "#ede9df",
    mutedForeground: "#6b6459",
    accent: "#ff1a66",
    accentForeground: "#ffffff",
    destructive: "#f04040",
    destructiveForeground: "#ffffff",
    border: "#ddd6c6",
    input: "#ddd6c6",
  },
  dark: {
    text: "#fffcf0",
    tint: "#ff7a1a",
    background: "#141720",
    foreground: "#fffcf0",
    card: "#1a1c2b",
    cardForeground: "#fffcf0",
    primary: "#ff7a1a",
    primaryForeground: "#ffffff",
    secondary: "#0cb8cc",
    secondaryForeground: "#ffffff",
    muted: "#28293d",
    mutedForeground: "#c0bcae",
    accent: "#ff1a66",
    accentForeground: "#ffffff",
    destructive: "#f04040",
    destructiveForeground: "#ffffff",
    border: "#28293d",
    input: "#28293d",
  },
  radius: 16,
};

export default colors;
